"""
N64 hardware integration tests using mupen64plus cycle-accurate emulation.

These tests compile C programs (the kind generated by `pak explain`) to MIPS
machine code, assemble them into N64 ROMs, and verify correct execution on the
mupen64plus emulator.

Each test ROM uses the ROM protocol:
    *(0x80300000) = 0xDEADBEEF   — entry reached
    *(0x80300010 + i*4) = val_i  — results (signed i32)
    *(0x80300000) = 0xC0FFEE00   — done

Tests are SKIPPED when mupen64plus or the MIPS toolchain is unavailable.
"""
import os, subprocess, sys, tempfile, textwrap
import pytest

REPO     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNNER   = os.path.join(REPO, "tools", "n64_test_runner.py")
BUILD    = os.path.join(REPO, "tools", "n64_build_rom.py")
CORE_LIB = "/usr/lib/x86_64-linux-gnu/libmupen64plus.so.2"
MIPS_GCC = "/opt/n64/bin/mips64-elf-gcc"


# ── Fixtures & helpers ───────────────────────────────────────────────────────

def _have_n64():
    return os.path.exists(CORE_LIB) and os.path.exists(MIPS_GCC)


skip_no_n64 = pytest.mark.skipif(
    not _have_n64(),
    reason="mupen64plus or mips64-elf toolchain not available"
)


def _build(c_src: str, title="Test") -> str:
    """Write C source to a temp file, build ROM, return ROM path."""
    td   = tempfile.mkdtemp(prefix="pak_n64hw_")
    csrc = os.path.join(td, "test.c")
    zrom = os.path.join(td, "test.z64")
    with open(csrc, "w") as f:
        f.write(textwrap.dedent(c_src))
    ret = subprocess.run(
        [sys.executable, BUILD, csrc, zrom, "--title", title],
        capture_output=True, text=True
    )
    if ret.returncode != 0:
        pytest.fail(f"ROM build failed:\n{ret.stderr}")
    return zrom


def _run(rom, expect, timeout=30):
    """Run ROM on mupen64plus; assert expected results."""
    cmd = [sys.executable, RUNNER, rom,
           "--timeout", str(timeout),
           "--expect"] + [str(v) for v in expect]
    ret = subprocess.run(cmd, capture_output=True, text=True,
                         timeout=timeout + 5)
    assert ret.returncode == 0, \
        f"N64 runner FAIL:\nSTDOUT:\n{ret.stdout}\nSTDERR:\n{ret.stderr}"


# ── Boilerplate C wrapper ────────────────────────────────────────────────────

_HEADER = """
#include <stdint.h>

#define MAGIC   ((volatile uint32_t*)0x80300000)
#define RESULTS ((volatile int32_t*)0x80300010)

static inline void __attribute__((noinline)) _store(int i, int32_t v) {
    RESULTS[i] = v;
}
"""

_FOOTER = """
int main(void) {
    *MAGIC = 0xDEADBEEFu;
    run_test();
    *MAGIC = 0xC0FFEE00u;
    for (;;) {}
    return 0;
}
"""


def _wrap(body: str) -> str:
    """Wrap a `run_test()` body in the standard N64 test harness."""
    return _HEADER + "\nstatic void run_test(void) {\n" + body + "\n}\n" + _FOOTER


# ── Tests ────────────────────────────────────────────────────────────────────

@skip_no_n64
def test_n64_basic_arithmetic():
    """Add, subtract, multiply give correct MIPS results."""
    rom = _build(_wrap("""
        _store(0, 3 + 4);          /* 7   */
        _store(1, 100 + 197);      /* 297 */
        _store(2, 6 * 7);          /* 42  */
        _store(3, 1000 - 423);     /* 577 */
        _store(4, -50 + 30);       /* -20 */
        _store(5, -3 * 8);         /* -24 */
        _store(6, 10 * 10 * 10);   /* 1000 */
        _store(7, 0);
    """), "ArithTest")
    _run(rom, [7, 297, 42, 577, -20, -24, 1000, 0])


@skip_no_n64
def test_n64_factorial():
    """Recursive and iterative factorial produce correct results."""
    rom = _build(_wrap("""
        int32_t fact(int32_t n) {
            int32_t r = 1;
            for (int32_t i = 2; i <= n; i++) r *= i;
            return r;
        }
        _store(0, fact(0));   /* 1   */
        _store(1, fact(1));   /* 1   */
        _store(2, fact(5));   /* 120 */
        _store(3, fact(6));   /* 720 */
        _store(4, fact(7));   /* 5040 */
        _store(5, fact(10));  /* 3628800 */
        _store(6, 0);
        _store(7, 0);
    """), "FactTest")
    _run(rom, [1, 1, 120, 720, 5040, 3628800, 0, 0])


@skip_no_n64
def test_n64_function_calls():
    """Multiple function calls, passing/returning values correctly."""
    rom = _build(_wrap("""
        int32_t add(int32_t a, int32_t b) { return a + b; }
        int32_t mul(int32_t a, int32_t b) { return a * b; }
        int32_t neg(int32_t a) { return -a; }
        int32_t abs_val(int32_t a) { return a < 0 ? -a : a; }

        _store(0, add(10, 20));           /* 30  */
        _store(1, mul(add(3, 4), 6));     /* 42  */
        _store(2, neg(-99));              /* 99  */
        _store(3, abs_val(-42));          /* 42  */
        _store(4, abs_val(42));           /* 42  */
        _store(5, add(mul(5,5), mul(3,3)));  /* 34 */
        _store(6, 0);
        _store(7, 0);
    """), "FuncTest")
    _run(rom, [30, 42, 99, 42, 42, 34, 0, 0])


@skip_no_n64
def test_n64_arrays():
    """Array read/write and indexing produce correct values."""
    rom = _build(_wrap("""
        int32_t arr[8] = {10, 20, 30, 40, 50, 60, 70, 80};
        int32_t sum = 0;
        for (int32_t i = 0; i < 8; i++) sum += arr[i];
        _store(0, arr[0]);   /* 10  */
        _store(1, arr[7]);   /* 80  */
        _store(2, sum);      /* 360 */
        arr[3] = 999;
        _store(3, arr[3]);   /* 999 */
        _store(4, arr[4]);   /* 50  */
        _store(5, 0);
        _store(6, 0);
        _store(7, 0);
    """), "ArrayTest")
    _run(rom, [10, 80, 360, 999, 50, 0, 0, 0])


@skip_no_n64
def test_n64_structs():
    """Struct field access and assignment are laid out correctly in MIPS."""
    rom = _build(_wrap("""
        typedef struct {
            int32_t x;
            int32_t y;
            int32_t z;
        } Vec3;

        Vec3 v;
        v.x = 1; v.y = 2; v.z = 3;
        _store(0, v.x);             /* 1  */
        _store(1, v.y);             /* 2  */
        _store(2, v.z);             /* 3  */
        _store(3, v.x + v.y + v.z);/* 6  */

        typedef struct {
            int32_t id;
            int32_t hp;
            int32_t mp;
        } Entity;

        Entity e; e.id = 42; e.hp = 100; e.mp = 50;
        _store(4, e.id);   /* 42  */
        _store(5, e.hp);   /* 100 */
        _store(6, e.mp);   /* 50  */
        _store(7, 0);
    """), "StructTest")
    _run(rom, [1, 2, 3, 6, 42, 100, 50, 0])


@skip_no_n64
def test_n64_control_flow():
    """Loops and conditionals produce correct branch behavior on MIPS."""
    rom = _build(_wrap("""
        /* while loop */
        int32_t s = 0, i = 1;
        while (i <= 10) { s += i; i++; }
        _store(0, s);       /* 55  */

        /* break */
        int32_t b = 0;
        for (int32_t j = 0; j < 100; j++) {
            if (j == 7) break;
            b = j;
        }
        _store(1, b);       /* 6   */

        /* nested if/else */
        int32_t x = 15;
        int32_t cat = (x < 10) ? 0 : (x < 20) ? 1 : 2;
        _store(2, cat);     /* 1   */

        /* do-while */
        int32_t d = 0, k = 0;
        do { d += k; k++; } while (k < 5);
        _store(3, d);       /* 10  */

        _store(4, 0); _store(5, 0); _store(6, 0); _store(7, 0);
    """), "CtrlTest")
    _run(rom, [55, 6, 1, 10, 0, 0, 0, 0])


@skip_no_n64
def test_n64_pointers():
    """Pointer arithmetic and indirect writes are correct on MIPS."""
    rom = _build(_wrap("""
        int32_t buf[4] = {0, 0, 0, 0};
        int32_t *p = buf;
        *p = 11;
        *(p+1) = 22;
        *(p+2) = 33;
        *(p+3) = 44;
        _store(0, buf[0]);  /* 11  */
        _store(1, buf[1]);  /* 22  */
        _store(2, buf[2]);  /* 33  */
        _store(3, buf[3]);  /* 44  */

        /* pointer difference */
        int32_t *q = &buf[3];
        _store(4, (int32_t)(q - p));   /* 3 */
        _store(5, 0); _store(6, 0); _store(7, 0);
    """), "PtrTest")
    _run(rom, [11, 22, 33, 44, 3, 0, 0, 0])


@skip_no_n64
def test_n64_bitwise():
    """Bitwise ops (AND, OR, XOR, shifts) produce correct MIPS output."""
    rom = _build(_wrap("""
        int32_t a = 0xFF;
        int32_t b = 0x0F;
        _store(0, a & b);       /* 0x0F = 15     */
        _store(1, a | b);       /* 0xFF = 255    */
        _store(2, a ^ b);       /* 0xF0 = 240    */
        _store(3, a << 4);      /* 0xFF0 = 4080  */
        _store(4, a >> 4);      /* 0x0F = 15     */
        _store(5, ~b & 0xFF);   /* 0xF0 = 240    */
        _store(6, 0); _store(7, 0);
    """), "BitTest")
    _run(rom, [15, 255, 240, 4080, 15, 240, 0, 0])


@skip_no_n64
def test_n64_signed_overflow():
    """Signed integer wraparound matches MIPS two's-complement semantics."""
    rom = _build(_wrap("""
        int32_t max  =  2147483647;
        int32_t min_ = -2147483648; /* note: -INT_MIN is UB in C; use literal */
        _store(0, max + 1);         /* wraps to INT_MIN = -2147483648 */
        _store(1, min_ - 1);        /* wraps to INT_MAX = 2147483647  */
        _store(2, max);             /* 2147483647  */
        _store(3, min_);            /* -2147483648 */
        _store(4, 0); _store(5, 0); _store(6, 0); _store(7, 0);
    """), "OverflowTest")
    _run(rom, [-2147483648, 2147483647, 2147483647, -2147483648, 0, 0, 0, 0])


@skip_no_n64
def test_n64_recursion():
    """Recursive Fibonacci on MIPS correctly uses the call stack."""
    rom = _build(_wrap("""
        int32_t fib(int32_t n) {
            if (n <= 1) return n;
            return fib(n-1) + fib(n-2);
        }
        _store(0, fib(0));   /* 0  */
        _store(1, fib(1));   /* 1  */
        _store(2, fib(5));   /* 5  */
        _store(3, fib(8));   /* 21 */
        _store(4, fib(10));  /* 55 */
        _store(5, 0); _store(6, 0); _store(7, 0);
    """), "RecurTest")
    _run(rom, [0, 1, 5, 21, 55, 0, 0, 0])
