/* Generated by Pak Compiler - demo.03_functions */
#ifndef PAKMOD_DEMO_03_FUNCTIONS_H
#define PAKMOD_DEMO_03_FUNCTIONS_H

#include <stdint.h>
#include <stdbool.h>

int32_t add(int32_t a, int32_t b);
float max(float a, float b);
float clamp(float val, float lo, float hi);
void reset(int32_t * ptr);
void increment(int32_t * ptr);

#endif /* PAKMOD_DEMO_03_FUNCTIONS_H */