/* Generated by Pak Compiler - demo.05_enums */
#ifndef PAKMOD_DEMO_05_ENUMS_H
#define PAKMOD_DEMO_05_ENUMS_H

#include <stdint.h>
#include <stdbool.h>

typedef enum {
    Direction_north,
    Direction_south,
    Direction_east,
    Direction_west,
} Direction;

typedef enum {
    GameState_title,
    GameState_playing,
    GameState_paused,
    GameState_gameover,
} GameState;

typedef enum {
    ButtonMask_a = 0x80,
    ButtonMask_b = 0x40,
    ButtonMask_start = 0x10,
    ButtonMask_z = 0x20,
} ButtonMask;

Direction opposite(Direction dir);

#endif /* PAKMOD_DEMO_05_ENUMS_H */