/* Generated by Pak Compiler - demo.06_variants */
#ifndef PAKMOD_DEMO_06_VARIANTS_H
#define PAKMOD_DEMO_06_VARIANTS_H

#include <stdint.h>
#include <stdbool.h>

typedef enum {
    Entity_tag_player,
    Entity_tag_enemy,
    Entity_tag_projectile,
    Entity_tag_empty,
} Entity_tag;

typedef struct {
    Entity_tag tag;
    union {
    } data;
} Entity;

typedef struct {
    float field0;
} Shape_circle;

typedef struct {
    float field0;
    float field1;
} Shape_rect;

typedef enum {
    Shape_tag_circle,
    Shape_tag_rect,
    Shape_tag_point,
} Shape_tag;

typedef struct {
    Shape_tag tag;
    union {
        Shape_circle circle;
        Shape_rect rect;
    } data;
} Shape;

typedef struct {
    uint8_t field0;
} Event_key_press;

typedef struct {
    int32_t field0;
    int32_t field1;
} Event_mouse_move;

typedef enum {
    Event_tag_key_press,
    Event_tag_mouse_move,
    Event_tag_quit,
} Event_tag;

typedef struct {
    Event_tag tag;
    union {
        Event_key_press key_press;
        Event_mouse_move mouse_move;
    } data;
} Event;

typedef struct {
    int32_t id;
    uint8_t port;
} Packet_connect;

typedef struct {
    int32_t len;
    uint32_t checksum;
} Packet_data;

typedef enum {
    Packet_tag_connect,
    Packet_tag_data,
    Packet_tag_disconnect,
} Packet_tag;

typedef struct {
    Packet_tag tag;
    union {
        Packet_connect connect;
        Packet_data data;
    } data;
} Packet;

float area(Shape s);
int32_t entity_id(Entity e);

#endif /* PAKMOD_DEMO_06_VARIANTS_H */