/* Generated by Pak Compiler - demo.08_arrays */
#ifndef PAKMOD_DEMO_08_ARRAYS_H
#define PAKMOD_DEMO_08_ARRAYS_H

#include <stdint.h>
#include <stdbool.h>

int32_t sum_array(int32_t * arr, int32_t len);
void fill(int32_t * arr, int32_t len, int32_t value);

#endif /* PAKMOD_DEMO_08_ARRAYS_H */
