/* Generated by Pak Compiler - demo.15_game_loop */
#ifndef PAKMOD_DEMO_15_GAME_LOOP_H
#define PAKMOD_DEMO_15_GAME_LOOP_H

#include <stdint.h>
#include <stdbool.h>

typedef struct GameState GameState;

struct GameState {
    int32_t x;
    int32_t y;
    bool running;
};

void update(GameState * gs);
void render(GameState * gs);

#endif /* PAKMOD_DEMO_15_GAME_LOOP_H */
