/* Generated by Pak Compiler - demo.20_multifile */
#ifndef PAKMOD_DEMO_20_MULTIFILE_H
#define PAKMOD_DEMO_20_MULTIFILE_H

#include <stdint.h>
#include <stdbool.h>


#endif /* PAKMOD_DEMO_20_MULTIFILE_H */
