/* Generated by Pak Compiler - demo.23_containers */
#ifndef PAKMOD_DEMO_23_CONTAINERS_H
#define PAKMOD_DEMO_23_CONTAINERS_H

#include <stdint.h>
#include <stdbool.h>

typedef struct {
    float x;
    float y;
    int32_t active;
} Bullet;


#endif /* PAKMOD_DEMO_23_CONTAINERS_H */