/* Generated by Pak Compiler - demo.26_closures */
#ifndef PAKMOD_DEMO_26_CLOSURES_H
#define PAKMOD_DEMO_26_CLOSURES_H

#include <stdint.h>
#include <stdbool.h>

int32_t apply(int32_t (*)(int32_t) f, int32_t x);
int32_t compose(int32_t (*)(int32_t) f, int32_t (*)(int32_t) g, int32_t x);
int32_t map_sum(int32_t (*)(int32_t) f, int32_t lo, int32_t hi);

#endif /* PAKMOD_DEMO_26_CLOSURES_H */
