/* Generated by Pak Compiler - demo.32_t3d_cube */
#ifndef PAKMOD_DEMO_32_T3D_CUBE_H
#define PAKMOD_DEMO_32_T3D_CUBE_H

#include <stdint.h>
#include <stdbool.h>

typedef struct GameState GameState;

struct GameState {
    T3DViewport vp;
    T3DMat4 model;
    float ry;
    float rx;
    float spy;
    float spx;
    bool running;
};

void update(pak_joypad_status_t pad);
void init_scene(void);

#endif /* PAKMOD_DEMO_32_T3D_CUBE_H */
