#!/usr/bin/env bash
# Compare the Tcl codegen's C output against the Python backend (oracle) on the
# canonical examples. A file MATCHES when the generated C is byte-identical
# (after normalizing the path-bearing header comment, exactly as
# tests/test_snapshots.py does). Files the Tcl codegen can't yet lower print an
# UNPORTED marker and are counted separately — never as a content mismatch.
#
# Oracle: `pak explain` (the installed CLI). If pak is not on PATH, the snapshot
# files in tests/snapshots are used as the oracle instead.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
cd "$REPO"

HAVE_PAK=0
command -v pak >/dev/null 2>&1 && HAVE_PAK=1

# Normalize the per-file header comment so output is path-independent.
norm() { sed -E 's@/\* Generated by Pak Compiler - .+ \*/@/* Generated by Pak Compiler */@'; }

oracle() {  # $1 = pak file
    local f="$1"
    if [ "$HAVE_PAK" = "1" ]; then
        pak explain "$f" 2>/dev/null | norm
    else
        local snap="tests/snapshots/$(basename "$f" .pk64).c"
        [ -f "$snap" ] && norm < "$snap"
    fi
}

match=0; unported=0; mismatch=0; mism_files=""
while IFS= read -r f; do
    tcl="$(tclsh "$HERE/cg_dump.tcl" "$f" 2>/dev/null)"
    if printf '%s' "$tcl" | head -1 | grep -q '^UNPORTED\|^ERROR'; then
        unported=$((unported+1))
        [ "${SHOW_UNPORTED:-0}" = "1" ] && echo "UNPORTED: $f -> $(printf '%s' "$tcl" | head -1)"
        continue
    fi
    py="$(oracle "$f" | norm)"
    tcl="$(printf '%s' "$tcl" | norm)"
    if [ "$py" = "$tcl" ]; then
        match=$((match+1))
    else
        mismatch=$((mismatch+1))
        mism_files="$mism_files $f"
        if [ "${VERBOSE:-0}" = "1" ]; then
            echo "=== MISMATCH: $f ==="
            diff <(printf '%s' "$py") <(printf '%s' "$tcl") | head -40
        fi
    fi
done < <(find examples/canonical -name '*.pk64' | sort)

total=$((match+unported+mismatch))
echo "codegen parity: MATCH=$match  UNPORTED=$unported  MISMATCH=$mismatch  (of $total canonical)"
[ -n "$mism_files" ] && echo -e "MISMATCHED:\n$(echo $mism_files | tr ' ' '\n')"
[ "$mismatch" -eq 0 ]
