#!/usr/bin/env bash
# Compare the Tcl codegen's C output against the checked-in snapshots in
# tests/snapshots/*.c on the canonical examples. A file MATCHES when the
# generated C is byte-identical (after normalizing the path-bearing header
# comment). Files the Tcl codegen can't yet lower print an UNPORTED marker and
# are counted separately — never as a content mismatch.
#
# The snapshots are the ONLY oracle. `pak explain` is not usable as one: it
# calls the same pak::generate this script dumps, so comparing against it
# compares the codegen to itself and passes even when every snapshot is empty.
#
# Snapshots are regenerated with REGEN=1 (requires pak on PATH).
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
SNAP_DIR="$REPO/tests/snapshots"
cd "$REPO"

# Normalize the per-file header comment so output is path-independent.
norm() { sed -E 's@/\* Generated by Pak Compiler - .+ \*/@/* Generated by Pak Compiler */@'; }

match=0; unported=0; mismatch=0; missing=0; mism_files=""
while IFS= read -r f; do
    name=$(basename "$f" .pk64)
    tcl="$(tclsh "$HERE/cg_dump.tcl" "$f" 2>/dev/null)"
    if printf '%s' "$tcl" | head -1 | grep -q '^UNPORTED\|^ERROR'; then
        unported=$((unported+1))
        [ "${SHOW_UNPORTED:-0}" = "1" ] && echo "UNPORTED: $f -> $(printf '%s' "$tcl" | head -1)"
        continue
    fi

    snap="$SNAP_DIR/${name}.c"
    if [ "${REGEN:-0}" = "1" ]; then
        pak explain "$f" > "$snap" 2>/dev/null
    fi
    if [ ! -s "$snap" ]; then
        # An absent or EMPTY snapshot is a failure, not a free pass: a truncated
        # snapshot file is how this gate silently stopped checking anything.
        missing=$((missing+1))
        mism_files="$mism_files $f"
        echo "MISSING OR EMPTY SNAPSHOT: $snap"
        continue
    fi

    want="$(norm < "$snap")"
    got="$(printf '%s' "$tcl" | norm)"
    if [ "$want" = "$got" ]; then
        match=$((match+1))
    else
        mismatch=$((mismatch+1))
        mism_files="$mism_files $f"
        if [ "${VERBOSE:-0}" = "1" ]; then
            echo "=== MISMATCH: $f ==="
            diff <(printf '%s\n' "$want") <(printf '%s\n' "$got") | head -40
        fi
    fi
done < <(find examples/canonical -name '*.pk64' | sort)

total=$((match+unported+mismatch+missing))
echo "codegen parity: MATCH=$match  UNPORTED=$unported  MISMATCH=$mismatch  MISSING=$missing  (of $total canonical)"
[ -n "$mism_files" ] && echo -e "FAILED:\n$(echo $mism_files | tr ' ' '\n')"
[ "$((mismatch+missing))" -eq 0 ]
