#!/usr/bin/env bash
# Integration parity: the Tcl `pak` CLI vs the Python `pak` CLI on byte-exact
# surfaces — explain (c/mips), build artifacts (c/mips), init scaffolding, pack.
# (pak check's diagnostic *locations* are governed by the project-wide deferred
# AST position tracking — the schema omits line/col by design — so check-with-
# diagnostics is intentionally not compared here; check-on-clean is.)
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"; cd "$REPO"
PY="PYTHONPATH=$REPO python3 -m pak"
TCL="tclsh $REPO/tcl/cli.tcl"
norm() { sed -E 's@/\* Generated by Pak Compiler.*\*/@/*G*/@'; }
fail=0
ok() { echo "  $1: MATCH"; }
bad() { echo "  $1: MISMATCH"; fail=1; }

mksample() { local d=$1; mkdir -p "$d/src"; printf '[project]\nname = "demo"\nrom_title = "DEMO GAME"\nsave_type = "eeprom4k"\n\n[display]\nresolution = "320x240"\nbit_depth = 16\nframebuffers = 3\n\n[dependencies]\ntiny3d = false\n\n[build]\noptimization = "debug"\n' > "$d/pak.toml"
printf 'use n64.display\n\nstruct P { x: i32, y: i32 }\nfn mk() -> P { return P { x: 1, y: 2 } }\nentry { display.init(0,2,3,0,1)\n  let p = mk()\n  loop { } }\n' > "$d/src/main.pk64"; }

T=$(mktemp -d)
# explain c + mips
f=examples/canonical/05_enums.pk64
diff <(eval $PY explain "$f" 2>&1|norm) <(eval $TCL explain "$f" 2>&1|norm) >/dev/null && ok "explain-c" || bad "explain-c"
diff <(eval $PY explain --backend mips "$f" 2>&1) <(eval $TCL explain --backend mips "$f" 2>&1) >/dev/null && ok "explain-mips" || bad "explain-mips"
# build c
mksample "$T/bc_py"; mksample "$T/bc_tcl"
diff <(cd "$T/bc_py" && eval $PY build 2>&1) <(cd "$T/bc_tcl" && eval $TCL build 2>&1) >/dev/null && ok "build-c-stdout" || bad "build-c-stdout"
diff <(norm <"$T/bc_py/build/src/main.c") <(norm <"$T/bc_tcl/build/src/main.c") >/dev/null && ok "build-c-out" || bad "build-c-out"
diff "$T/bc_py/Makefile" "$T/bc_tcl/Makefile" >/dev/null && ok "build-makefile" || bad "build-makefile"
# build mips
mksample "$T/bm_py"; mksample "$T/bm_tcl"
diff <(cd "$T/bm_py" && eval $PY build --backend mips 2>&1) <(cd "$T/bm_tcl" && eval $TCL build --backend mips 2>&1) >/dev/null && ok "build-mips-stdout" || bad "build-mips-stdout"
diff "$T/bm_py/build/src/main.s" "$T/bm_tcl/build/src/main.s" >/dev/null && ok "build-mips-out" || bad "build-mips-out"
# init
mkdir -p "$T/i_py" "$T/i_tcl"
(cd "$T/i_py" && eval $PY init g >/dev/null 2>&1); (cd "$T/i_tcl" && eval $TCL init g >/dev/null 2>&1)
for ff in pak.toml src/main.pk64 .gitignore; do
  diff "$T/i_py/g/$ff" "$T/i_tcl/g/$ff" >/dev/null && ok "init-$ff" || bad "init-$ff"
done
# pack
mkdir -p "$T/pk/build/sprites"; printf 'SPRITE' >"$T/pk/build/sprites/p.sprite"; printf 'SND' >"$T/pk/build/s.wav64"
(cd "$T/pk" && eval $PY pack -o py.pakfs >/dev/null 2>&1); (cd "$T/pk" && eval $TCL pack -o tcl.pakfs >/dev/null 2>&1)
cmp "$T/pk/py.pakfs" "$T/pk/tcl.pakfs" >/dev/null && ok "pack-bytes" || bad "pack-bytes"
# check on clean (no diagnostics → no location lines)
mksample "$T/ck_py"; mksample "$T/ck_tcl"
diff <(cd "$T/ck_py" && eval $PY check 2>&1) <(cd "$T/ck_tcl" && eval $TCL check 2>&1) >/dev/null && ok "check-clean" || bad "check-clean"
rm -rf "$T"
[ $fail -eq 0 ] && echo "cli parity: ALL MATCH" || echo "cli parity: MISMATCH"
exit $fail
