#!/usr/bin/env tclsh
# Generate the MODULE_API index in STDLIB.md from the compiler's tables.
#
#   tclsh tcl/tools/gen_stdlib.tcl           # rewrite the generated block
#   tclsh tcl/tools/gen_stdlib.tcl --check   # exit 1 if STDLIB.md is stale
#
# The rest of STDLIB.md (builtins, types, handwritten module prose) is not
# touched. Markers:
#   <!-- BEGIN GENERATED MODULE API -->
#   <!-- END GENERATED MODULE API -->

set HERE [file dirname [file normalize [info script]]]
set REPO [file normalize [file join $HERE .. ..]]
source [file join $HERE .. module_api.tcl]

set STDLIB [file join $REPO STDLIB.md]
set BEGIN "<!-- BEGIN GENERATED MODULE API -->"
set END   "<!-- END GENERATED MODULE API -->"

proc pak::gen_stdlib_block {} {
    set lines {}
    lappend lines $::BEGIN
    lappend lines ""
    lappend lines "This index is generated by `tclsh tcl/tools/gen_stdlib.tcl` from"
    lappend lines "`tcl/module_api.tcl` (union of `CG_API` + `CG_API_LAMBDA`)."
    lappend lines "A function not listed here is `E010` at `pak check`, never silently"
    lappend lines "lowered. The **standalone** column is yes only when the C symbol is"
    lappend lines "defined in `runtime/standalone/runtime.pk64`; `pak check --backend mips`"
    lappend lines "rejects a no."
    lappend lines ""
    lappend lines "| Module | Function | C symbol | libdragon | standalone |"
    lappend lines "|--------|----------|----------|-----------|------------|"

    set n 0
    set standalone 0
    foreach key [pak::module_api_keys] {
        lassign $key mod fn
        set sym [pak::module_api_symbol $mod $fn]
        set mips [expr {[pak::mips_hal_has $mod $fn] ? "yes" : "no"}]
        if {$mips eq "yes"} { incr standalone }
        lappend lines "| `$mod` | `$fn` | `$sym` | yes | $mips |"
        incr n
    }
    lappend lines ""
    lappend lines "**$n functions** across the module surface; **$standalone** exist on the standalone HAL."
    lappend lines ""
    lappend lines $::END
    return [join $lines "\n"]
}

proc pak::stdlib_with_block {src block} {
    set bidx [string first $::BEGIN $src]
    set eidx [string first $::END $src]
    if {$bidx >= 0 && $eidx >= 0 && $eidx > $bidx} {
        set eidx [expr {$eidx + [string length $::END]}]
        # Keep a single trailing newline after the block.
        set after [string range $src $eidx end]
        if {![string match "\n*" $after]} { set after "\n$after" }
        return "[string range $src 0 [expr {$bidx - 1}]]$block$after"
    }
    # No markers: insert at the start of the N64 Modules section, after its intro.
    set needle "## N64 Modules"
    set nidx [string first $needle $src]
    if {$nidx < 0} {
        return -code error "STDLIB.md has no '## N64 Modules' heading to insert the index into"
    }
    # Find the first ### after that heading (handwritten display section).
    set rest [string range $src $nidx end]
    set hidx [string first "\n### " $rest]
    if {$hidx < 0} {
        return -code error "STDLIB.md: no '###' subsection under N64 Modules"
    }
    set abs [expr {$nidx + $hidx + 1}]
    return "[string range $src 0 [expr {$abs - 1}]]$block\n\n[string range $src $abs end]"
}

set src [read [open $STDLIB r]]
set block [pak::gen_stdlib_block]
set new [pak::stdlib_with_block $src $block]

set check [expr {"--check" in $argv}]
if {$check} {
    if {$src eq $new} {
        puts "STDLIB.md generated index is up to date."
        exit 0
    }
    puts stderr "STDLIB.md generated index is stale. Run: tclsh tcl/tools/gen_stdlib.tcl"
    exit 1
}

set fh [open $STDLIB w]
puts -nonewline $fh $new
close $fh
puts "Wrote generated MODULE_API index to STDLIB.md"
