#!/usr/bin/env python3
"""Print a Tcl AST-walker skeleton covering every node kind.

The output is a `switch` over all 89 kinds plus a matching
pak::assert_exhaustive call, so a new walker (checker/typechecker/codegen)
starts complete and stays honest as it's edited. Printed to stdout — paste it
into the new component, don't manage it as a file.

Usage:  python3 tcl/tools/gen_visitor.py <component_name>
"""
import dataclasses
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
import pak.ast as A  # noqa: E402

kinds = sorted(
    n for n in dir(A)
    if isinstance(getattr(A, n), type) and dataclasses.is_dataclass(getattr(A, n))
)
comp = sys.argv[1] if len(sys.argv) > 1 else "visit"

print(f"# --- {comp} AST walker skeleton (generated by tcl/tools/gen_visitor.py) ---")
print(f"# Fill in each case. pak::assert_exhaustive flags typo'd or forgotten kinds.")
print(f"pak::assert_exhaustive {comp} [list \\")
for chunk_line in textwrap.wrap(" ".join(kinds), width=70):
    print(f"    {chunk_line} \\")
print("]")
print()
print(f"proc pak::{comp}_node {{node ctx}} {{")
print(f"    switch -- [lindex $node 1] {{")
for k in kinds:
    print(f"        {k} {{ }}")
print(f'        default {{ return -code error "{comp}: unhandled [lindex $node 1]" }}')
print("    }")
print("}")
