/* Generated by Pak Compiler - examples/canonical/13_extern.pk64 */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include "pak_libdragon.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
/* extern "C" */
/* memset: already declared by the C standard headers */
/* memcpy: already declared by the C standard headers */
/* strlen: already declared by the C standard headers */

/* extern const uint32_t TICKS_PER_SECOND; (C macro passthrough) */

/* extern const uint32_t RDPQ_COMBINER_FLAT; (C macro passthrough) */

static uint8_t buf[64];

static uint32_t sink = 0;

int main(void) {
    memset(&buf[0], 0, 64);
    uint8_t src[8]; /* undefined */
    memset(&src[0], 0xA5, 8);
    memcpy(&buf[0], &src[0], 8);
    char * msg = "hello";
    sink = strlen(msg);
    sink = TICKS_PER_SECOND;
    buf[0] = (uint8_t)RDPQ_COMBINER_FLAT;
    return 0;
}

