/* Generated by Pak Compiler - examples/canonical/24_slices.pk64 */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include "pak_libdragon.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }

/* -- User type forward declarations -- */
typedef struct Point Point;

/* -- User types -- */
struct Point {
    int32_t x;
    int32_t y;
};


typedef struct { int32_t *data; int32_t len; } PakSlice_int32_t;
typedef struct { Point *data; int32_t len; } PakSlice_Point;
int32_t sum(PakSlice_int32_t s) {
    int32_t total = 0;
    for (int _i_item = 0; _i_item < (s).len; _i_item++) {
        __typeof__((s).data[0]) item = (s).data[_i_item];
        total += item;
    }
    return total;
}

int32_t find_max(PakSlice_int32_t s) {
    int32_t best = (s).data[0];
    for (int _i_item = 0; _i_item < (s).len; _i_item++) {
        __typeof__((s).data[0]) item = (s).data[_i_item];
        if (item > best) {
            best = item;
        }
    }
    return best;
}

void double_all(PakSlice_int32_t s) {
    for (int i = 0; i < s.len; i++) {
        (s).data[i] = ((s).data[i] * 2);
    }
}

int32_t sum_x(PakSlice_Point pts) {
    int32_t total = 0;
    for (int _i_p = 0; _i_p < (pts).len; _i_p++) {
        __typeof__((pts).data[0]) p = (pts).data[_i_p];
        total += p.x;
    }
    return total;
}

static int32_t sink = 0;

int main(void) {
    int32_t nums[8]; /* undefined */
    nums[0] = 10;
    nums[1] = 20;
    nums[2] = 30;
    nums[3] = 40;
    nums[4] = 50;
    nums[5] = 60;
    nums[6] = 70;
    nums[7] = 80;
    PakSlice_int32_t full = (PakSlice_int32_t){ .data = &(nums)[0], .len = (8) - (0) };
    sink = full.len;
    PakSlice_int32_t first_half = (PakSlice_int32_t){ .data = &(nums)[0], .len = (4) - (0) };
    sink = first_half.len;
    sink = sum(first_half);
    PakSlice_int32_t second_half = (PakSlice_int32_t){ .data = &(nums)[4], .len = (8) - (4) };
    sink = sum(second_half);
    sink = find_max(full);
    PakSlice_int32_t part = (PakSlice_int32_t){ .data = &(nums)[0], .len = (4) - (0) };
    double_all(part);
    sink = nums[0];
    sink = sum(first_half);
    Point points[4]; /* undefined */
    points[0] = (Point){.x = 1, .y = 10};
    points[1] = (Point){.x = 2, .y = 20};
    points[2] = (Point){.x = 3, .y = 30};
    points[3] = (Point){.x = 4, .y = 40};
    PakSlice_Point pt_slice = (PakSlice_Point){ .data = &(points)[0], .len = (4) - (0) };
    sink = pt_slice.len;
    sink = sum_x(pt_slice);
    PakSlice_Point mid = (PakSlice_Point){ .data = &(points)[1], .len = (3) - (1) };
    sink = mid.len;
    return 0;
}

