/* Generated by Pak Compiler - NORMALIZED */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }

/* -- Tuple types -- */
typedef struct {
    int32_t f0;
    int32_t f1;
} PakTuple2_int32_t_int32_t;
typedef struct {
    int32_t f0;
    float f1;
} PakTuple2_int32_t_float;
typedef struct {
    bool f0;
    int32_t f1;
} PakTuple2_bool_int32_t;
PakTuple2_int32_t_int32_t min_max(int32_t a, int32_t b) {
    if (a < b) {
        return (PakTuple2_int32_t_int32_t){.f0 = a, .f1 = b};
    }
    return (PakTuple2_int32_t_int32_t){.f0 = b, .f1 = a};
}

PakTuple2_int32_t_int32_t div_rem(int32_t a, int32_t b) {
    int32_t q = (a / b);
    int32_t r = (a - (q * b));
    return (PakTuple2_int32_t_int32_t){.f0 = q, .f1 = r};
}

int32_t pair_sum(PakTuple2_int32_t_int32_t t) {
    return ((t).f0 + (t).f1);
}

static int32_t sink_i = 0;

static float sink_f = 0.0f;

int main(void) {
    PakTuple2_int32_t_float t = (PakTuple2_int32_t_float){.f0 = 42, .f1 = 3.14f};
    sink_i = (t).f0;
    sink_f = (t).f1;
    PakTuple2_bool_int32_t flag_pair = (PakTuple2_bool_int32_t){.f0 = true, .f1 = 7};
    sink_i = (flag_pair).f1;
    __auto_type bounds = min_max(15, 3);
    sink_i = (bounds).f0;
    sink_i = (bounds).f1;
    PakTuple2_int32_t_int32_t mm = min_max(100, 200);
    sink_i = (mm).f0;
    sink_i = (mm).f1;
    __auto_type dr = div_rem(17, 5);
    sink_i = (dr).f0;
    sink_i = (dr).f1;
    PakTuple2_int32_t_int32_t p = (PakTuple2_int32_t_int32_t){.f0 = 10, .f1 = 32};
    sink_i = pair_sum(p);
    __auto_type result = min_max(99, 1);
    __auto_type lo = (result).f0;
    __auto_type hi = (result).f1;
    sink_i = (hi - lo);
    return 0;
}

