/* Generated by Pak Compiler - examples/canonical/26_closures.pk64 */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }
int32_t apply(int32_t (*)(int32_t) f, int32_t x) {
    return f(x);
}

int32_t compose(int32_t (*)(int32_t) f, int32_t (*)(int32_t) g, int32_t x) {
    return f(g(x));
}

int32_t map_sum(int32_t (*)(int32_t) f, int32_t lo, int32_t hi) {
    int32_t total = 0;
    for (int i = lo; i < hi; i++) {
        total += f(i);
    }
    return total;
}

static int32_t sink = 0;

int main(void) {
    int32_t _pak_clo_0(int32_t x) {
        return (x * 2);
    }
    int32_t (*)(int32_t) double = _pak_clo_0;
    sink = double(5);
    int32_t _pak_clo_0(int32_t x) {
        return (x * x);
    }
    int32_t (*)(int32_t) square = _pak_clo_0;
    sink = square(4);
    int32_t _pak_clo_0(int32_t x) {
        return (0 - x);
    }
    int32_t (*)(int32_t) negate = _pak_clo_0;
    sink = negate(7);
    sink = apply(double, 6);
    sink = apply(square, 3);
    sink = compose(double, square, 2);
    int32_t _pak_clo_0(int32_t x) {
        return (x + 100);
    }
    sink = apply(_pak_clo_0, 5);
    sink = map_sum(double, 1, 5);
    int32_t base = 10;
    int32_t _pak_clo_0(int32_t x) {
        return (x + base);
    }
    int32_t (*)(int32_t) add_base = _pak_clo_0;
    sink = add_base(5);
    sink = apply(add_base, 3);
    return 0;
}

