/* Generated by Pak Compiler - examples/canonical/27_dyn_trait.pk64 */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include "pak_libdragon.h"


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }

/* -- User type forward declarations -- */
typedef struct Circle Circle;
typedef struct Rect Rect;

/* -- User types -- */
struct Circle {
    float radius;
};

struct Rect {
    float width;
    float height;
};

/* trait Shape */
typedef struct {
    float (*area)(void *);
    float (*perimeter)(void *);
} Shape_vtable;

typedef struct {
    void *self;
    const Shape_vtable *vtable;
} Shape;

/* impl Circle for Shape */
float Circle_area(Circle * self) {
    return ((3.14159f * self->radius) * self->radius);
}

float Circle_perimeter(Circle * self) {
    return (6.28318f * self->radius);
}

static float _pak_Shape_area_Circle(void *_self) {
    return Circle_area((Circle *)_self);
}

static float _pak_Shape_perimeter_Circle(void *_self) {
    return Circle_perimeter((Circle *)_self);
}

static const Shape_vtable _pak_Shape_vtable_Circle = {
    .area = _pak_Shape_area_Circle,
    .perimeter = _pak_Shape_perimeter_Circle,
};

static inline Shape Shape_from_Circle(Circle *p) {
    return (Shape){ .self = (void *)p, .vtable = &_pak_Shape_vtable_Circle };
}

/* impl Rect for Shape */
float Rect_area(Rect * self) {
    return (self->width * self->height);
}

float Rect_perimeter(Rect * self) {
    return (2.0f * (self->width + self->height));
}

static float _pak_Shape_area_Rect(void *_self) {
    return Rect_area((Rect *)_self);
}

static float _pak_Shape_perimeter_Rect(void *_self) {
    return Rect_perimeter((Rect *)_self);
}

static const Shape_vtable _pak_Shape_vtable_Rect = {
    .area = _pak_Shape_area_Rect,
    .perimeter = _pak_Shape_perimeter_Rect,
};

static inline Shape Shape_from_Rect(Rect *p) {
    return (Shape){ .self = (void *)p, .vtable = &_pak_Shape_vtable_Rect };
}

float get_area(Shape s) {
    return (s.vtable->area)(s.self);
}

float get_perimeter(Shape s) {
    return (s.vtable->perimeter)(s.self);
}

static float sink_f = 0.0f;

static int32_t sink_i = 0;

int main(void) {
    __auto_type c = (Circle){.radius = 5.0f};
    Shape shape_c = Shape_from_Circle(&c);
    sink_f = (shape_c.vtable->area)(shape_c.self);
    sink_f = (shape_c.vtable->perimeter)(shape_c.self);
    __auto_type r = (Rect){.width = 4.0f, .height = 6.0f};
    Shape shape_r = Shape_from_Rect(&r);
    sink_f = (shape_r.vtable->area)(shape_r.self);
    sink_f = (shape_r.vtable->perimeter)(shape_r.self);
    sink_f = get_area(shape_c);
    sink_f = get_area(shape_r);
    sink_f = get_perimeter(shape_r);
    sink_f = Circle_area(&c);
    sink_f = Rect_area(&r);
    sink_i = (int32_t)(shape_r.vtable->area)(shape_r.self);
    return 0;
}

