/* Generated by Pak Compiler - examples/canonical/31_demo3d.pk64 */

#include <libdragon.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include "pak_math.h"
#include "pak_containers.h"
#include "pak_libdragon.h"
#include <display.h>
#include <joypad.h>
#include <rdpq.h>
#include <rdpq_attach.h>
#include <rdpq_mode.h>
#include <rdpq_rect.h>
#include <rdpq_tri.h>
#include <n64sys.h>
#include <n64sys.h>
#include <math.h>
#include "pak_rand.h"

static uint32_t _pak_last_tick = 0;
static inline float _pak_delta_time(void) {
    uint32_t now = TICKS_READ();
    float dt = (float)TIMER_MICROS(now - _pak_last_tick) / 1000000.0f;
    _pak_last_tick = now;
    return dt;
}


/* -- Pak runtime types -- */
typedef struct { const char *data; int32_t len; } PakStr;
typedef struct { uint8_t *base; uint8_t *ptr; size_t capacity; } PakArena;
static inline PakStr pak_str_from_cstr(const char *s) {
    return (PakStr){ .data = s, .len = (int32_t)strlen(s) }; }
static inline bool pak_str_eq(PakStr a, PakStr b) {
    return a.len == b.len && memcmp(a.data, b.data, (size_t)a.len) == 0; }
static inline void *pak_arena_alloc(PakArena *a, size_t sz) {
    sz = (sz + 7) & ~(size_t)7;  /* 8-byte align */
    if (a->ptr + sz > a->base + a->capacity) return NULL;
    void *p = a->ptr; a->ptr += sz; return p; }
static inline void pak_arena_reset(PakArena *a) { a->ptr = a->base; }

/* -- User type forward declarations -- */
typedef struct Star Star;
typedef struct Cube Cube;
typedef struct GameState GameState;

/* -- User types -- */
struct Star {
    int32_t sx;
    int32_t sy;
    float z;
};

struct Cube {
    float tx;
    float ty;
    float tz;
    float sc;
    float ry;
    float rx;
    float spy;
    float spx;
    uint32_t col0;
    uint32_t col1;
    uint32_t col2;
};


typedef struct { Star *data; int32_t len; } PakSlice_Star;

/* -- Container types -- */
typedef struct {
    Star data[64];
    int32_t len;
} _PakList_Star_64;


/* -- User types with generated-type fields -- */
struct GameState {
    _PakList_Star_64 stars;
    Cube cube_a;
    Cube cube_b;
    int32_t frame;
    bool running;
};


/* -- Function prototypes -- */
void Cube_spin(Cube * self);
uint32_t Cube_face_col(Cube * self, int32_t fi);
int32_t edge_x_at(int32_t ax, int32_t ay, int32_t bx, int32_t by, int32_t y);
__attribute__((hot))
void fill_quad(int32_t x0, int32_t y0, int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, uint32_t col);
__attribute__((hot))
void render_cube(Cube * cube);
void render_sky_ground(void);
void render_stars(void);
void update(pak_joypad_status_t pad);
void init_scene(void);
enum { SCREEN_W = 320 };

enum { SCREEN_H = 240 };

enum { HALF_W = 160 };

enum { HALF_H = 120 };

static const float FOV = 200.0f;

static const float TAU = 6.2832f;

static float cv_x[8] = {-1.0f, 1.0f, 1.0f, -1.0f, -1.0f, 1.0f, 1.0f, -1.0f};

static float cv_y[8] = {-1.0f, -1.0f, 1.0f, 1.0f, -1.0f, -1.0f, 1.0f, 1.0f};

static float cv_z[8] = {-1.0f, -1.0f, -1.0f, -1.0f, 1.0f, 1.0f, 1.0f, 1.0f};

static int32_t cf_idx[24] = {0, 1, 2, 3, 5, 4, 7, 6, 4, 0, 3, 7, 1, 5, 6, 2, 3, 2, 6, 7, 4, 5, 1, 0};

static uint32_t sky_col[6] = {0x050C14FF, 0x0A1828FF, 0x10243AFF, 0x182F4CFF, 0x1F3A5FFF, 0x2A4A70FF};

static uint32_t gnd_col[8] = {0x3C2B1AFF, 0x352717FF, 0x2E2214FF, 0x281E11FF, 0x221A0EFF, 0x1C160BFF, 0x161208FF, 0x100E06FF};

static GameState gs;

void Cube_spin(Cube * self) {
    self->ry += self->spy;
    self->rx += self->spx;
    if (self->ry > TAU) {
        self->ry -= TAU;
    }
    if (self->rx > TAU) {
        self->rx -= TAU;
    }
}

uint32_t Cube_face_col(Cube * self, int32_t fi) {
    if ((fi == 0) || (fi == 1)) {
        return self->col0;
    }
    if ((fi == 2) || (fi == 3)) {
        return self->col1;
    }
    return self->col2;
}

int32_t edge_x_at(int32_t ax, int32_t ay, int32_t bx, int32_t by, int32_t y) {
    float t = ((float)(y - ay) / (float)(by - ay));
    return (int32_t)((float)ax + (t * (float)(bx - ax)));
}

__attribute__((hot))
void fill_quad(int32_t x0, int32_t y0, int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, uint32_t col) {
    int32_t ymin = pak_min_i32(pak_min_i32(y0, y1), pak_min_i32(y2, y3));
    int32_t ymax = pak_max_i32(pak_max_i32(y0, y1), pak_max_i32(y2, y3));
    if (ymin < 0) {
        ymin = 0;
    }
    if (ymax > SCREEN_H) {
        ymax = SCREEN_H;
    }
    pak_rdpq_set_fill_color(col);
    for (int y = ymin; y < ymax; y++) {
        int32_t xl = SCREEN_W;
        int32_t xr = -1;
        if (((y0 <= y) && (y < y1)) || ((y1 <= y) && (y < y0))) {
            int32_t x = edge_x_at(x0, y0, x1, y1, y);
            if (x < xl) {
                xl = x;
            }
            if (x > xr) {
                xr = x;
            }
        }
        if (((y1 <= y) && (y < y2)) || ((y2 <= y) && (y < y1))) {
            int32_t x = edge_x_at(x1, y1, x2, y2, y);
            if (x < xl) {
                xl = x;
            }
            if (x > xr) {
                xr = x;
            }
        }
        if (((y2 <= y) && (y < y3)) || ((y3 <= y) && (y < y2))) {
            int32_t x = edge_x_at(x2, y2, x3, y3, y);
            if (x < xl) {
                xl = x;
            }
            if (x > xr) {
                xr = x;
            }
        }
        if (((y3 <= y) && (y < y0)) || ((y0 <= y) && (y < y3))) {
            int32_t x = edge_x_at(x3, y3, x0, y0, y);
            if (x < xl) {
                xl = x;
            }
            if (x > xr) {
                xr = x;
            }
        }
        if (xl <= xr) {
            if (xl < 0) {
                xl = 0;
            }
            if (xr > SCREEN_W) {
                xr = SCREEN_W;
            }
            rdpq_fill_rectangle(xl, y, xr, (y + 1));
        }
    }
}

__attribute__((hot))
void render_cube(Cube * cube) {
    int32_t px[8]; /* undefined */
    int32_t py[8]; /* undefined */
    int32_t vis[8]; /* undefined */
    float cy = cosf(cube->ry);
    float sy = sinf(cube->ry);
    float cxx = cosf(cube->rx);
    float sxx = sinf(cube->rx);
    for (int vi = 0; vi < 8; vi++) {
        float vx = (cv_x[vi] * cube->sc);
        float vy = (cv_y[vi] * cube->sc);
        float vz = (cv_z[vi] * cube->sc);
        float rx1 = ((vx * cy) + (vz * sy));
        float rz1 = ((-vx * sy) + (vz * cy));
        float ry1 = ((vy * cxx) - (rz1 * sxx));
        float rz2 = ((vy * sxx) + (rz1 * cxx));
        float wx = (rx1 + cube->tx);
        float wy = (ry1 + cube->ty);
        float wz = (rz2 + cube->tz);
        vis[vi] = 0;
        if (wz > 0.4f) {
            px[vi] = ((int32_t)((wx * FOV) / wz) + HALF_W);
            py[vi] = ((int32_t)((-wy * FOV) / wz) + HALF_H);
            vis[vi] = 1;
        }
    }
    for (int fi = 0; fi < 6; fi++) {
        int32_t i0 = cf_idx[((fi * 4) + 0)];
        int32_t i1 = cf_idx[((fi * 4) + 1)];
        int32_t i2 = cf_idx[((fi * 4) + 2)];
        int32_t i3 = cf_idx[((fi * 4) + 3)];
        if ((((vis[i0] == 0) || (vis[i1] == 0)) || (vis[i2] == 0)) || (vis[i3] == 0)) {
            continue;
        }
        int32_t cza = ((px[i1] - px[i0]) * (py[i2] - py[i0]));
        int32_t czb = ((py[i1] - py[i0]) * (px[i2] - px[i0]));
        if ((cza - czb) >= 0) {
            continue;
        }
        fill_quad(px[i0], py[i0], px[i1], py[i1], px[i2], py[i2], px[i3], py[i3], Cube_face_col(cube, fi));
    }
}

void render_sky_ground(void) {
    int32_t band_h = (HALF_H / 6);
    int32_t gband_h = (HALF_H / 8);
    pak_rdpq_set_mode_fill(sky_col[0]);
    for (int b = 0; b < 6; b++) {
        pak_rdpq_set_fill_color(sky_col[b]);
        rdpq_fill_rectangle(0, (b * band_h), SCREEN_W, ((b + 1) * band_h));
    }
    for (int b = 0; b < 8; b++) {
        pak_rdpq_set_fill_color(gnd_col[b]);
        rdpq_fill_rectangle(0, (HALF_H + (b * gband_h)), SCREEN_W, (HALF_H + ((b + 1) * gband_h)));
    }
    pak_rdpq_set_fill_color(0x4466AAFF);
    rdpq_fill_rectangle(0, (HALF_H - 2), SCREEN_W, (HALF_H + 2));
}

void render_stars(void) {
    __auto_type ss = (PakSlice_Star){ .data = (gs.stars).data, .len = (gs.stars).len };
    for (int i = 0; i < (ss).len; i++) {
        Star s = (ss).data[i];
        uint32_t col = 0x444444FF;
        if (s.z > 0.75f) {
            col = 0xFFFFFFFF;
        }
        else if (s.z > 0.5f) {
            col = 0xBBBBBBFF;
        }
        else if (s.z > 0.25f) {
            col = 0x888888FF;
        }
        pak_rdpq_set_fill_color(col);
        int32_t sz = 1;
        if (s.z > 0.7f) {
            sz = 2;
        }
        rdpq_fill_rectangle(s.sx, s.sy, (s.sx + sz), (s.sy + sz));
    }
}

void update(pak_joypad_status_t pad) {
    Cube_spin(&gs.cube_a);
    Cube_spin(&gs.cube_b);
    if (pad.held.l) {
        gs.cube_a.spy -= 0.003f;
    }
    if (pad.held.r) {
        gs.cube_a.spy += 0.003f;
    }
    if (pad.held.up) {
        gs.cube_b.spy -= 0.004f;
    }
    if (pad.held.down) {
        gs.cube_b.spy += 0.004f;
    }
    if (pad.pressed.start) {
        gs.running = false;
    }
    gs.frame += 1;
}

void init_scene(void) {
    memset(&(gs.stars), 0, sizeof(gs.stars));
    __pak_srand(0xDEAD);
    int32_t cnt = 0;
    while (cnt < 64) {
        ((gs.stars).len < 64 ? ((gs.stars).data[(gs.stars).len++] = ((Star){.sx = __pak_rand_range(0, 318), .sy = __pak_rand_range(0, 115), .z = __pak_rand_f()}), 1) : 0);
        cnt += 1;
    }
    gs.cube_a = (Cube){.tx = -0.5f, .ty = 0.0f, .tz = 5.5f, .sc = 1.6f, .ry = 0.0f, .rx = 0.5f, .spy = 0.018f, .spx = 0.011f, .col0 = 0xFF5500FF, .col1 = 0xCC3300FF, .col2 = 0xFF8800FF};
    gs.cube_b = (Cube){.tx = 3.2f, .ty = -0.5f, .tz = 4.5f, .sc = 0.9f, .ry = 1.0f, .rx = 0.3f, .spy = -0.025f, .spx = 0.016f, .col0 = 0x2266FFFF, .col1 = 0x1144CCFF, .col2 = 0x44AAFFFF};
    gs.frame = 0;
    gs.running = true;
}

int main(void) {
    pak_display_init(0, 2, 3, 0, 1);
    rdpq_init();
    joypad_init();
    timer_init();
    init_scene();
    while (true) {
        joypad_poll();
        __auto_type pad = pak_joypad_get_status(0);
        update(pad);
        if (!gs.running) {
            break;
        }
        __auto_type fb = display_get();
        pak_rdpq_attach_clear(fb, 0x000000FF);
        render_sky_ground();
        render_stars();
        render_cube(&gs.cube_a);
        render_cube(&gs.cube_b);
        rdpq_detach_show();
    }
    rdpq_close();
    return 0;
}

