#!/usr/bin/env bash
# tools/audit.sh — Comprehensive Pak enforcement audit
#
# Runs every verification layer in sequence and reports a final verdict.
# Usage:
#   ./tools/audit.sh            # full audit
#   ./tools/audit.sh --fast     # skip pak explain snapshots (faster)
#   ./tools/audit.sh --fix      # regenerate snapshots if they drift

set -euo pipefail

FAST=0
FIX=0
for arg in "$@"; do
  case "$arg" in
    --fast) FAST=1 ;;
    --fix)  FIX=1  ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RED='\033[0;31m'
GRN='\033[0;32m'
YLW='\033[1;33m'
CYN='\033[0;36m'
BLD='\033[1m'
RST='\033[0m'

PASS=0
FAIL=0

section() { echo -e "\n${CYN}${BLD}══ $1 ══${RST}"; }
ok()      { echo -e "  ${GRN}✓${RST} $1"; ((PASS++)) || true; }
fail()    { echo -e "  ${RED}✗${RST} $1"; ((FAIL++)) || true; }
warn()    { echo -e "  ${YLW}⚠${RST} $1"; }

# ── 1. Pak CLI available ──────────────────────────────────────────────────────
section "Environment"

if command -v pak &>/dev/null; then
  ok "pak CLI available: $(pak --version 2>&1 | head -1)"
else
  fail "pak not found — put bin/ on PATH (see README)"
  exit 1
fi

# ── 2. Canonical examples ─────────────────────────────────────────────────────
section "Canonical Examples (pak check)"

n_ok=0; n_fail=0
for f in examples/canonical/*.pk64; do
  name=$(basename "$f")
  if pak check "$f" &>/dev/null; then
    ((n_ok++)) || true
  else
    fail "$name — pak check failed:"
    pak check "$f" 2>&1 | sed 's/^/      /'
    ((n_fail++)) || true
  fi
done

if [ "$n_fail" -eq 0 ]; then
  ok "All $n_ok canonical examples pass pak check"
else
  fail "$n_fail/$((n_ok + n_fail)) canonical examples failed"
fi

# ── 3. Invalid examples ───────────────────────────────────────────────────────
section "Invalid Examples (must fail)"

n_ok=0; n_fail=0
for f in tests/invalid/*.pk64; do
  name=$(basename "$f")
  expected=$(grep -oP '(?<=EXPECT: )E\d+' "$f" 2>/dev/null || echo "")
  set +e
  output=$(pak check "$f" 2>&1)
  exit_code=$?
  set -e

  if [ "$exit_code" -eq 0 ]; then
    fail "$name — should have failed but passed"
    ((n_fail++)) || true
  elif [ -n "$expected" ] && ! echo "$output" | grep -q "$expected"; then
    actual=$(echo "$output" | grep -oP 'error\[E\d+\]' | head -1)
    fail "$name — expected $expected, got ${actual:-none}"
    ((n_fail++)) || true
  else
    ((n_ok++)) || true
  fi
done

if [ "$n_fail" -eq 0 ]; then
  ok "All $n_ok invalid examples fail with expected error codes"
else
  fail "$n_fail/$((n_ok + n_fail)) invalid example checks failed"
fi

# ── 4. pak explain snapshots ──────────────────────────────────────────────────
if [ "$FAST" -eq 0 ]; then
  section "Semantic Snapshots (pak explain)"

  n_ok=0; n_drift=0; n_missing=0
  for f in examples/canonical/*.pk64; do
    name=$(basename "$f" .pk64)
    snapshot="tests/snapshots/${name}.c"
    set +e
    actual=$(pak explain "$f" 2>/dev/null)
    set -e

    # Normalize path comment
    actual=$(echo "$actual" | sed 's|/\* Generated by Pak Compiler - .* \*/|/* Generated by Pak Compiler */|')

    if [ ! -f "$snapshot" ]; then
      if [ "$FIX" -eq 1 ]; then
        pak explain "$f" 2>/dev/null > "$snapshot"
        ok "$name — snapshot created"
        ((n_ok++)) || true
      else
        fail "$name — snapshot missing (run with --fix to create)"
        ((n_missing++)) || true
      fi
      continue
    fi

    # Normalize the snapshot's path comment the same way, so the two are
    # compared on content rather than on where the file happened to live.
    expected=$(sed 's|/\* Generated by Pak Compiler - .* \*/|/* Generated by Pak Compiler */|' "$snapshot")
    if [ "$actual" = "$expected" ]; then
      ((n_ok++)) || true
    else
      if [ "$FIX" -eq 1 ]; then
        pak explain "$f" 2>/dev/null > "$snapshot"
        warn "$name — snapshot updated (drift detected)"
        ((n_ok++)) || true
      else
        fail "$name — generated C drifted from snapshot"
        diff <(echo "$expected") <(echo "$actual") | head -12 | sed 's/^/      /'
        ((n_drift++)) || true
      fi
    fi
  done

  total_snap=$((n_ok + n_drift + n_missing))
  if [ "$((n_drift + n_missing))" -eq 0 ]; then
    ok "All $n_ok snapshots match"
  else
    [ "$n_drift"   -gt 0 ] && fail "$n_drift snapshot(s) drifted — run: ./tools/audit.sh --fix"
    [ "$n_missing" -gt 0 ] && fail "$n_missing snapshot(s) missing — run: ./tools/audit.sh --fix"
  fi
else
  warn "Skipping snapshot checks (--fast)"
fi

# ── 5. Golden regression suite ────────────────────────────────────────────────
section "Golden Suite"

# The goldens gate every compiler stage over the whole corpus; --fast runs only
# the diagnostic stages, which take about a second instead of a couple of minutes.
if [ "$FAST" -eq 1 ]; then
  GOLDEN_STAGES="check tc"
else
  GOLDEN_STAGES=""
fi

set +e
golden_out=$(tclsh tcl/tools/golden_test.tcl $GOLDEN_STAGES 2>&1)
golden_exit=$?
set -e

if [ "$golden_exit" -eq 0 ]; then
  ok "golden: $(echo "$golden_out" | grep -c 'PASS' ) stage(s) match"
  echo "$golden_out" | grep -E 'PASS|MISSING' | sed 's/^/      /'
else
  fail "golden suite has failures:"
  echo "$golden_out" | tail -20 | sed 's/^/      /'
fi

# ── 6. Binary back-end suites ─────────────────────────────────────────────────
section "Binary Back End"

for suite in n64enc_test n64link_test; do
  set +e
  out=$(tclsh "tcl/tools/$suite.tcl" 2>&1)
  rc=$?
  set -e
  if [ "$rc" -eq 0 ]; then
    ok "$suite: $(echo "$out" | grep '^PASS=' | tail -1)"
  else
    fail "$suite failed:"
    echo "$out" | grep -E '^FAIL' | head -10 | sed 's/^/      /'
  fi
done

# Every canonical example must reach a relocatable object file.
n_obj=0; n_obj_fail=0
for f in examples/canonical/*.pk64; do
  if pak objgen "$f" -o /tmp/_audit.pakobj &>/dev/null; then
    ((n_obj++)) || true
  else
    fail "$(basename "$f") — pak objgen failed"
    ((n_obj_fail++)) || true
  fi
done
rm -f /tmp/_audit.pakobj
[ "$n_obj_fail" -eq 0 ] && ok "objgen: $n_obj/$n_obj canonical examples produced objects"

# ── 7. Hook integrity ─────────────────────────────────────────────────────────
section "Tooling Integrity"

if tclsh -c 'exit 0' </dev/null &>/dev/null || command -v tclsh &>/dev/null; then
  ok "tclsh available: $(echo 'puts [info patchlevel]' | tclsh)"
else
  fail "tclsh not found — install tcl and tcllib"
fi

if [ -x tools/validate_pak.sh ]; then
  ok "tools/validate_pak.sh is executable"
else
  fail "tools/validate_pak.sh is not executable (run: chmod +x tools/validate_pak.sh)"
fi

# Check the PostToolUse hook is wired in settings.json
if grep -q "pak_hook.tcl" .claude/settings.json 2>/dev/null; then
  ok ".claude/settings.json has pak_hook PostToolUse hook"
else
  fail ".claude/settings.json missing pak_hook PostToolUse hook"
fi

# ── 7. Documentation consistency ─────────────────────────────────────────────
section "Documentation Consistency"

# Every canonical example must have a snapshot
missing_snaps=0
for f in examples/canonical/*.pk64; do
  name=$(basename "$f" .pk64)
  if [ ! -f "tests/snapshots/${name}.c" ]; then
    fail "Missing snapshot for $name"
    ((missing_snaps++)) || true
  fi
done
[ "$missing_snaps" -eq 0 ] && ok "All canonical examples have snapshots"

# Every file in tests/invalid/ must have an EXPECT annotation
missing_expect=0
for f in tests/invalid/*.pk64; do
  if ! grep -q "EXPECT: E" "$f" 2>/dev/null; then
    fail "$(basename "$f") missing -- EXPECT: EXXX annotation"
    ((missing_expect++)) || true
  fi
done
[ "$missing_expect" -eq 0 ] && ok "All invalid test files have EXPECT annotations"

# ── Final verdict ─────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════"
if [ "$FAIL" -eq 0 ]; then
  echo -e "${GRN}${BLD}ALL CHECKS PASSED${RST} ($PASS checks)"
else
  echo -e "${RED}${BLD}$FAIL CHECK(S) FAILED${RST} ($PASS passed, $FAIL failed)"
  exit 1
fi
