#!/usr/bin/env bash
# Build the reference-RDP harness used by tcl/tools/pixel_test.tcl.
#
# angrylion's RDP Plus is the accuracy reference for the N64 display processor.
# Its core rasterises a display list straight into an RDRAM buffer, so no
# OpenGL, window or VI scanout is needed -- the pixels are read back out of the
# same memory. That is what makes a headless pixel gate possible where
# examples/baremetal/README.md's mupen64plus attempt could not get one.
#
#   tools/build_rdp_harness.sh [outdir]
#
# Produces <outdir>/rdprun. Skips cleanly (exit 0, no binary) with no network
# or no compiler, so the pixel test can report SKIP rather than fail.
set -u
OUT="${1:-${TMPDIR:-/tmp}/pak-rdp-harness}"
# Pinned: a moving reference is not a reference.
REV="9c8b9ed3e7d7f00dff8bc872ccdd3fba1a3673fc"
REPO_URL="https://github.com/ata4/angrylion-rdp-plus"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$OUT" || { echo "rdp harness: cannot create $OUT"; exit 0; }
[ -x "$OUT/rdprun" ] && { echo "rdp harness: already built at $OUT/rdprun"; exit 0; }

command -v gcc >/dev/null 2>&1 || { echo "rdp harness: SKIP (no gcc)"; exit 0; }
command -v g++ >/dev/null 2>&1 || { echo "rdp harness: SKIP (no g++)"; exit 0; }
command -v git >/dev/null 2>&1 || { echo "rdp harness: SKIP (no git)"; exit 0; }

SRC="$OUT/angrylion-rdp-plus"
if [ ! -d "$SRC/src/core" ]; then
    rm -rf "$SRC"
    if ! git clone -q "$REPO_URL" "$SRC" 2>/dev/null; then
        echo "rdp harness: SKIP (cannot clone $REPO_URL)"
        exit 0
    fi
    ( cd "$SRC" && git checkout -q "$REV" ) || { echo "rdp harness: SKIP (revision $REV missing)"; exit 0; }
fi

cd "$OUT" || exit 0
# version.h is normally generated by CMake from git; the core only needs the
# macros to exist.
cat > version.h <<'EOF'
#pragma once
#define GIT_BRANCH "pak-harness"
#define GIT_TAG "pak-harness"
#define GIT_COMMIT_HASH "pinned"
#define GIT_COMMIT_DATE "pinned"
#define CORE_BASE_NAME "angrylion's RDP Plus"
#define CORE_NAME CORE_BASE_NAME
#define CORE_SIMPLE_NAME "angrylion-plus"
EOF

# msg_* are the core's diagnostics hooks; the plugin normally supplies them.
cat > msg.c <<'EOF'
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
void msg_error(const char *e, ...) {
    va_list a; va_start(a, e);
    fprintf(stderr, "rdp error: "); vfprintf(stderr, e, a); fprintf(stderr, "\n");
    va_end(a); exit(2);
}
void msg_warning(const char *e, ...) { (void)e; }
void msg_debug(const char *e, ...) { (void)e; }
EOF

cp "$HERE/rdprun.c" . 2>/dev/null || { echo "rdp harness: SKIP (rdprun.c missing)"; exit 0; }

INC="-I$SRC/src/core -I$OUT"
gcc -c -O2 $INC "$SRC/src/core/n64video.c" -o n64video.o 2>/dev/null || { echo "rdp harness: SKIP (core will not compile)"; exit 0; }
g++ -c -O2 -std=c++14 $INC "$SRC/src/core/parallel.cpp" -o parallel.o 2>/dev/null || { echo "rdp harness: SKIP (parallel will not compile)"; exit 0; }
gcc -c -O2 msg.c -o msg.o 2>/dev/null || { echo "rdp harness: SKIP"; exit 0; }
gcc -c -O2 $INC rdprun.c -o rdprun.o 2>/dev/null || { echo "rdp harness: SKIP (harness will not compile)"; exit 0; }
g++ -O2 rdprun.o n64video.o parallel.o msg.o -o rdprun -lpthread 2>/dev/null || { echo "rdp harness: SKIP (link failed)"; exit 0; }

echo "rdp harness: built $OUT/rdprun (angrylion @ ${REV:0:12})"
