# codegen/platformer.tcl — .pakstudio → valid .pk64 + pak.toml for platformer
# All procs are pure functions (dict in → string out). No I/O, no globals.

namespace eval codegen::platformer {}

# ── Entry point ──────────────────────────────────────────────────────────────

proc codegen::platformer::generate {doc} {
    return [dict create \
        "pak.toml"    [_pak_toml $doc] \
        "src/main.pk64" [_main_pk64 $doc] \
    ]
}

# ── pak.toml ─────────────────────────────────────────────────────────────────

proc codegen::platformer::_pak_toml {doc} {
    set m    [dict get $doc meta]
    set s    [dict get $doc settings]
    set name [string tolower [regsub -all {\s+} [dict get $m name] "_"]]
    set title [dict get $m rom_title]
    set save  [dict get $s save_type]
    set res   [dict get $s resolution]
    set bpp   [dict get $s bit_depth]
    set fbs   [dict get $s framebuffers]
    return "\[project\]
name = \"$name\"
rom_title = \"$title\"
save_type = \"$save\"

\[display\]
resolution = \"$res\"
bit_depth = $bpp
framebuffers = $fbs

\[build\]
optimization = \"release\"
"
}

# ── Single-file main.pk64 ────────────────────────────────────────────────────

proc codegen::platformer::_main_pk64 {doc} {
    set m     [dict get $doc meta]
    set phys  [dict get $doc physics]
    set lvls  [dict get $doc levels]
    set name  [dict get $m name]

    # Physics constants
    set gravity    [dict get $phys gravity]
    set jump_force [dict get $phys jump_force]
    set move_speed [dict get $phys move_speed]
    set max_fall   [dict get $phys max_fall]
    set coyote_f   [dict get $phys coyote_frames]
    set jump_buf_f [dict get $phys jump_buffer]

    # Build per-level data sections and entity data
    set level_data_blocks {}
    set entity_block      [_entity_block $doc]
    set level_count       [llength $lvls]

    for {set li 0} {$li < $level_count} {incr li} {
        lappend level_data_blocks [_level_data_block $li [lindex $lvls $li]]
    }

    # First level player start
    set lvl0   [lindex $lvls 0]
    set ps     [_find_player_start $lvl0]
    set start_x [expr {[dict get $ps x] * 16 + 0}]
    set start_y [expr {[dict get $ps y] * 16 - 4}]

    set out {}
    lappend out "-- $name"
    lappend out "-- Generated by PakStudio -- DO NOT EDIT"
    lappend out ""
    lappend out "use n64.display"
    lappend out "use n64.controller"
    lappend out "use n64.rdpq"
    lappend out "use n64.timer"
    lappend out "use n64.math"
    lappend out ""
    lappend out "const SCREEN_W: i32 = 320"
    lappend out "const SCREEN_H: i32 = 240"
    lappend out "const TILE_SZ:  i32 = 16"
    lappend out ""
    lappend out "-- Tile type constants"
    lappend out "const T_EMPTY:  u8 = 0"
    lappend out "const T_SOLID:  u8 = 1"
    lappend out "const T_ONEWAY: u8 = 2"
    lappend out "const T_HAZARD: u8 = 3"
    lappend out ""
    lappend out "-- Physics constants"
    lappend out "const GRAVITY:    f32 = ${gravity}"
    lappend out "const JUMP_FORCE: f32 = ${jump_force}"
    lappend out "const MOVE_SPEED: f32 = ${move_speed}"
    lappend out "const MAX_FALL:   f32 = ${max_fall}"
    lappend out "const COYOTE_F:   i32 = ${coyote_f}"
    lappend out "const JUMP_BUF_F: i32 = ${jump_buf_f}"
    lappend out ""
    lappend out "-- Level count"
    lappend out "const NUM_LEVELS: i32 = ${level_count}"
    lappend out ""

    # Level tile data
    foreach blk $level_data_blocks {
        lappend out $blk
    }

    # Entity data
    lappend out $entity_block

    # Types
    lappend out [_types_section]

    # Functions
    lappend out [_tile_functions_section $lvls]
    lappend out [_player_update_section]
    lappend out [_entity_update_section $doc]
    lappend out [_render_section $doc]

    # Entry
    lappend out [_entry_section $doc $start_x $start_y]

    return [join $out "\n"]
}

# ── Level tile data blocks ────────────────────────────────────────────────────

proc codegen::platformer::_level_data_block {li lvl} {
    set W  [dict get $lvl width]
    set H  [dict get $lvl height]
    set N  [expr {$W * $H}]
    set tiles [dict get $lvl tiles]
    set LI [expr {$li + 1}]

    set lines {}
    lappend lines "-- Level $LI: [dict get $lvl name] (${W}x${H})"
    lappend lines "const LEVEL${LI}_W: i32 = $W"
    lappend lines "const LEVEL${LI}_H: i32 = $H"
    lappend lines ""
    lappend lines "static level${LI}_tiles: \[${N}\]u8 = \["

    # 16 tiles per row for readability
    set row {}
    set col 0
    foreach t $tiles {
        lappend row $t
        incr col
        if {$col == 16} {
            lappend lines "    [join $row {, }],"
            set row {}
            set col 0
        }
    }
    if {[llength $row] > 0} {
        lappend lines "    [join $row {, }],"
    }
    lappend lines "\]"
    lappend lines ""
    return [join $lines "\n"]
}

# ── Entity data ───────────────────────────────────────────────────────────────

proc codegen::platformer::_entity_block {doc} {
    # Collect coins and enemies from level 0 (multi-level: first level only for now)
    set lvls [dict get $doc levels]
    set lvl0 [lindex $lvls 0]
    set objs [dict get $lvl0 objects]

    set coins   {}
    set enemies {}
    foreach obj $objs {
        switch [dict get $obj type] {
            coin          { lappend coins   $obj }
            enemy_patrol  { lappend enemies $obj }
            enemy_jumper  { lappend enemies $obj }
        }
    }

    set lines {}

    # Coins
    set NC [llength $coins]
    lappend lines "const NUM_COINS: i32 = $NC"
    lappend lines ""
    lappend lines "struct Coin {"
    lappend lines "    x: f32"
    lappend lines "    y: f32"
    lappend lines "    collected: bool"
    lappend lines "}"
    lappend lines ""
    if {$NC > 0} {
        lappend lines "static coins: \[${NC}\]Coin = undefined"
    } else {
        lappend lines "static coins: \[1\]Coin = undefined"
    }
    lappend lines ""

    # Enemies
    set NE [llength $enemies]
    lappend lines "const NUM_ENEMIES: i32 = $NE"
    lappend lines ""
    lappend lines "struct Enemy {"
    lappend lines "    x: f32"
    lappend lines "    y: f32"
    lappend lines "    vx: f32"
    lappend lines "    health: i32"
    lappend lines "    alive: bool"
    lappend lines "    ai: i32"
    lappend lines "}"
    lappend lines ""
    if {$NE > 0} {
        lappend lines "static enemies: \[${NE}\]Enemy = undefined"
    } else {
        lappend lines "static enemies: \[1\]Enemy = undefined"
    }
    lappend lines ""

    return [join $lines "\n"]
}

# ── Types (structs, enums, game state) ────────────────────────────────────────

proc codegen::platformer::_types_section {} {
    return {enum Phase: u8 { title, playing, paused, gameover }

struct Player {
    x:         f32
    y:         f32
    vx:        f32
    vy:        f32
    health:    i32
    on_ground: bool
    coyote:    i32
    jump_buf:  i32
    facing:    i32
}

struct GameState {
    phase:     Phase
    player:    Player
    score:     i32
    coins:     i32
    cam_x:     i32
    cur_level: i32
}

static gs: GameState = undefined
}
}

# ── Tile access functions ─────────────────────────────────────────────────────

proc codegen::platformer::_tile_functions_section {lvls} {
    # For multi-level support we dispatch on gs.cur_level.
    # For now generate a single-level version (simplest path for Phase 1).
    set lvl [lindex $lvls 0]
    set W   [dict get $lvl width]
    set H   [dict get $lvl height]

    return "fn tile_at(tx: i32, ty: i32) -> u8 {
    if tx < 0 or tx >= LEVEL1_W or ty < 0 or ty >= LEVEL1_H {
        return T_SOLID
    }
    return level1_tiles\[ty * LEVEL1_W + tx\]
}

fn tile_solid(t: u8) -> bool {
    return t == T_SOLID
}

fn tile_hazard(t: u8) -> bool {
    return t == T_HAZARD
}

fn check_solid(px: i32, py: i32) -> bool {
    return tile_solid(tile_at(px / TILE_SZ, py / TILE_SZ))
}
"
}

# ── Player update ─────────────────────────────────────────────────────────────

proc codegen::platformer::_player_update_section {} {
    return {fn player_update(gs: *GameState, pad: joypad_status_t) {
    let p: *Player = &gs.player

    -- Horizontal input
    p.vx = 0.0
    if pad.held.left  { p.vx = -MOVE_SPEED }
    if pad.held.right { p.vx =  MOVE_SPEED }
    if pad.held.left  { p.facing = -1 }
    if pad.held.right { p.facing =  1 }

    -- Jump input buffering
    if p.jump_buf > 0 { p.jump_buf -= 1 }
    if pad.pressed.a or pad.pressed.b { p.jump_buf = JUMP_BUF_F }

    -- Coyote time
    if p.on_ground {
        p.coyote = COYOTE_F
    } elif p.coyote > 0 {
        p.coyote -= 1
    }

    -- Execute jump
    if p.jump_buf > 0 and p.coyote > 0 {
        p.vy      = JUMP_FORCE
        p.jump_buf = 0
        p.coyote  = 0
    }

    -- Gravity
    p.vy += GRAVITY
    if p.vy > MAX_FALL { p.vy = MAX_FALL }

    -- Move X then collide
    p.x += p.vx
    let pi_x: i32 = p.x as i32
    let pi_y: i32 = p.y as i32
    if p.vx > 0.0 {
        if check_solid(pi_x + 13, pi_y + 8) {
            p.x  = ((pi_x + 13) / TILE_SZ * TILE_SZ - 13) as f32
            p.vx = 0.0
        }
    }
    if p.vx < 0.0 {
        if check_solid(pi_x, pi_y + 8) {
            p.x  = ((pi_x / TILE_SZ + 1) * TILE_SZ) as f32
            p.vx = 0.0
        }
    }

    -- Move Y then collide
    p.y += p.vy
    pi_y = p.y as i32
    p.on_ground = false
    -- Floor check (two feet)
    if p.vy >= 0.0 {
        if check_solid(pi_x + 2, pi_y + 15) or check_solid(pi_x + 11, pi_y + 15) {
            p.y         = ((pi_y + 15) / TILE_SZ * TILE_SZ - 15) as f32
            p.vy        = 0.0
            p.on_ground = true
        }
    }
    -- Ceiling check
    if p.vy < 0.0 {
        if check_solid(pi_x + 2, pi_y) or check_solid(pi_x + 11, pi_y) {
            p.y  = ((pi_y / TILE_SZ + 1) * TILE_SZ) as f32
            p.vy = 0.0
        }
    }

    -- Hazard tiles
    if tile_hazard(tile_at((pi_x + 6) / TILE_SZ, (pi_y + 8) / TILE_SZ)) {
        if p.health > 0 { p.health -= 1 }
    }

    -- Camera follow
    gs.cam_x = p.x as i32 - 160
    if gs.cam_x < 0 { gs.cam_x = 0 }
    let max_cam: i32 = LEVEL1_W * TILE_SZ - SCREEN_W
    if gs.cam_x > max_cam { gs.cam_x = max_cam }

    -- Death
    if p.health <= 0 { gs.phase = Phase.gameover }
    if p.y > (LEVEL1_H * TILE_SZ) as f32 { gs.phase = Phase.gameover }
}
}
}

# ── Entity update ─────────────────────────────────────────────────────────────

proc codegen::platformer::_entity_update_section {doc} {
    return {fn entities_update(gs: *GameState) {
    -- Coins: collect on overlap
    let ci: i32 = 0
    while ci < NUM_COINS {
        if not coins[ci].collected {
            let cx: i32 = coins[ci].x as i32
            let cy: i32 = coins[ci].y as i32
            let px: i32 = gs.player.x as i32
            let py: i32 = gs.player.y as i32
            if math.abs_i32(cx - px) < 14 and math.abs_i32(cy - py) < 14 {
                coins[ci].collected = true
                gs.coins += 1
                gs.score += 100
            }
        }
        ci += 1
    }

    -- Enemies: patrol AI
    let ei: i32 = 0
    while ei < NUM_ENEMIES {
        if enemies[ei].alive {
            enemies[ei].x += enemies[ei].vx
            let etx: i32 = enemies[ei].x as i32 / TILE_SZ
            let ety: i32 = (enemies[ei].y as i32 + 15) / TILE_SZ
            -- Reverse at wall or ledge
            if check_solid(enemies[ei].x as i32 + 16, enemies[ei].y as i32 + 8) {
                enemies[ei].vx = -enemies[ei].vx
            }
            if check_solid(enemies[ei].x as i32 - 1, enemies[ei].y as i32 + 8) {
                enemies[ei].vx = -enemies[ei].vx
            }
            -- Ledge reversal
            if not check_solid(etx * TILE_SZ, (ety + 1) * TILE_SZ) {
                enemies[ei].vx = -enemies[ei].vx
            }
            -- Player collision
            let px: i32 = gs.player.x as i32
            let py: i32 = gs.player.y as i32
            let ex: i32 = enemies[ei].x as i32
            let ey: i32 = enemies[ei].y as i32
            if math.abs_i32(ex - px) < 12 and math.abs_i32(ey - py) < 12 {
                -- Stomp from above kills enemy
                if py < ey and gs.player.vy > 0.0 {
                    enemies[ei].alive = false
                    gs.player.vy = -4.0
                    gs.score += 200
                } else {
                    if gs.player.health > 0 { gs.player.health -= 1 }
                    if gs.player.health <= 0 { gs.phase = Phase.gameover }
                }
            }
        }
        ei += 1
    }
}
}
}

# ── Render ────────────────────────────────────────────────────────────────────

proc codegen::platformer::_render_section {doc} {
    set lvl [lindex [dict get $doc levels] 0]
    set bg  [dict get $lvl bg_color]
    return "fn render_level(gs: *GameState) {
    rdpq.set_mode_fill(${bg})
    rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
    let start_tx: i32 = gs.cam_x / TILE_SZ
    let end_tx: i32   = start_tx + SCREEN_W / TILE_SZ + 2
    if end_tx > LEVEL1_W { end_tx = LEVEL1_W }
    let ty: i32 = 0
    while ty < LEVEL1_H {
        let tx: i32 = start_tx
        while tx < end_tx {
            let t: u8   = tile_at(tx, ty)
            if t != T_EMPTY {
                let sx: i32 = tx * TILE_SZ - gs.cam_x
                let sy: i32 = ty * TILE_SZ
                let col: u32 = 0xAA5533FF
                if t == T_ONEWAY { col = 0x558844FF }
                elif t == T_HAZARD { col = 0xFF2200FF }
                rdpq.set_fill_color(col)
                rdpq.fill_rectangle(sx, sy, sx + TILE_SZ, sy + TILE_SZ)
            }
            tx += 1
        }
        ty += 1
    }
}

fn render_entities(gs: *GameState) {
    -- Coins
    let ci: i32 = 0
    while ci < NUM_COINS {
        if not coins\[ci\].collected {
            let sx: i32 = coins\[ci\].x as i32 - gs.cam_x
            let sy: i32 = coins\[ci\].y as i32
            rdpq.set_fill_color(0xFFDD00FF)
            rdpq.fill_rectangle(sx + 3, sy + 3, sx + 11, sy + 11)
        }
        ci += 1
    }
    -- Enemies
    let ei: i32 = 0
    while ei < NUM_ENEMIES {
        if enemies\[ei\].alive {
            let sx: i32 = enemies\[ei\].x as i32 - gs.cam_x
            let sy: i32 = enemies\[ei\].y as i32
            rdpq.set_fill_color(0xFF4488FF)
            rdpq.fill_rectangle(sx, sy, sx + 14, sy + 14)
        }
        ei += 1
    }
}

fn render_player(gs: *GameState) {
    let sx: i32 = gs.player.x as i32 - gs.cam_x
    let sy: i32 = gs.player.y as i32
    -- Body
    rdpq.set_fill_color(0xFF4444FF)
    rdpq.fill_rectangle(sx + 2, sy + 4, sx + 12, sy + 15)
    -- Head
    rdpq.set_fill_color(0xFFCC99FF)
    rdpq.fill_rectangle(sx + 3, sy, sx + 11, sy + 5)
}

fn render_hud(gs: *GameState) {
    rdpq.set_fill_color(0x00000088)
    rdpq.fill_rectangle(0, 0, SCREEN_W, 12)
    -- Health pips
    let hi: i32 = 0
    while hi < gs.player.health {
        rdpq.set_fill_color(0xFF0000FF)
        rdpq.fill_rectangle(4 + hi * 10, 2, 10 + hi * 10, 10)
        hi += 1
    }
}
"
}

# ── Entry block ────────────────────────────────────────────────────────────────

proc codegen::platformer::_entry_section {doc start_x start_y} {
    # Collect coin/enemy init lines from level 0
    set lvl0 [lindex [dict get $doc levels] 0]
    set objs [dict get $lvl0 objects]

    set coin_init  {}
    set enemy_init {}
    set ci 0
    set ei 0
    foreach obj $objs {
        set ox [expr {[dict get $obj x] * 16 + 4}]
        set oy [expr {[dict get $obj y] * 16}]
        switch [dict get $obj type] {
            coin {
                lappend coin_init \
                    "    coins\[${ci}\] = Coin { x: ${ox}.0, y: ${oy}.0, collected: false }"
                incr ci
            }
            enemy_patrol -
            enemy_jumper {
                lappend enemy_init \
                    "    enemies\[${ei}\] = Enemy { x: ${ox}.0, y: ${oy}.0, vx: 1.5, health: 1, alive: true, ai: 0 }"
                incr ei
            }
        }
    }

    set init_lines [concat $coin_init $enemy_init]
    set init_block [join $init_lines "\n"]

    return "entry {
    display.init(0, 2, 3, 0, 1)
    rdpq.init()
    controller.init()
    timer.init()
    defer { rdpq.close() }

    -- Initialize game state
    gs.phase     = Phase.playing
    gs.cur_level = 0
    gs.score     = 0
    gs.coins     = 0
    gs.cam_x     = 0
    gs.player = Player {
        x:         ${start_x}.0,
        y:         ${start_y}.0,
        vx:        0.0,
        vy:        0.0,
        health:    3,
        on_ground: false,
        coyote:    0,
        jump_buf:  0,
        facing:    1,
    }

${init_block}

    loop {
        controller.poll()
        let pad = controller.read(0)

        match gs.phase {
            .title => {
                if pad.pressed.start { gs.phase = Phase.playing }
            }
            .playing => {
                player_update(&gs, pad)
                entities_update(&gs)
            }
            .paused => {
                if pad.pressed.start { gs.phase = Phase.playing }
            }
            .gameover => {
                if pad.pressed.start {
                    gs.phase  = Phase.playing
                    gs.player.health = 3
                    gs.player.x = ${start_x}.0
                    gs.player.y = ${start_y}.0
                    gs.player.vy = 0.0
                }
            }
        }

        let fb = display.get()
        rdpq.attach_clear(fb)

        match gs.phase {
            .title => {
                rdpq.set_mode_fill(0x000000FF)
                rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
            }
            .playing => {
                render_level(&gs)
                render_entities(&gs)
                render_player(&gs)
                render_hud(&gs)
            }
            .paused => {
                render_level(&gs)
                render_entities(&gs)
                render_player(&gs)
                render_hud(&gs)
            }
            .gameover => {
                rdpq.set_mode_fill(0x110000FF)
                rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
            }
        }

        rdpq.detach_show()
    }
}
"
}

# ── Helpers ────────────────────────────────────────────────────────────────────

proc codegen::platformer::_find_player_start {lvl} {
    foreach obj [dict get $lvl objects] {
        if {[dict get $obj type] eq "player_start"} { return $obj }
    }
    return [dict create x 2 y 10]
}
