# codegen/shmup.tcl — .pakstudio → scrolling shoot-em-up .pk64 + pak.toml
#
# Supports both orientations via the ORIENT constant (0 = horizontal scroll /
# shoot right, 1 = vertical scroll / shoot up). The bitmap font and EEPROM save
# blocks are shared with the platformer generator (they are pure, genre-neutral
# static blocks). Gameplay, rendering, audio and level data are shmup-specific.

namespace eval codegen::shmup {}

proc codegen::shmup::generate {doc} {
    return [dict create \
        "pak.toml"      [_pak_toml $doc] \
        "src/main.pk64" [_main_pk64 $doc] \
    ]
}

# ── pak.toml ─────────────────────────────────────────────────────────────────

proc codegen::shmup::_pak_toml {doc} {
    set m    [dict get $doc meta]
    set s    [dict get $doc settings]
    set name [string tolower [regsub -all {\s+} [dict get $m name] "_"]]
    set title [dict get $m rom_title]
    set save  [dict get $s save_type]
    set res   [dict get $s resolution]
    set bpp   [dict get $s bit_depth]
    set fbs   [dict get $s framebuffers]
    return "\[project\]
name = \"$name\"
rom_title = \"$title\"
save_type = \"$save\"

\[display\]
resolution = \"$res\"
bit_depth = $bpp
framebuffers = $fbs

\[build\]
optimization = \"release\"
"
}

# ── Save helpers (shared with platformer) ────────────────────────────────────

proc codegen::shmup::_save_type {doc} {
    if {[dict exists $doc settings save_type]} {
        return [dict get $doc settings save_type]
    }
    return "none"
}
proc codegen::shmup::_save_on {doc} {
    expr {[_save_type $doc] ne "none"}
}

# ── Orientation ──────────────────────────────────────────────────────────────
# 0 = horizontal (scroll left, ship moves freely, fires right)
# 1 = vertical   (scroll up,   ship moves freely, fires up)
proc codegen::shmup::_orient {doc} {
    if {[dict exists $doc settings orientation]
        && [dict get $doc settings orientation] eq "vertical"} {
        return 1
    }
    return 0
}

# ── Fixed-point helper (reused convention) ───────────────────────────────────
proc codegen::shmup::_f {v} {
    if {[string is integer -strict $v]} { return "${v}.0" }
    if {![string match "*.*" $v] && ![string match "*e*" $v]} { return "${v}.0" }
    return $v
}

# ── Main assembly ─────────────────────────────────────────────────────────────

proc codegen::shmup::_main_pk64 {doc} {
    set out {}
    lappend out [_header $doc]
    lappend out [_constants $doc]
    lappend out [codegen::platformer::_font_block]
    lappend out [_audio_block]
    lappend out [_gamestate_block]
    lappend out [codegen::platformer::_save_block $doc]
    lappend out [_gameplay_block $doc]
    lappend out [_load_level $doc]
    lappend out [_render_block $doc]
    lappend out [_update_block]
    lappend out [_entry_block $doc]
    return [join $out "\n"]
}

proc codegen::shmup::_header {doc} {
    set name [dict get $doc meta name]
    set lines {}
    lappend lines "-- $name"
    lappend lines "-- Generated by PakStudio (shoot-em-up). DO NOT EDIT — regenerate from the .pakstudio project."
    lappend lines ""
    lappend lines "use n64.display"
    lappend lines "use n64.controller"
    lappend lines "use n64.rdpq"
    lappend lines "use n64.timer"
    lappend lines "use n64.audio"
    lappend lines "use n64.math"
    if {[_save_on $doc]} {
        lappend lines "use n64.eeprom"
    }
    lappend lines ""
    return [join $lines "\n"]
}

proc codegen::shmup::_constants {doc} {
    set phys [dict get $doc physics]
    set ms [_f [expr {[dict exists $phys move_speed]   ? [dict get $phys move_speed]   : 2.6}]]
    set sc [_f [expr {[dict exists $phys scroll_speed] ? [dict get $phys scroll_speed] : 1.0}]]
    set fc     [expr {[dict exists $phys fire_rate]    ? [dict get $phys fire_rate]    : 8}]
    set bs [_f [expr {[dict exists $phys bullet_speed] ? [dict get $phys bullet_speed] : 5.5}]]
    set orient [_orient $doc]
    set nlevels [llength [dict get $doc levels]]
    return "const SCREEN_W: i32 = 320
const SCREEN_H: i32 = 240
const ORIENT: i32 = $orient

const PLAYER_SPEED:  f32 = $ms
const SCROLL_STEP:   i32 = 1
const FIRE_COOLDOWN: i32 = $fc
const BULLET_SPEED:  f32 = $bs
const EBULLET_SPEED: f32 = 2.6
const ENEMY_SPEED:   f32 = 1.4
const SHIP_W: i32 = 14
const SHIP_H: i32 = 12
const INVULN_F: i32 = 90

const MAX_BULLETS:  i32 = 16
const MAX_ENEMIES:  i32 = 24
const MAX_EBULLETS: i32 = 32
const MAX_SPAWNS:   i32 = 64

const NUM_LEVELS: i32 = $nlevels

const SAVE_BLOCK: i32 = 0
const SAVE_MAGIC_HI: u8 = 0x53
const SAVE_MAGIC_LO: u8 = 0x48
"
}

# ── Procedural audio (asset-free, shmup voices) ──────────────────────────────

proc codegen::shmup::_audio_block {} {
    return {-- ── Procedural sound engine (asset-free) ─────────────────────────────────────
const SR: i32 = 44100

static sfx_len:  i32 = 0
static sfx_left: i32 = 0
static sfx_f0:   i32 = 220
static sfx_f1:   i32 = 220
static sfx_kind: i32 = 0
static snd_t:    i32 = 0
static rng:      i32 = 22483

static music_on: bool = false
static mus_idx:  i32 = 0
static mus_t:    i32 = 0

const MUS_NOTES: i32 = 8
static mus_freq: [8]i32 = undefined

fn init_music_table() {
    mus_freq[0] = 196
    mus_freq[1] = 262
    mus_freq[2] = 330
    mus_freq[3] = 392
    mus_freq[4] = 330
    mus_freq[5] = 262
    mus_freq[6] = 247
    mus_freq[7] = 165
}

fn play_sfx(kind: i32, f0: i32, f1: i32, dur_ms: i32) {
    sfx_kind = kind
    sfx_f0 = f0
    sfx_f1 = f1
    sfx_len = (SR / 1000) * dur_ms
    sfx_left = sfx_len
}

fn sfx_shoot()   { play_sfx(0, 880, 1500, 55) }
fn sfx_explode() { play_sfx(1, 400, 60, 220) }
fn sfx_hit()     { play_sfx(1, 300, 90, 180) }
fn sfx_powerup() { play_sfx(0, 523, 1320, 200) }

fn next_rng() -> i32 {
    rng = (rng * 1103515245 + 12345) & 0x7FFFFFFF
    return rng
}

fn square_at(freq: i32, t: i32, amp: i32) -> i32 {
    if freq <= 0 { return 0 }
    let period: i32 = SR / freq
    if period <= 0 { return 0 }
    if (t % period) < (period / 2) { return amp }
    return -amp
}

fn sfx_sample() -> i32 {
    if sfx_left <= 0 { return 0 }
    let elapsed: i32 = sfx_len - sfx_left
    let freq: i32 = sfx_f0
    if sfx_len > 0 {
        freq = sfx_f0 + (sfx_f1 - sfx_f0) * elapsed / sfx_len
    }
    let amp: i32 = 5000 * sfx_left / sfx_len
    let s: i32 = 0
    if sfx_kind == 1 {
        if (next_rng() & 1) == 1 { s = amp } else { s = -amp }
    } else {
        s = square_at(freq, snd_t, amp)
    }
    sfx_left -= 1
    return s
}

fn mus_sample() -> i32 {
    if not music_on { return 0 }
    let note_len: i32 = SR / 6
    mus_t += 1
    if mus_t >= note_len {
        mus_t = 0
        mus_idx += 1
        if mus_idx >= MUS_NOTES { mus_idx = 0 }
    }
    return square_at(mus_freq[mus_idx], snd_t, 1500)
}

fn fill_audio() {
    let buf: *i16 = audio.get_buffer()
    if buf == none { return }
    let i: i32 = 0
    loop {
        if i >= 1470 { break }
        let s: i32 = sfx_sample() + mus_sample()
        if s > 32000 { s = 32000 }
        if s < -32000 { s = -32000 }
        buf[i]     = s as i16
        buf[i + 1] = s as i16
        snd_t += 1
        i += 2
    }
}

fn snd_init() {
    audio.init(44100, 4)
    init_music_table()
}

fn music_start() { music_on = true }
fn music_stop()  { music_on = false }
}
}

# ── Game state + arrays ──────────────────────────────────────────────────────

proc codegen::shmup::_gamestate_block {} {
    return {-- ── Entities ─────────────────────────────────────────────────────────────────
enum Phase { title, playing, gameover, win }

struct Ship { x: f32, y: f32, health: i32, invuln: i32, cool: i32 }
struct Bullet { x: f32, y: f32, active: bool }
struct Enemy { x: f32, y: f32, vx: f32, vy: f32, hp: i32, kind: i32, alive: bool, fire: i32, ph: f32, color: u32 }
struct EBullet { x: f32, y: f32, vx: f32, vy: f32, active: bool }
struct Spawn { at: i32, lane: i32, kind: i32 }

struct GameState {
    phase: Phase
    ship: Ship
    score: i32
    lives: i32
    wave: i32
    scroll: i32
    frame: i32
    hi_score: i32
    best_stage: i32
}

static gs: GameState = undefined
static bullets:  [16]Bullet = undefined
static enemies:  [24]Enemy = undefined
static ebullets: [32]EBullet = undefined
static spawns:   [64]Spawn = undefined
static num_spawns: i32 = 0
static next_spawn: i32 = 0
static level_len:  i32 = 1800
}
}

# ── Core gameplay (orientation-aware via ORIENT branches) ────────────────────

proc codegen::shmup::_gameplay_block {doc} {
    return {-- ── Gameplay ─────────────────────────────────────────────────────────────────
fn spawn_enemy(kind: i32, lane: i32) {
    let i: i32 = 0
    while i < MAX_ENEMIES {
        if not enemies[i].alive {
            enemies[i].alive = true
            enemies[i].kind = kind
            enemies[i].hp = 1
            enemies[i].fire = 50
            enemies[i].ph = 0.0
            if kind == 2 { enemies[i].hp = 2 }
            if ORIENT == 0 {
                enemies[i].x = (SCREEN_W + 8) as f32
                enemies[i].y = lane as f32
                enemies[i].vx = -ENEMY_SPEED
                enemies[i].vy = 0.0
            } else {
                enemies[i].x = lane as f32
                enemies[i].y = -8.0
                enemies[i].vx = 0.0
                enemies[i].vy = ENEMY_SPEED
            }
            enemies[i].color = 0xFF5555FF
            if kind == 1 { enemies[i].color = 0xFFAA33FF }
            if kind == 2 { enemies[i].color = 0xAA55FFFF }
            return
        }
        i += 1
    }
}

fn fire_bullet() {
    if gs.ship.cool > 0 { return }
    let i: i32 = 0
    while i < MAX_BULLETS {
        if not bullets[i].active {
            bullets[i].active = true
            if ORIENT == 0 {
                bullets[i].x = gs.ship.x + SHIP_W as f32
                bullets[i].y = gs.ship.y + (SHIP_H / 2) as f32
            } else {
                bullets[i].x = gs.ship.x + (SHIP_W / 2) as f32
                bullets[i].y = gs.ship.y
            }
            gs.ship.cool = FIRE_COOLDOWN
            sfx_shoot()
            return
        }
        i += 1
    }
}

fn spawn_ebullet(ex: f32, ey: f32) {
    let i: i32 = 0
    while i < MAX_EBULLETS {
        if not ebullets[i].active {
            ebullets[i].active = true
            ebullets[i].x = ex
            ebullets[i].y = ey
            let dx: f32 = gs.ship.x - ex
            let dy: f32 = gs.ship.y - ey
            let d: f32 = math.sqrt_f(dx * dx + dy * dy)
            if d < 1.0 { d = 1.0 }
            ebullets[i].vx = dx / d * EBULLET_SPEED
            ebullets[i].vy = dy / d * EBULLET_SPEED
            return
        }
        i += 1
    }
}

fn hurt_ship() {
    if gs.ship.invuln > 0 { return }
    gs.ship.health -= 1
    gs.ship.invuln = INVULN_F
    sfx_hit()
    if gs.ship.health <= 0 {
        gs.lives -= 1
        if gs.lives <= 0 {
            gs.phase = Phase.gameover
            music_stop()
        } else {
            gs.ship.health = 3
            gs.ship.invuln = INVULN_F
        }
    }
}

fn ship_update(pad: joypad_status_t) {
    if gs.ship.invuln > 0 { gs.ship.invuln -= 1 }
    if gs.ship.cool > 0 { gs.ship.cool -= 1 }
    if pad.held.left  { gs.ship.x -= PLAYER_SPEED }
    if pad.held.right { gs.ship.x += PLAYER_SPEED }
    if pad.held.up    { gs.ship.y -= PLAYER_SPEED }
    if pad.held.down  { gs.ship.y += PLAYER_SPEED }
    if gs.ship.x < 0.0 { gs.ship.x = 0.0 }
    if gs.ship.y < 16.0 { gs.ship.y = 16.0 }
    if gs.ship.x > (SCREEN_W - SHIP_W) as f32 { gs.ship.x = (SCREEN_W - SHIP_W) as f32 }
    if gs.ship.y > (SCREEN_H - SHIP_H) as f32 { gs.ship.y = (SCREEN_H - SHIP_H) as f32 }
    if pad.held.a or pad.held.b { fire_bullet() }
}

fn enemies_update() {
    let i: i32 = 0
    while i < MAX_ENEMIES {
        if enemies[i].alive {
            enemies[i].ph += 0.12
            enemies[i].x += enemies[i].vx
            enemies[i].y += enemies[i].vy
            if enemies[i].kind == 1 {
                if ORIENT == 0 {
                    enemies[i].y += math.sin_f(enemies[i].ph) * 2.0
                } else {
                    enemies[i].x += math.sin_f(enemies[i].ph) * 2.0
                }
            }
            if enemies[i].kind == 2 {
                enemies[i].fire -= 1
                if enemies[i].fire <= 0 {
                    enemies[i].fire = 90
                    spawn_ebullet(enemies[i].x + 6.0, enemies[i].y + 6.0)
                }
            }
            if enemies[i].x < -20.0 or enemies[i].x > (SCREEN_W + 20) as f32 { enemies[i].alive = false }
            if enemies[i].y < -20.0 or enemies[i].y > (SCREEN_H + 20) as f32 { enemies[i].alive = false }
        }
        i += 1
    }
}

fn bullets_update() {
    let i: i32 = 0
    while i < MAX_BULLETS {
        if bullets[i].active {
            if ORIENT == 0 { bullets[i].x += BULLET_SPEED } else { bullets[i].y -= BULLET_SPEED }
            if bullets[i].x > (SCREEN_W + 8) as f32 { bullets[i].active = false }
            if bullets[i].y < -8.0 { bullets[i].active = false }
        }
        i += 1
    }
}

fn ebullets_update() {
    let i: i32 = 0
    while i < MAX_EBULLETS {
        if ebullets[i].active {
            ebullets[i].x += ebullets[i].vx
            ebullets[i].y += ebullets[i].vy
            if ebullets[i].x < -8.0 or ebullets[i].x > (SCREEN_W + 8) as f32 { ebullets[i].active = false }
            if ebullets[i].y < -8.0 or ebullets[i].y > (SCREEN_H + 8) as f32 { ebullets[i].active = false }
        }
        i += 1
    }
}

fn aabb(ax: f32, ay: f32, aw: i32, ah: i32, bx: f32, by: f32, bw: i32, bh: i32) -> bool {
    if ax + aw as f32 < bx { return false }
    if bx + bw as f32 < ax { return false }
    if ay + ah as f32 < by { return false }
    if by + bh as f32 < ay { return false }
    return true
}

fn collisions() {
    let bi: i32 = 0
    while bi < MAX_BULLETS {
        if bullets[bi].active {
            let ei: i32 = 0
            while ei < MAX_ENEMIES {
                if enemies[ei].alive and aabb(bullets[bi].x, bullets[bi].y, 6, 2, enemies[ei].x, enemies[ei].y, 14, 14) {
                    bullets[bi].active = false
                    enemies[ei].hp -= 1
                    if enemies[ei].hp <= 0 {
                        enemies[ei].alive = false
                        gs.score += 100
                        sfx_explode()
                    }
                }
                ei += 1
            }
        }
        bi += 1
    }
    let ej: i32 = 0
    while ej < MAX_ENEMIES {
        if enemies[ej].alive and gs.ship.invuln == 0 and aabb(gs.ship.x, gs.ship.y, SHIP_W, SHIP_H, enemies[ej].x, enemies[ej].y, 14, 14) {
            hurt_ship()
        }
        ej += 1
    }
    let xi: i32 = 0
    while xi < MAX_EBULLETS {
        if ebullets[xi].active and gs.ship.invuln == 0 and aabb(gs.ship.x, gs.ship.y, SHIP_W, SHIP_H, ebullets[xi].x, ebullets[xi].y, 4, 4) {
            ebullets[xi].active = false
            hurt_ship()
        }
        xi += 1
    }
}

fn any_enemy_alive() -> bool {
    let i: i32 = 0
    while i < MAX_ENEMIES {
        if enemies[i].alive { return true }
        i += 1
    }
    return false
}
}
}

# ── Level data (spawns from placed objects) ──────────────────────────────────

proc codegen::shmup::_load_level {doc} {
    set orient [_orient $doc]
    set lvls [dict get $doc levels]
    set lines {}
    lappend lines "fn load_level(level: i32) \{"
    lappend lines "    num_spawns = 0"
    lappend lines "    next_spawn = 0"
    lappend lines "    gs.scroll = 0"
    lappend lines "    let i: i32 = 0"
    lappend lines "    while i < MAX_ENEMIES \{ enemies\[i\].alive = false; i += 1 \}"
    lappend lines "    i = 0"
    lappend lines "    while i < MAX_BULLETS \{ bullets\[i\].active = false; i += 1 \}"
    lappend lines "    i = 0"
    lappend lines "    while i < MAX_EBULLETS \{ ebullets\[i\].active = false; i += 1 \}"
    # Default ship position by orientation
    if {$orient == 0} {
        lappend lines "    gs.ship.x = 30.0"
        lappend lines "    gs.ship.y = (SCREEN_H / 2) as f32"
    } else {
        lappend lines "    gs.ship.x = (SCREEN_W / 2) as f32"
        lappend lines "    gs.ship.y = (SCREEN_H - 30) as f32"
    }

    set li 0
    foreach lvl $lvls {
        set W [dict get $lvl width]
        set H [dict get $lvl height]
        set objs [dict get $lvl objects]

        # Build spawn list: timeline along the scroll axis, lane across it.
        # Horizontal: at = x*step, lane = y*16. Vertical: at = y*step, lane = x*16.
        set step 24
        set spawnlist {}
        set ship_lane ""
        set max_at 0
        foreach obj $objs {
            set ox [dict get $obj x]
            set oy [dict get $obj y]
            set type [dict get $obj type]
            if {$orient == 0} {
                set at [expr {$ox * $step}]
                set lane [expr {$oy * 16}]
            } else {
                set at [expr {$oy * $step}]
                set lane [expr {$ox * 16}]
            }
            switch $type {
                player_start { set ship_lane $lane }
                enemy_patrol { lappend spawnlist [list $at $lane 0]; if {$at > $max_at} {set max_at $at} }
                enemy_jumper { lappend spawnlist [list $at $lane 1]; if {$at > $max_at} {set max_at $at} }
                spring       { lappend spawnlist [list $at $lane 2]; if {$at > $max_at} {set max_at $at} }
                coin         { lappend spawnlist [list $at $lane 0]; if {$at > $max_at} {set max_at $at} }
            }
        }
        # Sort by spawn time and cap to MAX_SPAWNS
        set spawnlist [lsort -integer -index 0 $spawnlist]
        if {[llength $spawnlist] > 64} { set spawnlist [lrange $spawnlist 0 63] }
        set level_len [expr {$max_at + 320}]

        lappend lines "    if level == $li \{"
        lappend lines "        level_len = $level_len"
        set si 0
        foreach sp $spawnlist {
            lassign $sp at lane kind
            lappend lines "        spawns\[$si\] = Spawn \{ at: $at, lane: $lane, kind: $kind \}"
            incr si
        }
        lappend lines "        num_spawns = $si"
        if {$ship_lane ne ""} {
            if {$orient == 0} {
                lappend lines "        gs.ship.y = ${ship_lane}.0"
            } else {
                lappend lines "        gs.ship.x = ${ship_lane}.0"
            }
        }
        lappend lines "    \}"
        incr li
    }

    lappend lines "    gs.ship.invuln = 0"
    lappend lines "    gs.ship.cool = 0"
    lappend lines "\}"
    return [join $lines "\n"]
}

# ── Rendering ────────────────────────────────────────────────────────────────

proc codegen::shmup::_render_block {doc} {
    set name [string toupper [dict get $doc meta name]]
    regsub -all {[^A-Z0-9 :.!-]} $name " " name
    set name [string range $name 0 19]
    return "fn render_stars() \{
    rdpq.set_mode_fill(0x070A14FF)
    rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
    rdpq.sync_pipe()
    let i: i32 = 0
    while i < 48 \{
        let base: i32 = i * 71 + 13
        let sx: i32 = 0
        let sy: i32 = 0
        if ORIENT == 0 \{
            sx = (base + (SCREEN_W - gs.scroll % SCREEN_W) * (1 + i % 3)) % SCREEN_W
            sy = (i * 37 + i * i * 7) % SCREEN_H
        \} else \{
            sx = (i * 37 + i * i * 7) % SCREEN_W
            sy = (base + (gs.scroll % SCREEN_H) * (1 + i % 3)) % SCREEN_H
        \}
        rdpq.set_fill_color(0xFFFFFFFF)
        rdpq.fill_rectangle(sx, sy, sx + 1 + i % 2, sy + 1 + i % 2)
        i += 1
    \}
    rdpq.sync_pipe()
\}

fn render_play() \{
    render_stars()
    rdpq.set_mode_fill(0xFFEE44FF)
    let i: i32 = 0
    while i < MAX_BULLETS \{
        if bullets\[i\].active \{
            let bx: i32 = bullets\[i\].x as i32
            let by: i32 = bullets\[i\].y as i32
            rdpq.fill_rectangle(bx, by, bx + 6, by + 2)
        \}
        i += 1
    \}
    rdpq.sync_pipe()
    i = 0
    while i < MAX_ENEMIES \{
        if enemies\[i\].alive \{
            let ex: i32 = enemies\[i\].x as i32
            let ey: i32 = enemies\[i\].y as i32
            rdpq.set_fill_color(enemies\[i\].color)
            rdpq.fill_rectangle(ex, ey, ex + 14, ey + 14)
            rdpq.set_fill_color(0x000000FF)
            rdpq.fill_rectangle(ex + 3, ey + 5, ex + 5, ey + 8)
            rdpq.fill_rectangle(ex + 9, ey + 5, ex + 11, ey + 8)
        \}
        i += 1
    \}
    rdpq.sync_pipe()
    rdpq.set_mode_fill(0xFF66FFFF)
    i = 0
    while i < MAX_EBULLETS \{
        if ebullets\[i\].active \{
            let xx: i32 = ebullets\[i\].x as i32
            let yy: i32 = ebullets\[i\].y as i32
            rdpq.fill_rectangle(xx, yy, xx + 4, yy + 4)
        \}
        i += 1
    \}
    rdpq.sync_pipe()
    if gs.ship.invuln > 0 and (gs.frame / 3) % 2 == 0 \{
    \} else \{
        let sx: i32 = gs.ship.x as i32
        let sy: i32 = gs.ship.y as i32
        rdpq.set_mode_fill(0x44DDFFFF)
        rdpq.fill_rectangle(sx, sy + 3, sx + SHIP_W, sy + SHIP_H - 3)
        rdpq.set_fill_color(0xFFFFFFFF)
        if ORIENT == 0 \{
            rdpq.fill_rectangle(sx + SHIP_W - 4, sy + 5, sx + SHIP_W, sy + 7)
        \} else \{
            rdpq.fill_rectangle(sx + 6, sy, sx + 8, sy + 4)
        \}
    \}
    rdpq.sync_pipe()
    rdpq.set_mode_fill(0x000000AA)
    rdpq.fill_rectangle(0, 0, SCREEN_W, 14)
    rdpq.sync_pipe()
    draw_text(\"SCORE\", 4, 3, 1, 0xFFFFFFFF)
    draw_number(gs.score, 32, 3, 1, 0xFFEE44FF)
    draw_text(\"LIVES\", 150, 3, 1, 0xFFFFFFFF)
    draw_number(gs.lives, 178, 3, 1, 0xFF5555FF)
    draw_text(\"WAVE\", 230, 3, 1, 0xFFFFFFFF)
    draw_number(gs.wave + 1, 256, 3, 1, 0x88FF88FF)
    rdpq.sync_pipe()
    rdpq.set_mode_fill(0xFF2222FF)
    let hi: i32 = 0
    while hi < gs.ship.health \{
        rdpq.fill_rectangle(290 + hi * 8, 3, 296 + hi * 8, 11)
        hi += 1
    \}
\}

fn render_title() \{
    rdpq.set_mode_fill(0x070A14FF)
    rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
    rdpq.sync_pipe()
    render_stars()
    draw_text_centered(\"$name\", SCREEN_W / 2, 60, 2, 0x44DDFFFF)
    draw_text_centered(\"A PAK SHOOTER\", SCREEN_W / 2, 96, 1, 0x88AAFFFF)
    if (gs.frame / 20) % 2 == 0 \{
        draw_text_centered(\"PRESS START\", SCREEN_W / 2, 150, 2, 0xFFFFFFFF)
    \}
    draw_text(\"HI\", 110, 195, 1, 0xFFFFFFFF)
    draw_number(gs.hi_score, 124, 195, 1, 0xFFEE44FF)
    if gs.best_stage > 0 \{
        draw_text(\"BEST WAVE\", 110, 210, 1, 0x88FF88FF)
        draw_number(gs.best_stage, 170, 210, 1, 0x88FF88FF)
    \}
\}

fn render_gameover() \{
    rdpq.set_mode_fill(0x280808FF)
    rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
    rdpq.sync_pipe()
    draw_text_centered(\"GAME OVER\", SCREEN_W / 2, 80, 3, 0xFF4444FF)
    draw_text(\"SCORE\", 110, 130, 1, 0xFFFFFFFF)
    draw_number(gs.score, 142, 130, 1, 0xFFEE44FF)
    draw_text_centered(\"PRESS START\", SCREEN_W / 2, 170, 1, 0xFFFFFFFF)
\}

fn render_win() \{
    rdpq.set_mode_fill(0x081828FF)
    rdpq.fill_rectangle(0, 0, SCREEN_W, SCREEN_H)
    rdpq.sync_pipe()
    draw_text_centered(\"STAGE CLEAR\", SCREEN_W / 2, 80, 2, 0x44FF88FF)
    draw_text(\"SCORE\", 110, 130, 1, 0xFFFFFFFF)
    draw_number(gs.score, 142, 130, 1, 0xFFEE44FF)
    draw_text_centered(\"PRESS START\", SCREEN_W / 2, 170, 1, 0xFFFFFFFF)
\}

fn render() \{
    let fb = display.get()
    rdpq.attach_clear(fb)
    match gs.phase \{
        .title    => \{ render_title() \}
        .playing  => \{ render_play() \}
        .gameover => \{ render_gameover() \}
        .win      => \{ render_win() \}
    \}
    rdpq.detach_show()
\}
"
}

# ── Update / start ───────────────────────────────────────────────────────────

proc codegen::shmup::_update_block {} {
    return {-- ── Update ───────────────────────────────────────────────────────────────────
fn start_game() {
    gs.score = 0
    gs.lives = 3
    gs.wave = 0
    gs.ship.health = 3
    if gs.best_stage < 1 { gs.best_stage = 1 }
    load_level(0)
    gs.phase = Phase.playing
    music_start()
}

fn update(pad: joypad_status_t) {
    match gs.phase {
        .title => {
            if pad.pressed.start or pad.pressed.a { start_game() }
        }
        .playing => {
            ship_update(pad)
            gs.scroll += SCROLL_STEP
            while next_spawn < num_spawns and spawns[next_spawn].at <= gs.scroll {
                spawn_enemy(spawns[next_spawn].kind, spawns[next_spawn].lane)
                next_spawn += 1
            }
            enemies_update()
            bullets_update()
            ebullets_update()
            collisions()
            if gs.scroll >= level_len and not any_enemy_alive() {
                gs.wave += 1
                if gs.wave + 1 > gs.best_stage { gs.best_stage = gs.wave + 1 }
                if gs.wave >= NUM_LEVELS {
                    gs.phase = Phase.win
                    music_stop()
                } else {
                    load_level(gs.wave)
                }
            }
        }
        .gameover => {
            if pad.pressed.start or pad.pressed.a {
                if gs.score > gs.hi_score { gs.hi_score = gs.score }
                save_hi(gs.hi_score)
                gs.phase = Phase.title
            }
        }
        .win => {
            if pad.pressed.start or pad.pressed.a {
                if gs.score > gs.hi_score { gs.hi_score = gs.score }
                save_hi(gs.hi_score)
                gs.phase = Phase.title
            }
        }
    }
    gs.frame += 1
}
}
}

proc codegen::shmup::_entry_block {doc} {
    if {[_save_on $doc]} {
        set eeprom_init "    eeprom.init()\n"
    } else {
        set eeprom_init ""
    }
    set tmpl {-- ── Entry ────────────────────────────────────────────────────────────────────
entry {
    display.init(0, 2, 3, 0, 1)
    rdpq.init()
    controller.init()
    timer.init()
@@EEPROMINIT@@
    defer { rdpq.close() }

    init_font()
    snd_init()

    gs.phase = Phase.title
    gs.frame = 0
    gs.score = 0
    gs.lives = 3
    gs.wave = 0
    gs.best_stage = 0
    gs.hi_score = load_hi()

    loop {
        fill_audio()
        controller.poll()
        let pad = controller.read(0)
        update(pad)
        render()
    }
}
}
    return [string map [list @@EEPROMINIT@@ $eeprom_init] $tmpl]
}
