# codegen/topdown.tcl — .pakstudio (topdown genre) → .pk64 + pak.toml
#
# Generates a complete top-down RPG with:
#   • Tile-based world map with 4-dir player movement
#   • Turn-based battle system (encounter on contact / random step)
#   • Full stat engine: HP/MP/ATK/DEF/MAG/SPD
#   • EXP accumulation and level-up with per-stat growth
#   • Mob drops: gold + item drops (configurable rate)
#   • Skills with MP cost, elemental power, targeting
#   • Item system: consumables (heal HP/MP), key items
#   • Crafting system: station-based recipes, ingredient check + consume
#   • Party of up to 3 actors, 1-6 enemy types per encounter
#
# Architecture: a large static Pak engine is assembled from fixed blocks
# (structs, AI, render, battle loop) plus data-driven tables generated from
# the editor's database, quest, craft, and level records.

namespace eval codegen::topdown {}

# ── Entry point ───────────────────────────────────────────────────────────────

proc codegen::topdown::generate {doc} {
    return [dict create \
        "pak.toml"      [_pak_toml $doc] \
        "src/main.pk64" [_main_pk64 $doc] \
    ]
}

# ── pak.toml ──────────────────────────────────────────────────────────────────

proc codegen::topdown::_pak_toml {doc} {
    set m     [dict get $doc meta]
    set s     [dict get $doc settings]
    set name  [string tolower [regsub -all {\s+} [dict get $m name] "_"]]
    set title [dict get $m rom_title]
    set save  [dict get $s save_type]
    return "\[project\]
name = \"$name\"
rom_title = \"$title\"
save_type = \"$save\"

\[display\]
resolution = \"320x240\"
bit_depth = 16
framebuffers = 2

\[build\]
optimization = \"release\"
"
}

# ── Helpers: database access ──────────────────────────────────────────────────

proc codegen::topdown::_actors  {doc} { _db_list $doc actors  }
proc codegen::topdown::_enemies {doc} { _db_list $doc enemies }
proc codegen::topdown::_skills  {doc} { _db_list $doc skills  }
proc codegen::topdown::_items   {doc} { _db_list $doc items   }
proc codegen::topdown::_recipes {doc} {
    if {[dict exists $doc recipes]} { return [dict get $doc recipes] }
    return {}
}

proc codegen::topdown::_db_list {doc key} {
    if {[dict exists $doc database $key]} { return [dict get $doc database $key] }
    return {}
}

proc codegen::topdown::_df {rec key default} {
    if {[dict exists $rec $key] && [dict get $rec $key] ne ""} {
        return [dict get $rec $key]
    }
    return $default
}

# Convert a doc identifier to a safe Pak identifier
proc codegen::topdown::_id {s} {
    regsub -all {[^a-zA-Z0-9_]} [string tolower $s] "_"
}

# Clamp an integer field to a range
proc codegen::topdown::_int {rec key lo hi default} {
    set v [_df $rec $key $default]
    if {![string is integer -strict $v]} { set v $default }
    if {$v < $lo} { set v $lo }
    if {$v > $hi} { set v $hi }
    return $v
}

# ── Main source assembly ──────────────────────────────────────────────────────

proc codegen::topdown::_main_pk64 {doc} {
    set out {}
    lappend out [_header $doc]
    lappend out [_use_block]
    lappend out [_constants $doc]
    lappend out [_asset_decls $doc]
    lappend out [_type_defs]
    lappend out [_data_tables $doc]
    lappend out [_static_state $doc]
    lappend out [_map_data $doc]
    lappend out [_font_block]
    lappend out [_math_block]
    lappend out [_draw_block]
    lappend out [_world_block]
    lappend out [_battle_block]
    lappend out [_craft_block]
    lappend out [_ui_block]
    lappend out [_entry_block $doc]
    return [join $out "\n"]
}

# ── Header ────────────────────────────────────────────────────────────────────

proc codegen::topdown::_header {doc} {
    set name [dict get $doc meta name]
    return "-- $name — generated by PakStudio (top-down RPG)
-- Edit in PakStudio; re-generate to update.
"
}

proc codegen::topdown::_use_block {} {
    return {use n64.display
use n64.controller
use n64.rdpq
use n64.audio
}
}

# ── Constants ─────────────────────────────────────────────────────────────────

proc codegen::topdown::_constants {doc} {
    set actors  [_actors  $doc]
    set enemies [_enemies $doc]
    set skills  [_skills  $doc]
    set items   [_items   $doc]
    set recipes [_recipes $doc]

    set na [llength $actors];  if {$na < 1} { set na 1 }
    set ne [llength $enemies]; if {$ne < 1} { set ne 1 }
    set ns [llength $skills];  if {$ns < 1} { set ns 1 }
    set ni [llength $items];   if {$ni < 1} { set ni 1 }
    set nr [llength $recipes]; if {$nr < 1} { set nr 1 }

    # Count enemy skills
    set max_eskills 4

    # Levels from levels list
    set levels [dict get $doc levels]
    set nlev [llength $levels]; if {$nlev < 1} { set nlev 1 }

    # Map dimensions from first level
    set lev0 [lindex $levels 0]
    set mw 16; set mh 12
    if {[dict exists $lev0 width]}  { set mw [dict get $lev0 width]  }
    if {[dict exists $lev0 height]} { set mh [dict get $lev0 height] }
    if {$mw < 1} { set mw 16 }; if {$mh < 1} { set mh 12 }

    return "-- ── Constants ───────────────────────────────────────────────────────────────
const NUM_ACTORS:   i32 = $na
const NUM_ENEMIES:  i32 = $ne
const NUM_SKILLS:   i32 = $ns
const NUM_ITEMS:    i32 = $ni
const NUM_RECIPES:  i32 = $nr
const MAX_ESKILLS:  i32 = $max_eskills
const PARTY_SIZE:   i32 = 3
const INV_SIZE:     i32 = 64
const MAP_W:        i32 = $mw
const MAP_H:        i32 = $mh
const TILE_SZ:      i32 = 16
const SCREEN_W:     i32 = 320
const SCREEN_H:     i32 = 240
const MAX_LEVEL:    i32 = 99

-- EXP needed for next level: base * level^1.5 (approximated with integers)
const EXP_BASE:     i32 = 100

-- Battle constants
const BATTLE_ANIM_FRAMES: i32 = 20
const CRIT_MULT:    i32 = 15   -- critical multiplier / 10
const FLEE_CHANCE:  i32 = 40   -- % base flee chance

-- Phase enum indices (used as i32)
const PHASE_TITLE:    i32 = 0
const PHASE_WORLD:    i32 = 1
const PHASE_BATTLE:   i32 = 2
const PHASE_MENU:     i32 = 3
const PHASE_CRAFT:    i32 = 4
const PHASE_GAMEOVER: i32 = 5
const PHASE_WIN:      i32 = 6

-- Menu cursor ids
const MENU_ATTACK: i32 = 0
const MENU_SKILL:  i32 = 1
const MENU_ITEM:   i32 = 2
const MENU_RUN:    i32 = 3

-- Element ids
const ELEM_NONE:  i32 = 0
const ELEM_FIRE:  i32 = 1
const ELEM_ICE:   i32 = 2
const ELEM_BOLT:  i32 = 3
const ELEM_LIGHT: i32 = 4
const ELEM_DARK:  i32 = 5

-- Item kind ids
const ITEM_CONSUMABLE: i32 = 0
const ITEM_WEAPON:     i32 = 1
const ITEM_ARMOR:      i32 = 2
const ITEM_MATERIAL:   i32 = 3
const ITEM_KEY:        i32 = 4

-- Item effect ids
const FX_NONE:    i32 = 0
const FX_HEAL_HP: i32 = 1
const FX_HEAL_MP: i32 = 2
const FX_REVIVE:  i32 = 3
"
}

# ── Asset declarations ────────────────────────────────────────────────────────

proc codegen::topdown::_asset_decls {doc} {
    set lines {"-- ── Assets ──────────────────────────────────────────────────────────────────"}
    foreach role {player_walk enemy_idle npc_idle battle_bg title_bg} {
        if {[dict exists $doc assets sprites $role]
            && [dict get $doc assets sprites $role] ne ""} {
            lappend lines "asset spr_${role}: Sprite from \"sprites/${role}.png\""
        }
    }
    if {[dict exists $doc assets audio music]
        && [dict get $doc assets audio music] ne ""} {
        lappend lines "asset bgm: XMPlayer from \"audio/music.xm\""
    }
    foreach role {battle_start battle_win battle_lose cursor step} {
        if {[dict exists $doc assets audio $role]
            && [dict get $doc assets audio $role] ne ""} {
            lappend lines "asset sfx_$role: Wav from \"audio/${role}.wav\""
        }
    }
    lappend lines ""
    return [join $lines "\n"]
}

# ── Type definitions ──────────────────────────────────────────────────────────

proc codegen::topdown::_type_defs {} {
    return {-- ── Type Definitions ─────────────────────────────────────────────────────────

struct ActorBase {
    max_hp:  i32
    max_mp:  i32
    atk:     i32
    def:     i32
    mag:     i32
    spd:     i32
    -- stat growth per level (scaled *10, applied /10 at level-up)
    hp_grow: i32
    mp_grow: i32
    at_grow: i32
    df_grow: i32
    mg_grow: i32
    sp_grow: i32
}

struct EnemyDef {
    max_hp:    i32
    max_mp:    i32
    atk:       i32
    def:       i32
    mag:       i32
    spd:       i32
    exp:       i32
    gold:      i32
    drop_item: i32   -- -1 = none
    drop_rate: i32   -- 0-100 percent
    ai:        i32   -- 0=chase 1=erratic 2=ranged 3=boss 4=static
    touch_dmg: i32
    n_skills:  i32
    skills:    [4]i32
}

struct SkillDef {
    mp_cost: i32
    power:   i32
    element: i32
    target:  i32   -- 0=one_enemy 1=all_enemies 2=one_ally 3=all_allies 4=self
}

struct ItemDef {
    kind:   i32
    effect: i32
    power:  i32
    price:  i32
}

struct RecipeDef {
    station:    i32   -- 0=alchemy 1=forge 2=cooking 3=tailor 4=any
    n_inputs:   i32
    in_item:    [4]i32
    in_qty:     [4]i32
    out_item:   i32
    out_qty:    i32
}

-- Runtime actor (party member)
struct Actor {
    base_idx: i32    -- index into ACTOR_BASE
    level:    i32
    exp:      i32
    hp:       i32
    mp:       i32
    atk:      i32
    def:      i32
    mag:      i32
    spd:      i32
    alive:    bool
}

-- Live battle enemy slot
struct BattleEnemy {
    def_idx: i32
    hp:      i32
    alive:   bool
}

-- Player world position
struct WorldState {
    x:         i32
    y:         i32
    dir:       i32    -- 0=down 1=up 2=left 3=right
    step:      i32
    move_cool: i32
    steps_til_encounter: i32
}
}
}

# ── Data tables ───────────────────────────────────────────────────────────────

proc codegen::topdown::_data_tables {doc} {
    set out {}
    lappend out "-- ── Data Tables (generated from Database editor) ───────────────────────────"
    lappend out ""
    lappend out [_actor_table  $doc]
    lappend out [_enemy_table  $doc]
    lappend out [_skill_table  $doc]
    lappend out [_item_table   $doc]
    lappend out [_recipe_table $doc]
    return [join $out "\n"]
}

proc codegen::topdown::_actor_table {doc} {
    set actors [_actors $doc]
    if {[llength $actors] == 0} {
        # default hero
        set actors [list [dict create id hero name "Hero" level 1 hp 100 mp 30 \
                               atk 12 def 8 mag 6 spd 10 skills ""]]
    }
    set lines {}
    lappend lines "const ACTOR_BASE: \[[llength $actors]\]ActorBase = \["
    foreach a $actors {
        set hp  [_int $a hp  1 9999 100]
        set mp  [_int $a mp  0 9999  30]
        set atk [_int $a atk 0  999  12]
        set def [_int $a def 0  999   8]
        set mag [_int $a mag 0  999   6]
        set spd [_int $a spd 0  999  10]
        # growth: roughly 10% per level (stored *10, applied /10)
        lappend lines "    ActorBase \{ max_hp: $hp, max_mp: $mp, atk: $atk, def: $def, mag: $mag, spd: $spd,"
        lappend lines "               hp_grow: [expr {$hp/10+3}], mp_grow: [expr {$mp/10+1}],"
        lappend lines "               at_grow: 2, df_grow: 2, mg_grow: 2, sp_grow: 1 \},"
    }
    lappend lines "\]"
    return [join $lines "\n"]
}

proc codegen::topdown::_enemy_table {doc} {
    set enemies [_enemies $doc]
    if {[llength $enemies] == 0} {
        set enemies [list [dict create id goblin name "Goblin" hp 40 mp 0 \
                                atk 8 def 4 mag 0 spd 8 exp 20 gold 10 \
                                ai chase touch 2 skills ""]]
    }
    # build item id → index map for drop references
    set items [_items $doc]
    set item_idx {}
    set i 0
    foreach it $items { dict set item_idx [_df $it id ""] $i; incr i }

    set lines {}
    lappend lines "const ENEMIES: \[[llength $enemies]\]EnemyDef = \["
    foreach e $enemies {
        set hp  [_int $e hp  1 99999  40]
        set mp  [_int $e mp  0  9999   0]
        set atk [_int $e atk 0   999   8]
        set def [_int $e def 0   999   4]
        set mag [_int $e mag 0   999   0]
        set spd [_int $e spd 0   999   8]
        set exp [_int $e exp 0 99999  20]
        set gold [_int $e gold 0 99999 10]
        set tdmg [_int $e touch 0 999 2]

        # drop item
        set drop_id [_df $e drop_item ""]
        set drop_idx -1
        set drop_rate 0
        if {$drop_id ne "" && [dict exists $item_idx $drop_id]} {
            set drop_idx [dict get $item_idx $drop_id]
            set drop_rate [_int $e drop_rate 0 100 20]
        }

        # AI
        set ai_s [string tolower [_df $e ai "chase"]]
        set ai 0
        switch $ai_s {
            erratic { set ai 1 }
            ranged  { set ai 2 }
            boss    { set ai 3 }
            static  { set ai 4 }
        }

        # skills
        set skill_ids [split [_df $e skills ""] " "]
        set skill_ids [lsearch -all -inline -not $skill_ids ""]
        set nskills 0
        set sk_arr {-1, -1, -1, -1}

        # build skill name → index map
        set slist [_skills $doc]
        set skmap {}
        set si 0
        foreach sk $slist { dict set skmap [_df $sk id ""] $si; incr si }

        set sk_entries {}
        foreach sid $skill_ids {
            if {$nskills >= 4} break
            if {[dict exists $skmap $sid]} {
                lappend sk_entries [dict get $skmap $sid]
                incr nskills
            }
        }
        while {[llength $sk_entries] < 4} { lappend sk_entries -1 }
        set sk_arr [join $sk_entries ", "]

        lappend lines "    EnemyDef \{ max_hp: $hp, max_mp: $mp, atk: $atk, def: $def,"
        lappend lines "              mag: $mag, spd: $spd, exp: $exp, gold: $gold,"
        lappend lines "              drop_item: $drop_idx, drop_rate: $drop_rate,"
        lappend lines "              ai: $ai, touch_dmg: $tdmg,"
        lappend lines "              n_skills: $nskills, skills: \[$sk_arr\] \},"
    }
    lappend lines "\]"
    return [join $lines "\n"]
}

proc codegen::topdown::_skill_table {doc} {
    set skills [_skills $doc]
    if {[llength $skills] == 0} {
        set skills [list [dict create id fire name "Fire" mp 8 power 40 element fire target one_enemy]]
    }
    set elem_map {none 0 fire 1 ice 2 bolt 3 light 4 dark 5}
    set tgt_map  {one_enemy 0 all_enemies 1 one_ally 2 all_allies 3 self 4}
    set lines {}
    lappend lines "const SKILLS: \[[llength $skills]\]SkillDef = \["
    foreach sk $skills {
        set mp  [_int $sk mp    0 999  8]
        set pow [_int $sk power 0 9999 40]
        set el_s [string tolower [_df $sk element "none"]]
        set el [expr {[dict exists $elem_map $el_s] ? [dict get $elem_map $el_s] : 0}]
        set tg_s [string tolower [_df $sk target "one_enemy"]]
        set tg [expr {[dict exists $tgt_map $tg_s] ? [dict get $tgt_map $tg_s] : 0}]
        lappend lines "    SkillDef \{ mp_cost: $mp, power: $pow, element: $el, target: $tg \},"
    }
    lappend lines "\]"
    return [join $lines "\n"]
}

proc codegen::topdown::_item_table {doc} {
    set items [_items $doc]
    if {[llength $items] == 0} {
        set items [list \
            [dict create id potion name "Potion" kind consumable effect heal_hp power 50 price 50] \
            [dict create id ether  name "Ether"  kind consumable effect heal_mp power 20 price 80]]
    }
    set kind_map  {consumable 0 weapon 1 armor 2 material 3 key 4}
    set fx_map    {none 0 heal_hp 1 heal_mp 2 atk 0 def 0 revive 3}
    set lines {}
    lappend lines "const ITEMS: \[[llength $items]\]ItemDef = \["
    foreach it $items {
        set kd_s [string tolower [_df $it kind "consumable"]]
        set kd [expr {[dict exists $kind_map $kd_s] ? [dict get $kind_map $kd_s] : 0}]
        set fx_s [string tolower [_df $it effect "none"]]
        set fx [expr {[dict exists $fx_map $fx_s] ? [dict get $fx_map $fx_s] : 0}]
        set pow   [_int $it power 0 9999 50]
        set price [_int $it price 0 99999 50]
        lappend lines "    ItemDef \{ kind: $kd, effect: $fx, power: $pow, price: $price \},"
    }
    lappend lines "\]"
    return [join $lines "\n"]
}

proc codegen::topdown::_recipe_table {doc} {
    set recipes [_recipes $doc]
    if {[llength $recipes] == 0} {
        return "const RECIPES: \[1\]RecipeDef = \[
    RecipeDef \{ station: 4, n_inputs: 0, in_item: \[0,0,0,0\], in_qty: \[0,0,0,0\], out_item: 0, out_qty: 0 \},
\]"
    }
    # build item id → index map
    set items [_items $doc]
    set item_idx {}
    set i 0
    foreach it $items { dict set item_idx [_df $it id ""] $i; incr i }

    set stn_map {alchemy 0 forge 1 cooking 2 tailor 3 any 4}
    set lines {}
    lappend lines "const RECIPES: \[[llength $recipes]\]RecipeDef = \["
    foreach r $recipes {
        set stn_s [string tolower [_df $r station "any"]]
        set stn [expr {[dict exists $stn_map $stn_s] ? [dict get $stn_map $stn_s] : 4}]

        # parse inputs: list of {item qty} dicts
        set inputs [_df $r inputs ""]
        set in_items {0 0 0 0}; set in_qtys {0 0 0 0}; set nin 0
        if {[llength $inputs] > 0 && [dict exists [lindex $inputs 0] item]} {
            # structured list from save_to_doc
            foreach inp $inputs {
                if {$nin >= 4} break
                set iid [_df $inp item ""]
                set qty [_df $inp qty 1]
                set idx [expr {[dict exists $item_idx $iid] ? [dict get $item_idx $iid] : 0}]
                lset in_items $nin $idx
                lset in_qtys  $nin $qty
                incr nin
            }
        } elseif {[string is list $inputs]} {
            # fallback: plain list of item ids
            foreach iid $inputs {
                if {$nin >= 4} break
                if {[dict exists $item_idx $iid]} {
                    lset in_items $nin [dict get $item_idx $iid]
                    lset in_qtys  $nin 1
                    incr nin
                }
            }
        }

        # output
        set output [_df $r output ""]
        set out_item 0; set out_qty 1
        if {[dict size $output] > 0 && [dict exists $output item]} {
            set oid [dict get $output item]
            set out_qty [_df $output qty 1]
            if {[dict exists $item_idx $oid]} { set out_item [dict get $item_idx $oid] }
        }

        lappend lines "    RecipeDef \{ station: $stn, n_inputs: $nin,"
        lappend lines "              in_item: \[[join $in_items ,]\], in_qty: \[[join $in_qtys ,]\],"
        lappend lines "              out_item: $out_item, out_qty: $out_qty \},"
    }
    lappend lines "\]"
    return [join $lines "\n"]
}

# ── Static state ──────────────────────────────────────────────────────────────

proc codegen::topdown::_static_state {doc} {
    set actors [_actors $doc]
    set na [llength $actors]; if {$na < 1} { set na 1 }
    set party_sz [expr {$na < 3 ? $na : 3}]

    # Build initial party HP/MP/level arrays
    set hp_init {}; set mp_init {}; set lv_init {}
    for {set i 0} {$i < $party_sz} {incr i} {
        set a [lindex $actors $i]
        lappend hp_init [_int $a hp 1 9999 100]
        lappend mp_init [_int $a mp 0 9999  30]
        lappend lv_init [_int $a level 1 99 1]
    }
    while {[llength $hp_init] < 3} { lappend hp_init 0 }
    while {[llength $mp_init] < 3} { lappend mp_init 0 }
    while {[llength $lv_init] < 3} { lappend lv_init 1 }

    return "-- ── Runtime State ───────────────────────────────────────────────────────────

-- Game phase
static phase: i32 = PHASE_TITLE

-- Party
static party: \[3\]Actor = \[
    Actor \{ base_idx: 0, level: [lindex $lv_init 0], exp: 0,
           hp: [lindex $hp_init 0], mp: [lindex $mp_init 0],
           atk: 0, def: 0, mag: 0, spd: 0, alive: true \},
    Actor \{ base_idx: [expr {$party_sz > 1 ? 1 : 0}], level: [lindex $lv_init 1], exp: 0,
           hp: [lindex $hp_init 1], mp: [lindex $mp_init 1],
           atk: 0, def: 0, mag: 0, spd: 0, alive: [expr {$party_sz > 1 ? "true" : "false"}] \},
    Actor \{ base_idx: [expr {$party_sz > 2 ? 2 : 0}], level: [lindex $lv_init 2], exp: 0,
           hp: [lindex $hp_init 2], mp: [lindex $mp_init 2],
           atk: 0, def: 0, mag: 0, spd: 0, alive: [expr {$party_sz > 2 ? "true" : "false"}] \},
\]

-- Inventory: item counts indexed by item id
static inventory: \[INV_SIZE\]i32 = \[0; INV_SIZE\]

-- Gold
static gold: i32 = 50

-- World
static world: WorldState = WorldState \{
    x: 4, y: 4, dir: 0, step: 0, move_cool: 0,
    steps_til_encounter: 15
\}

-- Battle state
static b_enemies:   \[4\]BattleEnemy = undefined
static b_n_enemies: i32 = 0
static b_turn:      i32 = 0    -- 0=player choose, 1=player anim, 2=enemy turn
static b_menu:      i32 = MENU_ATTACK
static b_target:    i32 = 0
static b_skill_sel: i32 = 0
static b_item_sel:  i32 = 0
static b_msg:       \[48\]u8 = \[0; 48\]
static b_msg_timer: i32 = 0
static b_exp_gain:  i32 = 0
static b_gold_gain: i32 = 0
static b_anim:      i32 = 0
static b_actor_turn: i32 = 0   -- which party member acts next

-- Crafting state
static craft_sel:    i32 = 0
static craft_result: \[32\]u8 = \[0; 32\]
static craft_timer:  i32 = 0

-- Title / menu
static title_sel: i32 = 0
static frame:     i32 = 0
"
}

# ── Map data ──────────────────────────────────────────────────────────────────

proc codegen::topdown::_map_data {doc} {
    set levels [dict get $doc levels]
    set lev0 [lindex $levels 0]
    set mw 16; set mh 12
    if {[dict exists $lev0 width]}  { set mw [dict get $lev0 width]  }
    if {[dict exists $lev0 height]} { set mh [dict get $lev0 height] }
    if {$mw < 1} { set mw 16 }; if {$mh < 1} { set mh 12 }

    # Build flat tile array from level data
    set tiles {}
    if {[dict exists $lev0 tiles]} {
        set tiles [dict get $lev0 tiles]
    }
    set ncells [expr {$mw * $mh}]
    set arr {}
    for {set i 0} {$i < $ncells} {incr i} {
        if {$i < [llength $tiles]} {
            lappend arr [lindex $tiles $i]
        } else {
            lappend arr 0
        }
    }

    # Format as rows
    set lines {}
    lappend lines "-- ── Map Data ────────────────────────────────────────────────────────────────"
    lappend lines "const MAP: \[$ncells\]u8 = \["
    for {set row 0} {$row < $mh} {incr row} {
        set rowdata {}
        for {set col 0} {$col < $mw} {incr col} {
            lappend rowdata [lindex $arr [expr {$row*$mw+$col}]]
        }
        lappend lines "    [join $rowdata {, }],"
    }
    lappend lines "\]"
    lappend lines ""

    lappend lines {fn tile_at(tx: i32, ty: i32) -> u8 {
    if tx < 0 or ty < 0 or tx >= MAP_W or ty >= MAP_H { return 1 }
    return MAP[ty * MAP_W + tx] as u8
}

fn tile_solid(t: u8) -> bool {
    return t == 1 or t == 2 or t == 5
}

fn tile_encounter(t: u8) -> bool {
    -- grass and floor tiles can have random encounters
    return t == 0 or t == 3
}
}
    return [join $lines "\n"]
}

# ── Font ──────────────────────────────────────────────────────────────────────

proc codegen::topdown::_font_block {} {
    return {-- ── Font (4×5 bitmap) ─────────────────────────────────────────────────────────
const FONT_W: i32 = 4
const FONT_H: i32 = 5

const FONT: [280]u8 = [
    -- A-Z (5 bytes each, 4-bit wide bitmask per row)
    0x6,0x9,0xF,0x9,0x9, 0xE,0x9,0xE,0x9,0xE, 0x6,0x9,0x8,0x9,0x6,
    0xE,0x9,0x9,0x9,0xE, 0xF,0x8,0xE,0x8,0xF, 0xF,0x8,0xE,0x8,0x8,
    0x6,0x8,0xB,0x9,0x7, 0x9,0x9,0xF,0x9,0x9, 0xE,0x4,0x4,0x4,0xE,
    0x2,0x2,0x2,0xA,0x4, 0x9,0xA,0xC,0xA,0x9, 0x8,0x8,0x8,0x8,0xF,
    0x9,0xF,0xF,0x9,0x9, 0x9,0xD,0xB,0x9,0x9, 0x6,0x9,0x9,0x9,0x6,
    0xE,0x9,0xE,0x8,0x8, 0x6,0x9,0xB,0xA,0x5, 0xE,0x9,0xE,0xA,0x9,
    0x7,0x8,0x6,0x1,0xE, 0xE,0x4,0x4,0x4,0x4, 0x9,0x9,0x9,0x9,0x6,
    0x9,0x9,0xA,0xA,0x4, 0x9,0x9,0xF,0xF,0x9, 0x9,0xA,0x4,0xA,0x9,
    0x9,0xA,0x4,0x4,0x4, 0xF,0x2,0x4,0x8,0xF,
    -- 0-9
    0x6,0x9,0x9,0x9,0x6, 0x2,0x6,0x2,0x2,0x7, 0xE,0x1,0x6,0x8,0xF,
    0xE,0x1,0x6,0x1,0xE, 0x9,0x9,0xF,0x1,0x1, 0xF,0x8,0xE,0x1,0xE,
    0x6,0x8,0xE,0x9,0x6, 0xF,0x1,0x2,0x4,0x4, 0x6,0x9,0x6,0x9,0x6,
    0x6,0x9,0x7,0x1,0x6,
]

fn draw_char(x: i32, y: i32, c: u8, col: u32) {
    let idx: i32 = 0
    if c >= 65 and c <= 90 { idx = (c as i32 - 65) * 5 }
    elif c >= 97 and c <= 122 { idx = (c as i32 - 97) * 5 }
    elif c >= 48 and c <= 57  { idx = (c as i32 - 48 + 26) * 5 }
    else { return }
    for row in 0..5 {
        let bits: u8 = FONT[idx + row]
        for bit in 0..4 {
            if (bits >> (3 - bit)) & 1 == 1 {
                rdpq.set_prim_color(col)
                rdpq.fill_rectangle(
                    (x + bit) as f32, (y + row) as f32,
                    (x + bit + 1) as f32, (y + row + 1) as f32)
            }
        }
    }
}

fn draw_str(x: i32, y: i32, s: []u8, col: u32) {
    let cx: i32 = x
    for i in 0..s.len {
        let c: u8 = s[i]
        if c == 0 { break }
        if c == 32 { cx = cx + FONT_W + 1; continue }
        draw_char(cx, y, c, col)
        cx = cx + FONT_W + 1
    }
}

fn draw_int(x: i32, y: i32, v: i32, col: u32) {
    let buf: [8]u8 = [0; 8]
    let n: i32 = v
    if n < 0 { n = 0 }
    let i: i32 = 7
    if n == 0 {
        buf[7] = 48
    } else {
        while n > 0 {
            buf[i] = (48 + n % 10) as u8
            n = n / 10
            i = i - 1
        }
        i = i + 1
    }
    draw_str(x, y, buf[i..8], col)
}
}
}

# ── Math helpers ──────────────────────────────────────────────────────────────

proc codegen::topdown::_math_block {} {
    return {-- ── Math helpers ──────────────────────────────────────────────────────────────

-- Fast pseudo-random (xorshift32)
static rng_state: u32 = 12345

fn rand_next() -> u32 {
    rng_state = rng_state ^ (rng_state << 13)
    rng_state = rng_state ^ (rng_state >> 17)
    rng_state = rng_state ^ (rng_state << 5)
    return rng_state
}

fn rand_range(lo: i32, hi: i32) -> i32 {
    if hi <= lo { return lo }
    return lo + (rand_next() as i32 % (hi - lo))
}

fn clamp(v: i32, lo: i32, hi: i32) -> i32 {
    if v < lo { return lo }
    if v > hi { return hi }
    return v
}

-- EXP threshold for the next level (100 * level^1.5 approximated)
fn exp_for_level(lv: i32) -> i32 {
    -- approx lv * lv * 10 + lv * EXP_BASE
    return lv * lv * 10 + lv * EXP_BASE
}

-- Damage formula: (atk * power / 100) - (def / 2) + small random variance
fn calc_damage(atk: i32, def: i32, power: i32) -> i32 {
    let base: i32 = atk * power / 100
    let reduction: i32 = def / 2
    let raw: i32 = base - reduction
    if raw < 1 { raw = 1 }
    -- ±20% variance
    let spread: i32 = raw / 5
    if spread < 1 { spread = 1 }
    raw = raw + rand_range(-spread, spread)
    return clamp(raw, 1, 9999)
}

-- Apply stat growth on level-up (grow values are *10, applied /10)
fn level_up_stats(idx: i32) {
    let base: *ActorBase = &ACTOR_BASE[party[idx].base_idx]
    party[idx].level = party[idx].level + 1
    party[idx].atk = party[idx].atk + base.at_grow / 10 + 1
    party[idx].def = party[idx].def + base.df_grow / 10 + 1
    party[idx].mag = party[idx].mag + base.mg_grow / 10 + 1
    party[idx].spd = party[idx].spd + base.sp_grow / 10 + 1
    -- also increase current HP/MP caps
    let hp_gain: i32 = base.hp_grow / 10 + 2
    let mp_gain: i32 = base.mp_grow / 10 + 1
    let base_ptr: *ActorBase = &ACTOR_BASE[party[idx].base_idx]
    -- heal a portion on level-up (bonus HP)
    party[idx].hp = clamp(party[idx].hp + hp_gain, 0, base_ptr.max_hp + party[idx].level * 5)
    party[idx].mp = clamp(party[idx].mp + mp_gain, 0, base_ptr.max_mp + party[idx].level * 2)
}

fn gain_exp(idx: i32, amount: i32) {
    if not party[idx].alive { return }
    party[idx].exp = party[idx].exp + amount
    while party[idx].exp >= exp_for_level(party[idx].level)
          and party[idx].level < MAX_LEVEL {
        party[idx].exp = party[idx].exp - exp_for_level(party[idx].level)
        level_up_stats(idx)
        b_msg_timer = 90    -- show level-up notice
    }
}
}
}

# ── Draw utilities ────────────────────────────────────────────────────────────

proc codegen::topdown::_draw_block {} {
    return {-- ── Draw utilities ────────────────────────────────────────────────────────────

fn fill_rect(x: i32, y: i32, w: i32, h: i32, col: u32) {
    rdpq.set_prim_color(col)
    rdpq.fill_rectangle(x as f32, y as f32, (x+w) as f32, (y+h) as f32)
}

fn draw_bar(x: i32, y: i32, w: i32, h: i32,
            cur: i32, max_val: i32, fillcol: u32) {
    fill_rect(x, y, w, h, 0x111111FF)
    if max_val > 0 {
        let fw: i32 = w * cur / max_val
        if fw < 0 { fw = 0 }
        if fw > w { fw = w }
        if fw > 0 { fill_rect(x, y, fw, h, fillcol) }
    }
    -- outline
    fill_rect(x,     y,     w, 1, 0x444444FF)
    fill_rect(x,     y+h-1, w, 1, 0x444444FF)
    fill_rect(x,     y,     1, h, 0x444444FF)
    fill_rect(x+w-1, y,     1, h, 0x444444FF)
}

fn draw_panel(x: i32, y: i32, w: i32, h: i32) {
    fill_rect(x, y, w, h, 0x0A0A1AFF)
    fill_rect(x,     y,     w, 1, 0x4466AAFF)
    fill_rect(x,     y+h-1, w, 1, 0x4466AAFF)
    fill_rect(x,     y,     1, h, 0x4466AAFF)
    fill_rect(x+w-1, y,     1, h, 0x4466AAFF)
}

-- Tile color lookup
fn tile_color(t: u8) -> u32 {
    match t as i32 {
        0 => return 0x4A7A30FF   -- grass
        1 => return 0x606060FF   -- wall
        2 => return 0x808080FF   -- stone
        3 => return 0x7A6040FF   -- dirt/floor
        4 => return 0x2060B0FF   -- water
        5 => return 0x505060FF   -- road
        6 => return 0x604020FF   -- chest/item tile
        _ => return 0x303030FF
    }
}
}
}

# ── World system ──────────────────────────────────────────────────────────────

proc codegen::topdown::_world_block {} {
    return {-- ── World System ──────────────────────────────────────────────────────────────

fn draw_world() {
    -- Camera: center on player
    let cam_x: i32 = world.x * TILE_SZ - SCREEN_W / 2 + TILE_SZ / 2
    let cam_y: i32 = world.y * TILE_SZ - SCREEN_H / 2 + TILE_SZ / 2
    -- Clamp camera to map bounds
    let max_cx: i32 = MAP_W * TILE_SZ - SCREEN_W
    let max_cy: i32 = MAP_H * TILE_SZ - SCREEN_H
    if cam_x < 0 { cam_x = 0 }
    if cam_y < 0 { cam_y = 0 }
    if cam_x > max_cx { cam_x = max_cx }
    if cam_y > max_cy { cam_y = max_cy }

    -- Draw visible tiles
    let tx0: i32 = cam_x / TILE_SZ
    let ty0: i32 = cam_y / TILE_SZ
    let tx1: i32 = (cam_x + SCREEN_W) / TILE_SZ + 1
    let ty1: i32 = (cam_y + SCREEN_H) / TILE_SZ + 1
    for ty in ty0..(ty1+1) {
        for tx in tx0..(tx1+1) {
            let t: u8 = tile_at(tx, ty)
            let col: u32 = tile_color(t)
            let sx: i32 = tx * TILE_SZ - cam_x
            let sy: i32 = ty * TILE_SZ - cam_y
            fill_rect(sx, sy, TILE_SZ, TILE_SZ, col)
        }
    }

    -- Draw player (simple colored square with direction indicator)
    let px: i32 = world.x * TILE_SZ - cam_x
    let py: i32 = world.y * TILE_SZ - cam_y
    fill_rect(px+2, py+2, TILE_SZ-4, TILE_SZ-4, 0xE8D060FF)
    -- Direction pip
    let pip_col: u32 = 0x303030FF
    match world.dir {
        0 => fill_rect(px + TILE_SZ/2 - 1, py + TILE_SZ - 5, 3, 3, pip_col)  -- down
        1 => fill_rect(px + TILE_SZ/2 - 1, py + 2,           3, 3, pip_col)  -- up
        2 => fill_rect(px + 2,             py + TILE_SZ/2-1, 3, 3, pip_col)  -- left
        3 => fill_rect(px + TILE_SZ - 5,  py + TILE_SZ/2-1, 3, 3, pip_col)  -- right
    }
}

fn world_update(pad: joypad_buttons_t) {
    if world.move_cool > 0 {
        world.move_cool = world.move_cool - 1
        return
    }

    let dx: i32 = 0
    let dy: i32 = 0
    if pad.d_left  { dx = -1; world.dir = 2 }
    elif pad.d_right { dx = 1; world.dir = 3 }
    elif pad.d_up    { dy = -1; world.dir = 1 }
    elif pad.d_down  { dy = 1; world.dir = 0 }

    if dx == 0 and dy == 0 { return }

    let nx: i32 = world.x + dx
    let ny: i32 = world.y + dy
    let nt: u8 = tile_at(nx, ny)

    if not tile_solid(nt) {
        world.x = nx
        world.y = ny
        world.step = world.step + 1
        world.move_cool = 8

        -- Random encounter check on encounter tiles
        if tile_encounter(nt) {
            world.steps_til_encounter = world.steps_til_encounter - 1
            if world.steps_til_encounter <= 0 {
                world.steps_til_encounter = rand_range(10, 20)
                start_encounter()
            }
        }
    }
}

fn start_encounter() {
    -- Pick random enemy group: 1-3 enemies of a random type
    let etype: i32 = rand_range(0, NUM_ENEMIES)
    let n: i32 = rand_range(1, 4)
    if n > 4 { n = 4 }
    b_n_enemies = n
    for i in 0..4 {
        if i < n {
            b_enemies[i] = BattleEnemy {
                def_idx: etype,
                hp: ENEMIES[etype].max_hp,
                alive: true
            }
        } else {
            b_enemies[i].alive = false
        }
    }
    b_turn    = 0
    b_menu    = MENU_ATTACK
    b_target  = 0
    b_exp_gain  = 0
    b_gold_gain = 0
    b_anim    = 0
    b_actor_turn = 0
    phase     = PHASE_BATTLE
}
}
}

# ── Battle system ─────────────────────────────────────────────────────────────

proc codegen::topdown::_battle_block {} {
    return {-- ── Battle System ─────────────────────────────────────────────────────────────

fn first_alive_actor() -> i32 {
    for i in 0..PARTY_SIZE {
        if party[i].alive and party[i].hp > 0 { return i }
    }
    return -1
}

fn first_alive_enemy() -> i32 {
    for i in 0..b_n_enemies {
        if b_enemies[i].alive { return i }
    }
    return -1
}

fn party_all_dead() -> bool {
    for i in 0..PARTY_SIZE {
        if party[i].alive and party[i].hp > 0 { return false }
    }
    return true
}

fn enemies_all_dead() -> bool {
    for i in 0..b_n_enemies {
        if b_enemies[i].alive { return false }
    }
    return true
}

fn apply_item_effect(actor_idx: i32, item_idx: i32) {
    if item_idx < 0 or item_idx >= NUM_ITEMS { return }
    let it: *ItemDef = &ITEMS[item_idx]
    let a: *Actor    = &party[actor_idx]
    let base: *ActorBase = &ACTOR_BASE[a.base_idx]
    let max_hp_eff: i32 = base.max_hp + a.level * 5
    let max_mp_eff: i32 = base.max_mp + a.level * 2
    match it.effect {
        FX_HEAL_HP => a.hp = clamp(a.hp + it.power, 0, max_hp_eff)
        FX_HEAL_MP => a.mp = clamp(a.mp + it.power, 0, max_mp_eff)
        FX_REVIVE  => {
            if not a.alive {
                a.alive = true
                a.hp    = it.power
            }
        }
        _ => {}
    }
}

fn battle_do_attack(actor_idx: i32, enemy_idx: i32) {
    let a:   *Actor     = &party[actor_idx]
    let e:   *BattleEnemy = &b_enemies[enemy_idx]
    let edef: *EnemyDef  = &ENEMIES[e.def_idx]
    let dmg: i32 = calc_damage(a.atk, edef.def, 100)
    e.hp = e.hp - dmg
    if e.hp <= 0 {
        e.hp    = 0
        e.alive = false
        b_exp_gain  = b_exp_gain  + edef.exp
        b_gold_gain = b_gold_gain + edef.gold
        -- Item drop
        if edef.drop_item >= 0 and edef.drop_rate > 0 {
            if rand_range(0, 100) < edef.drop_rate {
                let drop_slot: i32 = edef.drop_item
                if drop_slot < INV_SIZE {
                    inventory[drop_slot] = inventory[drop_slot] + 1
                }
            }
        }
    }
    b_anim = BATTLE_ANIM_FRAMES
}

fn battle_do_skill(actor_idx: i32, skill_idx: i32, target: i32) {
    if skill_idx < 0 or skill_idx >= NUM_SKILLS { return }
    let sk: *SkillDef = &SKILLS[skill_idx]
    let a:  *Actor    = &party[actor_idx]
    if a.mp < sk.mp_cost { return }
    a.mp = a.mp - sk.mp_cost
    -- Apply to target(s)
    let power: i32 = sk.power
    match sk.target {
        0 => {
            -- one_enemy
            if target >= 0 and target < b_n_enemies and b_enemies[target].alive {
                let edef: *EnemyDef = &ENEMIES[b_enemies[target].def_idx]
                let mag_atk: i32 = a.mag * 2
                let dmg: i32 = calc_damage(mag_atk, edef.def / 2, power)
                b_enemies[target].hp = b_enemies[target].hp - dmg
                if b_enemies[target].hp <= 0 {
                    b_enemies[target].hp    = 0
                    b_enemies[target].alive = false
                    b_exp_gain  = b_exp_gain  + edef.exp
                    b_gold_gain = b_gold_gain + edef.gold
                }
            }
        }
        1 => {
            -- all_enemies
            for i in 0..b_n_enemies {
                if b_enemies[i].alive {
                    let edef: *EnemyDef = &ENEMIES[b_enemies[i].def_idx]
                    let mag_atk: i32 = a.mag * 2
                    let dmg: i32 = calc_damage(mag_atk, edef.def / 2, power)
                    b_enemies[i].hp = b_enemies[i].hp - dmg
                    if b_enemies[i].hp <= 0 {
                        b_enemies[i].hp    = 0
                        b_enemies[i].alive = false
                        b_exp_gain  = b_exp_gain  + edef.exp
                        b_gold_gain = b_gold_gain + edef.gold
                    }
                }
            }
        }
        2 => {
            -- one_ally: heal
            let ally: *Actor = &party[target % PARTY_SIZE]
            let base: *ActorBase = &ACTOR_BASE[ally.base_idx]
            let max_hp_e: i32 = base.max_hp + ally.level * 5
            ally.hp = clamp(ally.hp + power, 0, max_hp_e)
        }
        3 => {
            -- all_allies: heal all
            for i in 0..PARTY_SIZE {
                if party[i].alive {
                    let base: *ActorBase = &ACTOR_BASE[party[i].base_idx]
                    let max_hp_e: i32 = base.max_hp + party[i].level * 5
                    party[i].hp = clamp(party[i].hp + power, 0, max_hp_e)
                }
            }
        }
        4 => {
            -- self
            let base: *ActorBase = &ACTOR_BASE[a.base_idx]
            let max_hp_e: i32 = base.max_hp + a.level * 5
            a.hp = clamp(a.hp + power, 0, max_hp_e)
        }
        _ => {}
    }
    b_anim = BATTLE_ANIM_FRAMES
}

fn enemy_take_turn() {
    -- Find a living enemy
    let eidx: i32 = first_alive_enemy()
    if eidx < 0 { b_turn = 0; return }
    let e:    *BattleEnemy = &b_enemies[eidx]
    let edef: *EnemyDef    = &ENEMIES[e.def_idx]

    -- Find a living party target
    let aidx: i32 = first_alive_actor()
    if aidx < 0 { return }

    -- Check if enemy uses a skill
    let used_skill: bool = false
    if edef.n_skills > 0 and edef.max_mp > 0 {
        let sk_idx: i32 = edef.skills[rand_range(0, edef.n_skills)]
        if sk_idx >= 0 and sk_idx < NUM_SKILLS {
            let sk: *SkillDef = &SKILLS[sk_idx]
            -- Enemy uses skill against player party
            let mag: i32 = edef.mag
            let dmg: i32 = calc_damage(mag * 2, party[aidx].def / 2, sk.power)
            party[aidx].hp = party[aidx].hp - dmg
            if party[aidx].hp <= 0 {
                party[aidx].hp    = 0
                party[aidx].alive = false
            }
            used_skill = true
        }
    }

    if not used_skill {
        -- Basic attack
        let dmg: i32 = calc_damage(edef.atk, party[aidx].def, 100)
        party[aidx].hp = party[aidx].hp - dmg
        if party[aidx].hp <= 0 {
            party[aidx].hp    = 0
            party[aidx].alive = false
        }
    }
    b_turn = 0
    b_anim = BATTLE_ANIM_FRAMES / 2
}

fn battle_end_check() {
    if enemies_all_dead() {
        -- Distribute exp + gold
        gold = gold + b_gold_gain
        for i in 0..PARTY_SIZE {
            if party[i].alive {
                gain_exp(i, b_exp_gain)
            }
        }
        b_msg_timer = 90
        phase = PHASE_WORLD
        return
    }
    if party_all_dead() {
        phase = PHASE_GAMEOVER
    }
}

fn battle_update(pad: joypad_buttons_t) {
    if b_anim > 0 { b_anim = b_anim - 1; return }

    if b_turn == 2 {
        -- Enemy phase
        enemy_take_turn()
        battle_end_check()
        return
    }

    -- Player menu navigation
    if pad.d_up   { b_menu = (b_menu + MENU_RUN) % (MENU_RUN + 1) }
    if pad.d_down { b_menu = (b_menu + 1)        % (MENU_RUN + 1) }

    match b_menu {
        MENU_ATTACK => {
            -- Target selection with left/right
            if pad.d_left  { b_target = clamp(b_target - 1, 0, b_n_enemies - 1) }
            if pad.d_right { b_target = clamp(b_target + 1, 0, b_n_enemies - 1) }
            -- Find next alive target if current is dead
            if not b_enemies[b_target].alive {
                b_target = 0
                for i in 0..b_n_enemies {
                    if b_enemies[i].alive { b_target = i; break }
                }
            }
            if pad.a {
                let actor: i32 = first_alive_actor()
                if actor >= 0 {
                    battle_do_attack(actor, b_target)
                    b_turn = 2
                    battle_end_check()
                }
            }
        }
        MENU_SKILL => {
            if pad.d_left  { b_skill_sel = clamp(b_skill_sel - 1, 0, NUM_SKILLS - 1) }
            if pad.d_right { b_skill_sel = clamp(b_skill_sel + 1, 0, NUM_SKILLS - 1) }
            if pad.a {
                let actor: i32 = first_alive_actor()
                if actor >= 0 {
                    battle_do_skill(actor, b_skill_sel, b_target)
                    b_turn = 2
                    battle_end_check()
                }
            }
        }
        MENU_ITEM => {
            if pad.d_left  { b_item_sel = clamp(b_item_sel - 1, 0, INV_SIZE - 1) }
            if pad.d_right { b_item_sel = clamp(b_item_sel + 1, 0, INV_SIZE - 1) }
            if pad.a {
                if inventory[b_item_sel] > 0 {
                    let actor: i32 = first_alive_actor()
                    if actor >= 0 {
                        apply_item_effect(actor, b_item_sel)
                        inventory[b_item_sel] = inventory[b_item_sel] - 1
                        b_turn = 2
                        battle_end_check()
                    }
                }
            }
        }
        MENU_RUN => {
            if pad.a {
                let chance: i32 = FLEE_CHANCE + world.step % 20
                if rand_range(0, 100) < chance {
                    phase = PHASE_WORLD
                } else {
                    b_turn = 2
                }
            }
        }
        _ => {}
    }
}

fn draw_battle() {
    -- Sky gradient (simple fill)
    fill_rect(0, 0, SCREEN_W, 120, 0x0A1830FF)
    fill_rect(0, 120, SCREEN_W, 60, 0x183010FF)
    fill_rect(0, 180, SCREEN_W, SCREEN_H - 180, 0x0A0A1AFF)

    -- Draw enemies
    for i in 0..b_n_enemies {
        if b_enemies[i].alive {
            let ex: i32 = 60 + i * 60
            let ey: i32 = 80
            -- Body
            let ecol: u32 = 0x60A040FF
            if i == b_target and b_turn == 0 { ecol = 0x80C060FF }
            fill_rect(ex, ey, 28, 36, ecol)
            -- Eyes
            fill_rect(ex+6, ey+8, 4, 4, 0xFF4040FF)
            fill_rect(ex+18, ey+8, 4, 4, 0xFF4040FF)
            -- HP bar
            let edef: *EnemyDef = &ENEMIES[b_enemies[i].def_idx]
            draw_bar(ex, ey+38, 28, 4, b_enemies[i].hp, edef.max_hp, 0xCC2020FF)
        }
    }

    -- Draw party
    for i in 0..PARTY_SIZE {
        if party[i].alive {
            let px: i32 = 30 + i * 90
            let py: i32 = 135
            fill_rect(px, py, 22, 30, 0xD0A040FF)
            fill_rect(px+5, py+5, 5, 5, 0x303030FF)
            fill_rect(px+12, py+5, 5, 5, 0x303030FF)
        }
    }

    -- Battle UI panel
    draw_panel(0, 178, SCREEN_W, SCREEN_H - 178)

    -- Enemy HP text
    for i in 0..b_n_enemies {
        if b_enemies[i].alive {
            let edef: *EnemyDef = &ENEMIES[b_enemies[i].def_idx]
            draw_int(4 + i * 80, 183, b_enemies[i].hp, 0xFF6060FF)
        }
    }

    -- Party bars
    for i in 0..PARTY_SIZE {
        if party[i].alive {
            let base: *ActorBase = &ACTOR_BASE[party[i].base_idx]
            let max_hp_e: i32 = base.max_hp + party[i].level * 5
            let max_mp_e: i32 = base.max_mp + party[i].level * 2
            let bx: i32 = 4 + i * 100
            draw_bar(bx, 192, 90, 5, party[i].hp, max_hp_e, 0x20CC20FF)
            draw_bar(bx, 200, 90, 5, party[i].mp, max_mp_e, 0x2060FFFF)
            draw_int(bx, 208, party[i].level, 0xCCCC40FF)
        }
    }

    -- Command menu
    let menu_labels: [4][7]u8 = [
        [65,84,84,65,67,75,0],  -- ATTACK
        [83,75,73,76,76,0,0],   -- SKILL
        [73,84,69,77,0,0,0],    -- ITEM
        [82,85,78,0,0,0,0],     -- RUN
    ]
    for i in 0..4 {
        let mx: i32 = 200 + (i % 2) * 58
        let my: i32 = 182 + (i / 2) * 14
        let tcol: u32 = 0x8888CCFF
        if i == b_menu { tcol = 0xFFFF60FF; fill_rect(mx-2, my-1, 56, 12, 0x1A1A3AFF) }
        draw_str(mx, my, menu_labels[i][0..7], tcol)
    }
}
}
}

# ── Crafting system ───────────────────────────────────────────────────────────

proc codegen::topdown::_craft_block {} {
    return {-- ── Crafting System ────────────────────────────────────────────────────────────

fn can_craft(recipe_idx: i32) -> bool {
    if recipe_idx < 0 or recipe_idx >= NUM_RECIPES { return false }
    let r: *RecipeDef = &RECIPES[recipe_idx]
    for i in 0..r.n_inputs {
        let item_id: i32 = r.in_item[i]
        let qty_needed: i32 = r.in_qty[i]
        if item_id < 0 or item_id >= INV_SIZE { return false }
        if inventory[item_id] < qty_needed { return false }
    }
    return true
}

fn do_craft(recipe_idx: i32) {
    if not can_craft(recipe_idx) { return }
    let r: *RecipeDef = &RECIPES[recipe_idx]
    -- Consume ingredients
    for i in 0..r.n_inputs {
        let item_id: i32 = r.in_item[i]
        inventory[item_id] = inventory[item_id] - r.in_qty[i]
    }
    -- Produce output
    let out_id: i32 = r.out_item
    if out_id >= 0 and out_id < INV_SIZE {
        inventory[out_id] = inventory[out_id] + r.out_qty
    }
    craft_timer = 60
}

fn craft_update(pad: joypad_buttons_t) {
    if craft_timer > 0 { craft_timer = craft_timer - 1 }
    if pad.d_up   { craft_sel = clamp(craft_sel - 1, 0, NUM_RECIPES - 1) }
    if pad.d_down { craft_sel = clamp(craft_sel + 1, 0, NUM_RECIPES - 1) }
    if pad.a      { do_craft(craft_sel) }
    if pad.b      { phase = PHASE_MENU }
}

fn draw_crafting() {
    draw_panel(0, 0, SCREEN_W, SCREEN_H)
    -- Title
    let title_str: [9]u8 = [67,82,65,70,84,73,78,71,0]  -- CRAFTING
    draw_str(8, 8, title_str[0..9], 0xFFDD60FF)

    for i in 0..NUM_RECIPES {
        let r: *RecipeDef = &RECIPES[i]
        let ry: i32 = 24 + i * 20
        let selcol: u32 = 0x6688BBFF
        if i == craft_sel { selcol = 0xFFFF80FF; fill_rect(4, ry-2, SCREEN_W-8, 18, 0x1A2040FF) }
        -- Ingredients
        let ok: bool = can_craft(i)
        let ic: u32 = 0xCC4444FF
        if ok { ic = 0x44CC44FF }
        fill_rect(SCREEN_W - 10, ry + 2, 6, 6, ic)
        -- Output item id
        draw_int(8, ry, r.out_item, selcol)
        draw_int(30, ry, r.out_qty, selcol)
        -- n inputs
        draw_int(60, ry, r.n_inputs, 0x8888CCFF)
    }

    -- Gold
    let gold_lbl: [5]u8 = [71,79,76,68,0]  -- GOLD
    draw_str(8, SCREEN_H - 16, gold_lbl[0..5], 0xFFDD40FF)
    draw_int(40, SCREEN_H - 16, gold, 0xFFDD40FF)
}
}
}

# ── UI block ──────────────────────────────────────────────────────────────────

proc codegen::topdown::_ui_block {} {
    return {-- ── UI ────────────────────────────────────────────────────────────────────────

fn draw_hud() {
    -- Mini HP bars bottom-left
    for i in 0..PARTY_SIZE {
        if party[i].alive {
            let base: *ActorBase = &ACTOR_BASE[party[i].base_idx]
            let max_hp_hud: i32 = base.max_hp + party[i].level * 5
            draw_bar(2, SCREEN_H - 12 - i * 10, 50, 5,
                     party[i].hp, max_hp_hud, 0x20DD20FF)
        }
    }
    -- Gold top-right
    draw_int(SCREEN_W - 36, 2, gold, 0xFFDD40FF)
}

fn draw_title() {
    fill_rect(0, 0, SCREEN_W, SCREEN_H, 0x05081AFF)
    -- Stars
    let star_xs: [12]i32 = [20,80,140,200,260,50,120,180,240,30,100,220]
    let star_ys: [12]i32 = [10,25,15,30,8,50,40,55,20,70,60,45]
    for i in 0..12 {
        let blink: i32 = (frame / 20 + i) % 4
        if blink < 3 {
            fill_rect(star_xs[i], star_ys[i], 2, 2, 0xCCCCFFFF)
        }
    }
    -- Title text (drawn as colored rectangle + label)
    fill_rect(40, 80, SCREEN_W - 80, 30, 0x1A1040FF)
    fill_rect(40, 80, SCREEN_W - 80, 2, 0x8060FFFF)
    fill_rect(40, 108, SCREEN_W - 80, 2, 0x8060FFFF)

    -- Menu items: NEW GAME, CONTINUE
    let sel_items: [2]bool = [title_sel == 0, title_sel == 1]
    let ny: [2]i32 = [140, 160]
    for i in 0..2 {
        let tc: u32 = 0x6688CCFF
        if sel_items[i] { tc = 0xFFFF60FF; fill_rect(60, ny[i]-2, SCREEN_W-120, 14, 0x1A1A3AFF) }
        if i == 0 {
            let ng: [9]u8 = [78,69,87,32,71,65,77,69,0]  -- NEW GAME
            draw_str(SCREEN_W/2 - 30, ny[i], ng[0..9], tc)
        } else {
            let ct: [9]u8 = [67,79,78,84,73,78,85,69,0]  -- CONTINUE
            draw_str(SCREEN_W/2 - 30, ny[i], ct[0..9], tc)
        }
    }
}

fn draw_gameover() {
    fill_rect(0, 0, SCREEN_W, SCREEN_H, 0x100808FF)
    let go: [10]u8 = [71,65,77,69,32,79,86,69,82,0]  -- GAME OVER
    draw_str(SCREEN_W/2 - 20, SCREEN_H/2 - 6, go[0..10], 0xFF4040FF)
}

fn title_update(pad: joypad_buttons_t) {
    if pad.d_up   { title_sel = (title_sel + 1) % 2 }
    if pad.d_down { title_sel = (title_sel + 1) % 2 }
    if pad.a {
        -- init party stats from base table
        for i in 0..PARTY_SIZE {
            if party[i].alive {
                let base: *ActorBase = &ACTOR_BASE[party[i].base_idx]
                party[i].atk = base.atk
                party[i].def = base.def
                party[i].mag = base.mag
                party[i].spd = base.spd
            }
        }
        phase = PHASE_WORLD
    }
}

fn menu_update(pad: joypad_buttons_t) {
    if pad.a { phase = PHASE_CRAFT }
    if pad.b { phase = PHASE_WORLD }
}

fn draw_menu() {
    draw_panel(40, 40, SCREEN_W - 80, SCREEN_H - 80)
    -- Basic party status
    for i in 0..PARTY_SIZE {
        if party[i].alive {
            let ay: i32 = 55 + i * 40
            let base: *ActorBase = &ACTOR_BASE[party[i].base_idx]
            let max_hp_m: i32 = base.max_hp + party[i].level * 5
            let max_mp_m: i32 = base.max_mp + party[i].level * 2
            draw_bar(50, ay, 100, 7, party[i].hp, max_hp_m, 0x20CC20FF)
            draw_bar(50, ay+10, 100, 7, party[i].mp, max_mp_m, 0x2060FFFF)
            draw_int(160, ay, party[i].level, 0xFFFF60FF)
            draw_int(160, ay+10, party[i].exp, 0xCC8840FF)
        }
    }
    -- Gold
    draw_int(50, SCREEN_H - 55, gold, 0xFFDD40FF)
}
}
}

# ── Entry block ───────────────────────────────────────────────────────────────

proc codegen::topdown::_entry_block {doc} {
    return {-- ── Entry point ────────────────────────────────────────────────────────────────
entry {
    display.init(RESOLUTION_320x240, DEPTH_16_BPP, 2, GAMMA_NONE, FILTERS_RESAMPLE)
    controller.init()
    rdpq.init()
    rdpq.debug_start()

    -- Seed RNG with a simple value
    rng_state = 0xDEAD1234

    -- Init party stats from base table
    for i in 0..PARTY_SIZE {
        if party[i].alive {
            let base: *ActorBase = &ACTOR_BASE[party[i].base_idx]
            party[i].atk = base.atk
            party[i].def = base.def
            party[i].mag = base.mag
            party[i].spd = base.spd
        }
    }

    loop {
        controller.poll()
        let pad: joypad_buttons_t = controller.read(0).held

        let surface: *surface_t = display.get()
        rdpq.attach(surface, none)
        rdpq.clear(0x050810FF)

        match phase {
            PHASE_TITLE => {
                title_update(pad)
                draw_title()
            }
            PHASE_WORLD => {
                world_update(pad)
                draw_world()
                draw_hud()
                -- Open menu with Start
                if pad.start { phase = PHASE_MENU }
            }
            PHASE_BATTLE => {
                battle_update(pad)
                draw_battle()
            }
            PHASE_MENU => {
                menu_update(pad)
                draw_menu()
            }
            PHASE_CRAFT => {
                craft_update(pad)
                draw_crafting()
            }
            PHASE_GAMEOVER => {
                draw_gameover()
                if pad.start { phase = PHASE_TITLE }
            }
            _ => { phase = PHASE_TITLE }
        }

        rdpq.detach_show()
        frame = frame + 1
    }
}
}
}
