# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl Player_init
	.type Player_init, @function
Player_init:
    sw $a0, 96($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t6, 96($sp)
    lw $t7, 0($t6)
    swc1 $f12, 0($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t6, 96($sp)
    lw $t7, 0($t6)
    swc1 $f12, 4($t7)
    move $t9, $t8
    li $t8, 100
    lw $t7, 96($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    lw $t7, 96($sp)
    swc1 $f12, 12($t7)
    move $t9, $t8
    li $t8, 1
    lw $t7, 96($sp)
    sb $t8, 16($t7)
    move $t9, $t8
.LPlayer_init_ret_0:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size Player_init, . - Player_init

	.section .text
	.globl Player_move
	.type Player_move, @function
Player_move:
    sw $a0, 96($sp)
    swc1 $f12, 100($sp)
    swc1 $f12, 104($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    lwc1 $f12, 100($sp)
    la $t7, __cur
    lw $t7, 0($t7)
    addu $t8, $t7, $t8
    lw $t6, 96($sp)
    lw $t7, 0($t6)
    swc1 $f12, 0($t7)
    move $t9, $t8
    lwc1 $f12, 104($sp)
    la $t7, __cur
    lw $t7, 0($t7)
    addu $t8, $t7, $t8
    lw $t6, 96($sp)
    lw $t7, 0($t6)
    swc1 $f12, 4($t7)
    move $t9, $t8
.LPlayer_move_ret_1:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size Player_move, . - Player_move

	.section .text
	.globl Player_is_alive
	.type Player_is_alive, @function
Player_is_alive:
    sw $a0, 96($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    lw $t8, 96($sp)
    lw $t9, 8($t8)
    li $t8, 0
    sgt $v0, $t9, $t8
    j .LPlayer_is_alive_ret_2
    nop
.LPlayer_is_alive_ret_2:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size Player_is_alive, . - Player_is_alive

	.section .text
	.globl Player_take_damage
	.type Player_take_damage, @function
Player_take_damage:
    sw $a0, 96($sp)
    sw $a1, 100($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    lw $t8, 100($sp)
    la $t7, __cur
    lw $t7, 0($t7)
    subu $t8, $t7, $t8
    lw $t7, 96($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    lw $t7, 96($sp)
    lw $t8, 8($t7)
    li $t7, 0
    sle $t9, $t8, $t7
    beqz $t9, .Lif_end_4
    nop
    li $t8, 0
    lw $t7, 96($sp)
    sb $t8, 16($t7)
    move $t9, $t8
.Lif_end_4:
.LPlayer_take_damage_ret_3:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size Player_take_damage, . - Player_take_damage

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    sw $zero, 100($sp)
    sw $zero, 104($sp)
    sw $zero, 108($sp)
    sw $zero, 112($sp)
    sw $zero, 116($sp)
    sw $zero, 120($sp)
    sw $zero, 124($sp)
    la $t6, .Lf322
    lwc1 $f12, 0($t6)
    swc1 $f12, 120($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    swc1 $f12, 124($sp)
    addiu $t8, $sp, 120
    sw $t8, 100($sp)
    li $t8, 100
    sw $t8, 108($sp)
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    swc1 $f12, 112($sp)
    li $t8, 1
    sb $t8, 116($sp)
    addiu $t9, $sp, 100
    sw $t9, 96($sp)
    lw $t6, 96($sp)
    lw $t7, 0($t6)
    lwc1 $f12, 0($t7)
    la $t7, sink_x
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 96($sp)
    lw $t8, 8($t7)
    la $t7, sink_hp
    sw $t8, 0($t7)
    move $t9, $t8
    addiu $t8, $sp, 96
    move $a0, $t8
    la $t8, .Lf324
    lwc1 $f12, 0($t8)
    la $t8, .Lf320
    lwc1 $f12, 0($t8)
    jal P_move
    nop
    move $t9, $v0
    addiu $t8, $sp, 96
    move $a0, $t8
    li $a1, 10
    jal P_take_damage
    nop
    move $t9, $v0
    lw $t7, 96($sp)
    lw $t8, 8($t7)
    la $t7, sink_hp
    sw $t8, 0($t7)
    move $t9, $t8
    addiu $t8, $sp, 96
    move $a0, $t8
    jal P_is_alive
    nop
    move $t9, $v0
    beqz $t9, .Lif_end_6
    nop
    lw $t7, 96($sp)
    lw $t8, 8($t7)
    la $t7, sink_hp
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_6:
.Lmain_ret_5:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 2
.Lf320:
	.word 0
	.align 2
.Lf321:
	.word 1075838976
	.align 2
.Lf322:
	.word 1092616192
	.align 2
.Lf323:
	.word 1101004800
	.align 2
.Lf324:
	.word 1065353216

	.section .data
	.align 2
	.globl sink_hp
sink_hp:
	.word 0

	.section .bss
	.align 2
	.globl sink_x
sink_x:
	.space 4
