# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl area
	.type area, @function
area:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    sw $a0, 96($sp)
    lw $t9, 96($sp)
    lbu $t8, 0($t9)
    li $t7, 0
    bne $t8, $t7, .Larm_skip_3
    nop
    lwc1 $f12, 4($t9)
    swc1 $f12, 108($sp)
    lwc1 $f12, 108($sp)
    mov.s $f14, $f12
    lwc1 $f12, 108($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    mul.s $f12, $f14, $f12
    j .Larea_ret_0
    nop
    j .Lmatch_end_1
    nop
.Larm_skip_3:
    lbu $t8, 0($t9)
    li $t7, 1
    bne $t8, $t7, .Larm_skip_5
    nop
    lwc1 $f12, 4($t9)
    swc1 $f12, 112($sp)
    lwc1 $f12, 8($t9)
    swc1 $f12, 116($sp)
    lwc1 $f12, 112($sp)
    mov.s $f14, $f12
    lwc1 $f12, 116($sp)
    mul.s $f12, $f14, $f12
    j .Larea_ret_0
    nop
    j .Lmatch_end_1
    nop
.Larm_skip_5:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_7
    nop
    la $t8, .Lf321
    lwc1 $f12, 0($t8)
    j .Larea_ret_0
    nop
    j .Lmatch_end_1
    nop
.Larm_skip_7:
.Lmatch_end_1:
.Larea_ret_0:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size area, . - area

	.section .text
	.globl entity_id
	.type entity_id, @function
entity_id:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    sb $a0, 96($sp)
    lb $t9, 96($sp)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_11
    nop
    li $v0, 0
    j .Lentity_id_ret_8
    nop
    j .Lmatch_end_9
    nop
.Larm_skip_11:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_13
    nop
    li $v0, 1
    j .Lentity_id_ret_8
    nop
    j .Lmatch_end_9
    nop
.Larm_skip_13:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_15
    nop
    li $v0, 2
    j .Lentity_id_ret_8
    nop
    j .Lmatch_end_9
    nop
.Larm_skip_15:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_17
    nop
    li $v0, 3
    j .Lentity_id_ret_8
    nop
    j .Lmatch_end_9
    nop
.Larm_skip_17:
.Lmatch_end_9:
.Lentity_id_ret_8:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size entity_id, . - entity_id

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    sw $zero, 96($sp)
    sw $zero, 100($sp)
    sw $zero, 104($sp)
    li $t7, 0
    sb $t7, 96($sp)
    la $t6, .Lf322
    lwc1 $f12, 0($t6)
    swc1 $f12, 100($sp)
    addiu $a0, $sp, 96
    jal area
    nop
    move $t8, $v0
    la $t7, sink
    swc1 $f12, 0($t7)
    move $t9, $t8
    sw $zero, 108($sp)
    sw $zero, 112($sp)
    sw $zero, 116($sp)
    li $t7, 1
    sb $t7, 108($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    swc1 $f12, 112($sp)
    la $t6, .Lf324
    lwc1 $f12, 0($t6)
    swc1 $f12, 116($sp)
    addiu $a0, $sp, 108
    jal area
    nop
    move $t8, $v0
    la $t7, sink
    swc1 $f12, 0($t7)
    move $t9, $t8
    sw $zero, 120($sp)
    sw $zero, 124($sp)
    sw $zero, 128($sp)
    li $t7, 2
    sb $t7, 120($sp)
    addiu $a0, $sp, 120
    jal area
    nop
    move $t8, $v0
    la $t7, sink
    swc1 $f12, 0($t7)
    move $t9, $t8
    sw $zero, 132($sp)
    li $t7, 1
    sb $t7, 132($sp)
    addiu $a0, $sp, 132
    jal entity_id
    nop
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 140($sp)
    sw $zero, 144($sp)
    sw $zero, 148($sp)
    li $t8, 1
    sb $t8, 140($sp)
    li $t8, 100
    sw $t8, 144($sp)
    li $t8, 200
    sw $t8, 148($sp)
    addiu $t9, $sp, 140
    sw $t9, 136($sp)
    lw $t9, 136($sp)
    lbu $t8, 0($t9)
    li $t7, 0
    bne $t8, $t7, .Larm_skip_21
    nop
    lbu $t8, 1($t9)
    sb $t8, 152($sp)
    lbu $t6, 152($sp)
    move $t7, $t6
    la $t6, sink_i
    sw $t7, 0($t6)
    move $t8, $t7
    j .Lmatch_end_19
    nop
.Larm_skip_21:
    lbu $t8, 0($t9)
    li $t7, 1
    bne $t8, $t7, .Larm_skip_23
    nop
    lw $t8, 4($t9)
    sw $t8, 156($sp)
    lw $t8, 8($t9)
    sw $t8, 160($sp)
    lw $t6, 156($sp)
    lw $t5, 160($sp)
    addu $t7, $t6, $t5
    la $t6, sink_i
    sw $t7, 0($t6)
    move $t8, $t7
    j .Lmatch_end_19
    nop
.Larm_skip_23:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_25
    nop
    li $t6, 1
    subu $t7, $zero, $t6
    la $t6, sink_i
    sw $t7, 0($t6)
    move $t8, $t7
    j .Lmatch_end_19
    nop
.Larm_skip_25:
.Lmatch_end_19:
    sw $zero, 168($sp)
    sw $zero, 172($sp)
    sw $zero, 176($sp)
    li $t8, 0
    sb $t8, 168($sp)
    li $t8, 42
    sw $t8, 172($sp)
    li $t8, 80
    sb $t8, 176($sp)
    addiu $t9, $sp, 168
    sw $t9, 164($sp)
    lw $t9, 164($sp)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_28
    nop
    li $t7, 1
    la $t6, sink_i
    sw $t7, 0($t6)
    move $t8, $t7
    j .Lmatch_end_26
    nop
.Larm_skip_28:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_30
    nop
    li $t7, 2
    la $t6, sink_i
    sw $t7, 0($t6)
    move $t8, $t7
    j .Lmatch_end_26
    nop
.Larm_skip_30:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_32
    nop
    li $t7, 0
    la $t6, sink_i
    sw $t7, 0($t6)
    move $t8, $t7
    j .Lmatch_end_26
    nop
.Larm_skip_32:
.Lmatch_end_26:
.Lmain_ret_18:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 2
.Lf320:
	.word 1078530000
	.align 2
.Lf321:
	.word 0
	.align 2
.Lf322:
	.word 1084227584
	.align 2
.Lf323:
	.word 1082130432
	.align 2
.Lf324:
	.word 1077936128

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0

	.section .bss
	.align 2
	.globl sink
sink:
	.space 4
