# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl sum_array
	.type sum_array, @function
sum_array:
    sw $a0, 96($sp)
    sw $a1, 100($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    li $t9, 0
    sw $t9, 104($sp)
    li $t9, 0
    sw $t9, 108($sp)
    lw $t8, 100($sp)
.Lfor_h_1:
    lw $t7, 108($sp)
    bge $t7, $t8, .Lfor_x_2
    nop
    lw $t4, 96($sp)
    lw $t3, 108($sp)
    sll $t3, $t3, 2
    addu $t4, $t4, $t3
    lw $t5, 0($t4)
    lw $t4, 104($sp)
    addu $t5, $t4, $t5
    sw $t5, 104($sp)
    move $t6, $t5
    lw $t7, 108($sp)
    addiu $t7, $t7, 1
    sw $t7, 108($sp)
    j .Lfor_h_1
    nop
.Lfor_x_2:
    lw $v0, 104($sp)
    j .Lsum_array_ret_0
    nop
.Lsum_array_ret_0:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size sum_array, . - sum_array

	.section .text
	.globl fill
	.type fill, @function
fill:
    sw $a0, 96($sp)
    sw $a1, 100($sp)
    sw $a2, 104($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    li $t9, 0
    sw $t9, 108($sp)
    lw $t8, 100($sp)
.Lfor_h_4:
    lw $t7, 108($sp)
    bge $t7, $t8, .Lfor_x_5
    nop
    lw $t5, 104($sp)
    lw $t4, 96($sp)
    lw $t3, 108($sp)
    sll $t3, $t3, 2
    addu $t4, $t4, $t3
    sw $t5, 0($t4)
    move $t6, $t5
    lw $t7, 108($sp)
    addiu $t7, $t7, 1
    sw $t7, 108($sp)
    j .Lfor_h_4
    nop
.Lfor_x_5:
.Lfill_ret_3:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size fill, . - fill

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    move $t9, $zero
    sw $t9, 96($sp)
    move $t9, $zero
    sw $t9, 128($sp)
    li $t8, 100
    lw $t7, 96($sp)
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    li $t8, 200
    lw $t7, 96($sp)
    li $t6, 1
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    li $t8, 50
    lw $t7, 96($sp)
    li $t6, 2
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 96($sp)
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lw $t8, 0($t7)
    sw $t8, 192($sp)
    addiu $a0, $sp, 192
    li $a1, 8
    li $a2, 0
    jal fill
    nop
    move $t9, $v0
    li $t8, 5
    lw $t7, 128($sp)
    li $t4, 3
    li $t3, 8
    mul $t5, $t4, $t3
    li $t4, 2
    addu $t6, $t5, $t4
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t6, 128($sp)
    li $t3, 3
    li $t2, 8
    mul $t4, $t3, $t2
    li $t3, 2
    addu $t5, $t4, $t3
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    lw $t7, 0($t6)
    move $t8, $t7
    la $t7, sink
    sw $t8, 0($t7)
    move $t9, $t8
    li $t8, 10
    lw $t7, 96($sp)
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    li $t8, 20
    lw $t7, 96($sp)
    li $t6, 1
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t6, 96($sp)
    li $t5, 0
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    lw $t7, 0($t6)
    sw $t7, 196($sp)
    addiu $a0, $sp, 196
    li $a1, 8
    jal sum_array
    nop
    move $t8, $v0
    la $t7, sink
    sw $t8, 0($t7)
    move $t9, $t8
.Lmain_ret_6:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size main, . - main

	.section .data
	.align 2
	.globl sink
sink:
	.word 0
