# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl update
	.type update, @function
update:
    sw $a0, 96($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    li $a0, 0
    jal joypad_get_status
    nop
    move $t9, $v0
    sw $t9, 100($sp)
    lw $t7, 100($sp)
    lw $t8, 0($t7)
    lb $t9, 7($t8)
    beqz $t9, .Lif_end_1
    nop
    li $t8, 2
    la $t7, __cur
    lw $t7, 0($t7)
    addu $t8, $t7, $t8
    lw $t7, 96($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_1:
    lw $t7, 100($sp)
    lw $t8, 0($t7)
    lb $t9, 6($t8)
    beqz $t9, .Lif_end_2
    nop
    li $t8, 2
    la $t7, __cur
    lw $t7, 0($t7)
    subu $t8, $t7, $t8
    lw $t7, 96($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_2:
    lw $t7, 100($sp)
    lw $t8, 0($t7)
    lb $t9, 5($t8)
    beqz $t9, .Lif_end_3
    nop
    li $t8, 2
    la $t7, __cur
    lw $t7, 0($t7)
    addu $t8, $t7, $t8
    lw $t7, 96($sp)
    sw $t8, 4($t7)
    move $t9, $t8
.Lif_end_3:
    lw $t7, 100($sp)
    lw $t8, 0($t7)
    lb $t9, 4($t8)
    beqz $t9, .Lif_end_4
    nop
    li $t8, 2
    la $t7, __cur
    lw $t7, 0($t7)
    subu $t8, $t7, $t8
    lw $t7, 96($sp)
    sw $t8, 4($t7)
    move $t9, $t8
.Lif_end_4:
    lw $t7, 96($sp)
    lw $t8, 0($t7)
    li $t7, 0
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_5
    nop
    li $t8, 0
    lw $t7, 96($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_5:
    lw $t7, 96($sp)
    lw $t8, 0($t7)
    li $t7, 320
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_6
    nop
    li $t8, 320
    lw $t7, 96($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_6:
    lw $t7, 96($sp)
    lw $t8, 4($t7)
    li $t7, 0
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_7
    nop
    li $t8, 0
    lw $t7, 96($sp)
    sw $t8, 4($t7)
    move $t9, $t8
.Lif_end_7:
    lw $t7, 96($sp)
    lw $t8, 4($t7)
    li $t7, 240
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_8
    nop
    li $t8, 240
    lw $t7, 96($sp)
    sw $t8, 4($t7)
    move $t9, $t8
.Lif_end_8:
    lw $t7, 100($sp)
    lw $t8, 4($t7)
    lb $t9, 3($t8)
    beqz $t9, .Lif_end_9
    nop
    li $t8, 0
    lw $t7, 96($sp)
    sb $t8, 8($t7)
    move $t9, $t8
.Lif_end_9:
.Lupdate_ret_0:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size update, . - update

	.section .text
	.globl render
	.type render, @function
render:
    sw $a0, 96($sp)
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    jal display_get
    nop
    move $t9, $v0
    sw $t9, 100($sp)
    lw $a0, 100($sp)
    jal rdpq_attach_clear
    nop
    move $t9, $v0
    li $a0, 4278190335
    jal rdpq_set_mode_fill
    nop
    move $t9, $v0
    lw $t8, 96($sp)
    lw $a0, 0($t8)
    lw $t8, 96($sp)
    lw $a1, 4($t8)
    lw $t7, 96($sp)
    lw $t8, 0($t7)
    li $t7, 16
    addu $a2, $t8, $t7
    lw $t7, 96($sp)
    lw $t8, 4($t7)
    li $t7, 16
    addu $a3, $t8, $t7
    jal rdpq_fill_rectangle
    nop
    move $t9, $v0
    jal rdpq_detach_show
    nop
    move $t9, $v0
.Lrender_ret_10:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size render, . - render

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    li $a0, 0
    li $a1, 0
    li $a2, 2
    li $a3, 0
    li $t8, 0
    sw $t8, 16($sp)
    jal display_init
    nop
    move $t9, $v0
    jal joypad_init
    nop
    move $t9, $v0
    jal rdpq_init
    nop
    move $t9, $v0
    jal timer_init
    nop
    move $t9, $v0
    sw $zero, 100($sp)
    sw $zero, 104($sp)
    sw $zero, 108($sp)
    li $t8, 160
    sw $t8, 100($sp)
    li $t8, 120
    sw $t8, 104($sp)
    li $t8, 1
    sb $t8, 108($sp)
    addiu $t9, $sp, 100
    sw $t9, 96($sp)
.Lloop_h_12:
    jal joypad_poll
    nop
    move $t9, $v0
    addiu $a0, $sp, 96
    jal update
    nop
    move $t9, $v0
    lw $t7, 96($sp)
    lbu $t8, 8($t7)
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_14
    nop
    j .Lloop_x_13
    nop
.Lif_end_14:
    addiu $a0, $sp, 96
    jal render
    nop
    move $t9, $v0
    j .Lloop_h_12
    nop
.Lloop_x_13:
    jal rdpq_close
    nop
    move $t9, $v0
    la $a0, .Lstr0
    jal debugf
    nop
    move $t9, $v0
.Lmain_ret_11:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 0
.Lstr0:
	.asciiz "game over"
