# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_triangle
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl init_platforms
	.type init_platforms, @function
init_platforms:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $zero, 136($sp)
    sw $zero, 140($sp)
    sw $zero, 144($sp)
    sw $zero, 148($sp)
    sw $zero, 152($sp)
    li $t7, 0
    sw $t7, 136($sp)
    li $t7, 200
    sw $t7, 140($sp)
    li $t7, 320
    sw $t7, 144($sp)
    li $t7, 40
    sw $t7, 148($sp)
    li $t7, 1
    sb $t7, 152($sp)
    addiu $t8, $sp, 136
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 156($sp)
    sw $zero, 160($sp)
    sw $zero, 164($sp)
    sw $zero, 168($sp)
    sw $zero, 172($sp)
    li $t7, 40
    sw $t7, 156($sp)
    li $t7, 160
    sw $t7, 160($sp)
    li $t7, 80
    sw $t7, 164($sp)
    li $t7, 12
    sw $t7, 168($sp)
    li $t7, 1
    sb $t7, 172($sp)
    addiu $t8, $sp, 156
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 1
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 176($sp)
    sw $zero, 180($sp)
    sw $zero, 184($sp)
    sw $zero, 188($sp)
    sw $zero, 192($sp)
    li $t7, 160
    sw $t7, 176($sp)
    li $t7, 130
    sw $t7, 180($sp)
    li $t7, 80
    sw $t7, 184($sp)
    li $t7, 12
    sw $t7, 188($sp)
    li $t7, 1
    sb $t7, 192($sp)
    addiu $t8, $sp, 176
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 2
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 196($sp)
    sw $zero, 200($sp)
    sw $zero, 204($sp)
    sw $zero, 208($sp)
    sw $zero, 212($sp)
    li $t7, 60
    sw $t7, 196($sp)
    li $t7, 100
    sw $t7, 200($sp)
    li $t7, 60
    sw $t7, 204($sp)
    li $t7, 12
    sw $t7, 208($sp)
    li $t7, 1
    sb $t7, 212($sp)
    addiu $t8, $sp, 196
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 3
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 216($sp)
    sw $zero, 220($sp)
    sw $zero, 224($sp)
    sw $zero, 228($sp)
    sw $zero, 232($sp)
    li $t7, 220
    sw $t7, 216($sp)
    li $t7, 90
    sw $t7, 220($sp)
    li $t7, 70
    sw $t7, 224($sp)
    li $t7, 12
    sw $t7, 228($sp)
    li $t7, 1
    sb $t7, 232($sp)
    addiu $t8, $sp, 216
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 4
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 236($sp)
    sw $zero, 240($sp)
    sw $zero, 244($sp)
    sw $zero, 248($sp)
    sw $zero, 252($sp)
    li $t7, 10
    sw $t7, 236($sp)
    li $t7, 60
    sw $t7, 240($sp)
    li $t7, 50
    sw $t7, 244($sp)
    li $t7, 12
    sw $t7, 248($sp)
    li $t7, 1
    sb $t7, 252($sp)
    addiu $t8, $sp, 236
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 5
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 256($sp)
    sw $zero, 260($sp)
    sw $zero, 264($sp)
    sw $zero, 268($sp)
    sw $zero, 272($sp)
    li $t7, 130
    sw $t7, 256($sp)
    li $t7, 50
    sw $t7, 260($sp)
    li $t7, 60
    sw $t7, 264($sp)
    li $t7, 12
    sw $t7, 268($sp)
    li $t7, 1
    sb $t7, 272($sp)
    addiu $t8, $sp, 256
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 6
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 276($sp)
    sw $zero, 280($sp)
    sw $zero, 284($sp)
    sw $zero, 288($sp)
    sw $zero, 292($sp)
    li $t7, 250
    sw $t7, 276($sp)
    li $t7, 70
    sw $t7, 280($sp)
    li $t7, 60
    sw $t7, 284($sp)
    li $t7, 12
    sw $t7, 288($sp)
    li $t7, 0
    sb $t7, 292($sp)
    addiu $t8, $sp, 276
    la $t7, platforms
    lw $t7, 0($t7)
    li $t6, 7
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
.Linit_platforms_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size init_platforms, . - init_platforms

	.section .text
	.globl init_pickups
	.type init_pickups, @function
init_pickups:
    addiu $sp, $sp, -336
    sw $ra, 332($sp)
    sw $fp, 328($sp)
    addiu $fp, $sp, 336
    sw $zero, 136($sp)
    sw $zero, 140($sp)
    sw $zero, 144($sp)
    li $t7, 0
    sb $t7, 136($sp)
    li $t7, 60
    sw $t7, 140($sp)
    li $t7, 145
    sw $t7, 144($sp)
    addiu $t8, $sp, 136
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 148($sp)
    sw $zero, 152($sp)
    sw $zero, 156($sp)
    li $t7, 0
    sb $t7, 148($sp)
    li $t7, 80
    sw $t7, 152($sp)
    li $t7, 145
    sw $t7, 156($sp)
    addiu $t8, $sp, 148
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 1
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 160($sp)
    sw $zero, 164($sp)
    sw $zero, 168($sp)
    li $t7, 0
    sb $t7, 160($sp)
    li $t7, 180
    sw $t7, 164($sp)
    li $t7, 115
    sw $t7, 168($sp)
    addiu $t8, $sp, 160
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 2
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 172($sp)
    sw $zero, 176($sp)
    sw $zero, 180($sp)
    li $t7, 0
    sb $t7, 172($sp)
    li $t7, 200
    sw $t7, 176($sp)
    li $t7, 115
    sw $t7, 180($sp)
    addiu $t8, $sp, 172
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 3
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 184($sp)
    sw $zero, 188($sp)
    sw $zero, 192($sp)
    li $t7, 0
    sb $t7, 184($sp)
    li $t7, 80
    sw $t7, 188($sp)
    li $t7, 85
    sw $t7, 192($sp)
    addiu $t8, $sp, 184
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 4
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 196($sp)
    sw $zero, 200($sp)
    sw $zero, 204($sp)
    li $t7, 0
    sb $t7, 196($sp)
    li $t7, 150
    sw $t7, 200($sp)
    li $t7, 35
    sw $t7, 204($sp)
    addiu $t8, $sp, 196
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 5
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 208($sp)
    sw $zero, 212($sp)
    sw $zero, 216($sp)
    li $t7, 0
    sb $t7, 208($sp)
    li $t7, 165
    sw $t7, 212($sp)
    li $t7, 35
    sw $t7, 216($sp)
    addiu $t8, $sp, 208
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 6
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 220($sp)
    sw $zero, 224($sp)
    sw $zero, 228($sp)
    li $t7, 0
    sb $t7, 220($sp)
    li $t7, 260
    sw $t7, 224($sp)
    li $t7, 55
    sw $t7, 228($sp)
    addiu $t8, $sp, 220
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 7
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 232($sp)
    sw $zero, 236($sp)
    sw $zero, 240($sp)
    li $t7, 1
    sb $t7, 232($sp)
    addiu $t8, $sp, 232
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 8
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 244($sp)
    sw $zero, 248($sp)
    sw $zero, 252($sp)
    li $t7, 1
    sb $t7, 244($sp)
    addiu $t8, $sp, 244
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 9
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 256($sp)
    sw $zero, 260($sp)
    sw $zero, 264($sp)
    li $t7, 1
    sb $t7, 256($sp)
    addiu $t8, $sp, 256
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 10
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 268($sp)
    sw $zero, 272($sp)
    sw $zero, 276($sp)
    li $t7, 1
    sb $t7, 268($sp)
    addiu $t8, $sp, 268
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 11
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 280($sp)
    sw $zero, 284($sp)
    sw $zero, 288($sp)
    li $t7, 1
    sb $t7, 280($sp)
    addiu $t8, $sp, 280
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 12
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 292($sp)
    sw $zero, 296($sp)
    sw $zero, 300($sp)
    li $t7, 1
    sb $t7, 292($sp)
    addiu $t8, $sp, 292
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 13
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 304($sp)
    sw $zero, 308($sp)
    sw $zero, 312($sp)
    li $t7, 1
    sb $t7, 304($sp)
    addiu $t8, $sp, 304
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 14
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 316($sp)
    sw $zero, 320($sp)
    sw $zero, 324($sp)
    li $t7, 1
    sb $t7, 316($sp)
    addiu $t8, $sp, 316
    la $t7, pickups
    lw $t7, 0($t7)
    li $t6, 15
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
.Linit_pickups_ret_1:
    lw $fp, 328($sp)
    lw $ra, 332($sp)
    addiu $sp, $sp, 336
    jr $ra
    nop
	.size init_pickups, . - init_pickups

	.section .text
	.globl aabb_overlap
	.type aabb_overlap, @function
aabb_overlap:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    sw $a2, 144($sp)
    sw $a3, 148($sp)
    lw $t9, 16($fp)
    sw $t9, 152($sp)
    lw $t9, 20($fp)
    sw $t9, 156($sp)
    lw $t9, 24($fp)
    sw $t9, 160($sp)
    lw $t9, 28($fp)
    sw $t9, 164($sp)
    lw $t7, 136($sp)
    lw $t6, 144($sp)
    addu $t8, $t7, $t6
    lw $t7, 152($sp)
    sle $t9, $t8, $t7
    beqz $t9, .Lif_end_3
    nop
    li $v0, 0
    j .Laabb_overlap_ret_2
    nop
.Lif_end_3:
    lw $t8, 136($sp)
    lw $t6, 152($sp)
    lw $t5, 160($sp)
    addu $t7, $t6, $t5
    sge $t9, $t8, $t7
    beqz $t9, .Lif_end_4
    nop
    li $v0, 0
    j .Laabb_overlap_ret_2
    nop
.Lif_end_4:
    lw $t7, 140($sp)
    lw $t6, 148($sp)
    addu $t8, $t7, $t6
    lw $t7, 156($sp)
    sle $t9, $t8, $t7
    beqz $t9, .Lif_end_5
    nop
    li $v0, 0
    j .Laabb_overlap_ret_2
    nop
.Lif_end_5:
    lw $t8, 140($sp)
    lw $t6, 156($sp)
    lw $t5, 164($sp)
    addu $t7, $t6, $t5
    sge $t9, $t8, $t7
    beqz $t9, .Lif_end_6
    nop
    li $v0, 0
    j .Laabb_overlap_ret_2
    nop
.Lif_end_6:
    li $v0, 1
    j .Laabb_overlap_ret_2
    nop
.Laabb_overlap_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size aabb_overlap, . - aabb_overlap

	.section .text
	.globl check_platform_landing
	.type check_platform_landing, @function
check_platform_landing:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    sw $a2, 144($sp)
    lw $t8, 144($sp)
    mov.s $f14, $f12
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    c.le.s $f14, $f12
    li $t9, 0
    bc1f .Lfle_9
    nop
    li $t9, 1
.Lfle_9:
    beqz $t9, .Lif_end_8
    nop
    li $t9, 1
    subu $v0, $zero, $t9
    j .Lcheck_platform_landing_ret_7
    nop
.Lif_end_8:
    li $t9, 0
    sw $t9, 148($sp)
.Lwhile_h_10:
    lw $t8, 148($sp)
    li $t7, 8
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_11
    nop
    la $t7, platforms
    lw $t7, 0($t7)
    lw $t6, 148($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lw $t8, 0($t7)
    sw $t8, 156($sp)
    addiu $t9, $sp, 156
    sw $t9, 152($sp)
    lw $t8, 152($sp)
    lbu $t9, 16($t8)
    beqz $t9, .Lif_end_12
    nop
    lw $t8, 140($sp)
    li $t7, 16
    addu $t9, $t8, $t7
    sw $t9, 160($sp)
    lw $t7, 152($sp)
    lw $t8, 12($t7)
    sw $t8, 28($sp)
    lw $t7, 152($sp)
    lw $t8, 8($t7)
    sw $t8, 24($sp)
    lw $t7, 152($sp)
    lw $t8, 4($t7)
    sw $t8, 20($sp)
    lw $t7, 152($sp)
    lw $t8, 0($t7)
    sw $t8, 16($sp)
    li $a3, 4
    li $a2, 12
    lw $t8, 160($sp)
    li $t7, 2
    subu $a1, $t8, $t7
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal aabb_overlap
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 164($sp)
    lw $t9, 164($sp)
    beqz $t9, .Lif_end_13
    nop
    lw $t9, 152($sp)
    lw $v0, 4($t9)
    j .Lcheck_platform_landing_ret_7
    nop
.Lif_end_13:
.Lif_end_12:
    li $t8, 1
    lw $t7, 148($sp)
    addu $t8, $t7, $t8
    sw $t8, 148($sp)
    move $t9, $t8
    j .Lwhile_h_10
    nop
.Lwhile_x_11:
    li $t9, 1
    subu $v0, $zero, $t9
    j .Lcheck_platform_landing_ret_7
    nop
.Lcheck_platform_landing_ret_7:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size check_platform_landing, . - check_platform_landing

	.section .text
	.globl Player_init
	.type Player_init, @function
Player_init:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, .Lf322
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 4($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 12($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 17($t7)
    move $t9, $t8
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 18($t7)
    move $t9, $t8
    li $t8, 3
    lw $t7, 136($sp)
    sw $t8, 20($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 24($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 28($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 32($t7)
    move $t9, $t8
.LPlayer_init_ret_14:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Player_init, . - Player_init

	.section .text
	.globl Player_physics
	.type Player_physics, @function
Player_physics:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t7, 136($sp)
    lbu $t8, 17($t7)
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_16
    nop
    la $t8, GRAVITY
    lw $t8, 0($t8)
    lw $t6, 136($sp)
    lw $t7, 12($t6)
    addu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 12($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lw $t8, 12($t7)
    la $t7, MAX_FALL
    lw $t7, 0($t7)
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_17
    nop
    la $t8, MAX_FALL
    lw $t8, 0($t8)
    lw $t7, 136($sp)
    sw $t8, 12($t7)
    move $t9, $t8
.Lif_end_17:
.Lif_end_16:
    lw $t7, 136($sp)
    lw $t8, 12($t7)
    lw $t6, 136($sp)
    lw $t7, 4($t6)
    addu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 4($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lw $t8, 8($t7)
    lw $t6, 136($sp)
    lw $t7, 0($t6)
    addu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t6, 136($sp)
    lw $t7, 8($t6)
    mov.s $f14, $f12
    la $t5, .Lf323
    lwc1 $f12, 0($t5)
    mul.s $f12, $f14, $f12
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    mov.s $f14, $f12
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_19
    nop
    li $t9, 1
.Lflt_19:
    beqz $t9, .Lif_end_18
    nop
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_18:
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    mov.s $f14, $f12
    la $t6, .Lf324
    lwc1 $f12, 0($t6)
    c.lt.s $f12, $f14
    li $t9, 0
    bc1f .Lfgt_21
    nop
    li $t9, 1
.Lfgt_21:
    beqz $t9, .Lif_end_20
    nop
    la $t7, .Lf324
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_20:
.LPlayer_physics_ret_15:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Player_physics, . - Player_physics

	.section .text
	.globl Player_resolve_collisions
	.type Player_resolve_collisions, @function
Player_resolve_collisions:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    move $t9, $t8
    sw $t9, 140($sp)
    lw $t7, 136($sp)
    lw $t8, 4($t7)
    move $t9, $t8
    sw $t9, 144($sp)
    lw $t8, 136($sp)
    lw $a2, 12($t8)
    lw $a1, 144($sp)
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal check_platform_landing
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 148($sp)
    lw $t8, 148($sp)
    li $t6, 1
    subu $t7, $zero, $t6
    sne $t9, $t8, $t7
    beqz $t9, .Lif_else_24
    nop
    lw $t6, 148($sp)
    li $t5, 16
    subu $t7, $t6, $t5
    sll $t8, $t7, 16
    lw $t7, 136($sp)
    sw $t8, 4($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 12($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lbu $t8, 17($t7)
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_25
    nop
    li $t8, 4
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
    li $t8, 4
    lw $t7, 136($sp)
    sw $t8, 28($t7)
    move $t9, $t8
.Lif_end_25:
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 17($t7)
    move $t9, $t8
    li $t8, 8
    lw $t7, 136($sp)
    sw $t8, 32($t7)
    move $t9, $t8
    j .Lif_end_23
    nop
.Lif_else_24:
    lw $t7, 136($sp)
    lw $t8, 32($t7)
    li $t7, 0
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_else_27
    nop
    li $t8, 1
    lw $t6, 136($sp)
    lw $t7, 32($t6)
    subu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 32($t7)
    move $t9, $t8
    j .Lif_end_26
    nop
.Lif_else_27:
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 17($t7)
    move $t9, $t8
.Lif_end_26:
.Lif_end_23:
    lw $t7, 136($sp)
    lw $t8, 4($t7)
    mov.s $f14, $f12
    la $t6, .Lf325
    lwc1 $f12, 0($t6)
    c.lt.s $f12, $f14
    li $t9, 0
    bc1f .Lfgt_29
    nop
    li $t9, 1
.Lfgt_29:
    beqz $t9, .Lif_end_28
    nop
    la $t7, .Lf322
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 4($t7)
    move $t9, $t8
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 12($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    li $t8, 1
    lw $t6, 136($sp)
    lw $t7, 20($t6)
    subu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 20($t7)
    move $t9, $t8
.Lif_end_28:
.LPlayer_resolve_collisions_ret_22:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Player_resolve_collisions, . - Player_resolve_collisions

	.section .text
	.globl Player_handle_input
	.type Player_handle_input, @function
Player_handle_input:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t7, 140($sp)
    lw $t8, 12($t7)
    move $t9, $t8
    sw $t9, 144($sp)
    li $t9, 10
    sw $t9, 148($sp)
    lw $t8, 144($sp)
    lw $t7, 148($sp)
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_else_32
    nop
    lw $t6, 144($sp)
    sll $t7, $t6, 16
    mov.s $f14, $f12
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    mul.s $f12, $f14, $f12
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 18($t7)
    move $t9, $t8
    j .Lif_end_31
    nop
.Lif_else_32:
    lw $t8, 144($sp)
    lw $t6, 148($sp)
    subu $t7, $zero, $t6
    slt $t9, $t8, $t7
    beqz $t9, .Lelif_else_33
    nop
    lw $t6, 144($sp)
    sll $t7, $t6, 16
    mov.s $f14, $f12
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    mul.s $f12, $f14, $f12
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 18($t7)
    move $t9, $t8
    j .Lif_end_31
    nop
.Lelif_else_33:
.Lif_end_31:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 7($t8)
    beqz $t9, .Lif_end_34
    nop
    la $t8, MOVE_SPEED
    lw $t8, 0($t8)
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 18($t7)
    move $t9, $t8
.Lif_end_34:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 6($t8)
    beqz $t9, .Lif_end_35
    nop
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    subu $t8, $zero, $t7
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 18($t7)
    move $t9, $t8
.Lif_end_35:
    lw $t7, 140($sp)
    lw $t8, 4($t7)
    lb $t9, 0($t8)
    beqz $t9, .Lif_end_36
    nop
    lw $t7, 136($sp)
    lbu $t8, 17($t7)
    lw $t5, 136($sp)
    lw $t6, 32($t5)
    li $t5, 0
    sgt $t7, $t6, $t5
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lif_end_37
    nop
    la $t7, JUMP_FORCE
    lw $t7, 0($t7)
    subu $t8, $zero, $t7
    lw $t7, 136($sp)
    sw $t8, 12($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 17($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 32($t7)
    move $t9, $t8
    li $t8, 2
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
.Lif_end_37:
.Lif_end_36:
.LPlayer_handle_input_ret_30:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Player_handle_input, . - Player_handle_input

	.section .text
	.globl Player_update_state
	.type Player_update_state, @function
Player_update_state:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t7, 136($sp)
    lw $t8, 28($t7)
    li $t7, 0
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_39
    nop
    li $t8, 1
    lw $t6, 136($sp)
    lw $t7, 28($t6)
    subu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 28($t7)
    move $t9, $t8
.Lif_end_39:
    lw $t7, 136($sp)
    lbu $t8, 17($t7)
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_else_41
    nop
    lw $t7, 136($sp)
    lw $t8, 12($t7)
    mov.s $f14, $f12
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_44
    nop
    li $t9, 1
.Lflt_44:
    beqz $t9, .Lif_else_43
    nop
    li $t8, 2
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
    j .Lif_end_42
    nop
.Lif_else_43:
    li $t8, 3
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
.Lif_end_42:
    j .Lif_end_40
    nop
.Lif_else_41:
    lw $t7, 136($sp)
    lw $t8, 28($t7)
    li $t7, 0
    sgt $t9, $t8, $t7
    beqz $t9, .Lelif_else_45
    nop
    li $t8, 4
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
    j .Lif_end_40
    nop
.Lelif_else_45:
    lw $t6, 136($sp)
    lw $t7, 8($t6)
    mov.s $f14, $f12
    la $t5, .Lf327
    lwc1 $f12, 0($t5)
    c.lt.s $f12, $f14
    li $t8, 0
    bc1f .Lfgt_47
    nop
    li $t8, 1
.Lfgt_47:
    lw $t5, 136($sp)
    lw $t6, 8($t5)
    mov.s $f14, $f12
    la $t3, .Lf327
    lwc1 $f12, 0($t3)
    neg.s $f12, $f12
    c.lt.s $f14, $f12
    li $t7, 0
    bc1f .Lflt_48
    nop
    li $t7, 1
.Lflt_48:
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lelif_else_46
    nop
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
    j .Lif_end_40
    nop
.Lelif_else_46:
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 16($t7)
    move $t9, $t8
.Lif_end_40:
.LPlayer_update_state_ret_38:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Player_update_state, . - Player_update_state

	.section .text
	.globl Player_collect_pickups
	.type Player_collect_pickups, @function
Player_collect_pickups:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    move $t9, $t8
    sw $t9, 140($sp)
    lw $t7, 136($sp)
    lw $t8, 4($t7)
    move $t9, $t8
    sw $t9, 144($sp)
    li $t9, 0
    sw $t9, 148($sp)
.Lwhile_h_50:
    lw $t8, 148($sp)
    li $t7, 16
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_51
    nop
    la $t8, pickups
    lw $t8, 0($t8)
    lw $t7, 148($sp)
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $t9, 0($t8)
    lbu $t8, 0($t9)
    li $t7, 0
    bne $t8, $t7, .Larm_skip_54
    nop
    lw $t8, 4($t9)
    sw $t8, 152($sp)
    lw $t8, 8($t9)
    sw $t8, 156($sp)
    li $t7, 8
    sw $t7, 28($sp)
    li $t7, 8
    sw $t7, 24($sp)
    lw $t6, 156($sp)
    li $t5, 4
    subu $t7, $t6, $t5
    sw $t7, 20($sp)
    lw $t6, 152($sp)
    li $t5, 4
    subu $t7, $t6, $t5
    sw $t7, 16($sp)
    li $a3, 16
    li $a2, 12
    lw $a1, 144($sp)
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal aabb_overlap
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    beqz $t8, .Lif_end_55
    nop
    li $t7, 10
    lw $t5, 136($sp)
    lw $t6, 24($t5)
    addu $t7, $t6, $t7
    lw $t6, 136($sp)
    sw $t7, 24($t6)
    move $t8, $t7
    sw $zero, 160($sp)
    sw $zero, 164($sp)
    sw $zero, 168($sp)
    li $t6, 1
    sb $t6, 160($sp)
    addiu $t7, $sp, 160
    la $t6, pickups
    lw $t6, 0($t6)
    lw $t5, 148($sp)
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    sw $t7, 0($t6)
    move $t8, $t7
.Lif_end_55:
    j .Lmatch_end_52
    nop
.Larm_skip_54:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_57
    nop
    j .Lmatch_end_52
    nop
.Larm_skip_57:
.Lmatch_end_52:
    li $t8, 1
    lw $t7, 148($sp)
    addu $t8, $t7, $t8
    sw $t8, 148($sp)
    move $t9, $t8
    j .Lwhile_h_50
    nop
.Lwhile_x_51:
.LPlayer_collect_pickups_ret_49:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Player_collect_pickups, . - Player_collect_pickups

	.section .text
	.globl Camera_init
	.type Camera_init, @function
Camera_init:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 4($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
.LCamera_init_ret_58:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Camera_init, . - Camera_init

	.section .text
	.globl Camera_follow
	.type Camera_follow, @function
Camera_follow:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t8, 140($sp)
    mov.s $f14, $f12
    la $t6, .Lf328
    lwc1 $f12, 0($t6)
    sub.s $f12, $f14, $f12
    sw $t9, 144($sp)
    lw $t8, 144($sp)
    lw $t6, 136($sp)
    lw $t7, 0($t6)
    subu $t9, $t8, $t7
    sw $t9, 148($sp)
    lw $t7, 148($sp)
    mov.s $f14, $f12
    la $t5, .Lf329
    lwc1 $f12, 0($t5)
    mul.s $f12, $f14, $f12
    lw $t6, 136($sp)
    lw $t7, 0($t6)
    addu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    mov.s $f14, $f12
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_61
    nop
    li $t9, 1
.Lflt_61:
    beqz $t9, .Lif_end_60
    nop
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_60:
    lw $t6, 136($sp)
    lw $t7, 0($t6)
    move $t8, $t7
    lw $t7, 136($sp)
    sw $t8, 8($t7)
    move $t9, $t8
.LCamera_follow_ret_59:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Camera_follow, . - Camera_follow

	.section .text
	.globl draw_rect_world
	.type draw_rect_world, @function
draw_rect_world:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    sw $a2, 144($sp)
    sw $a3, 148($sp)
    lw $t9, 16($fp)
    sw $t9, 152($sp)
    lw $t9, 20($fp)
    sw $t9, 156($sp)
    lw $t8, 136($sp)
    lw $t7, 152($sp)
    subu $t9, $t8, $t7
    sw $t9, 160($sp)
    lw $t7, 160($sp)
    lw $t6, 144($sp)
    addu $t8, $t7, $t6
    li $t7, 0
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_63
    nop
    j .Ldraw_rect_world_ret_62
    nop
.Lif_end_63:
    lw $t8, 160($sp)
    li $t7, 320
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_64
    nop
    j .Ldraw_rect_world_ret_62
    nop
.Lif_end_64:
    lw $t9, 160($sp)
    sw $t9, 164($sp)
    lw $t8, 160($sp)
    lw $t7, 144($sp)
    addu $t9, $t8, $t7
    sw $t9, 168($sp)
    lw $t8, 164($sp)
    li $t7, 0
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_65
    nop
    li $t8, 0
    sw $t8, 164($sp)
    move $t9, $t8
.Lif_end_65:
    lw $t8, 168($sp)
    li $t7, 320
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_66
    nop
    li $t8, 320
    sw $t8, 168($sp)
    move $t9, $t8
.Lif_end_66:
    lw $a0, 156($sp)
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 140($sp)
    lw $t7, 148($sp)
    addu $a3, $t8, $t7
    lw $a2, 168($sp)
    lw $a1, 140($sp)
    lw $a0, 164($sp)
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Ldraw_rect_world_ret_62:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size draw_rect_world, . - draw_rect_world

	.section .text
	.globl draw_platforms
	.type draw_platforms, @function
draw_platforms:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    li $t9, 0
    sw $t9, 140($sp)
.Lwhile_h_68:
    lw $t8, 140($sp)
    li $t7, 8
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_69
    nop
    la $t7, platforms
    lw $t7, 0($t7)
    lw $t6, 140($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lw $t8, 0($t7)
    sw $t8, 148($sp)
    addiu $t9, $sp, 148
    sw $t9, 144($sp)
    lw $t8, 144($sp)
    lbu $t9, 16($t8)
    beqz $t9, .Lif_end_70
    nop
    li $t8, 862335999
    sw $t8, 20($sp)
    lw $t8, 136($sp)
    sw $t8, 16($sp)
    lw $t8, 144($sp)
    lw $a3, 12($t8)
    lw $t8, 144($sp)
    lw $a2, 8($t8)
    lw $t8, 144($sp)
    lw $a1, 4($t8)
    lw $t8, 144($sp)
    lw $a0, 0($t8)
    sw $t9, 96($sp)
    jal draw_rect_world
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_70:
    li $t8, 1
    lw $t7, 140($sp)
    addu $t8, $t7, $t8
    sw $t8, 140($sp)
    move $t9, $t8
    j .Lwhile_h_68
    nop
.Lwhile_x_69:
.Ldraw_platforms_ret_67:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size draw_platforms, . - draw_platforms

	.section .text
	.globl draw_player
	.type draw_player, @function
draw_player:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    move $t9, $t8
    sw $t9, 144($sp)
    lw $t7, 136($sp)
    lw $t8, 4($t7)
    move $t9, $t8
    sw $t9, 148($sp)
    lw $t8, 144($sp)
    lw $t7, 140($sp)
    subu $t9, $t8, $t7
    sw $t9, 152($sp)
    lw $t6, 152($sp)
    li $t5, 12
    addu $t7, $t6, $t5
    li $t6, 0
    slt $t8, $t7, $t6
    lw $t6, 152($sp)
    li $t5, 320
    sgt $t7, $t6, $t5
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lif_end_72
    nop
    j .Ldraw_player_ret_71
    nop
.Lif_end_72:
    li $t9, 4282664191
    sw $t9, 156($sp)
    lw $t8, 136($sp)
    lbu $t9, 16($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_75
    nop
    li $t7, 4282664191
    sw $t7, 156($sp)
    move $t8, $t7
    j .Lmatch_end_73
    nop
.Larm_skip_75:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_77
    nop
    li $t7, 4284883711
    sw $t7, 156($sp)
    move $t8, $t7
    j .Lmatch_end_73
    nop
.Larm_skip_77:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_79
    nop
    li $t7, 4289331455
    sw $t7, 156($sp)
    move $t8, $t7
    j .Lmatch_end_73
    nop
.Larm_skip_79:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_81
    nop
    li $t7, 4287120639
    sw $t7, 156($sp)
    move $t8, $t7
    j .Lmatch_end_73
    nop
.Larm_skip_81:
    li $t8, 4
    bne $t9, $t8, .Larm_skip_83
    nop
    li $t7, 4294945535
    sw $t7, 156($sp)
    move $t8, $t7
    j .Lmatch_end_73
    nop
.Larm_skip_83:
.Lmatch_end_73:
    lw $a0, 156($sp)
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 148($sp)
    li $t7, 16
    addu $a3, $t8, $t7
    lw $t8, 152($sp)
    li $t7, 12
    addu $a2, $t8, $t7
    lw $a1, 148($sp)
    lw $a0, 152($sp)
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 4294967295
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 136($sp)
    lbu $t9, 18($t8)
    beqz $t9, .Lif_else_85
    nop
    lw $t8, 148($sp)
    li $t7, 6
    addu $a3, $t8, $t7
    lw $t8, 152($sp)
    li $t7, 10
    addu $a2, $t8, $t7
    lw $t8, 148($sp)
    li $t7, 4
    addu $a1, $t8, $t7
    lw $t8, 152($sp)
    li $t7, 8
    addu $a0, $t8, $t7
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    j .Lif_end_84
    nop
.Lif_else_85:
    lw $t8, 148($sp)
    li $t7, 6
    addu $a3, $t8, $t7
    lw $t8, 152($sp)
    li $t7, 4
    addu $a2, $t8, $t7
    lw $t8, 148($sp)
    li $t7, 4
    addu $a1, $t8, $t7
    lw $t8, 152($sp)
    li $t7, 2
    addu $a0, $t8, $t7
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_84:
.Ldraw_player_ret_71:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size draw_player, . - draw_player

	.section .text
	.globl draw_pickup
	.type draw_pickup, @function
draw_pickup:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 148($sp)
    lw $t9, 136($sp)
    lbu $t8, 0($t9)
    li $t7, 0
    bne $t8, $t7, .Larm_skip_89
    nop
    lw $t8, 4($t9)
    sw $t8, 152($sp)
    lw $t8, 8($t9)
    sw $t8, 156($sp)
    lw $t7, 152($sp)
    lw $t6, 148($sp)
    subu $t8, $t7, $t6
    sw $t8, 160($sp)
    lw $t6, 160($sp)
    li $t4, 8
    subu $t5, $zero, $t4
    slt $t7, $t6, $t5
    lw $t5, 160($sp)
    li $t4, 320
    sgt $t6, $t5, $t4
    or $t5, $t7, $t6
    sltu $t8, $zero, $t5
    beqz $t8, .Lif_end_90
    nop
    j .Ldraw_pickup_ret_86
    nop
.Lif_end_90:
    li $a0, 4292673791
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    lw $t7, 156($sp)
    li $t6, 4
    addu $a3, $t7, $t6
    lw $t7, 160($sp)
    li $t6, 4
    addu $a2, $t7, $t6
    lw $t7, 156($sp)
    li $t6, 4
    subu $a1, $t7, $t6
    lw $t7, 160($sp)
    li $t6, 4
    subu $a0, $t7, $t6
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_87
    nop
.Larm_skip_89:
    li $t8, 0
    bne $t9, $t8, .Larm_skip_92
    nop
    j .Lmatch_end_87
    nop
.Larm_skip_92:
.Lmatch_end_87:
.Ldraw_pickup_ret_86:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size draw_pickup, . - draw_pickup

	.section .text
	.globl draw_pickups
	.type draw_pickups, @function
draw_pickups:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    li $t9, 0
    sw $t9, 140($sp)
.Lwhile_h_94:
    lw $t8, 140($sp)
    li $t7, 16
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_95
    nop
    lw $a1, 136($sp)
    la $t8, pickups
    lw $t8, 0($t8)
    lw $t7, 140($sp)
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $a0, 0($t8)
    sw $t9, 96($sp)
    jal draw_pickup
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 1
    lw $t7, 140($sp)
    addu $t8, $t7, $t8
    sw $t8, 140($sp)
    move $t9, $t8
    j .Lwhile_h_94
    nop
.Lwhile_x_95:
.Ldraw_pickups_ret_93:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size draw_pickups, . - draw_pickups

	.section .text
	.globl draw_hud
	.type draw_hud, @function
draw_hud:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    li $t9, 0
    sw $t9, 140($sp)
.Lwhile_h_97:
    lw $t8, 140($sp)
    lw $t5, 136($sp)
    lw $t6, 0($t5)
    lw $t7, 20($t6)
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_98
    nop
    li $t8, 8
    lw $t6, 140($sp)
    li $t5, 14
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    sw $t9, 144($sp)
    li $a0, 4280427263
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 16
    lw $t8, 144($sp)
    li $t7, 10
    addu $a2, $t8, $t7
    li $a1, 8
    lw $a0, 144($sp)
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 1
    lw $t7, 140($sp)
    addu $t8, $t7, $t8
    sw $t8, 140($sp)
    move $t9, $t8
    j .Lwhile_h_97
    nop
.Lwhile_x_98:
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    lw $t9, 24($t8)
    sw $t9, 148($sp)
    lw $t8, 148($sp)
    li $t7, 200
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_99
    nop
    li $t8, 200
    sw $t8, 148($sp)
    move $t9, $t8
.Lif_end_99:
    lw $t8, 148($sp)
    li $t7, 0
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_100
    nop
    li $a0, 4292691199
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 26
    li $t8, 8
    lw $t7, 148($sp)
    addu $a2, $t8, $t7
    li $a1, 20
    li $a0, 8
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_100:
.Ldraw_hud_ret_96:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size draw_hud, . - draw_hud

	.section .text
	.globl update_playing
	.type update_playing, @function
update_playing:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal player_handle_input
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal player_physics
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal player_resolve_collisions
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal player_update_state
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal player_collect_pickups
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    lw $a0, 0($t8)
    sw $t9, 96($sp)
    jal camera_follow
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t7, 140($sp)
    lw $t8, 4($t7)
    lb $t9, 3($t8)
    beqz $t9, .Lif_end_102
    nop
    li $t8, 2
    lw $t7, 136($sp)
    sb $t8, 48($t7)
    move $t9, $t8
.Lif_end_102:
    lw $t6, 136($sp)
    lw $t7, 0($t6)
    lw $t8, 20($t7)
    li $t7, 0
    sle $t9, $t8, $t7
    beqz $t9, .Lif_end_103
    nop
    li $t8, 3
    lw $t7, 136($sp)
    sb $t8, 48($t7)
    move $t9, $t8
.Lif_end_103:
    li $t8, 1
    lw $t6, 136($sp)
    lw $t7, 52($t6)
    addu $t8, $t7, $t8
    lw $t7, 136($sp)
    sw $t8, 52($t7)
    move $t9, $t8
.Lupdate_playing_ret_101:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update_playing, . - update_playing

	.section .text
	.globl update_title
	.type update_title, @function
update_title:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t6, 140($sp)
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    lw $t5, 140($sp)
    lw $t6, 4($t5)
    lb $t7, 0($t6)
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lif_end_105
    nop
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 48($t7)
    move $t9, $t8
.Lif_end_105:
.Lupdate_title_ret_104:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update_title, . - update_title

	.section .text
	.globl update_paused
	.type update_paused, @function
update_paused:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t7, 140($sp)
    lw $t8, 4($t7)
    lb $t9, 3($t8)
    beqz $t9, .Lif_end_107
    nop
    li $t8, 1
    lw $t7, 136($sp)
    sb $t8, 48($t7)
    move $t9, $t8
.Lif_end_107:
.Lupdate_paused_ret_106:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update_paused, . - update_paused

	.section .text
	.globl update_gameover
	.type update_gameover, @function
update_gameover:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t6, 140($sp)
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    lw $t5, 140($sp)
    lw $t6, 4($t5)
    lb $t7, 0($t6)
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lif_end_109
    nop
    sw $t9, 96($sp)
    jal player_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal camera_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 52($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 56($t7)
    move $t9, $t8
    sw $t9, 96($sp)
    jal init_platforms
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal init_pickups
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 48($t7)
    move $t9, $t8
.Lif_end_109:
.Lupdate_gameover_ret_108:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update_gameover, . - update_gameover

	.section .text
	.globl update
	.type update, @function
update:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t8, 136($sp)
    lbu $t9, 48($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_113
    nop
    lw $a1, 140($sp)
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal update_title
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_111
    nop
.Larm_skip_113:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_115
    nop
    lw $a1, 140($sp)
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal update_playing
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_111
    nop
.Larm_skip_115:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_117
    nop
    lw $a1, 140($sp)
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal update_paused
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_111
    nop
.Larm_skip_117:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_119
    nop
    lw $a1, 140($sp)
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal update_gameover
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_111
    nop
.Larm_skip_119:
.Lmatch_end_111:
.Lupdate_ret_110:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update, . - update

	.section .text
	.globl render_world
	.type render_world, @function
render_world:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t7, 136($sp)
    lw $t8, 36($t7)
    lw $t9, 8($t8)
    sw $t9, 140($sp)
    li $a0, 1435028735
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal draw_platforms
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal draw_pickups
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $a1, 140($sp)
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    sw $t8, 144($sp)
    addiu $a0, $sp, 144
    sw $t9, 96($sp)
    jal draw_player
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal draw_hud
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_world_ret_120:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_world, . - render_world

	.section .text
	.globl render_title
	.type render_title, @function
render_title:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $a0, 437930751
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 4282664191
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 100
    li $a2, 260
    li $a1, 80
    li $a0, 60
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 4294967295
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 160
    li $a2, 220
    li $a1, 150
    li $a0, 100
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_title_ret_121:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_title, . - render_title

	.section .text
	.globl render_paused
	.type render_paused, @function
render_paused:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal render_world
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 136
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 140
    li $a2, 240
    li $a1, 100
    li $a0, 80
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 4294967295
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 120
    li $a2, 220
    li $a1, 112
    li $a0, 100
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_paused_ret_122:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_paused, . - render_paused

	.section .text
	.globl render_gameover
	.type render_gameover, @function
render_gameover:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $a0, 570425599
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 4280427263
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 130
    li $a2, 260
    li $a1, 100
    li $a0, 60
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_sync_pipe
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 4294967295
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 170
    li $a2, 220
    li $a1, 160
    li $a0, 100
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_gameover_ret_123:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_gameover, . - render_gameover

	.section .text
	.globl render
	.type render, @function
render:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $t9, 96($sp)
    jal display_get
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 140($sp)
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal rdpq_attach_clear
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 136($sp)
    lbu $t9, 48($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_127
    nop
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_title
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_125
    nop
.Larm_skip_127:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_129
    nop
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_world
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_125
    nop
.Larm_skip_129:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_131
    nop
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_paused
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_125
    nop
.Larm_skip_131:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_133
    nop
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_gameover
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_125
    nop
.Larm_skip_133:
.Lmatch_end_125:
    sw $t9, 96($sp)
    jal rdpq_detach_show
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_ret_124:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render, . - render

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $t8, 1
    sw $t8, 16($sp)
    li $a3, 0
    li $a2, 3
    li $a1, 2
    li $a0, 0
    sw $t9, 96($sp)
    jal display_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal joypad_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal timer_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    move $t9, $zero
    addiu $t8, $sp, 136
    move $a0, $t8
    move $a1, $t9
    li $a2, 60
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memcpy
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    sw $t9, 96($sp)
    jal player_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal camera_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 48($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 52($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 56($t7)
    move $t9, $t8
    sw $t9, 96($sp)
    jal init_platforms
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal init_pickups
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lloop_h_135:
    sw $t9, 96($sp)
    jal joypad_poll
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 0
    sw $t9, 96($sp)
    jal joypad_get_status
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 196($sp)
    lw $a1, 196($sp)
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal update
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal render
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    j .Lloop_h_135
    nop
.Lloop_x_136:
    sw $t9, 96($sp)
    jal rdpq_close
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    la $a0, .Lstr10
    sw $t9, 96($sp)
    jal debugf
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lmain_ret_134:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 0
.Lstr10:
	.asciiz "platformer: shutdown"
	.align 2
.Lf320:
	.word 0
	.align 2
.Lf321:
	.word 1109393408
	.align 2
.Lf322:
	.word 1127481344
	.align 2
.Lf323:
	.word 1061997773
	.align 2
.Lf324:
	.word 1134166016
	.align 2
.Lf325:
	.word 1133248512
	.align 2
.Lf326:
	.word 1017370378
	.align 2
.Lf327:
	.word 1045220557
	.align 2
.Lf328:
	.word 1123024896
	.align 2
.Lf329:
	.word 1036831949

	.section .bss
	.align 2
	.globl platforms
platforms:
	.space 160
	.align 2
	.globl pickups
pickups:
	.space 192
