# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl sum_scanline
	.type sum_scanline, @function
sum_scanline:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $s7, 308($sp)
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    sw $a2, 144($sp)
    li $t9, 0
    sw $t9, 148($sp)
    li $t9, 0
    sw $t9, 152($sp)
    lw $t8, 144($sp)
.Lfor_h_1:
    lw $t7, 152($sp)
    bge $t7, $t8, .Lfor_x_3
    nop
    lw $t3, 136($sp)
    lw $t0, 140($sp)
    lw $s7, 144($sp)
    mul $t1, $t0, $s7
    lw $t0, 152($sp)
    addu $t2, $t1, $t0
    addu $t3, $t3, $t2
    lbu $t4, 0($t3)
    move $t5, $t4
    lw $t4, 148($sp)
    addu $t5, $t4, $t5
    sw $t5, 148($sp)
    move $t6, $t5
.Lfor_i_2:
    lw $t7, 152($sp)
    addiu $t7, $t7, 1
    sw $t7, 152($sp)
    j .Lfor_h_1
    nop
.Lfor_x_3:
    lw $v0, 148($sp)
    j .Lsum_scanline_ret_0
    nop
.Lsum_scanline_ret_0:
    lw $s7, 308($sp)
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size sum_scanline, . - sum_scanline

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -784
    sw $ra, 780($sp)
    sw $fp, 776($sp)
    addiu $fp, $sp, 784
    addiu $a0, $sp, 200
    move $a1, $zero
    li $a2, 64
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memset
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    li $t7, 43981
    sw $t7, 200($sp)
    move $t7, $zero
    sw $t7, 204($sp)
    addiu $t9, $sp, 200
    addiu $t8, $sp, 136
    move $a0, $t8
    move $a1, $t9
    li $a2, 64
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memcpy
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    addiu $t6, $sp, 136
    lw $t7, 0($t6)
    andi $t8, $t7, 255
    la $t7, dma_out
    li $t6, 0
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    addiu $a0, $sp, 520
    move $a1, $zero
    li $a2, 256
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memset
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t7, $zero
    sw $t7, 520($sp)
    addiu $t9, $sp, 520
    addiu $t8, $sp, 264
    move $a0, $t8
    move $a1, $t9
    li $a2, 256
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memcpy
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    addiu $t6, $sp, 264
    li $t5, 0
    addu $t6, $t6, $t5
    lbu $t7, 0($t6)
    move $t8, $t7
    la $t7, sink
    sw $t8, 0($t7)
    move $t9, $t8
    li $a2, 320
    li $a1, 0
    la $t7, dma_out
    li $t6, 0
    addu $t7, $t7, $t6
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal sum_scanline
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink
    sw $t8, 0($t7)
    move $t9, $t8
.Lmain_ret_4:
    lw $fp, 776($sp)
    lw $ra, 780($sp)
    addiu $sp, $sp, 784
    jr $ra
    nop
	.size main, . - main

	.section .data
	.align 2
	.globl sink
sink:
	.word 0

	.section .bss
	.align 0
	.globl dma_out
dma_out:
	.space 4096
	.align 2
	.globl debug_counters
debug_counters:
	.space 64
