# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_triangle
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl gen_sample
	.type gen_sample, @function
gen_sample:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    li $t9, 100
    sw $t9, 140($sp)
    lw $t7, 136($sp)
    lw $t6, 140($sp)
    div $t7, $t6
    mfhi $t8
    lw $t6, 140($sp)
    li $t5, 2
    div $t6, $t5
    mflo $t7
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_1
    nop
    li $t9, 8000
    sll $v0, $t9, 16
    sra $v0, $v0, 16
    j .Lgen_sample_ret_0
    nop
.Lif_end_1:
    li $t8, 8000
    sll $t9, $t8, 16
    sra $t9, $t9, 16
    subu $v0, $zero, $t9
    j .Lgen_sample_ret_0
    nop
.Lgen_sample_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size gen_sample, . - gen_sample

	.section .text
	.globl fill_audio_buffer
	.type fill_audio_buffer, @function
fill_audio_buffer:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $t9, 96($sp)
    jal audio_get_buffer
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 136($sp)
    lw $t8, 136($sp)
    move $t7, $zero
    seq $t9, $t8, $t7
    beqz $t9, .Lif_end_3
    nop
    j .Lfill_audio_buffer_ret_2
    nop
.Lif_end_3:
    li $t9, 0
    sw $t9, 140($sp)
.Lloop_h_4:
    lw $t8, 140($sp)
    li $t7, 1470
    sge $t9, $t8, $t7
    beqz $t9, .Lif_end_6
    nop
    j .Lloop_x_5
    nop
.Lif_end_6:
    la $t7, frame
    lw $t7, 0($t7)
    li $t6, 735
    mul $t8, $t7, $t6
    lw $t6, 140($sp)
    li $t5, 2
    div $t6, $t5
    mflo $t7
    addu $a0, $t8, $t7
    sw $t9, 96($sp)
    jal gen_sample
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sh $t9, 144($sp)
    lh $t8, 144($sp)
    lw $t7, 136($sp)
    lw $t6, 140($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    lh $t8, 144($sp)
    lw $t7, 136($sp)
    lw $t5, 140($sp)
    li $t4, 1
    addu $t6, $t5, $t4
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 140($sp)
    li $t6, 2
    addu $t8, $t7, $t6
    sw $t8, 140($sp)
    move $t9, $t8
    j .Lloop_h_4
    nop
.Lloop_x_5:
.Lfill_audio_buffer_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size fill_audio_buffer, . - fill_audio_buffer

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $t8, 1
    sw $t8, 16($sp)
    li $a3, 0
    li $a2, 3
    li $a1, 2
    li $a0, 0
    sw $t9, 96($sp)
    jal display_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a1, 4
    li $a0, 44100
    sw $t9, 96($sp)
    jal audio_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lloop_h_8:
    sw $t9, 96($sp)
    jal fill_audio_buffer
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal display_get
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 136($sp)
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal rdpq_attach_clear
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 437923583
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_detach_show
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    la $t7, frame
    lw $t7, 0($t7)
    li $t6, 1
    addu $t8, $t7, $t6
    la $t7, frame
    sw $t8, 0($t7)
    move $t9, $t8
    j .Lloop_h_8
    nop
.Lloop_x_9:
.Lmain_ret_7:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .data
	.align 2
	.globl frame
frame:
	.word 0
