# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl save_game
	.type save_game, @function
save_game:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal eeprom_present
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_1
    nop
    j .Lsave_game_ret_0
    nop
.Lif_end_1:
    li $t8, 222
    la $t7, eeprom_buf
    li $t6, 0
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    li $t8, 173
    la $t7, eeprom_buf
    li $t6, 1
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    la $t6, score
    lw $t6, 0($t6)
    li $t5, 24
    srav $t7, $t6, $t5
    andi $t8, $t7, 255
    la $t7, eeprom_buf
    li $t6, 2
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    la $t6, score
    lw $t6, 0($t6)
    li $t5, 16
    srav $t7, $t6, $t5
    andi $t8, $t7, 255
    la $t7, eeprom_buf
    li $t6, 3
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    la $t6, score
    lw $t6, 0($t6)
    li $t5, 8
    srav $t7, $t6, $t5
    andi $t8, $t7, 255
    la $t7, eeprom_buf
    li $t6, 4
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    la $t7, score
    lw $t7, 0($t7)
    andi $t8, $t7, 255
    la $t7, eeprom_buf
    li $t6, 5
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    la $t8, level
    lw $t8, 0($t8)
    la $t7, eeprom_buf
    li $t6, 6
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    li $t8, 0
    la $t7, eeprom_buf
    li $t6, 7
    addu $t7, $t7, $t6
    sb $t8, 0($t7)
    move $t9, $t8
    la $t8, eeprom_buf
    li $t7, 0
    addu $t8, $t8, $t7
    move $a1, $t8
    li $a0, 0
    sw $t9, 96($sp)
    jal eeprom_write
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lsave_game_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size save_game, . - save_game

	.section .text
	.globl load_game
	.type load_game, @function
load_game:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal eeprom_present
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_3
    nop
    li $v0, 0
    j .Lload_game_ret_2
    nop
.Lif_end_3:
    la $t8, eeprom_buf
    li $t7, 0
    addu $t8, $t8, $t7
    move $a1, $t8
    li $a0, 0
    sw $t9, 96($sp)
    jal eeprom_read
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    la $t7, eeprom_buf
    li $t6, 0
    addu $t7, $t7, $t6
    lbu $t8, 0($t7)
    li $t7, 222
    sne $t9, $t8, $t7
    beqz $t9, .Lif_end_4
    nop
    li $v0, 0
    j .Lload_game_ret_2
    nop
.Lif_end_4:
    la $t7, eeprom_buf
    li $t6, 1
    addu $t7, $t7, $t6
    lbu $t8, 0($t7)
    li $t7, 173
    sne $t9, $t8, $t7
    beqz $t9, .Lif_end_5
    nop
    li $v0, 0
    j .Lload_game_ret_2
    nop
.Lif_end_5:
    la $t2, eeprom_buf
    li $t1, 2
    addu $t2, $t2, $t1
    lbu $t3, 0($t2)
    move $t4, $t3
    li $t3, 24
    sllv $t5, $t4, $t3
    la $t1, eeprom_buf
    li $t0, 3
    addu $t1, $t1, $t0
    lbu $t2, 0($t1)
    move $t3, $t2
    li $t2, 16
    sllv $t4, $t3, $t2
    or $t6, $t5, $t4
    la $t2, eeprom_buf
    li $t1, 4
    addu $t2, $t2, $t1
    lbu $t3, 0($t2)
    move $t4, $t3
    li $t3, 8
    sllv $t5, $t4, $t3
    or $t7, $t6, $t5
    la $t4, eeprom_buf
    li $t3, 5
    addu $t4, $t4, $t3
    lbu $t5, 0($t4)
    move $t6, $t5
    or $t8, $t7, $t6
    la $t7, score
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, eeprom_buf
    li $t6, 6
    addu $t7, $t7, $t6
    lbu $t8, 0($t7)
    la $t7, level
    sw $t8, 0($t7)
    move $t9, $t8
    li $v0, 1
    j .Lload_game_ret_2
    nop
.Lload_game_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size load_game, . - load_game

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $t8, 0
    sw $t8, 16($sp)
    li $a3, 0
    li $a2, 2
    li $a1, 2
    li $a0, 0
    sw $t9, 96($sp)
    jal display_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal load_game
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 136($sp)
    lw $t8, 136($sp)
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_7
    nop
    li $t8, 0
    la $t7, score
    sw $t8, 0($t7)
    move $t9, $t8
    li $t8, 1
    la $t7, level
    sw $t8, 0($t7)
    move $t9, $t8
.Lif_end_7:
    la $t7, score
    lw $t7, 0($t7)
    li $t6, 100
    addu $t8, $t7, $t6
    la $t7, score
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, level
    lw $t7, 0($t7)
    li $t6, 1
    addu $t8, $t7, $t6
    la $t7, level
    sw $t8, 0($t7)
    move $t9, $t8
    sw $t9, 96($sp)
    jal save_game
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lloop_h_8:
    sw $t9, 96($sp)
    jal display_get
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 140($sp)
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal rdpq_attach_clear
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 437923583
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_detach_show
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    j .Lloop_h_8
    nop
.Lloop_x_9:
.Lmain_ret_6:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .data
	.align 0
	.globl save_magic_0
save_magic_0:
	.byte 0
	.align 0
	.globl save_magic_1
save_magic_1:
	.byte 0
	.align 0
	.globl save_score_0
save_score_0:
	.byte 0
	.align 0
	.globl save_score_1
save_score_1:
	.byte 0
	.align 0
	.globl save_score_2
save_score_2:
	.byte 0
	.align 0
	.globl save_score_3
save_score_3:
	.byte 0
	.align 0
	.globl save_level
save_level:
	.byte 0
	.align 0
	.globl save_flags
save_flags:
	.byte 0
	.align 2
	.globl score
score:
	.word 0
	.align 0
	.globl level
level:
	.byte 1

	.section .bss
	.align 0
	.globl eeprom_buf
eeprom_buf:
	.space 8
