# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -256
    sw $ra, 252($sp)
    sw $fp, 248($sp)
    addiu $fp, $sp, 256
    la $t7, FixedList
    move $a0, $t7
    jal FixedList_init
    nop
    move $t9, $v0
    addiu $t8, $sp, 96
    move $a0, $t8
    move $a1, $t9
    li $a2, 388
    jal memcpy
    nop
    lw $t8, 480($sp)
    li $t7, 32
    bge $t8, $t7, .Lpush_1
    nop
    sw $zero, 484($sp)
    sw $zero, 488($sp)
    sw $zero, 492($sp)
    la $t4, .Lf320
    lwc1 $f12, 0($t4)
    swc1 $f12, 484($sp)
    la $t4, .Lf321
    lwc1 $f12, 0($t4)
    swc1 $f12, 488($sp)
    li $t5, 1
    sw $t5, 492($sp)
    addiu $t6, $sp, 484
    li $t5, 12
    mul $t5, $t8, $t5
    addiu $t5, $t5, 96
    addu $t5, $sp, $t5
    sw $t6, 0($t5)
    addiu $t8, $t8, 1
    sw $t8, 480($sp)
    li $t9, 1
.Lpush_1:
    lw $t8, 480($sp)
    li $t7, 32
    bge $t8, $t7, .Lpush_2
    nop
    sw $zero, 496($sp)
    sw $zero, 500($sp)
    sw $zero, 504($sp)
    la $t4, .Lf322
    lwc1 $f12, 0($t4)
    swc1 $f12, 496($sp)
    la $t4, .Lf323
    lwc1 $f12, 0($t4)
    swc1 $f12, 500($sp)
    li $t6, 1
    sw $t6, 504($sp)
    addiu $t5, $sp, 496
    li $t6, 12
    mul $t6, $t8, $t6
    addiu $t6, $t6, 96
    addu $t6, $sp, $t6
    sw $t5, 0($t6)
    addiu $t8, $t8, 1
    sw $t8, 480($sp)
    li $t9, 1
.Lpush_2:
    lw $t8, 480($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    lw $t8, 480($sp)
    seq $t9, $t8, $zero
    sw $t9, 508($sp)
    lw $t8, 480($sp)
    addiu $t8, $t8, -1
    sw $t8, 480($sp)
    li $t7, 12
    mul $t7, $t8, $t7
    addiu $t7, $t7, 96
    addu $t7, $sp, $t7
    lw $t9, 0($t7)
    sw $t9, 512($sp)
    lw $t8, 512($sp)
    lwc1 $f12, 0($t8)
    la $t9, sink_f
    sw $t7, 0($t9)
    move $t9, $t7
    lw $t7, 480($sp)
    la $t9, sink_i
    sw $t7, 0($t9)
    move $t9, $t7
    addiu $a0, $sp, 96
    li $a1, 0
    jal _PakList_remove
    nop
    move $t9, $v0
    lw $t7, 480($sp)
    la $t9, sink_i
    sw $t7, 0($t9)
    move $t9, $t7
    la $t8, RingBuffer
    move $a0, $t8
    jal RingBuffer_init
    nop
    move $t9, $v0
    addiu $t7, $sp, 516
    move $a0, $t7
    move $a1, $t9
    li $a2, 44
    jal memcpy
    nop
    lw $t7, 552($sp)
    la $t6, .Lf324
    lwc1 $f12, 0($t6)
    li $t6, 4
    mul $t6, $t7, $t6
    addiu $t6, $t6, 516
    addu $t6, $sp, $t6
    sw $t8, 0($t6)
    addiu $t7, $t7, 1
    li $t5, 8
    div $t7, $t5
    mfhi $t7
    sw $t7, 552($sp)
    lw $t4, 556($sp)
    bge $t4, $t5, .Lrbf_3
    nop
    addiu $t4, $t4, 1
    sw $t4, 556($sp)
.Lrbf_3:
    lw $t4, 552($sp)
    la $t6, .Lf325
    lwc1 $f12, 0($t6)
    li $t6, 4
    mul $t6, $t4, $t6
    addiu $t6, $t6, 516
    addu $t6, $sp, $t6
    sw $t5, 0($t6)
    addiu $t4, $t4, 1
    li $t8, 8
    div $t4, $t8
    mfhi $t4
    sw $t4, 552($sp)
    lw $t7, 556($sp)
    bge $t7, $t8, .Lrbf_4
    nop
    addiu $t7, $t7, 1
    sw $t7, 556($sp)
.Lrbf_4:
    lw $t7, 552($sp)
    la $t6, .Lf326
    lwc1 $f12, 0($t6)
    li $t6, 4
    mul $t6, $t7, $t6
    addiu $t6, $t6, 516
    addu $t6, $sp, $t6
    sw $t8, 0($t6)
    addiu $t7, $t7, 1
    li $t5, 8
    div $t7, $t5
    mfhi $t7
    sw $t7, 552($sp)
    lw $t4, 556($sp)
    bge $t4, $t5, .Lrbf_5
    nop
    addiu $t4, $t4, 1
    sw $t4, 556($sp)
.Lrbf_5:
    lw $t4, 556($sp)
    la $t9, sink_i
    sw $t4, 0($t9)
    move $t9, $t4
    addiu $a0, $sp, 516
    li $a1, 0
    jal _PakRBuf_peek_back
    nop
    move $t9, $v0
    sw $t9, 560($sp)
    lw $t4, 560($sp)
    la $t9, sink_f
    sw $t4, 0($t9)
    move $t9, $t4
    lw $t4, 548($sp)
    li $t5, 4
    mul $t5, $t4, $t5
    addiu $t5, $t5, 516
    addu $t5, $sp, $t5
    lw $t9, 0($t5)
    addiu $t4, $t4, 1
    li $t6, 8
    div $t4, $t6
    mfhi $t4
    sw $t4, 548($sp)
    lw $t8, 556($sp)
    beqz $t8, .Lrbe_6
    nop
    addiu $t8, $t8, -1
    sw $t8, 556($sp)
.Lrbe_6:
    sw $t9, 564($sp)
    lw $t8, 564($sp)
    la $t9, sink_f
    sw $t8, 0($t9)
    move $t9, $t8
    lw $t5, 556($sp)
    seq $t6, $t5, $zero
    move $t8, $t6
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    la $t6, FixedMap
    move $a0, $t6
    jal FixedMap_init
    nop
    move $t9, $v0
    addiu $t8, $sp, 568
    move $a0, $t8
    move $a1, $t9
    li $a2, 148
    jal memcpy
    nop
    addiu $a0, $sp, 568
    li $a1, 16
    li $a2, 1
    li $a3, 100
    jal pak_map_set
    nop
    addiu $a0, $sp, 568
    li $a1, 16
    li $a2, 2
    li $a3, 200
    jal pak_map_set
    nop
    addiu $a0, $sp, 568
    li $a1, 16
    li $a2, 3
    li $a3, 300
    jal pak_map_set
    nop
    lw $t8, 712($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    addiu $a0, $sp, 568
    li $a1, 16
    li $a2, 2
    jal pak_map_get
    nop
    move $t9, $v0
    sw $t9, 716($sp)
    lw $t8, 716($sp)
    move $t6, $zero
    sne $t9, $t8, $t6
    beqz $t9, .Lif_end_7
    nop
    lw $t6, 716($sp)
    lw $t8, 0($t6)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
.Lif_end_7:
    addiu $a0, $sp, 568
    li $a1, 16
    li $a2, 3
    jal pak_map_has
    nop
    move $t9, $v0
    sw $t9, 720($sp)
    addiu $a0, $sp, 568
    li $a1, 16
    li $a2, 1
    jal pak_map_remove
    nop
    lw $t8, 712($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    la $t6, Pool
    move $a0, $t6
    jal Pool_init
    nop
    move $t9, $v0
    addiu $t8, $sp, 724
    move $a0, $t8
    move $a1, $t9
    li $a2, 196
    jal memcpy
    nop
    addiu $a0, $sp, 724
    jal pak_pool_acquire
    nop
    move $t9, $v0
    sw $t9, 920($sp)
    lw $t8, 920($sp)
    move $t6, $zero
    sne $t9, $t8, $t6
    beqz $t9, .Lif_end_8
    nop
    la $t6, .Lf327
    lwc1 $f12, 0($t6)
    lw $t6, 920($sp)
    swc1 $f12, 0($t6)
    move $t9, $t8
    li $t8, 1
    lw $t6, 920($sp)
    sw $t8, 8($t6)
    move $t9, $t8
    lw $t6, 920($sp)
    lwc1 $f12, 0($t6)
    la $t9, sink_f
    sw $t8, 0($t9)
    move $t9, $t8
    addiu $a0, $sp, 724
    lw $a1, 920($sp)
    jal pak_pool_release
    nop
.Lif_end_8:
    lw $t8, 916($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    la $t8, Vec
    move $a0, $t8
    jal Vec_init
    nop
    move $t9, $v0
    sw $t9, 924($sp)
    addiu $a0, $sp, 924
    li $a1, 10
    jal _pak_vec_push
    nop
    addiu $a0, $sp, 924
    li $a1, 20
    jal _pak_vec_push
    nop
    addiu $a0, $sp, 924
    li $a1, 30
    jal _pak_vec_push
    nop
    lw $t8, 928($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    addiu $a0, $sp, 924
    li $a1, 0
    jal _pak_vec_get
    nop
    move $t9, $v0
    sw $t9, 936($sp)
    lw $t8, 936($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    lw $t8, 928($sp)
    seq $t9, $t8, $zero
    sw $t9, 940($sp)
    addiu $a0, $sp, 924
    jal _pak_vec_clear
    nop
    move $t9, $v0
    lw $t8, 928($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    addiu $a0, $sp, 924
    li $a1, 99
    jal _pak_vec_push
    nop
    addiu $a0, $sp, 924
    li $a1, 64
    jal _pak_vec_reserve
    nop
    move $t9, $v0
    lw $t8, 928($sp)
    la $t9, sink_i
    sw $t8, 0($t9)
    move $t9, $t8
    addiu $a0, $sp, 924
    jal _pak_vec_free
    nop
    move $t9, $v0
.Lmain_ret_0:
    lw $fp, 248($sp)
    lw $ra, 252($sp)
    addiu $sp, $sp, 256
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 2
.Lf320:
	.word 1092616192
	.align 2
.Lf321:
	.word 1101004800
	.align 2
.Lf322:
	.word 1084227584
	.align 2
.Lf323:
	.word 1097859072
	.align 2
.Lf324:
	.word 1065353216
	.align 2
.Lf325:
	.word 1073741824
	.align 2
.Lf326:
	.word 1077936128
	.align 2
.Lf327:
	.word 1088421888

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0

	.section .bss
	.align 2
	.globl sink_f
sink_f:
	.space 4
