# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_persp
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_tex_persp
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern pakfs_read
	.extern pakfs_size
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern get_memory_size
	.extern system_has_expansion
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern debug_init_isviewer
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_rotate_x
	.extern t3d_mat4_rotate_y
	.extern t3d_mat4_rotate_z
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_add
	.extern t3d_vec3_sub
	.extern t3d_vec3_scale
	.extern t3d_vec3_len
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_viewport_calc_viewspace_pos
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl sum
	.type sum, @function
sum:
    addiu $sp, $sp, -176
    sw $ra, 172($sp)
    sw $fp, 168($sp)
    addiu $fp, $sp, 176
    sw $s0, 164($sp)
    move $t9, $a0
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    li $t9, 0
    move $s0, $t9
    addiu $t9, $sp, 136
    lw $t8, 0($t9)
    sw $t8, 144($sp)
    lw $t8, 4($t9)
    sw $t8, 148($sp)
    sw $zero, 152($sp)
.Lfeach_h_1:
    lw $t9, 152($sp)
    lw $t8, 148($sp)
    bge $t9, $t8, .Lfeach_x_3
    nop
    lw $t7, 144($sp)
    move $t6, $t9
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lw $t5, 0($t7)
    sw $t5, 156($sp)
    lw $t7, 156($sp)
    move $t6, $s0
    addu $t7, $t6, $t7
    move $s0, $t7
.Lfeach_i_2:
    lw $t9, 152($sp)
    addiu $t9, $t9, 1
    sw $t9, 152($sp)
    j .Lfeach_h_1
    nop
.Lfeach_x_3:
    move $v0, $s0
    j .Lsum_ret_0
    nop
.Lsum_ret_0:
    lw $s0, 164($sp)
    lw $fp, 168($sp)
    lw $ra, 172($sp)
    addiu $sp, $sp, 176
    jr $ra
    nop
	.size sum, . - sum

	.section .text
	.globl find_max
	.type find_max, @function
find_max:
    addiu $sp, $sp, -176
    sw $ra, 172($sp)
    sw $fp, 168($sp)
    addiu $fp, $sp, 176
    sw $s0, 164($sp)
    move $t9, $a0
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t8, $sp, 136
    lw $t8, 0($t8)
    li $t7, 0
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $t9, 0($t8)
    move $s0, $t9
    addiu $t9, $sp, 136
    lw $t8, 0($t9)
    sw $t8, 144($sp)
    lw $t8, 4($t9)
    sw $t8, 148($sp)
    sw $zero, 152($sp)
.Lfeach_h_5:
    lw $t9, 152($sp)
    lw $t8, 148($sp)
    bge $t9, $t8, .Lfeach_x_7
    nop
    lw $t7, 144($sp)
    move $t6, $t9
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lw $t5, 0($t7)
    sw $t5, 156($sp)
    lw $t7, 156($sp)
    move $t6, $s0
    slt $t5, $t6, $t7
    beqz $t5, .Lif_end_8
    nop
    lw $t7, 156($sp)
    move $s0, $t7
.Lif_end_8:
.Lfeach_i_6:
    lw $t9, 152($sp)
    addiu $t9, $t9, 1
    sw $t9, 152($sp)
    j .Lfeach_h_5
    nop
.Lfeach_x_7:
    move $v0, $s0
    j .Lfind_max_ret_4
    nop
.Lfind_max_ret_4:
    lw $s0, 164($sp)
    lw $fp, 168($sp)
    lw $ra, 172($sp)
    addiu $sp, $sp, 176
    jr $ra
    nop
	.size find_max, . - find_max

	.section .text
	.globl double_all
	.type double_all, @function
double_all:
    addiu $sp, $sp, -160
    sw $ra, 156($sp)
    sw $fp, 152($sp)
    addiu $fp, $sp, 160
    move $t9, $a0
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    li $t9, 0
    sw $t9, 144($sp)
    addiu $t7, $sp, 136
    lw $t8, 4($t7)
.Lfor_h_10:
    lw $t7, 144($sp)
    bge $t7, $t8, .Lfor_x_12
    nop
    addiu $t4, $sp, 136
    lw $t4, 0($t4)
    lw $t3, 144($sp)
    sll $t3, $t3, 2
    addu $t4, $t4, $t3
    lw $t5, 0($t4)
    li $t4, 2
    mul $t6, $t5, $t4
    addiu $t5, $sp, 136
    lw $t5, 0($t5)
    lw $t4, 144($sp)
    sll $t4, $t4, 2
    addu $t5, $t5, $t4
    sw $t6, 0($t5)
.Lfor_i_11:
    lw $t7, 144($sp)
    addiu $t7, $t7, 1
    sw $t7, 144($sp)
    j .Lfor_h_10
    nop
.Lfor_x_12:
.Ldouble_all_ret_9:
    lw $fp, 152($sp)
    lw $ra, 156($sp)
    addiu $sp, $sp, 160
    jr $ra
    nop
	.size double_all, . - double_all

	.section .text
	.globl sum_x
	.type sum_x, @function
sum_x:
    addiu $sp, $sp, -176
    sw $ra, 172($sp)
    sw $fp, 168($sp)
    addiu $fp, $sp, 176
    sw $s0, 164($sp)
    move $t9, $a0
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    li $t9, 0
    move $s0, $t9
    addiu $t9, $sp, 136
    lw $t8, 0($t9)
    sw $t8, 144($sp)
    lw $t8, 4($t9)
    sw $t8, 148($sp)
    sw $zero, 152($sp)
.Lfeach_h_14:
    lw $t9, 152($sp)
    lw $t8, 148($sp)
    bge $t9, $t8, .Lfeach_x_16
    nop
    lw $t7, 144($sp)
    move $t6, $t9
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    addiu $t5, $sp, 156
    lw $t4, 0($t7)
    sw $t4, 0($t5)
    lw $t4, 4($t7)
    sw $t4, 4($t5)
    addiu $t6, $sp, 156
    lw $t7, 0($t6)
    move $t6, $s0
    addu $t7, $t6, $t7
    move $s0, $t7
.Lfeach_i_15:
    lw $t9, 152($sp)
    addiu $t9, $t9, 1
    sw $t9, 152($sp)
    j .Lfeach_h_14
    nop
.Lfeach_x_16:
    move $v0, $s0
    j .Lsum_x_ret_13
    nop
.Lsum_x_ret_13:
    lw $s0, 164($sp)
    lw $fp, 168($sp)
    lw $ra, 172($sp)
    addiu $sp, $sp, 176
    jr $ra
    nop
	.size sum_x, . - sum_x

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -336
    sw $ra, 332($sp)
    sw $fp, 328($sp)
    addiu $fp, $sp, 336
    move $t9, $zero
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    lw $t7, 12($t9)
    sw $t7, 12($t8)
    lw $t7, 16($t9)
    sw $t7, 16($t8)
    lw $t7, 20($t9)
    sw $t7, 20($t8)
    lw $t7, 24($t9)
    sw $t7, 24($t8)
    lw $t7, 28($t9)
    sw $t7, 28($t8)
    li $t9, 10
    addiu $t8, $sp, 136
    li $t7, 0
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 20
    addiu $t8, $sp, 136
    li $t7, 1
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 30
    addiu $t8, $sp, 136
    li $t7, 2
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 40
    addiu $t8, $sp, 136
    li $t7, 3
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 50
    addiu $t8, $sp, 136
    li $t7, 4
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 60
    addiu $t8, $sp, 136
    li $t7, 5
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 70
    addiu $t8, $sp, 136
    li $t7, 6
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    li $t9, 80
    addiu $t8, $sp, 136
    li $t7, 7
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    sw $t9, 0($t8)
    addiu $t7, $sp, 136
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t7, 176($sp)
    li $t6, 8
    li $t5, 0
    subu $t6, $t6, $t5
    sw $t6, 180($sp)
    addiu $t9, $sp, 176
    addiu $t8, $sp, 168
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t8, $sp, 168
    lw $t9, 4($t8)
    la $t8, sink
    sw $t9, 0($t8)
    addiu $t7, $sp, 136
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t7, 192($sp)
    li $t6, 4
    li $t5, 0
    subu $t6, $t6, $t5
    sw $t6, 196($sp)
    addiu $t9, $sp, 192
    addiu $t8, $sp, 184
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t8, $sp, 184
    lw $t9, 4($t8)
    la $t8, sink
    sw $t9, 0($t8)
    addiu $a0, $sp, 184
    jal sum
    nop
    move $t9, $v0
    la $t8, sink
    sw $t9, 0($t8)
    addiu $t7, $sp, 136
    li $t6, 4
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t7, 208($sp)
    li $t6, 8
    li $t5, 4
    subu $t6, $t6, $t5
    sw $t6, 212($sp)
    addiu $t9, $sp, 208
    addiu $t8, $sp, 200
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $a0, $sp, 200
    jal sum
    nop
    move $t9, $v0
    la $t8, sink
    sw $t9, 0($t8)
    addiu $a0, $sp, 168
    jal find_max
    nop
    move $t9, $v0
    la $t8, sink
    sw $t9, 0($t8)
    addiu $t7, $sp, 136
    li $t6, 0
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    sw $t7, 224($sp)
    li $t6, 4
    li $t5, 0
    subu $t6, $t6, $t5
    sw $t6, 228($sp)
    addiu $t9, $sp, 224
    addiu $t8, $sp, 216
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $a0, $sp, 216
    jal double_all
    nop
    move $t9, $v0
    addiu $t8, $sp, 136
    li $t7, 0
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $t9, 0($t8)
    la $t8, sink
    sw $t9, 0($t8)
    addiu $a0, $sp, 184
    jal sum
    nop
    move $t9, $v0
    la $t8, sink
    sw $t9, 0($t8)
    move $t9, $zero
    addiu $t8, $sp, 232
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    lw $t7, 12($t9)
    sw $t7, 12($t8)
    lw $t7, 16($t9)
    sw $t7, 16($t8)
    lw $t7, 20($t9)
    sw $t7, 20($t8)
    lw $t7, 24($t9)
    sw $t7, 24($t8)
    lw $t7, 28($t9)
    sw $t7, 28($t8)
    sw $zero, 264($sp)
    sw $zero, 268($sp)
    li $t8, 1
    sw $t8, 264($sp)
    li $t8, 10
    sw $t8, 268($sp)
    addiu $t9, $sp, 264
    addiu $t7, $sp, 232
    li $t6, 0
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    move $t8, $t7
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    sw $zero, 272($sp)
    sw $zero, 276($sp)
    li $t8, 2
    sw $t8, 272($sp)
    li $t8, 20
    sw $t8, 276($sp)
    addiu $t9, $sp, 272
    addiu $t7, $sp, 232
    li $t6, 1
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    move $t8, $t7
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    sw $zero, 280($sp)
    sw $zero, 284($sp)
    li $t8, 3
    sw $t8, 280($sp)
    li $t8, 30
    sw $t8, 284($sp)
    addiu $t9, $sp, 280
    addiu $t7, $sp, 232
    li $t6, 2
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    move $t8, $t7
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    sw $zero, 288($sp)
    sw $zero, 292($sp)
    li $t8, 4
    sw $t8, 288($sp)
    li $t8, 40
    sw $t8, 292($sp)
    addiu $t9, $sp, 288
    addiu $t7, $sp, 232
    li $t6, 3
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    move $t8, $t7
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t7, $sp, 232
    li $t6, 0
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    sw $t7, 304($sp)
    li $t6, 4
    li $t5, 0
    subu $t6, $t6, $t5
    sw $t6, 308($sp)
    addiu $t9, $sp, 304
    addiu $t8, $sp, 296
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t8, $sp, 296
    lw $t9, 4($t8)
    la $t8, sink
    sw $t9, 0($t8)
    addiu $a0, $sp, 296
    jal sum_x
    nop
    move $t9, $v0
    la $t8, sink
    sw $t9, 0($t8)
    addiu $t7, $sp, 232
    li $t6, 1
    li $t5, 8
    mul $t6, $t6, $t5
    addu $t7, $t7, $t6
    sw $t7, 320($sp)
    li $t6, 3
    li $t5, 1
    subu $t6, $t6, $t5
    sw $t6, 324($sp)
    addiu $t9, $sp, 320
    addiu $t8, $sp, 312
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t8, $sp, 312
    lw $t9, 4($t8)
    la $t8, sink
    sw $t9, 0($t8)
.Lmain_ret_17:
    lw $fp, 328($sp)
    lw $ra, 332($sp)
    addiu $sp, $sp, 336
    jr $ra
    nop
	.size main, . - main

	.section .data
	.align 2
	.globl sink
sink:
	.word 0

	.section .bss
	.align 2
	.globl __pak_heap_ptr
__pak_heap_ptr:
	.space 4
