# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_triangle
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl min_max
	.type min_max, @function
min_max:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t8, 136($sp)
    lw $t7, 140($sp)
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_1
    nop
    lw $t9, 136($sp)
    sw $t9, 144($sp)
    lw $t9, 140($sp)
    sw $t9, 148($sp)
    addiu $v0, $sp, 144
    j .Lmin_max_ret_0
    nop
.Lif_end_1:
    lw $t9, 140($sp)
    sw $t9, 152($sp)
    lw $t9, 136($sp)
    sw $t9, 156($sp)
    addiu $v0, $sp, 152
    j .Lmin_max_ret_0
    nop
.Lmin_max_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size min_max, . - min_max

	.section .text
	.globl div_rem
	.type div_rem, @function
div_rem:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t8, 136($sp)
    lw $t7, 140($sp)
    div $t8, $t7
    mflo $t9
    sw $t9, 144($sp)
    lw $t8, 136($sp)
    lw $t6, 144($sp)
    lw $t5, 140($sp)
    mul $t7, $t6, $t5
    subu $t9, $t8, $t7
    sw $t9, 148($sp)
    lw $t9, 144($sp)
    sw $t9, 152($sp)
    lw $t9, 148($sp)
    sw $t9, 156($sp)
    addiu $v0, $sp, 152
    j .Ldiv_rem_ret_2
    nop
.Ldiv_rem_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size div_rem, . - div_rem

	.section .text
	.globl pair_sum
	.type pair_sum, @function
pair_sum:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t8, 136($sp)
    lw $t9, 0($t8)
    lw $t7, 136($sp)
    lw $t8, 4($t7)
    addu $v0, $t9, $t8
    j .Lpair_sum_ret_3
    nop
.Lpair_sum_ret_3:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size pair_sum, . - pair_sum

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $t8, 42
    sw $t8, 140($sp)
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    sw $t8, 144($sp)
    addiu $t9, $sp, 140
    sw $t9, 136($sp)
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lw $t8, 4($t7)
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    li $t8, 1
    sw $t8, 152($sp)
    li $t8, 7
    sw $t8, 156($sp)
    addiu $t9, $sp, 152
    sw $t9, 148($sp)
    lw $t7, 148($sp)
    lw $t8, 4($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    li $a1, 3
    li $a0, 15
    sw $t9, 96($sp)
    jal min_max
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 160($sp)
    lw $t7, 160($sp)
    lw $t8, 0($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 160($sp)
    lw $t8, 4($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    li $a1, 200
    li $a0, 100
    sw $t9, 96($sp)
    jal min_max
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 164($sp)
    lw $t7, 164($sp)
    lw $t8, 0($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 164($sp)
    lw $t8, 4($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    li $a1, 5
    li $a0, 17
    sw $t9, 96($sp)
    jal div_rem
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 168($sp)
    lw $t7, 168($sp)
    lw $t8, 0($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 168($sp)
    lw $t8, 4($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    li $t8, 10
    sw $t8, 176($sp)
    li $t8, 32
    sw $t8, 180($sp)
    addiu $t9, $sp, 176
    sw $t9, 172($sp)
    lw $a0, 172($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal pair_sum
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    li $a1, 1
    li $a0, 99
    sw $t9, 96($sp)
    jal min_max
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 184($sp)
    lw $t8, 184($sp)
    lw $t9, 0($t8)
    sw $t9, 188($sp)
    lw $t8, 184($sp)
    lw $t9, 4($t8)
    sw $t9, 192($sp)
    lw $t7, 192($sp)
    lw $t6, 188($sp)
    subu $t8, $t7, $t6
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
.Lmain_ret_4:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 2
.Lf320:
	.word 1078523331

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0

	.section .bss
	.align 2
	.globl sink_f
sink_f:
	.space 4
