# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl Circle_area
	.type Circle_area, @function
Circle_area:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    mov.s $f14, $f12
    lw $t6, 136($sp)
    lwc1 $f12, 0($t6)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 0($t7)
    mul.s $f12, $f14, $f12
    j .LCircle_area_ret_0
    nop
.LCircle_area_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Circle_area, . - Circle_area

	.section .text
	.globl Circle_perimeter
	.type Circle_perimeter, @function
Circle_perimeter:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    la $t8, .Lf321
    lwc1 $f12, 0($t8)
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 0($t7)
    mul.s $f12, $f14, $f12
    j .LCircle_perimeter_ret_1
    nop
.LCircle_perimeter_ret_1:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Circle_perimeter, . - Circle_perimeter

	.section .text
	.globl Rect_area
	.type Rect_area, @function
Rect_area:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t8, 136($sp)
    lwc1 $f12, 0($t8)
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 4($t7)
    mul.s $f12, $f14, $f12
    j .LRect_area_ret_2
    nop
.LRect_area_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Rect_area, . - Rect_area

	.section .text
	.globl Rect_perimeter
	.type Rect_perimeter, @function
Rect_perimeter:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    la $t8, .Lf322
    lwc1 $f12, 0($t8)
    mov.s $f14, $f12
    lw $t6, 136($sp)
    lwc1 $f12, 0($t6)
    mov.s $f14, $f12
    lw $t5, 136($sp)
    lwc1 $f12, 4($t5)
    add.s $f12, $f14, $f12
    mul.s $f12, $f14, $f12
    j .LRect_perimeter_ret_3
    nop
.LRect_perimeter_ret_3:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Rect_perimeter, . - Rect_perimeter

	.section .text
	.globl get_area
	.type get_area, @function
get_area:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    addiu $t9, $sp, 136
    move $a0, $t9
    sw $t9, 96($sp)
    jal S_area
    nop
    lw $t9, 96($sp)
    j .Lget_area_ret_4
    nop
.Lget_area_ret_4:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size get_area, . - get_area

	.section .text
	.globl get_perimeter
	.type get_perimeter, @function
get_perimeter:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    addiu $t9, $sp, 136
    move $a0, $t9
    sw $t9, 96($sp)
    jal S_perimeter
    nop
    lw $t9, 96($sp)
    j .Lget_perimeter_ret_5
    nop
.Lget_perimeter_ret_5:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size get_perimeter, . - get_perimeter

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $zero, 140($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    swc1 $f12, 140($sp)
    addiu $t9, $sp, 140
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal Shape_from_Circle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 144($sp)
    addiu $t7, $sp, 144
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Shape_c_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 144
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Shape_c_perimeter
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    sw $zero, 156($sp)
    sw $zero, 160($sp)
    la $t6, .Lf324
    lwc1 $f12, 0($t6)
    swc1 $f12, 156($sp)
    la $t6, .Lf325
    lwc1 $f12, 0($t6)
    swc1 $f12, 160($sp)
    addiu $t9, $sp, 156
    addiu $t8, $sp, 148
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $a0, $sp, 148
    sw $t9, 96($sp)
    jal Shape_from_Rect
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 164($sp)
    addiu $t7, $sp, 164
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Shape_r_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 164
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Shape_r_perimeter
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    lw $a0, 144($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal get_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    lw $a0, 164($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal get_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    lw $a0, 164($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal get_perimeter
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 136
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Circle_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 148
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Rect_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t6, $sp, 164
    move $a0, $t6
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t6, 108($sp)
    jal Shape_r_area
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t6, 108($sp)
    move $t7, $v0
    move $t8, $t7
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
.Lmain_ret_6:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 2
.Lf320:
	.word 1078530000
	.align 2
.Lf321:
	.word 1086918608
	.align 2
.Lf322:
	.word 1073741824
	.align 2
.Lf323:
	.word 1084227584
	.align 2
.Lf324:
	.word 1082130432
	.align 2
.Lf325:
	.word 1086324736

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0

	.section .bss
	.align 2
	.globl sink_f
sink_f:
	.space 4
