# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl Pair_sum_i32
	.type Pair_sum_i32, @function
Pair_sum_i32:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t8, 136($sp)
    lw $t9, 0($t8)
    lw $t7, 136($sp)
    lw $t8, 0($t7)
    addu $v0, $t9, $t8
    j .LPair_sum_i32_ret_0
    nop
.LPair_sum_i32_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Pair_sum_i32, . - Pair_sum_i32

	.section .text
	.globl Pair_get_first
	.type Pair_get_first, @function
Pair_get_first:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t9, 136($sp)
    lw $v0, 0($t9)
    j .LPair_get_first_ret_1
    nop
.LPair_get_first_ret_1:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Pair_get_first, . - Pair_get_first

	.section .text
	.globl Pair_get_second
	.type Pair_get_second, @function
Pair_get_second:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t9, 136($sp)
    lw $v0, 0($t9)
    j .LPair_get_second_ret_2
    nop
.LPair_get_second_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Pair_get_second, . - Pair_get_second

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $a0, 42
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal identity__i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, .Lf320
    lwc1 $f12, 0($t7)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal identity__f32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    li $a0, 1
    sw $t9, 96($sp)
    jal identity__bool
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 136($sp)
    li $a1, 7
    li $a0, 3
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal max_of__i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    mov.s $f14, $f12
    la $t7, .Lf322
    lwc1 $f12, 0($t7)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal max_of__f32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    li $a1, 50
    li $a0, 100
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal max_of__i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    li $a1, 2
    li $a0, 1
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal swap_first__i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 148($sp)
    sw $zero, 152($sp)
    li $t7, 10
    sw $t7, 148($sp)
    li $t7, 32
    sw $t7, 152($sp)
    addiu $t9, $sp, 148
    addiu $t8, $sp, 140
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 140
    lw $t8, 4($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 140
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal P_sum_i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 140
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal P_get_first
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 164($sp)
    sw $zero, 168($sp)
    la $t6, .Lf322
    lwc1 $f12, 0($t6)
    swc1 $f12, 164($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 168($sp)
    addiu $t9, $sp, 164
    addiu $t8, $sp, 156
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t7, $sp, 156
    lwc1 $f12, 0($t7)
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 156
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Fp_sum_i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 156
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal Fp_get_second
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
    li $a0, 99
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal identity__i32
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    sw $zero, 180($sp)
    sw $zero, 184($sp)
    li $t7, 1
    sw $t7, 180($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    swc1 $f12, 184($sp)
    addiu $t9, $sp, 180
    addiu $t8, $sp, 172
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $t7, $sp, 172
    lw $t8, 0($t7)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 172
    lwc1 $f12, 4($t7)
    la $t7, sink_f
    swc1 $f12, 0($t7)
    move $t9, $t8
.Lmain_ret_3:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .text
	.globl identity__i32
	.type identity__i32, @function
identity__i32:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $v0, 136($sp)
    j .Lidentity__i32_ret_4
    nop
.Lidentity__i32_ret_4:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size identity__i32, . - identity__i32

	.section .text
	.globl identity__f32
	.type identity__f32, @function
identity__f32:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    swc1 $f12, 136($sp)
    lwc1 $f12, 136($sp)
    j .Lidentity__f32_ret_5
    nop
.Lidentity__f32_ret_5:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size identity__f32, . - identity__f32

	.section .text
	.globl identity__bool
	.type identity__bool, @function
identity__bool:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sb $a0, 136($sp)
    lbu $v0, 136($sp)
    j .Lidentity__bool_ret_6
    nop
.Lidentity__bool_ret_6:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size identity__bool, . - identity__bool

	.section .text
	.globl max_of__i32
	.type max_of__i32, @function
max_of__i32:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t8, 136($sp)
    lw $t7, 140($sp)
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_8
    nop
    lw $v0, 136($sp)
    j .Lmax_of__i32_ret_7
    nop
.Lif_end_8:
    lw $v0, 140($sp)
    j .Lmax_of__i32_ret_7
    nop
.Lmax_of__i32_ret_7:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size max_of__i32, . - max_of__i32

	.section .text
	.globl max_of__f32
	.type max_of__f32, @function
max_of__f32:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    swc1 $f12, 136($sp)
    mov.s $f12, $f14
    swc1 $f12, 140($sp)
    lwc1 $f12, 136($sp)
    mov.s $f14, $f12
    lwc1 $f12, 140($sp)
    c.lt.s $f12, $f14
    li $t9, 0
    bc1f .Lfgt_11
    nop
    li $t9, 1
.Lfgt_11:
    beqz $t9, .Lif_end_10
    nop
    lwc1 $f12, 136($sp)
    j .Lmax_of__f32_ret_9
    nop
.Lif_end_10:
    lwc1 $f12, 140($sp)
    j .Lmax_of__f32_ret_9
    nop
.Lmax_of__f32_ret_9:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size max_of__f32, . - max_of__f32

	.section .text
	.globl swap_first__i32
	.type swap_first__i32, @function
swap_first__i32:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $v0, 140($sp)
    j .Lswap_first__i32_ret_12
    nop
.Lswap_first__i32_ret_12:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size swap_first__i32, . - swap_first__i32

	.section .rodata
	.align 2
.Lf320:
	.word 1078523331
	.align 2
.Lf321:
	.word 1075838976
	.align 2
.Lf322:
	.word 1069547520
	.align 2
.Lf323:
	.word 1092511334

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0

	.section .bss
	.align 2
	.globl sink_f
sink_f:
	.space 4
