# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_persp
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_tex_persp
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern pakfs_read
	.extern pakfs_size
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern get_memory_size
	.extern system_has_expansion
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern debug_init_isviewer
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_rotate_x
	.extern t3d_mat4_rotate_y
	.extern t3d_mat4_rotate_z
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_add
	.extern t3d_vec3_sub
	.extern t3d_vec3_scale
	.extern t3d_vec3_len
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_viewport_calc_viewspace_pos
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl check_greeting
	.type check_greeting, @function
check_greeting:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    sw $a0, 136($sp)
    lw $t8, 136($sp)
    la $t7, .Lstr0
    move $t6, $t8
    move $t5, $t7
.Lsw_3:
    lbu $t3, 0($t5)
    beqz $t3, .Lsw_yes_5
    nop
    lbu $t4, 0($t6)
    bne $t4, $t3, .Lsw_no_4
    nop
    addiu $t6, $t6, 1
    addiu $t5, $t5, 1
    j .Lsw_3
    nop
.Lsw_yes_5:
    li $t9, 1
    j .Lsw_d_6
    nop
.Lsw_no_4:
    li $t9, 0
.Lsw_d_6:
    beqz $t9, .Lsc_f_1
    nop
    lw $t8, 136($sp)
    la $t7, .Lstr1
    move $t5, $t8
.Lss_7:
    lbu $t2, 0($t5)
    beqz $t2, .Lss_m_9
    nop
    move $t4, $t5
    move $t3, $t7
.Lss_i_11:
    lbu $t1, 0($t3)
    beqz $t1, .Lss_f_8
    nop
    lbu $t2, 0($t4)
    bne $t2, $t1, .Lss_n_12
    nop
    addiu $t4, $t4, 1
    addiu $t3, $t3, 1
    j .Lss_i_11
    nop
.Lss_n_12:
    addiu $t5, $t5, 1
    j .Lss_7
    nop
.Lss_f_8:
    move $t6, $t5
    j .Lss_d_10
    nop
.Lss_m_9:
    move $t6, $zero
.Lss_d_10:
    sltu $t9, $zero, $t6
    beqz $t9, .Lsc_f_1
    nop
    li $v0, 1
    j .Lsc_e_2
    nop
.Lsc_f_1:
    move $v0, $zero
.Lsc_e_2:
    j .Lcheck_greeting_ret_0
    nop
.Lcheck_greeting_ret_0:
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size check_greeting, . - check_greeting

	.section .text
	.globl same_string
	.type same_string, @function
same_string:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t9, 136($sp)
    lw $t8, 140($sp)
    move $t7, $t9
    move $t6, $t8
.Lstreq_14:
    lbu $t5, 0($t7)
    lbu $t4, 0($t6)
    bne $t5, $t4, .Lstreq_ne_15
    nop
    beqz $t5, .Lstreq_d_16
    addiu $t7, $t7, 1
    move $v0, $zero
    addiu $t6, $t6, 1
    j .Lstreq_14
    nop
.Lstreq_ne_15:
    li $v0, 0
    j .Lstreq_d_16
    nop
.Lstreq_d_16:
    seq $v0, $t5, $t4
    j .Lsame_string_ret_13
    nop
.Lsame_string_ret_13:
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size same_string, . - same_string

	.section .text
	.globl find_offset
	.type find_offset, @function
find_offset:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t9, 136($sp)
    lw $t8, 140($sp)
    move $t6, $t9
.Lss_18:
    lbu $t3, 0($t6)
    beqz $t3, .Lss_m_20
    nop
    move $t5, $t6
    move $t4, $t8
.Lss_i_22:
    lbu $t2, 0($t4)
    beqz $t2, .Lss_f_19
    nop
    lbu $t3, 0($t5)
    bne $t3, $t2, .Lss_n_23
    nop
    addiu $t5, $t5, 1
    addiu $t4, $t4, 1
    j .Lss_i_22
    nop
.Lss_n_23:
    addiu $t6, $t6, 1
    j .Lss_18
    nop
.Lss_f_19:
    move $t7, $t6
    j .Lss_d_21
    nop
.Lss_m_20:
    move $t7, $zero
.Lss_d_21:
    bnez $t7, .Lsf_24
    nop
    li $v0, -1
    j .Lsfe_25
    nop
.Lsf_24:
    subu $v0, $t7, $t9
.Lsfe_25:
    j .Lfind_offset_ret_17
    nop
.Lfind_offset_ret_17:
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size find_offset, . - find_offset

	.section .text
	.globl check_pakstr
	.type check_pakstr, @function
check_pakstr:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    move $t9, $a0
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $v0, 140($sp)
    j .Lcheck_pakstr_ret_26
    nop
.Lcheck_pakstr_ret_26:
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size check_pakstr, . - check_pakstr

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -192
    sw $ra, 188($sp)
    sw $fp, 184($sp)
    addiu $fp, $sp, 192
    la $t9, .Lstr2
    sw $t9, 136($sp)
    lw $t8, 136($sp)
    la $t7, .Lstr1
    move $t5, $t8
.Lss_28:
    lbu $t2, 0($t5)
    beqz $t2, .Lss_m_30
    nop
    move $t4, $t5
    move $t3, $t7
.Lss_i_32:
    lbu $t1, 0($t3)
    beqz $t1, .Lss_f_29
    nop
    lbu $t2, 0($t4)
    bne $t2, $t1, .Lss_n_33
    nop
    addiu $t4, $t4, 1
    addiu $t3, $t3, 1
    j .Lss_i_32
    nop
.Lss_n_33:
    addiu $t5, $t5, 1
    j .Lss_28
    nop
.Lss_f_29:
    move $t6, $t5
    j .Lss_d_31
    nop
.Lss_m_30:
    move $t6, $zero
.Lss_d_31:
    sltu $t9, $zero, $t6
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr0
    move $t6, $t8
    move $t5, $t7
.Lsw_34:
    lbu $t3, 0($t5)
    beqz $t3, .Lsw_yes_36
    nop
    lbu $t4, 0($t6)
    bne $t4, $t3, .Lsw_no_35
    nop
    addiu $t6, $t6, 1
    addiu $t5, $t5, 1
    j .Lsw_34
    nop
.Lsw_yes_36:
    li $t9, 1
    j .Lsw_d_37
    nop
.Lsw_no_35:
    li $t9, 0
.Lsw_d_37:
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr1
    move $t4, $t7
    move $t6, $zero
.Lstrlen_38:
    lbu $t3, 0($t4)
    beqz $t3, .Lstrlend_39
    nop
    addiu $t4, $t4, 1
    addiu $t6, $t6, 1
    j .Lstrlen_38
    nop
.Lstrlend_39:
    move $t4, $t8
    move $t5, $zero
.Lstrlen_40:
    lbu $t3, 0($t4)
    beqz $t3, .Lstrlend_41
    nop
    addiu $t4, $t4, 1
    addiu $t5, $t5, 1
    j .Lstrlen_40
    nop
.Lstrlend_41:
    sltu $t9, $t5, $t6
    bnez $t9, .Lew_no_42
    nop
    addu $t4, $t8, $t5
    subu $t4, $t4, $t6
    move $t3, $t4
    move $t2, $t7
.Lstreq_45:
    lbu $t1, 0($t3)
    lbu $t0, 0($t2)
    bne $t1, $t0, .Lstreq_ne_46
    nop
    beqz $t1, .Lstreq_d_47
    addiu $t3, $t3, 1
    move $t9, $zero
    addiu $t2, $t2, 1
    j .Lstreq_45
    nop
.Lstreq_ne_46:
    li $t9, 0
    j .Lstreq_d_47
    nop
.Lstreq_d_47:
    seq $t9, $t1, $t0
    j .Lew_d_44
    nop
.Lew_no_42:
    li $t9, 0
.Lew_d_44:
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr2
    move $t6, $t8
    move $t5, $t7
.Lstreq_48:
    lbu $t4, 0($t6)
    lbu $t3, 0($t5)
    bne $t4, $t3, .Lstreq_ne_49
    nop
    beqz $t4, .Lstreq_d_50
    addiu $t6, $t6, 1
    move $t9, $zero
    addiu $t5, $t5, 1
    j .Lstreq_48
    nop
.Lstreq_ne_49:
    li $t9, 0
    j .Lstreq_d_50
    nop
.Lstreq_d_50:
    seq $t9, $t4, $t3
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr3
    move $t6, $t8
    move $t5, $t7
.Lstreq_51:
    lbu $t4, 0($t6)
    lbu $t3, 0($t5)
    bne $t4, $t3, .Lstreq_ne_52
    nop
    beqz $t4, .Lstreq_d_53
    addiu $t6, $t6, 1
    move $t9, $zero
    addiu $t5, $t5, 1
    j .Lstreq_51
    nop
.Lstreq_ne_52:
    li $t9, 0
    j .Lstreq_d_53
    nop
.Lstreq_d_53:
    seq $t9, $t4, $t3
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr1
    move $t5, $t8
.Lss_54:
    lbu $t2, 0($t5)
    beqz $t2, .Lss_m_56
    nop
    move $t4, $t5
    move $t3, $t7
.Lss_i_58:
    lbu $t1, 0($t3)
    beqz $t1, .Lss_f_55
    nop
    lbu $t2, 0($t4)
    bne $t2, $t1, .Lss_n_59
    nop
    addiu $t4, $t4, 1
    addiu $t3, $t3, 1
    j .Lss_i_58
    nop
.Lss_n_59:
    addiu $t5, $t5, 1
    j .Lss_54
    nop
.Lss_f_55:
    move $t6, $t5
    j .Lss_d_57
    nop
.Lss_m_56:
    move $t6, $zero
.Lss_d_57:
    bnez $t6, .Lsf_60
    nop
    li $t9, -1
    j .Lsfe_61
    nop
.Lsf_60:
    subu $t9, $t6, $t8
.Lsfe_61:
    la $t8, sink_i
    sw $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr0
    move $t5, $t8
.Lss_62:
    lbu $t2, 0($t5)
    beqz $t2, .Lss_m_64
    nop
    move $t4, $t5
    move $t3, $t7
.Lss_i_66:
    lbu $t1, 0($t3)
    beqz $t1, .Lss_f_63
    nop
    lbu $t2, 0($t4)
    bne $t2, $t1, .Lss_n_67
    nop
    addiu $t4, $t4, 1
    addiu $t3, $t3, 1
    j .Lss_i_66
    nop
.Lss_n_67:
    addiu $t5, $t5, 1
    j .Lss_62
    nop
.Lss_f_63:
    move $t6, $t5
    j .Lss_d_65
    nop
.Lss_m_64:
    move $t6, $zero
.Lss_d_65:
    bnez $t6, .Lsf_68
    nop
    li $t9, -1
    j .Lsfe_69
    nop
.Lsf_68:
    subu $t9, $t6, $t8
.Lsfe_69:
    la $t8, sink_i
    sw $t9, 0($t8)
    lw $t8, 136($sp)
    la $t7, .Lstr4
    move $t5, $t8
.Lss_70:
    lbu $t2, 0($t5)
    beqz $t2, .Lss_m_72
    nop
    move $t4, $t5
    move $t3, $t7
.Lss_i_74:
    lbu $t1, 0($t3)
    beqz $t1, .Lss_f_71
    nop
    lbu $t2, 0($t4)
    bne $t2, $t1, .Lss_n_75
    nop
    addiu $t4, $t4, 1
    addiu $t3, $t3, 1
    j .Lss_i_74
    nop
.Lss_n_75:
    addiu $t5, $t5, 1
    j .Lss_70
    nop
.Lss_f_71:
    move $t6, $t5
    j .Lss_d_73
    nop
.Lss_m_72:
    move $t6, $zero
.Lss_d_73:
    bnez $t6, .Lsf_76
    nop
    li $t9, -1
    j .Lsfe_77
    nop
.Lsf_76:
    subu $t9, $t6, $t8
.Lsfe_77:
    la $t8, sink_i
    sw $t9, 0($t8)
    lw $t8, 136($sp)
    lbu $t9, 0($t8)
    sltiu $t9, $t9, 1
    la $t8, sink_b
    sb $t9, 0($t8)
    la $t9, .Lstr5
    sw $t9, 140($sp)
    lw $t8, 140($sp)
    lbu $t9, 0($t8)
    sltiu $t9, $t9, 1
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 136($sp)
    move $t7, $t8
    move $t9, $zero
.Lstrlen_78:
    lbu $t6, 0($t7)
    beqz $t6, .Lstrlend_79
    nop
    addiu $t7, $t7, 1
    addiu $t9, $t9, 1
    j .Lstrlen_78
    nop
.Lstrlend_79:
    la $t8, sink_i
    sw $t9, 0($t8)
    lw $a0, 136($sp)
    jal check_greeting
    nop
    move $t9, $v0
    la $t8, sink_b
    sb $t9, 0($t8)
    la $a1, .Lstr2
    lw $a0, 136($sp)
    jal same_string
    nop
    move $t9, $v0
    la $t8, sink_b
    sb $t9, 0($t8)
    la $a1, .Lstr6
    lw $a0, 136($sp)
    jal same_string
    nop
    move $t9, $v0
    la $t8, sink_b
    sb $t9, 0($t8)
    la $a1, .Lstr1
    lw $a0, 136($sp)
    jal find_offset
    nop
    move $t9, $v0
    la $t8, sink_i
    sw $t9, 0($t8)
    la $t7, .Lstr7
    sw $t7, 152($sp)
    move $t5, $t7
    move $t6, $zero
.Lstrlen_81:
    lbu $t4, 0($t5)
    beqz $t4, .Lstrlend_82
    nop
    addiu $t5, $t5, 1
    addiu $t6, $t6, 1
    j .Lstrlen_81
    nop
.Lstrlend_82:
    sw $t6, 156($sp)
    addiu $t9, $sp, 152
    addiu $t8, $sp, 144
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    addiu $a0, $sp, 144
    jal check_pakstr
    nop
    move $t9, $v0
    la $t8, sink_i
    sw $t9, 0($t8)
    lw $t8, 148($sp)
    seq $t9, $t8, $zero
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t7, 136($sp)
    sw $t7, 168($sp)
    move $t5, $t7
    move $t6, $zero
.Lstrlen_84:
    lbu $t4, 0($t5)
    beqz $t4, .Lstrlend_85
    nop
    addiu $t5, $t5, 1
    addiu $t6, $t6, 1
    j .Lstrlen_84
    nop
.Lstrlend_85:
    sw $t6, 172($sp)
    addiu $t9, $sp, 168
    addiu $t8, $sp, 160
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t9, 164($sp)
    la $t8, sink_i
    sw $t9, 0($t8)
    lw $t8, 136($sp)
    li $t7, 6
    move $t5, $t8
    move $t6, $zero
.Lstrlen_86:
    lbu $t4, 0($t5)
    beqz $t4, .Lstrlend_87
    nop
    addiu $t5, $t5, 1
    addiu $t6, $t6, 1
    j .Lstrlen_86
    nop
.Lstrlend_87:
    subu $t6, $t6, $t7
    la $t5, __pak_cslice_0
    addu $t7, $t8, $t7
    move $t4, $t5
    move $t3, $t7
    move $t2, $t6
.Lmcb_88:
    beqz $t2, .Lmcb_d_89
    nop
    lbu $t1, 0($t3)
    sb $t1, 0($t4)
    addiu $t3, $t3, 1
    addiu $t4, $t4, 1
    addiu $t2, $t2, -1
    j .Lmcb_88
    nop
.Lmcb_d_89:
    addu $t5, $t5, $t6
    sb $zero, 0($t5)
    la $t9, __pak_cslice_0
    sw $t9, 176($sp)
    lw $t8, 176($sp)
    la $t7, .Lstr1
    move $t6, $t8
    move $t5, $t7
.Lstreq_90:
    lbu $t4, 0($t6)
    lbu $t3, 0($t5)
    bne $t4, $t3, .Lstreq_ne_91
    nop
    beqz $t4, .Lstreq_d_92
    addiu $t6, $t6, 1
    move $t9, $zero
    addiu $t5, $t5, 1
    j .Lstreq_90
    nop
.Lstreq_ne_91:
    li $t9, 0
    j .Lstreq_d_92
    nop
.Lstreq_d_92:
    seq $t9, $t4, $t3
    la $t8, sink_b
    sb $t9, 0($t8)
    lw $t8, 176($sp)
    la $t7, .Lstr1
    move $t6, $t8
    move $t5, $t7
.Lsw_93:
    lbu $t3, 0($t5)
    beqz $t3, .Lsw_yes_95
    nop
    lbu $t4, 0($t6)
    bne $t4, $t3, .Lsw_no_94
    nop
    addiu $t6, $t6, 1
    addiu $t5, $t5, 1
    j .Lsw_93
    nop
.Lsw_yes_95:
    li $t9, 1
    j .Lsw_d_96
    nop
.Lsw_no_94:
    li $t9, 0
.Lsw_d_96:
    la $t8, sink_b
    sb $t9, 0($t8)
.Lmain_ret_27:
    lw $fp, 184($sp)
    lw $ra, 188($sp)
    addiu $sp, $sp, 192
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 0
.Lstr0:
	.asciiz "hello"
	.align 0
.Lstr1:
	.asciiz "world"
	.align 0
.Lstr2:
	.asciiz "hello world"
	.align 0
.Lstr3:
	.asciiz "goodbye"
	.align 0
.Lstr4:
	.asciiz "xyz"
	.align 0
.Lstr5:
	.asciiz ""
	.align 0
.Lstr6:
	.asciiz "other"
	.align 0
.Lstr7:
	.asciiz "pak string"

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0
	.align 0
	.globl sink_b
sink_b:
	.byte 0

	.section .bss
	.align 0
	.globl __pak_cslice_0
__pak_cslice_0:
	.space 256
	.align 2
	.globl __pak_heap_ptr
__pak_heap_ptr:
	.space 4
