# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_triangle
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl check_greeting
	.type check_greeting, @function
check_greeting:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t8, 136($sp)
    la $t7, .Lstr0
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $a2, $v0
    move $a0, $t8
    move $a1, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strncmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    seq $t9, $v0, $zero
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr1
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strstr
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    sltu $t8, $zero, $v0
    move $t8, $v0
    sltu $t8, $zero, $t8
    sltiu $t7, $t9, 1
    sltiu $v0, $t8, 1
    or $v0, $t7, $v0
    sltiu $v0, $v0, 1
    j .Lcheck_greeting_ret_0
    nop
.Lcheck_greeting_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size check_greeting, . - check_greeting

	.section .text
	.globl same_string
	.type same_string, @function
same_string:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t9, 136($sp)
    move $a0, $t9
    lw $a1, 140($sp)
    sw $t9, 96($sp)
    jal strcmp
    nop
    lw $t9, 96($sp)
    seq $v0, $v0, $zero
    j .Lsame_string_ret_1
    nop
.Lsame_string_ret_1:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size same_string, . - same_string

	.section .text
	.globl find_offset
	.type find_offset, @function
find_offset:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t9, 136($sp)
    move $a0, $t9
    lw $a1, 140($sp)
    sw $t9, 96($sp)
    jal strstr
    nop
    lw $t9, 96($sp)
    bne $v0, $zero, .Lsf_3
    nop
    li $v0, -1
    j .Lsfe_4
    nop
.Lsf_3:
    subu $v0, $v0, $t9
.Lsfe_4:
    j .Lfind_offset_ret_2
    nop
.Lfind_offset_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size find_offset, . - find_offset

	.section .text
	.globl check_pakstr
	.type check_pakstr, @function
check_pakstr:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $v0, 140($sp)
    j .Lcheck_pakstr_ret_5
    nop
.Lcheck_pakstr_ret_5:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size check_pakstr, . - check_pakstr

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    la $t9, .Lstr2
    sw $t9, 136($sp)
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr1
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strstr
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    sltu $t8, $zero, $v0
    move $t8, $v0
    sltu $t8, $zero, $t8
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    la $t6, .Lstr0
    move $a0, $t6
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t6, 108($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t6, 108($sp)
    move $a2, $v0
    move $a0, $t7
    move $a1, $t6
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t6, 108($sp)
    jal strncmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t6, 108($sp)
    seq $t8, $v0, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    la $t6, .Lstr1
    move $a0, $t6
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t6, 108($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t6, 108($sp)
    move $t5, $v0
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t6, 108($sp)
    sw $t5, 112($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t6, 108($sp)
    lw $t5, 112($sp)
    move $t4, $v0
    addu $t3, $t7, $t4
    subu $t3, $t3, $t5
    move $a0, $t3
    move $a1, $t6
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t6, 108($sp)
    sw $t5, 112($sp)
    sw $t4, 116($sp)
    sw $t3, 120($sp)
    jal strcmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t6, 108($sp)
    lw $t5, 112($sp)
    lw $t4, 116($sp)
    lw $t3, 120($sp)
    seq $t8, $v0, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr2
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strcmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    seq $t8, $v0, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr3
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strcmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    seq $t8, $v0, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr1
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strstr
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    bne $v0, $zero, .Lsf_7
    nop
    li $t8, -1
    j .Lsfe_8
    nop
.Lsf_7:
    subu $t8, $v0, $t7
.Lsfe_8:
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr0
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strstr
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    bne $v0, $zero, .Lsf_9
    nop
    li $t8, -1
    j .Lsfe_10
    nop
.Lsf_9:
    subu $t8, $v0, $t7
.Lsfe_10:
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    move $a0, $t7
    la $a1, .Lstr4
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strstr
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    bne $v0, $zero, .Lsf_11
    nop
    li $t8, -1
    j .Lsfe_12
    nop
.Lsf_11:
    subu $t8, $v0, $t7
.Lsfe_12:
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    lb $t8, 0($t7)
    sltiu $t8, $t8, 1
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    la $t9, .Lstr5
    sw $t9, 140($sp)
    lw $t7, 140($sp)
    lb $t8, 0($t7)
    sltiu $t8, $t8, 1
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 136($sp)
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal check_greeting
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    la $a1, .Lstr2
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal same_string
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    la $a1, .Lstr6
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal same_string
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    la $a1, .Lstr1
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal find_offset
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    la $t8, str
    move $a0, $t8
    la $a1, .Lstr7
    sw $t9, 96($sp)
    jal Str_from_cstr
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 144($sp)
    lw $a0, 144($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal check_pakstr
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 148($sp)
    seq $t8, $t7, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t8, 136($sp)
    sw $t8, 160($sp)
    move $a0, $t8
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    sw $v0, 164($sp)
    addiu $t9, $sp, 160
    sw $t9, 152($sp)
    lw $t8, 156($sp)
    la $t7, sink_i
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t8, 136($sp)
    li $t7, 6
    addu $t9, $t8, $t7
    sw $t9, 168($sp)
    lw $t7, 168($sp)
    move $a0, $t7
    la $a1, .Lstr1
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal strcmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    seq $t8, $v0, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
    lw $t7, 168($sp)
    la $t3, .Lstr1
    move $a0, $t3
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t3, 108($sp)
    jal strlen
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t3, 108($sp)
    move $a2, $v0
    move $a0, $t7
    move $a1, $t3
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    sw $t3, 108($sp)
    jal strncmp
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    lw $t3, 108($sp)
    seq $t8, $v0, $zero
    la $t7, sink_b
    sw $t8, 0($t7)
    move $t9, $t8
.Lmain_ret_6:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 0
.Lstr0:
	.asciiz "hello"
	.align 0
.Lstr1:
	.asciiz "world"
	.align 0
.Lstr2:
	.asciiz "hello world"
	.align 0
.Lstr3:
	.asciiz "goodbye"
	.align 0
.Lstr4:
	.asciiz "xyz"
	.align 0
.Lstr5:
	.asciiz ""
	.align 0
.Lstr6:
	.asciiz "other"
	.align 0
.Lstr7:
	.asciiz "pak string"

	.section .data
	.align 2
	.globl sink_i
sink_i:
	.word 0
	.align 0
	.globl sink_b
sink_b:
	.byte 0
