# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_triangle
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl map_get
	.type map_get, @function
map_get:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t5, 136($sp)
    li $t4, 0
    slt $t6, $t5, $t4
    lw $t4, 136($sp)
    li $t3, 16
    sge $t5, $t4, $t3
    or $t4, $t6, $t5
    sltu $t7, $zero, $t4
    lw $t5, 140($sp)
    li $t4, 0
    slt $t6, $t5, $t4
    or $t5, $t7, $t6
    sltu $t8, $zero, $t5
    lw $t6, 140($sp)
    li $t5, 16
    sge $t7, $t6, $t5
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lif_end_1
    nop
    li $v0, 1
    j .Lmap_get_ret_0
    nop
.Lif_end_1:
    la $t9, dungeon_map
    lw $t6, 140($sp)
    li $t5, 16
    mul $t7, $t6, $t5
    lw $t6, 136($sp)
    addu $t8, $t7, $t6
    addu $t9, $t9, $t8
    lbu $v0, 0($t9)
    j .Lmap_get_ret_0
    nop
.Lmap_get_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size map_get, . - map_get

	.section .text
	.globl Camera_rotate
	.type Camera_rotate, @function
Camera_rotate:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    swc1 $f12, 140($sp)
    la $t8, math
    move $a0, $t8
    lwc1 $f12, 140($sp)
    sw $t9, 96($sp)
    jal Math_cos_f
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    swc1 $f12, 144($sp)
    la $t8, math
    move $a0, $t8
    lwc1 $f12, 140($sp)
    sw $t9, 96($sp)
    jal Math_sin_f
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    swc1 $f12, 148($sp)
    lw $t8, 136($sp)
    lwc1 $f12, 8($t8)
    swc1 $f12, 152($sp)
    lw $t8, 136($sp)
    lwc1 $f12, 16($t8)
    swc1 $f12, 156($sp)
    lw $t5, 136($sp)
    lwc1 $f12, 8($t5)
    mov.s $f14, $f12
    lwc1 $f12, 144($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t4, 136($sp)
    lwc1 $f12, 12($t4)
    mov.s $f14, $f12
    lwc1 $f12, 148($sp)
    mul.s $f12, $f14, $f12
    sub.s $f12, $f14, $f12
    lw $t7, 136($sp)
    swc1 $f12, 8($t7)
    move $t9, $t8
    lwc1 $f12, 152($sp)
    mov.s $f14, $f12
    lwc1 $f12, 148($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t4, 136($sp)
    lwc1 $f12, 12($t4)
    mov.s $f14, $f12
    lwc1 $f12, 144($sp)
    mul.s $f12, $f14, $f12
    add.s $f12, $f14, $f12
    lw $t7, 136($sp)
    swc1 $f12, 12($t7)
    move $t9, $t8
    lw $t5, 136($sp)
    lwc1 $f12, 16($t5)
    mov.s $f14, $f12
    lwc1 $f12, 144($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t4, 136($sp)
    lwc1 $f12, 20($t4)
    mov.s $f14, $f12
    lwc1 $f12, 148($sp)
    mul.s $f12, $f14, $f12
    sub.s $f12, $f14, $f12
    lw $t7, 136($sp)
    swc1 $f12, 16($t7)
    move $t9, $t8
    lwc1 $f12, 156($sp)
    mov.s $f14, $f12
    lwc1 $f12, 148($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t4, 136($sp)
    lwc1 $f12, 20($t4)
    mov.s $f14, $f12
    lwc1 $f12, 144($sp)
    mul.s $f12, $f14, $f12
    add.s $f12, $f14, $f12
    lw $t7, 136($sp)
    swc1 $f12, 20($t7)
    move $t9, $t8
.LCamera_rotate_ret_2:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Camera_rotate, . - Camera_rotate

	.section .text
	.globl Camera_try_move
	.type Camera_try_move, @function
Camera_try_move:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    swc1 $f12, 140($sp)
    mov.s $f12, $f14
    swc1 $f12, 144($sp)
    lw $t7, 136($sp)
    lwc1 $f12, 0($t7)
    mov.s $f14, $f12
    lwc1 $f12, 140($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t7, 136($sp)
    lwc1 $f12, 4($t7)
    mov.s $f14, $f12
    lwc1 $f12, 144($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 4($t6)
    move $a1, $t7
    lwc1 $f12, 148($sp)
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal map_get
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    li $t7, 0
    seq $t9, $t8, $t7
    beqz $t9, .Lif_end_4
    nop
    lwc1 $f12, 148($sp)
    lw $t7, 136($sp)
    swc1 $f12, 0($t7)
    move $t9, $t8
.Lif_end_4:
    lwc1 $f12, 152($sp)
    move $a1, $t7
    lw $t6, 136($sp)
    lwc1 $f12, 0($t6)
    move $a0, $t7
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal map_get
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    li $t7, 0
    seq $t9, $t8, $t7
    beqz $t9, .Lif_end_5
    nop
    lwc1 $f12, 152($sp)
    lw $t7, 136($sp)
    swc1 $f12, 4($t7)
    move $t9, $t8
.Lif_end_5:
.LCamera_try_move_ret_3:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size Camera_try_move, . - Camera_try_move

	.section .text
	.globl wall_color
	.type wall_color, @function
wall_color:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sb $a0, 136($sp)
    sw $a1, 140($sp)
    li $t9, 2857710591
    sw $t9, 144($sp)
    lbu $t8, 136($sp)
    li $t7, 2
    seq $t9, $t8, $t7
    beqz $t9, .Lif_else_8
    nop
    li $t8, 1148693247
    sw $t8, 144($sp)
    move $t9, $t8
    j .Lif_end_7
    nop
.Lif_else_8:
    lbu $t8, 136($sp)
    li $t7, 3
    seq $t9, $t8, $t7
    beqz $t9, .Lelif_else_9
    nop
    li $t8, 1152013823
    sw $t8, 144($sp)
    move $t9, $t8
    j .Lif_end_7
    nop
.Lelif_else_9:
.Lif_end_7:
    lw $t8, 140($sp)
    li $t7, 1
    seq $t9, $t8, $t7
    beqz $t9, .Lif_end_10
    nop
    li $t8, 1999839999
    sw $t8, 144($sp)
    move $t9, $t8
    lbu $t8, 136($sp)
    li $t7, 2
    seq $t9, $t8, $t7
    beqz $t9, .Lif_else_12
    nop
    li $t8, 862357759
    sw $t8, 144($sp)
    move $t9, $t8
    j .Lif_end_11
    nop
.Lif_else_12:
    lbu $t8, 136($sp)
    li $t7, 3
    seq $t9, $t8, $t7
    beqz $t9, .Lelif_else_13
    nop
    li $t8, 864568575
    sw $t8, 144($sp)
    move $t9, $t8
    j .Lif_end_11
    nop
.Lelif_else_13:
.Lif_end_11:
.Lif_end_10:
    lw $v0, 144($sp)
    j .Lwall_color_ret_6
    nop
.Lwall_color_ret_6:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size wall_color, . - wall_color

	.section .text
	.globl render_minimap
	.type render_minimap, @function
render_minimap:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    li $t9, 0
    sw $t9, 140($sp)
.Lwhile_h_15:
    lw $t8, 140($sp)
    li $t7, 16
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_16
    nop
    li $t9, 0
    sw $t9, 144($sp)
.Lwhile_h_17:
    lw $t8, 144($sp)
    li $t7, 16
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_18
    nop
    la $t8, dungeon_map
    lw $t5, 140($sp)
    li $t4, 16
    mul $t6, $t5, $t4
    lw $t5, 144($sp)
    addu $t7, $t6, $t5
    addu $t8, $t8, $t7
    lbu $t9, 0($t8)
    sb $t9, 148($sp)
    li $t8, 252
    lw $t6, 144($sp)
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    sw $t9, 152($sp)
    li $t8, 2
    lw $t6, 140($sp)
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    sw $t9, 156($sp)
    li $t9, 858993663
    sw $t9, 160($sp)
    lbu $t8, 148($sp)
    li $t7, 1
    seq $t9, $t8, $t7
    beqz $t9, .Lif_else_20
    nop
    li $t8, 2857710591
    sw $t8, 160($sp)
    move $t9, $t8
    j .Lif_end_19
    nop
.Lif_else_20:
    lbu $t8, 148($sp)
    li $t7, 2
    seq $t9, $t8, $t7
    beqz $t9, .Lelif_else_21
    nop
    li $t8, 1148693247
    sw $t8, 160($sp)
    move $t9, $t8
    j .Lif_end_19
    nop
.Lelif_else_21:
    lbu $t8, 148($sp)
    li $t7, 3
    seq $t9, $t8, $t7
    beqz $t9, .Lelif_else_22
    nop
    li $t8, 1152013823
    sw $t8, 160($sp)
    move $t9, $t8
    j .Lif_end_19
    nop
.Lelif_else_22:
.Lif_end_19:
    lw $a0, 160($sp)
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 156($sp)
    li $t7, 4
    addu $a3, $t8, $t7
    lw $t8, 152($sp)
    li $t7, 4
    addu $a2, $t8, $t7
    lw $a1, 156($sp)
    lw $a0, 152($sp)
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 1
    lw $t7, 144($sp)
    addu $t8, $t7, $t8
    sw $t8, 144($sp)
    move $t9, $t8
    j .Lwhile_h_17
    nop
.Lwhile_x_18:
    li $t8, 1
    lw $t7, 140($sp)
    addu $t8, $t7, $t8
    sw $t8, 140($sp)
    move $t9, $t8
    j .Lwhile_h_15
    nop
.Lwhile_x_16:
    li $t8, 252
    lw $t4, 136($sp)
    lwc1 $f12, 0($t4)
    move $t6, $t5
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    sw $t9, 164($sp)
    li $t8, 2
    lw $t4, 136($sp)
    lwc1 $f12, 4($t4)
    move $t6, $t5
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    sw $t9, 168($sp)
    li $a0, 4294902015
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 168($sp)
    li $t7, 4
    addu $a3, $t8, $t7
    lw $t8, 164($sp)
    li $t7, 4
    addu $a2, $t8, $t7
    lw $a1, 168($sp)
    lw $a0, 164($sp)
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_minimap_ret_14:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_minimap, . - render_minimap

	.section .text
	.globl render_3d
	.type render_3d, @function
render_3d:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    lw $t9, 136($sp)
    sw $t9, 140($sp)
    li $a0, 219884287
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 120
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 437390079
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 120
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t9, 0
    sw $t9, 144($sp)
.Lwhile_h_24:
    lw $t8, 144($sp)
    li $t7, 320
    slt $t9, $t8, $t7
    beqz $t9, .Lwhile_x_25
    nop
    la $t5, .Lf320
    lwc1 $f12, 0($t5)
    mov.s $f14, $f12
    lw $t4, 144($sp)
    mtc1 $t4, $f12
    cvt.s.w $f12, $f12
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    li $t5, 320
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    div.s $f12, $f14, $f12
    mov.s $f14, $f12
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    sub.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 8($t7)
    mov.s $f14, $f12
    lw $t5, 140($sp)
    lwc1 $f12, 16($t5)
    mov.s $f14, $f12
    lwc1 $f12, 148($sp)
    mul.s $f12, $f14, $f12
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 12($t7)
    mov.s $f14, $f12
    lw $t5, 140($sp)
    lwc1 $f12, 20($t5)
    mov.s $f14, $f12
    lwc1 $f12, 148($sp)
    mul.s $f12, $f14, $f12
    add.s $f12, $f14, $f12
    swc1 $f12, 156($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 0($t7)
    move $t9, $t8
    sw $t9, 160($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 4($t7)
    move $t9, $t8
    sw $t9, 164($sp)
    la $t8, .Lf322
    lwc1 $f12, 0($t8)
    swc1 $f12, 168($sp)
    lwc1 $f12, 152($sp)
    mov.s $f14, $f12
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    c.eq.s $f14, $f12
    li $t9, 1
    bc1f .Lfne_27
    nop
    li $t9, 0
.Lfne_27:
    beqz $t9, .Lif_end_26
    nop
    la $t7, math
    move $a0, $t7
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    mov.s $f14, $f12
    lwc1 $f12, 152($sp)
    div.s $f12, $f14, $f12
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal Math_abs_f
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    swc1 $f12, 168($sp)
    move $t9, $t8
.Lif_end_26:
    la $t8, .Lf322
    lwc1 $f12, 0($t8)
    swc1 $f12, 172($sp)
    lwc1 $f12, 156($sp)
    mov.s $f14, $f12
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    c.eq.s $f14, $f12
    li $t9, 1
    bc1f .Lfne_29
    nop
    li $t9, 0
.Lfne_29:
    beqz $t9, .Lif_end_28
    nop
    la $t7, math
    move $a0, $t7
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    mov.s $f14, $f12
    lwc1 $f12, 156($sp)
    div.s $f12, $f14, $f12
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal Math_abs_f
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    swc1 $f12, 172($sp)
    move $t9, $t8
.Lif_end_28:
    li $t9, 1
    sw $t9, 176($sp)
    lw $t5, 160($sp)
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    mov.s $f14, $f12
    la $t4, .Lf321
    lwc1 $f12, 0($t4)
    add.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t5, 140($sp)
    lwc1 $f12, 0($t5)
    sub.s $f12, $f14, $f12
    mov.s $f14, $f12
    lwc1 $f12, 168($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 180($sp)
    lwc1 $f12, 152($sp)
    mov.s $f14, $f12
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_31
    nop
    li $t9, 1
.Lflt_31:
    beqz $t9, .Lif_end_30
    nop
    li $t7, 1
    subu $t8, $zero, $t7
    sw $t8, 176($sp)
    move $t9, $t8
    lw $t5, 140($sp)
    lwc1 $f12, 0($t5)
    mov.s $f14, $f12
    lw $t4, 160($sp)
    mtc1 $t4, $f12
    cvt.s.w $f12, $f12
    sub.s $f12, $f14, $f12
    mov.s $f14, $f12
    lwc1 $f12, 168($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 180($sp)
    move $t9, $t8
.Lif_end_30:
    li $t9, 1
    sw $t9, 184($sp)
    lw $t5, 164($sp)
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    mov.s $f14, $f12
    la $t4, .Lf321
    lwc1 $f12, 0($t4)
    add.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t5, 140($sp)
    lwc1 $f12, 4($t5)
    sub.s $f12, $f14, $f12
    mov.s $f14, $f12
    lwc1 $f12, 172($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 188($sp)
    lwc1 $f12, 156($sp)
    mov.s $f14, $f12
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_33
    nop
    li $t9, 1
.Lflt_33:
    beqz $t9, .Lif_end_32
    nop
    li $t7, 1
    subu $t8, $zero, $t7
    sw $t8, 184($sp)
    move $t9, $t8
    lw $t5, 140($sp)
    lwc1 $f12, 4($t5)
    mov.s $f14, $f12
    lw $t4, 164($sp)
    mtc1 $t4, $f12
    cvt.s.w $f12, $f12
    sub.s $f12, $f14, $f12
    mov.s $f14, $f12
    lwc1 $f12, 172($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 188($sp)
    move $t9, $t8
.Lif_end_32:
    li $t9, 0
    sw $t9, 192($sp)
    li $t9, 0
    sb $t9, 196($sp)
    li $t9, 0
    sb $t9, 197($sp)
    li $t9, 0
    sw $t9, 200($sp)
.Lwhile_h_34:
    lbu $t7, 197($sp)
    sltiu $t8, $t7, 1
    lw $t6, 200($sp)
    li $t5, 24
    slt $t7, $t6, $t5
    sltiu $t6, $t8, 1
    sltiu $t9, $t7, 1
    or $t9, $t6, $t9
    sltiu $t9, $t9, 1
    beqz $t9, .Lwhile_x_35
    nop
    lwc1 $f12, 180($sp)
    mov.s $f14, $f12
    lwc1 $f12, 188($sp)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_38
    nop
    li $t9, 1
.Lflt_38:
    beqz $t9, .Lif_else_37
    nop
    lwc1 $f12, 168($sp)
    mov.s $f14, $f12
    lwc1 $f12, 180($sp)
    add.s $f12, $f12, $f14
    swc1 $f12, 180($sp)
    move $t9, $t8
    lw $t8, 176($sp)
    lw $t7, 160($sp)
    addu $t8, $t7, $t8
    sw $t8, 160($sp)
    move $t9, $t8
    li $t8, 0
    sw $t8, 192($sp)
    move $t9, $t8
    j .Lif_end_36
    nop
.Lif_else_37:
    lwc1 $f12, 172($sp)
    mov.s $f14, $f12
    lwc1 $f12, 188($sp)
    add.s $f12, $f12, $f14
    swc1 $f12, 188($sp)
    move $t9, $t8
    lw $t8, 184($sp)
    lw $t7, 164($sp)
    addu $t8, $t7, $t8
    sw $t8, 164($sp)
    move $t9, $t8
    li $t8, 1
    sw $t8, 192($sp)
    move $t9, $t8
.Lif_end_36:
    lw $a1, 164($sp)
    lw $a0, 160($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal map_get
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    sb $t8, 196($sp)
    move $t9, $t8
    lbu $t8, 196($sp)
    li $t7, 0
    sne $t9, $t8, $t7
    beqz $t9, .Lif_end_39
    nop
    li $t8, 1
    sb $t8, 197($sp)
    move $t9, $t8
.Lif_end_39:
    li $t8, 1
    lw $t7, 200($sp)
    addu $t8, $t7, $t8
    sw $t8, 200($sp)
    move $t9, $t8
    j .Lwhile_h_34
    nop
.Lwhile_x_35:
    la $t8, .Lf321
    lwc1 $f12, 0($t8)
    swc1 $f12, 204($sp)
    lw $t8, 192($sp)
    li $t7, 0
    seq $t9, $t8, $t7
    beqz $t9, .Lif_else_41
    nop
    lwc1 $f12, 180($sp)
    mov.s $f14, $f12
    lwc1 $f12, 168($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 204($sp)
    move $t9, $t8
    j .Lif_end_40
    nop
.Lif_else_41:
    lwc1 $f12, 188($sp)
    mov.s $f14, $f12
    lwc1 $f12, 172($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 204($sp)
    move $t9, $t8
.Lif_end_40:
    lwc1 $f12, 204($sp)
    mov.s $f14, $f12
    la $t6, .Lf324
    lwc1 $f12, 0($t6)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_43
    nop
    li $t9, 1
.Lflt_43:
    beqz $t9, .Lif_end_42
    nop
    la $t7, .Lf324
    lwc1 $f12, 0($t7)
    swc1 $f12, 204($sp)
    move $t9, $t8
.Lif_end_42:
    li $t6, 240
    mtc1 $t6, $f12
    cvt.s.w $f12, $f12
    mov.s $f14, $f12
    lwc1 $f12, 204($sp)
    div.s $f12, $f14, $f12
    move $t9, $t8
    sw $t9, 208($sp)
    lw $t8, 208($sp)
    li $t7, 240
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_44
    nop
    li $t8, 240
    sw $t8, 208($sp)
    move $t9, $t8
.Lif_end_44:
    li $t8, 120
    lw $t6, 208($sp)
    li $t5, 2
    div $t6, $t5
    mflo $t7
    subu $t9, $t8, $t7
    sw $t9, 212($sp)
    li $t8, 120
    lw $t6, 208($sp)
    li $t5, 2
    div $t6, $t5
    mflo $t7
    addu $t9, $t8, $t7
    sw $t9, 216($sp)
    lw $t8, 212($sp)
    li $t7, 0
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_45
    nop
    li $t8, 0
    sw $t8, 212($sp)
    move $t9, $t8
.Lif_end_45:
    lw $t8, 216($sp)
    li $t7, 240
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_46
    nop
    li $t8, 240
    sw $t8, 216($sp)
    move $t9, $t8
.Lif_end_46:
    lw $a1, 192($sp)
    lbu $a0, 196($sp)
    sw $t9, 96($sp)
    jal wall_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 220($sp)
    lw $a0, 220($sp)
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $a3, 216($sp)
    lw $t8, 144($sp)
    li $t7, 2
    addu $a2, $t8, $t7
    lw $a1, 212($sp)
    lw $a0, 144($sp)
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 2
    lw $t7, 144($sp)
    addu $t8, $t7, $t8
    sw $t8, 144($sp)
    move $t9, $t8
    j .Lwhile_h_24
    nop
.Lwhile_x_25:
.Lrender_3d_ret_23:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_3d, . - render_3d

	.section .text
	.globl update_playing
	.type update_playing, @function
update_playing:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    lw $t7, 140($sp)
    lw $t8, 12($t7)
    move $t9, $t8
    sw $t9, 144($sp)
    lw $t7, 140($sp)
    lw $t8, 16($t7)
    move $t9, $t8
    sw $t9, 148($sp)
    lw $t7, 144($sp)
    li $t6, 12
    sgt $t8, $t7, $t6
    lw $t6, 144($sp)
    li $t4, 12
    subu $t5, $zero, $t4
    slt $t7, $t6, $t5
    or $t6, $t8, $t7
    sltu $t9, $zero, $t6
    beqz $t9, .Lif_end_48
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t7, 144($sp)
    mtc1 $t7, $f12
    cvt.s.w $f12, $f12
    mov.s $f14, $f12
    la $t6, STICK_SCALE
    lw $t6, 0($t6)
    subu $t7, $zero, $t6
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_rotate
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_48:
    lw $t8, 148($sp)
    li $t7, 12
    sgt $t9, $t8, $t7
    beqz $t9, .Lif_end_49
    nop
    lw $t7, 148($sp)
    mtc1 $t7, $f12
    cvt.s.w $f12, $f12
    mov.s $f14, $f12
    la $t7, STICK_SCALE
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t7, 136($sp)
    lwc1 $f12, 12($t7)
    mov.s $f14, $f12
    lwc1 $f12, 152($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 8($t7)
    mov.s $f14, $f12
    lwc1 $f12, 152($sp)
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_try_move
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_49:
    lw $t8, 148($sp)
    li $t6, 12
    subu $t7, $zero, $t6
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_50
    nop
    lw $t7, 148($sp)
    mtc1 $t7, $f12
    cvt.s.w $f12, $f12
    mov.s $f14, $f12
    la $t7, STICK_SCALE
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    swc1 $f12, 156($sp)
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t7, 136($sp)
    lwc1 $f12, 12($t7)
    mov.s $f14, $f12
    lwc1 $f12, 156($sp)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 8($t7)
    mov.s $f14, $f12
    lwc1 $f12, 156($sp)
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_try_move
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_50:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 8($t8)
    beqz $t9, .Lif_end_51
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t7, 136($sp)
    lwc1 $f12, 20($t7)
    mov.s $f14, $f12
    la $t6, MOVE_SPEED
    lw $t6, 0($t6)
    subu $t7, $zero, $t6
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 16($t7)
    mov.s $f14, $f12
    la $t6, MOVE_SPEED
    lw $t6, 0($t6)
    subu $t7, $zero, $t6
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_try_move
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_51:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 9($t8)
    beqz $t9, .Lif_end_52
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t7, 136($sp)
    lwc1 $f12, 20($t7)
    mov.s $f14, $f12
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 16($t7)
    mov.s $f14, $f12
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_try_move
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_52:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 7($t8)
    beqz $t9, .Lif_end_53
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    la $t8, ROT_SPEED
    lw $t8, 0($t8)
    subu $a1, $zero, $t8
    sw $t9, 96($sp)
    jal Camera_rotate
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_53:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 6($t8)
    beqz $t9, .Lif_end_54
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    la $a1, ROT_SPEED
    lw $a1, 0($a1)
    sw $t9, 96($sp)
    jal Camera_rotate
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_54:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 4($t8)
    beqz $t9, .Lif_end_55
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t7, 136($sp)
    lwc1 $f12, 12($t7)
    mov.s $f14, $f12
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t7, 136($sp)
    lwc1 $f12, 8($t7)
    mov.s $f14, $f12
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_try_move
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_55:
    lw $t7, 140($sp)
    lw $t8, 0($t7)
    lb $t9, 5($t8)
    beqz $t9, .Lif_end_56
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t6, 136($sp)
    lwc1 $f12, 12($t6)
    neg.s $f12, $f12
    mov.s $f14, $f12
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    mov.s $f14, $f12
    lw $t6, 136($sp)
    lwc1 $f12, 8($t6)
    neg.s $f12, $f12
    mov.s $f14, $f12
    la $t7, MOVE_SPEED
    lw $t7, 0($t7)
    mul.s $f12, $f14, $f12
    sw $t9, 96($sp)
    jal Camera_try_move
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_56:
    lw $t7, 140($sp)
    lw $t8, 4($t7)
    lb $t9, 3($t8)
    beqz $t9, .Lif_end_57
    nop
    li $t8, 2
    lw $t7, 136($sp)
    sb $t8, 24($t7)
    move $t9, $t8
.Lif_end_57:
.Lupdate_playing_ret_47:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update_playing, . - update_playing

	.section .text
	.globl render_screen
	.type render_screen, @function
render_screen:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $t9, 96($sp)
    jal display_get
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 140($sp)
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal rdpq_attach_clear
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 136($sp)
    lbu $t9, 24($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_61
    nop
    li $a0, 4607
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_59
    nop
.Larm_skip_61:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_63
    nop
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_3d
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_minimap
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_59
    nop
.Larm_skip_63:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_65
    nop
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_3d
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal render_minimap
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    li $a0, 859002367
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    li $a3, 140
    li $a2, 220
    li $a1, 100
    li $a0, 100
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_59
    nop
.Larm_skip_65:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_67
    nop
    li $a0, 285212927
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_59
    nop
.Larm_skip_67:
.Lmatch_end_59:
    sw $t9, 96($sp)
    jal rdpq_detach_show
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lrender_screen_ret_58:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size render_screen, . - render_screen

	.section .text
	.globl init_game
	.type init_game, @function
init_game:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    la $t7, .Lf325
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    swc1 $f12, 0($t7)
    move $t9, $t8
    la $t7, .Lf326
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    swc1 $f12, 4($t7)
    move $t9, $t8
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    swc1 $f12, 8($t7)
    move $t9, $t8
    la $t7, .Lf323
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    swc1 $f12, 12($t7)
    move $t9, $t8
    la $t7, .Lf323
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    swc1 $f12, 16($t7)
    move $t9, $t8
    la $t7, .Lf327
    lwc1 $f12, 0($t7)
    lw $t7, 136($sp)
    swc1 $f12, 20($t7)
    move $t9, $t8
    li $t8, 10
    lw $t7, 136($sp)
    sw $t8, 32($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 36($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sw $t8, 28($t7)
    move $t9, $t8
    li $t8, 0
    lw $t7, 136($sp)
    sb $t8, 24($t7)
    move $t9, $t8
.Linit_game_ret_68:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size init_game, . - init_game

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $t8, 1
    sw $t8, 16($sp)
    li $a3, 0
    li $a2, 3
    li $a1, 2
    li $a0, 0
    sw $t9, 96($sp)
    jal display_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal joypad_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal timer_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    move $t9, $zero
    addiu $t8, $sp, 136
    move $a0, $t8
    move $a1, $t9
    li $a2, 40
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memcpy
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal init_game
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lloop_h_70:
    sw $t9, 96($sp)
    jal joypad_poll
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 0
    sw $t9, 96($sp)
    jal joypad_get_status
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 176($sp)
    addiu $t8, $sp, 136
    lbu $t9, 24($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_74
    nop
    lw $t5, 176($sp)
    lw $t6, 4($t5)
    lb $t7, 3($t6)
    lw $t4, 176($sp)
    lw $t5, 4($t4)
    lb $t6, 0($t5)
    or $t5, $t7, $t6
    sltu $t8, $zero, $t5
    beqz $t8, .Lif_end_75
    nop
    li $t7, 1
    addiu $t6, $sp, 136
    sb $t7, 24($t6)
    move $t8, $t7
.Lif_end_75:
    j .Lmatch_end_72
    nop
.Larm_skip_74:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_77
    nop
    lw $a1, 176($sp)
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal update_playing
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    j .Lmatch_end_72
    nop
.Larm_skip_77:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_79
    nop
    lw $t6, 176($sp)
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    beqz $t8, .Lif_end_80
    nop
    li $t7, 1
    addiu $t6, $sp, 136
    sb $t7, 24($t6)
    move $t8, $t7
.Lif_end_80:
    lw $t6, 176($sp)
    lw $t7, 4($t6)
    lb $t8, 1($t7)
    beqz $t8, .Lif_end_81
    nop
    li $t7, 3
    addiu $t6, $sp, 136
    sb $t7, 24($t6)
    move $t8, $t7
.Lif_end_81:
    j .Lmatch_end_72
    nop
.Larm_skip_79:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_83
    nop
    lw $t6, 176($sp)
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    beqz $t8, .Lif_end_84
    nop
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal init_game
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
.Lif_end_84:
    j .Lmatch_end_72
    nop
.Larm_skip_83:
.Lmatch_end_72:
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal render_screen
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t8, 1
    addiu $t6, $sp, 136
    lw $t7, 28($t6)
    addu $t8, $t7, $t8
    addiu $t7, $sp, 136
    sw $t8, 28($t7)
    move $t9, $t8
    j .Lloop_h_70
    nop
.Lloop_x_71:
    sw $t9, 96($sp)
    jal rdpq_close
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    la $a0, .Lstr8
    sw $t9, 96($sp)
    jal debugf
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lmain_ret_69:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 0
.Lstr8:
	.asciiz "PAK3D exited"
	.align 2
.Lf320:
	.word 1073741824
	.align 2
.Lf321:
	.word 1065353216
	.align 2
.Lf322:
	.word 1232348144
	.align 2
.Lf323:
	.word 0
	.align 2
.Lf324:
	.word 1036831949
	.align 2
.Lf325:
	.word 1069547520
	.align 2
.Lf326:
	.word 1091043328
	.align 2
.Lf327:
	.word 1059648963

	.section .bss
	.align 0
	.globl dungeon_map
dungeon_map:
	.space 256
