# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_persp
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_tex_persp
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern pakfs_read
	.extern pakfs_size
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern get_memory_size
	.extern system_has_expansion
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern debug_init_isviewer
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_rotate_x
	.extern t3d_mat4_rotate_y
	.extern t3d_mat4_rotate_z
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_add
	.extern t3d_vec3_sub
	.extern t3d_vec3_scale
	.extern t3d_vec3_len
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_viewport_calc_viewspace_pos
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl map_get
	.type map_get, @function
map_get:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    sw $s0, 140($sp)
    sw $s1, 136($sp)
    move $s0, $a0
    move $s1, $a1
    move $t9, $s0
    bltz $t9, .Lsc_2
    nop
    move $t9, $s0
    li $t8, 16
    slt $t7, $t9, $t8
    beqz $t7, .Lsc_2
    nop
    move $t9, $s1
    bltz $t9, .Lsc_2
    nop
    move $t9, $s1
    li $t8, 16
    slt $t7, $t9, $t8
    bnez $t7, .Lif_end_1
    nop
.Lsc_2:
    li $v0, 1
    j .Lmap_get_ret_0
    nop
.Lif_end_1:
    la $t9, dungeon_map
    move $t6, $s1
    li $t5, 16
    mul $t7, $t6, $t5
    move $t6, $s0
    addu $t8, $t7, $t6
    addu $t9, $t9, $t8
    lbu $v0, 0($t9)
    j .Lmap_get_ret_0
    nop
.Lmap_get_ret_0:
    lw $s1, 136($sp)
    lw $s0, 140($sp)
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size map_get, . - map_get

	.section .text
	.globl Camera_rotate
	.type Camera_rotate, @function
Camera_rotate:
    addiu $sp, $sp, -176
    sw $ra, 172($sp)
    sw $fp, 168($sp)
    addiu $fp, $sp, 176
    sw $a0, 136($sp)
    swc1 $f12, 140($sp)
    lwc1 $f12, 140($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 148($sp)
    jal math_cos_f
    nop
    move $t9, $v0
    swc1 $f12, 144($sp)
    lwc1 $f12, 140($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 148($sp)
    jal math_sin_f
    nop
    move $t9, $v0
    swc1 $f12, 152($sp)
    lw $t8, 136($sp)
    lwc1 $f12, 8($t8)
    swc1 $f12, 156($sp)
    lw $t8, 136($sp)
    lwc1 $f12, 16($t8)
    swc1 $f12, 160($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 8($t6)
    swc1 $f12, 164($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    lwc1 $f12, 12($t5)
    swc1 $f12, 164($sp)
    lwc1 $f12, 152($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 148($sp)
    sub.s $f12, $f14, $f12
    lw $t8, 136($sp)
    swc1 $f12, 8($t8)
    lwc1 $f12, 156($sp)
    swc1 $f12, 164($sp)
    lwc1 $f12, 152($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    lwc1 $f12, 12($t5)
    swc1 $f12, 164($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    lw $t8, 136($sp)
    swc1 $f12, 12($t8)
    lw $t6, 136($sp)
    lwc1 $f12, 16($t6)
    swc1 $f12, 164($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    lwc1 $f12, 20($t5)
    swc1 $f12, 164($sp)
    lwc1 $f12, 152($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 148($sp)
    sub.s $f12, $f14, $f12
    lw $t8, 136($sp)
    swc1 $f12, 16($t8)
    lwc1 $f12, 160($sp)
    swc1 $f12, 164($sp)
    lwc1 $f12, 152($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    lwc1 $f12, 20($t5)
    swc1 $f12, 164($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 164($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    lw $t8, 136($sp)
    swc1 $f12, 20($t8)
.LCamera_rotate_ret_3:
    lw $fp, 168($sp)
    lw $ra, 172($sp)
    addiu $sp, $sp, 176
    jr $ra
    nop
	.size Camera_rotate, . - Camera_rotate

	.section .text
	.globl Camera_try_move
	.type Camera_try_move, @function
Camera_try_move:
    addiu $sp, $sp, -176
    sw $ra, 172($sp)
    sw $fp, 168($sp)
    addiu $fp, $sp, 176
    sw $a0, 136($sp)
    swc1 $f12, 140($sp)
    mov.s $f12, $f14
    swc1 $f12, 144($sp)
    lw $t7, 136($sp)
    lwc1 $f12, 0($t7)
    swc1 $f12, 152($sp)
    lwc1 $f12, 140($sp)
    lwc1 $f14, 152($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t7, 136($sp)
    lwc1 $f12, 4($t7)
    swc1 $f12, 152($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 152($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 156($sp)
    lw $t7, 136($sp)
    lwc1 $f12, 4($t7)
    trunc.w.s $f12, $f12
    mfc1 $a1, $f12
    lwc1 $f12, 148($sp)
    trunc.w.s $f12, $f12
    mfc1 $a0, $f12
    jal map_get
    nop
    move $t9, $v0
    bnez $t9, .Lif_end_5
    nop
    lwc1 $f12, 148($sp)
    lw $t8, 136($sp)
    swc1 $f12, 0($t8)
.Lif_end_5:
    lwc1 $f12, 156($sp)
    trunc.w.s $f12, $f12
    mfc1 $t8, $f12
    sw $t8, 160($sp)
    lw $t7, 136($sp)
    lwc1 $f12, 0($t7)
    trunc.w.s $f12, $f12
    mfc1 $a0, $f12
    lw $a1, 160($sp)
    jal map_get
    nop
    move $t9, $v0
    bnez $t9, .Lif_end_6
    nop
    lwc1 $f12, 156($sp)
    lw $t8, 136($sp)
    swc1 $f12, 4($t8)
.Lif_end_6:
.LCamera_try_move_ret_4:
    lw $fp, 168($sp)
    lw $ra, 172($sp)
    addiu $sp, $sp, 176
    jr $ra
    nop
	.size Camera_try_move, . - Camera_try_move

	.section .text
	.globl wall_color
	.type wall_color, @function
wall_color:
    addiu $sp, $sp, -160
    sw $ra, 156($sp)
    sw $fp, 152($sp)
    addiu $fp, $sp, 160
    sw $s0, 148($sp)
    sw $s1, 144($sp)
    sb $a0, 136($sp)
    move $s1, $a1
    li $t9, 2857710591
    move $s0, $t9
    lbu $t9, 136($sp)
    li $t8, 2
    bne $t9, $t8, .Lif_else_9
    nop
    li $t9, 1148693247
    move $s0, $t9
    j .Lif_end_8
    nop
.Lif_else_9:
    lbu $t9, 136($sp)
    li $t8, 3
    bne $t9, $t8, .Lelif_else_10
    nop
    li $t9, 1152013823
    move $s0, $t9
    j .Lif_end_8
    nop
.Lelif_else_10:
.Lif_end_8:
    move $t9, $s1
    li $t8, 1
    bne $t9, $t8, .Lif_end_11
    nop
    li $t9, 1999839999
    move $s0, $t9
    lbu $t9, 136($sp)
    li $t8, 2
    bne $t9, $t8, .Lif_else_13
    nop
    li $t9, 862357759
    move $s0, $t9
    j .Lif_end_12
    nop
.Lif_else_13:
    lbu $t9, 136($sp)
    li $t8, 3
    bne $t9, $t8, .Lelif_else_14
    nop
    li $t9, 864568575
    move $s0, $t9
    j .Lif_end_12
    nop
.Lelif_else_14:
.Lif_end_12:
.Lif_end_11:
    move $v0, $s0
    j .Lwall_color_ret_7
    nop
.Lwall_color_ret_7:
    lw $s1, 144($sp)
    lw $s0, 148($sp)
    lw $fp, 152($sp)
    lw $ra, 156($sp)
    addiu $sp, $sp, 160
    jr $ra
    nop
	.size wall_color, . - wall_color

	.section .text
	.globl render_minimap
	.type render_minimap, @function
render_minimap:
    addiu $sp, $sp, -184
    sw $ra, 180($sp)
    sw $fp, 176($sp)
    addiu $fp, $sp, 184
    sw $s0, 172($sp)
    sw $s1, 168($sp)
    sw $s2, 164($sp)
    sw $s3, 160($sp)
    sw $s4, 156($sp)
    sw $s5, 152($sp)
    sw $a0, 136($sp)
    li $t9, 0
    move $s0, $t9
.Lwhile_h_16:
    move $t9, $s0
    li $t8, 16
    slt $t7, $t9, $t8
    beqz $t7, .Lwhile_x_17
    nop
    li $t9, 0
    move $s1, $t9
.Lwhile_h_18:
    move $t9, $s1
    li $t8, 16
    slt $t7, $t9, $t8
    beqz $t7, .Lwhile_x_19
    nop
    la $t8, dungeon_map
    move $t5, $s0
    li $t4, 16
    mul $t6, $t5, $t4
    move $t5, $s1
    addu $t7, $t6, $t5
    addu $t8, $t8, $t7
    lbu $t9, 0($t8)
    sb $t9, 140($sp)
    li $t8, 252
    move $t6, $s1
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    move $s3, $t9
    li $t8, 2
    move $t6, $s0
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    move $s4, $t9
    li $t9, 858993663
    move $s2, $t9
    lbu $t9, 140($sp)
    li $t8, 1
    bne $t9, $t8, .Lif_else_21
    nop
    li $t9, 2857710591
    move $s2, $t9
    j .Lif_end_20
    nop
.Lif_else_21:
    lbu $t9, 140($sp)
    li $t8, 2
    bne $t9, $t8, .Lelif_else_22
    nop
    li $t9, 1148693247
    move $s2, $t9
    j .Lif_end_20
    nop
.Lelif_else_22:
    lbu $t9, 140($sp)
    li $t8, 3
    bne $t9, $t8, .Lelif_else_23
    nop
    li $t9, 1152013823
    move $s2, $t9
    j .Lif_end_20
    nop
.Lelif_else_23:
.Lif_end_20:
    move $a0, $s2
    jal rdpq_set_fill_color
    nop
    move $t9, $v0
    move $t8, $s4
    li $t7, 4
    addu $a3, $t8, $t7
    move $t8, $s3
    li $t7, 4
    addu $a2, $t8, $t7
    move $a1, $s4
    move $a0, $s3
    jal rdpq_fill_rectangle
    nop
    move $t9, $v0
    li $t9, 1
    move $t8, $s1
    addu $t9, $t8, $t9
    move $s1, $t9
    j .Lwhile_h_18
    nop
.Lwhile_x_19:
    li $t9, 1
    move $t8, $s0
    addu $t9, $t8, $t9
    move $s0, $t9
    j .Lwhile_h_16
    nop
.Lwhile_x_17:
    li $t8, 252
    lw $t4, 136($sp)
    lwc1 $f12, 0($t4)
    trunc.w.s $f12, $f12
    mfc1 $t6, $f12
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    move $s5, $t9
    li $t8, 2
    lw $t4, 136($sp)
    lwc1 $f12, 4($t4)
    trunc.w.s $f12, $f12
    mfc1 $t6, $f12
    li $t5, 4
    mul $t7, $t6, $t5
    addu $t9, $t8, $t7
    sw $t9, 144($sp)
    li $a0, 4294902015
    jal rdpq_set_fill_color
    nop
    move $t9, $v0
    lw $t8, 144($sp)
    li $t7, 4
    addu $a3, $t8, $t7
    move $t8, $s5
    li $t7, 4
    addu $a2, $t8, $t7
    lw $a1, 144($sp)
    move $a0, $s5
    jal rdpq_fill_rectangle
    nop
    move $t9, $v0
.Lrender_minimap_ret_15:
    lw $s5, 152($sp)
    lw $s4, 156($sp)
    lw $s3, 160($sp)
    lw $s2, 164($sp)
    lw $s1, 168($sp)
    lw $s0, 172($sp)
    lw $fp, 176($sp)
    lw $ra, 180($sp)
    addiu $sp, $sp, 184
    jr $ra
    nop
	.size render_minimap, . - render_minimap

	.section .text
	.globl render_3d
	.type render_3d, @function
render_3d:
    addiu $sp, $sp, -248
    sw $ra, 244($sp)
    sw $fp, 240($sp)
    addiu $fp, $sp, 248
    sw $s0, 236($sp)
    sw $s1, 232($sp)
    sw $s2, 228($sp)
    sw $s3, 224($sp)
    sw $s4, 220($sp)
    sw $s5, 216($sp)
    sw $a0, 136($sp)
    lw $t9, 136($sp)
    sw $t9, 140($sp)
    li $a0, 219884287
    jal rdpq_set_mode_fill
    nop
    move $t9, $v0
    li $a3, 120
    li $a2, 320
    li $a1, 0
    li $a0, 0
    jal rdpq_fill_rectangle
    nop
    move $t9, $v0
    li $a0, 437390079
    jal rdpq_set_fill_color
    nop
    move $t9, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 120
    li $a0, 0
    jal rdpq_fill_rectangle
    nop
    move $t9, $v0
    li $t9, 0
    move $s0, $t9
.Lwhile_h_25:
    move $t9, $s0
    li $t8, 320
    slt $t7, $t9, $t8
    beqz $t7, .Lwhile_x_26
    nop
    la $t5, .Lf320
    lwc1 $f12, 0($t5)
    swc1 $f12, 156($sp)
    move $t4, $s0
    mtc1 $t4, $f12
    cvt.s.w $f12, $f12
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    li $t5, 320
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    lwc1 $f14, 152($sp)
    div.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    lwc1 $f14, 148($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 8($t7)
    swc1 $f12, 148($sp)
    lw $t5, 140($sp)
    lwc1 $f12, 16($t5)
    swc1 $f12, 152($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 152($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 160($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 12($t7)
    swc1 $f12, 148($sp)
    lw $t5, 140($sp)
    lwc1 $f12, 20($t5)
    swc1 $f12, 152($sp)
    lwc1 $f12, 144($sp)
    lwc1 $f14, 152($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 164($sp)
    lw $t7, 140($sp)
    lwc1 $f12, 0($t7)
    trunc.w.s $f12, $f12
    mfc1 $t9, $f12
    move $s1, $t9
    lw $t7, 140($sp)
    lwc1 $f12, 4($t7)
    trunc.w.s $f12, $f12
    mfc1 $t9, $f12
    move $s2, $t9
    la $t8, .Lf322
    lwc1 $f12, 0($t8)
    swc1 $f12, 168($sp)
    lwc1 $f12, 160($sp)
    swc1 $f12, 148($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    lwc1 $f14, 148($sp)
    c.eq.s $f14, $f12
    li $t9, 1
    bc1f .Lfne_28
    nop
    li $t9, 0
.Lfne_28:
    beqz $t9, .Lif_end_27
    nop
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    swc1 $f12, 152($sp)
    lwc1 $f12, 160($sp)
    lwc1 $f14, 152($sp)
    div.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 148($sp)
    jal math_abs_f
    nop
    move $t9, $v0
    swc1 $f12, 168($sp)
.Lif_end_27:
    la $t8, .Lf322
    lwc1 $f12, 0($t8)
    swc1 $f12, 172($sp)
    lwc1 $f12, 164($sp)
    swc1 $f12, 148($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    lwc1 $f14, 148($sp)
    c.eq.s $f14, $f12
    li $t9, 1
    bc1f .Lfne_30
    nop
    li $t9, 0
.Lfne_30:
    beqz $t9, .Lif_end_29
    nop
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    swc1 $f12, 152($sp)
    lwc1 $f12, 164($sp)
    lwc1 $f14, 152($sp)
    div.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 148($sp)
    jal math_abs_f
    nop
    move $t9, $v0
    swc1 $f12, 172($sp)
.Lif_end_29:
    li $t9, 1
    sw $t9, 176($sp)
    move $t5, $s1
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    swc1 $f12, 156($sp)
    la $t4, .Lf321
    lwc1 $f12, 0($t4)
    lwc1 $f14, 156($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t5, 140($sp)
    lwc1 $f12, 0($t5)
    lwc1 $f14, 152($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 168($sp)
    lwc1 $f14, 148($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 180($sp)
    lwc1 $f12, 160($sp)
    swc1 $f12, 148($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    lwc1 $f14, 148($sp)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_32
    nop
    li $t9, 1
.Lflt_32:
    beqz $t9, .Lif_end_31
    nop
    li $t8, 1
    subu $t9, $zero, $t8
    sw $t9, 176($sp)
    lw $t6, 140($sp)
    lwc1 $f12, 0($t6)
    swc1 $f12, 152($sp)
    move $t5, $s1
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    lwc1 $f14, 152($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 168($sp)
    lwc1 $f14, 148($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 180($sp)
.Lif_end_31:
    li $t9, 1
    sw $t9, 184($sp)
    move $t5, $s2
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    swc1 $f12, 156($sp)
    la $t4, .Lf321
    lwc1 $f12, 0($t4)
    lwc1 $f14, 156($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t5, 140($sp)
    lwc1 $f12, 4($t5)
    lwc1 $f14, 152($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 172($sp)
    lwc1 $f14, 148($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 188($sp)
    lwc1 $f12, 164($sp)
    swc1 $f12, 148($sp)
    la $t6, .Lf323
    lwc1 $f12, 0($t6)
    lwc1 $f14, 148($sp)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_34
    nop
    li $t9, 1
.Lflt_34:
    beqz $t9, .Lif_end_33
    nop
    li $t8, 1
    subu $t9, $zero, $t8
    sw $t9, 184($sp)
    lw $t6, 140($sp)
    lwc1 $f12, 4($t6)
    swc1 $f12, 152($sp)
    move $t5, $s2
    mtc1 $t5, $f12
    cvt.s.w $f12, $f12
    lwc1 $f14, 152($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 172($sp)
    lwc1 $f14, 148($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 188($sp)
.Lif_end_33:
    li $t9, 0
    move $s3, $t9
    li $t9, 0
    sb $t9, 192($sp)
    li $t9, 0
    sb $t9, 193($sp)
    li $t9, 0
    sw $t9, 196($sp)
.Lwhile_h_35:
    lbu $t9, 193($sp)
    bnez $t9, .Lwhile_x_36
    nop
    lw $t9, 196($sp)
    slti $t8, $t9, 24
    beqz $t8, .Lwhile_x_36
    nop
    lwc1 $f12, 180($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 188($sp)
    lwc1 $f14, 148($sp)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_39
    nop
    li $t9, 1
.Lflt_39:
    beqz $t9, .Lif_else_38
    nop
    lwc1 $f12, 168($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 180($sp)
    lwc1 $f14, 148($sp)
    add.s $f12, $f12, $f14
    swc1 $f12, 180($sp)
    lw $t9, 176($sp)
    move $t8, $s1
    addu $t9, $t8, $t9
    move $s1, $t9
    li $t9, 0
    move $s3, $t9
    j .Lif_end_37
    nop
.Lif_else_38:
    lwc1 $f12, 172($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 188($sp)
    lwc1 $f14, 148($sp)
    add.s $f12, $f12, $f14
    swc1 $f12, 188($sp)
    lw $t9, 184($sp)
    move $t8, $s2
    addu $t9, $t8, $t9
    move $s2, $t9
    li $t9, 1
    move $s3, $t9
.Lif_end_37:
    move $a1, $s2
    move $a0, $s1
    jal map_get
    nop
    move $t9, $v0
    sb $t9, 192($sp)
    lbu $t9, 192($sp)
    beqz $t9, .Lif_end_40
    nop
    li $t9, 1
    sb $t9, 193($sp)
.Lif_end_40:
    li $t9, 1
    lw $t8, 196($sp)
    addu $t9, $t8, $t9
    sw $t9, 196($sp)
    j .Lwhile_h_35
    nop
.Lwhile_x_36:
    la $t8, .Lf321
    lwc1 $f12, 0($t8)
    swc1 $f12, 200($sp)
    move $t9, $s3
    bnez $t9, .Lif_else_42
    nop
    lwc1 $f12, 180($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 168($sp)
    lwc1 $f14, 148($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 200($sp)
    j .Lif_end_41
    nop
.Lif_else_42:
    lwc1 $f12, 188($sp)
    swc1 $f12, 148($sp)
    lwc1 $f12, 172($sp)
    lwc1 $f14, 148($sp)
    sub.s $f12, $f14, $f12
    swc1 $f12, 200($sp)
.Lif_end_41:
    lwc1 $f12, 200($sp)
    swc1 $f12, 148($sp)
    la $t6, .Lf324
    lwc1 $f12, 0($t6)
    lwc1 $f14, 148($sp)
    c.lt.s $f14, $f12
    li $t9, 0
    bc1f .Lflt_44
    nop
    li $t9, 1
.Lflt_44:
    beqz $t9, .Lif_end_43
    nop
    la $t8, .Lf324
    lwc1 $f12, 0($t8)
    swc1 $f12, 200($sp)
.Lif_end_43:
    li $t6, 240
    mtc1 $t6, $f12
    cvt.s.w $f12, $f12
    swc1 $f12, 148($sp)
    lwc1 $f12, 200($sp)
    lwc1 $f14, 148($sp)
    div.s $f12, $f14, $f12
    trunc.w.s $f12, $f12
    mfc1 $t9, $f12
    move $s4, $t9
    move $t9, $s4
    li $t8, 240
    slt $t7, $t8, $t9
    beqz $t7, .Lif_end_45
    nop
    li $t9, 240
    move $s4, $t9
.Lif_end_45:
    li $t8, 120
    move $t6, $s4
    li $t5, 2
    div $zero, $t6, $t5
    mflo $t7
    subu $t9, $t8, $t7
    move $s5, $t9
    li $t8, 120
    move $t6, $s4
    li $t5, 2
    div $zero, $t6, $t5
    mflo $t7
    addu $t9, $t8, $t7
    sw $t9, 204($sp)
    move $t9, $s5
    bgez $t9, .Lif_end_46
    nop
    li $t9, 0
    move $s5, $t9
.Lif_end_46:
    lw $t9, 204($sp)
    li $t8, 240
    slt $t7, $t8, $t9
    beqz $t7, .Lif_end_47
    nop
    li $t9, 240
    sw $t9, 204($sp)
.Lif_end_47:
    move $a1, $s3
    lbu $a0, 192($sp)
    jal wall_color
    nop
    move $t9, $v0
    sw $t9, 208($sp)
    lw $a0, 208($sp)
    jal rdpq_set_fill_color
    nop
    move $t9, $v0
    lw $a3, 204($sp)
    move $t8, $s0
    li $t7, 2
    addu $a2, $t8, $t7
    move $a1, $s5
    move $a0, $s0
    jal rdpq_fill_rectangle
    nop
    move $t9, $v0
    li $t9, 2
    move $t8, $s0
    addu $t9, $t8, $t9
    move $s0, $t9
    j .Lwhile_h_25
    nop
.Lwhile_x_26:
.Lrender_3d_ret_24:
    lw $s5, 216($sp)
    lw $s4, 220($sp)
    lw $s3, 224($sp)
    lw $s2, 228($sp)
    lw $s1, 232($sp)
    lw $s0, 236($sp)
    lw $fp, 240($sp)
    lw $ra, 244($sp)
    addiu $sp, $sp, 248
    jr $ra
    nop
	.size render_3d, . - render_3d

	.section .text
	.globl update_playing
	.type update_playing, @function
update_playing:
    addiu $sp, $sp, -184
    sw $ra, 180($sp)
    sw $fp, 176($sp)
    addiu $fp, $sp, 184
    sw $s0, 172($sp)
    sw $s1, 168($sp)
    sw $a0, 136($sp)
    move $t9, $a1
    addiu $t8, $sp, 140
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    addiu $t7, $sp, 140
    lw $t8, 12($t7)
    move $t9, $t8
    move $s1, $t9
    addiu $t7, $sp, 140
    lw $t8, 16($t7)
    move $t9, $t8
    move $s0, $t9
    move $t9, $s1
    li $t8, 12
    slt $t7, $t8, $t9
    bnez $t7, .Lsc_50
    nop
    move $t9, $s1
    li $t7, 12
    subu $t8, $zero, $t7
    slt $t7, $t9, $t8
    beqz $t7, .Lif_end_49
    nop
.Lsc_50:
    lw $t8, 136($sp)
    move $a0, $t8
    move $t6, $s1
    mtc1 $t6, $f12
    cvt.s.w $f12, $f12
    swc1 $f12, 148($sp)
    la $t4, .Lf325
    lwc1 $f12, 0($t4)
    subu $t6, $zero, $t5
    lwc1 $f14, 148($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_rotate
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_49:
    move $t9, $s0
    li $t8, 12
    slt $t7, $t8, $t9
    beqz $t7, .Lif_end_51
    nop
    move $t7, $s0
    mtc1 $t7, $f12
    cvt.s.w $f12, $f12
    swc1 $f12, 144($sp)
    la $t6, .Lf325
    lwc1 $f12, 0($t6)
    lwc1 $f14, 144($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t6, 136($sp)
    lwc1 $f12, 12($t6)
    swc1 $f12, 156($sp)
    lwc1 $f12, 152($sp)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 8($t6)
    swc1 $f12, 156($sp)
    lwc1 $f12, 152($sp)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f14, 148($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_try_move
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_51:
    move $t9, $s0
    li $t7, 12
    subu $t8, $zero, $t7
    slt $t7, $t9, $t8
    beqz $t7, .Lif_end_52
    nop
    move $t7, $s0
    mtc1 $t7, $f12
    cvt.s.w $f12, $f12
    swc1 $f12, 144($sp)
    la $t6, .Lf325
    lwc1 $f12, 0($t6)
    lwc1 $f14, 144($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 160($sp)
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t6, 136($sp)
    lwc1 $f12, 12($t6)
    swc1 $f12, 156($sp)
    lwc1 $f12, 160($sp)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 8($t6)
    swc1 $f12, 156($sp)
    lwc1 $f12, 160($sp)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f14, 148($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_try_move
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_52:
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    lb $t9, 8($t8)
    beqz $t9, .Lif_end_53
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t6, 136($sp)
    lwc1 $f12, 20($t6)
    swc1 $f12, 156($sp)
    la $t4, .Lf326
    lwc1 $f12, 0($t4)
    subu $t6, $zero, $t5
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 16($t6)
    swc1 $f12, 156($sp)
    la $t4, .Lf326
    lwc1 $f12, 0($t4)
    subu $t6, $zero, $t5
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f14, 148($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_try_move
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_53:
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    lb $t9, 9($t8)
    beqz $t9, .Lif_end_54
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t6, 136($sp)
    lwc1 $f12, 20($t6)
    swc1 $f12, 156($sp)
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 16($t6)
    swc1 $f12, 156($sp)
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f14, 148($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_try_move
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_54:
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    lb $t9, 7($t8)
    beqz $t9, .Lif_end_55
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    la $t6, .Lf327
    lwc1 $f12, 0($t6)
    subu $a1, $zero, $t7
    sw $t8, 96($sp)
    jal Camera_rotate
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_55:
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    lb $t9, 6($t8)
    beqz $t9, .Lif_end_56
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    la $t7, .Lf327
    lwc1 $f12, 0($t7)
    sw $t8, 96($sp)
    jal Camera_rotate
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_56:
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    lb $t9, 4($t8)
    beqz $t9, .Lif_end_57
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t6, 136($sp)
    lwc1 $f12, 12($t6)
    swc1 $f12, 156($sp)
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t6, 136($sp)
    lwc1 $f12, 8($t6)
    swc1 $f12, 156($sp)
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f14, 148($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_try_move
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_57:
    addiu $t7, $sp, 140
    lw $t8, 0($t7)
    lb $t9, 5($t8)
    beqz $t9, .Lif_end_58
    nop
    lw $t8, 136($sp)
    move $a0, $t8
    lw $t5, 136($sp)
    lwc1 $f12, 12($t5)
    neg.s $f12, $f12
    swc1 $f12, 156($sp)
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    lwc1 $f12, 8($t5)
    neg.s $f12, $f12
    swc1 $f12, 156($sp)
    la $t5, .Lf326
    lwc1 $f12, 0($t5)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 144($sp)
    lwc1 $f14, 148($sp)
    lwc1 $f12, 144($sp)
    sw $t8, 96($sp)
    jal Camera_try_move
    nop
    lw $t8, 96($sp)
    move $t9, $v0
.Lif_end_58:
    addiu $t7, $sp, 140
    lw $t8, 4($t7)
    lb $t9, 3($t8)
    beqz $t9, .Lif_end_59
    nop
    li $t9, 2
    lw $t8, 136($sp)
    sb $t9, 24($t8)
.Lif_end_59:
.Lupdate_playing_ret_48:
    lw $s1, 168($sp)
    lw $s0, 172($sp)
    lw $fp, 176($sp)
    lw $ra, 180($sp)
    addiu $sp, $sp, 184
    jr $ra
    nop
	.size update_playing, . - update_playing

	.section .text
	.globl render_screen
	.type render_screen, @function
render_screen:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    sw $a0, 136($sp)
    jal display_get
    nop
    move $t9, $v0
    sw $t9, 140($sp)
    lw $a0, 140($sp)
    move $a1, $zero
    jal rdpq_attach_clear
    nop
    move $t9, $v0
    lw $t8, 136($sp)
    lbu $t9, 24($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_63
    nop
    li $a0, 4607
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    j .Lmatch_end_61
    nop
.Larm_skip_63:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_65
    nop
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal render_3d
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal render_minimap
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    j .Lmatch_end_61
    nop
.Larm_skip_65:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_67
    nop
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal render_3d
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    lw $a0, 136($sp)
    sw $t9, 96($sp)
    jal render_minimap
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    li $a0, 859002367
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    li $a3, 140
    li $a2, 220
    li $a1, 100
    li $a0, 100
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    j .Lmatch_end_61
    nop
.Larm_skip_67:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_69
    nop
    li $a0, 285212927
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    li $a3, 240
    li $a2, 320
    li $a1, 0
    li $a0, 0
    sw $t9, 96($sp)
    jal rdpq_fill_rectangle
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    j .Lmatch_end_61
    nop
.Larm_skip_69:
.Lmatch_end_61:
    jal rdpq_detach_show
    nop
    move $t9, $v0
.Lrender_screen_ret_60:
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size render_screen, . - render_screen

	.section .text
	.globl init_game
	.type init_game, @function
init_game:
    addiu $sp, $sp, -152
    sw $ra, 148($sp)
    sw $fp, 144($sp)
    addiu $fp, $sp, 152
    sw $a0, 136($sp)
    la $t8, .Lf328
    lwc1 $f12, 0($t8)
    lw $t8, 136($sp)
    swc1 $f12, 0($t8)
    la $t8, .Lf329
    lwc1 $f12, 0($t8)
    lw $t8, 136($sp)
    swc1 $f12, 4($t8)
    la $t8, .Lf321
    lwc1 $f12, 0($t8)
    lw $t8, 136($sp)
    swc1 $f12, 8($t8)
    la $t8, .Lf323
    lwc1 $f12, 0($t8)
    lw $t8, 136($sp)
    swc1 $f12, 12($t8)
    la $t8, .Lf323
    lwc1 $f12, 0($t8)
    lw $t8, 136($sp)
    swc1 $f12, 16($t8)
    la $t8, .Lf3210
    lwc1 $f12, 0($t8)
    lw $t8, 136($sp)
    swc1 $f12, 20($t8)
    li $t9, 10
    lw $t8, 136($sp)
    sw $t9, 32($t8)
    li $t9, 0
    lw $t8, 136($sp)
    sw $t9, 36($t8)
    li $t9, 0
    lw $t8, 136($sp)
    sw $t9, 28($t8)
    li $t9, 0
    lw $t8, 136($sp)
    sb $t9, 24($t8)
.Linit_game_ret_70:
    lw $fp, 144($sp)
    lw $ra, 148($sp)
    addiu $sp, $sp, 152
    jr $ra
    nop
	.size init_game, . - init_game

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -192
    sw $ra, 188($sp)
    sw $fp, 184($sp)
    addiu $fp, $sp, 192
    li $t8, 1
    sw $t8, 16($sp)
    li $a3, 0
    li $a2, 3
    li $a1, 2
    li $a0, 0
    jal display_init
    nop
    move $t9, $v0
    jal rdpq_init
    nop
    move $t9, $v0
    jal joypad_init
    nop
    move $t9, $v0
    jal timer_init
    nop
    move $t9, $v0
    move $t9, $zero
    addiu $t8, $sp, 136
    move $a0, $t8
    move $a1, $t9
    li $a2, 40
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal memcpy
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    addiu $a0, $sp, 136
    jal init_game
    nop
    move $t9, $v0
.Lloop_h_72:
    jal joypad_poll
    nop
    move $t9, $v0
    li $a0, 0
    jal joypad_get_status
    nop
    move $t9, $v0
    sw $t9, 176($sp)
    addiu $t8, $sp, 136
    lbu $t9, 24($t8)
    li $t8, 0
    bne $t9, $t8, .Larm_skip_76
    nop
    addiu $t6, $sp, 176
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    bnez $t8, .Lsc_78
    nop
    addiu $t6, $sp, 176
    lw $t7, 4($t6)
    lb $t8, 0($t7)
    beqz $t8, .Lif_end_77
    nop
.Lsc_78:
    li $t8, 1
    addiu $t7, $sp, 136
    sb $t8, 24($t7)
.Lif_end_77:
    j .Lmatch_end_74
    nop
.Larm_skip_76:
    li $t8, 1
    bne $t9, $t8, .Larm_skip_80
    nop
    addiu $t7, $sp, 176
    sw $t7, 180($sp)
    addiu $a0, $sp, 136
    lw $a1, 180($sp)
    sw $t9, 96($sp)
    jal update_playing
    nop
    lw $t9, 96($sp)
    move $t8, $v0
    j .Lmatch_end_74
    nop
.Larm_skip_80:
    li $t8, 2
    bne $t9, $t8, .Larm_skip_82
    nop
    addiu $t6, $sp, 176
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    beqz $t8, .Lif_end_83
    nop
    li $t8, 1
    addiu $t7, $sp, 136
    sb $t8, 24($t7)
.Lif_end_83:
    addiu $t6, $sp, 176
    lw $t7, 4($t6)
    lb $t8, 1($t7)
    beqz $t8, .Lif_end_84
    nop
    li $t8, 3
    addiu $t7, $sp, 136
    sb $t8, 24($t7)
.Lif_end_84:
    j .Lmatch_end_74
    nop
.Larm_skip_82:
    li $t8, 3
    bne $t9, $t8, .Larm_skip_86
    nop
    addiu $t6, $sp, 176
    lw $t7, 4($t6)
    lb $t8, 3($t7)
    beqz $t8, .Lif_end_87
    nop
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal init_game
    nop
    lw $t9, 96($sp)
    move $t8, $v0
.Lif_end_87:
    j .Lmatch_end_74
    nop
.Larm_skip_86:
.Lmatch_end_74:
    addiu $a0, $sp, 136
    jal render_screen
    nop
    move $t9, $v0
    li $t9, 1
    addiu $t7, $sp, 136
    lw $t8, 28($t7)
    addu $t9, $t8, $t9
    addiu $t8, $sp, 136
    sw $t9, 28($t8)
    j .Lloop_h_72
    nop
.Lloop_x_73:
    jal rdpq_close
    nop
    move $t9, $v0
    la $a0, .Lstr11
    jal debugf
    nop
    move $t9, $v0
.Lmain_ret_71:
    lw $fp, 184($sp)
    lw $ra, 188($sp)
    addiu $sp, $sp, 192
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 0
.Lstr11:
	.asciiz "PAK3D exited"
	.align 2
.Lf320:
	.word 1073741824
	.align 2
.Lf321:
	.word 1065353216
	.align 2
.Lf322:
	.word 1232348144
	.align 2
.Lf323:
	.word 0
	.align 2
.Lf324:
	.word 1036831949
	.align 2
.Lf325:
	.word 971763194
	.align 2
.Lf326:
	.word 1029785518
	.align 2
.Lf327:
	.word 1025222115
	.align 2
.Lf328:
	.word 1069547520
	.align 2
.Lf329:
	.word 1091043328
	.align 2
.Lf3210:
	.word 1059648963

	.section .data
	.align 0
	.globl dungeon_map
dungeon_map:
	.word 16843009
	.word 16843009
	.word 16843009
	.word 16843009
	.word 16777216
	.word 256
	.word 0
	.word 1
	.word 16777730
	.word 256
	.word 65536
	.word 33554433
	.word 16777728
	.word 0
	.word 0
	.word 1
	.word 16777216
	.word 16843008
	.word 65793
	.word 1
	.word 16777216
	.word 16777216
	.word 1
	.word 1
	.word 16842752
	.word 771
	.word 50331648
	.word 257
	.word 16777216
	.word 768
	.word 50331648
	.word 1
	.word 16777216
	.word 768
	.word 50331648
	.word 1
	.word 16842752
	.word 771
	.word 50331648
	.word 257
	.word 16777216
	.word 16777216
	.word 1
	.word 1
	.word 16777216
	.word 16843008
	.word 65793
	.word 1
	.word 16777728
	.word 0
	.word 0
	.word 1
	.word 16777730
	.word 256
	.word 65536
	.word 33554433
	.word 16777216
	.word 256
	.word 0
	.word 1
	.word 16843009
	.word 16843009
	.word 16843009
	.word 16843009

	.section .bss
	.align 2
	.globl __pak_heap_ptr
__pak_heap_ptr:
	.space 4
