# Generated by PAK MIPS backend
# .set mips3
# .set noreorder

	.extern display_init
	.extern display_get
	.extern display_show
	.extern display_close
	.extern joypad_init
	.extern joypad_get_status
	.extern joypad_poll
	.extern rdpq_init
	.extern rdpq_close
	.extern rdpq_attach
	.extern rdpq_attach_clear
	.extern rdpq_detach
	.extern rdpq_detach_show
	.extern rdpq_set_mode_standard
	.extern rdpq_set_mode_standard_persp
	.extern rdpq_set_mode_standard_z
	.extern rdpq_set_mode_copy
	.extern rdpq_set_mode_fill
	.extern rdpq_clear_z
	.extern rdpq_fill_rectangle
	.extern rdpq_sync_full
	.extern rdpq_sync_pipe
	.extern rdpq_sync_tile
	.extern rdpq_sync_load
	.extern rdpq_set_scissor
	.extern rdpq_set_color_image
	.extern rdpq_set_z_image
	.extern rdpq_set_other_modes_raw
	.extern rdpq_set_combiner_raw
	.extern rdpq_set_fill_color
	.extern rdpq_set_blend_color
	.extern rdpq_set_fog_color
	.extern rdpq_set_env_color
	.extern rdpq_set_prim_color
	.extern rdpq_set_prim_depth
	.extern rdpq_set_key_r
	.extern rdpq_set_key_gb
	.extern rdpq_set_convert
	.extern rdpq_set_texture_image
	.extern rdpq_set_tile
	.extern rdpq_set_tile_mask
	.extern rdpq_set_tile_size
	.extern rdpq_load_tile
	.extern rdpq_load_block
	.extern rdpq_load_tlut
	.extern rdpq_texture_rectangle
	.extern rdpq_texture_rectangle_scaled
	.extern rdpq_texture_rectangle_flip
	.extern rdpq_triangle
	.extern rdpq_triangle_z
	.extern rdpq_triangle_shade
	.extern rdpq_triangle_shade_z
	.extern rdpq_triangle_tex
	.extern rdpq_triangle_tex_z
	.extern rdpq_triangle_tex_persp
	.extern rdpq_triangle_shade_tex
	.extern rdpq_triangle_shade_tex_z
	.extern rdpq_set_tri_z
	.extern sprite_load
	.extern pakfs_read
	.extern pakfs_size
	.extern rdpq_sprite_blit
	.extern timer_init
	.extern _pak_delta_time
	.extern get_ticks
	.extern get_memory_size
	.extern system_has_expansion
	.extern audio_init
	.extern audio_close
	.extern audio_get_buffer
	.extern audio_get_frequency
	.extern audio_can_write
	.extern audio_write
	.extern audio_write_silence
	.extern audio_set_buffer_num
	.extern debugf
	.extern debug_init_isviewer
	.extern assert
	.extern dma_read
	.extern dma_write
	.extern dma_wait
	.extern data_cache_hit_writeback
	.extern data_cache_hit_invalidate
	.extern data_cache_hit_writeback_invalidate
	.extern eeprom_present
	.extern eeprom_type_detect
	.extern eeprom_read
	.extern eeprom_write
	.extern rumble_init
	.extern rumble_start
	.extern rumble_stop
	.extern cpak_init
	.extern cpak_is_plugged
	.extern cpak_is_formatted
	.extern cpak_format
	.extern cpak_read_sector
	.extern cpak_write_sector
	.extern cpak_get_free_space
	.extern tpak_init
	.extern tpak_set_value
	.extern tpak_get_value
	.extern t3d_init
	.extern t3d_destroy
	.extern t3d_frame_start
	.extern rspq_block_run
	.extern t3d_screen_projection
	.extern t3d_viewport_create
	.extern t3d_viewport_set_projection
	.extern t3d_model_load
	.extern t3d_model_free
	.extern t3d_model_draw
	.extern t3d_mat4_identity
	.extern t3d_mat4_rotate
	.extern t3d_mat4_rotate_x
	.extern t3d_mat4_rotate_y
	.extern t3d_mat4_rotate_z
	.extern t3d_mat4_translate
	.extern t3d_mat4_scale
	.extern t3d_mat4_mul
	.extern t3d_mat4_from_srt
	.extern t3d_mat4_from_srt_euler
	.extern t3d_mat4_invert
	.extern t3d_mat4_transpose
	.extern t3d_vec3_add
	.extern t3d_vec3_sub
	.extern t3d_vec3_scale
	.extern t3d_vec3_len
	.extern t3d_vec3_norm
	.extern t3d_vec3_cross
	.extern t3d_vec3_dot
	.extern t3d_vec3_lerp
	.extern t3d_quat_identity
	.extern t3d_quat_from_axis_angle
	.extern t3d_quat_mul
	.extern t3d_quat_nlerp
	.extern t3d_quat_slerp
	.extern t3d_light_set_ambient
	.extern t3d_light_set_directional
	.extern t3d_light_set_count
	.extern t3d_light_set_point
	.extern t3d_light_set_spot
	.extern t3d_light_set_point_params
	.extern t3d_viewport_attach
	.extern t3d_viewport_set_fov
	.extern t3d_set_camera
	.extern t3d_look_at
	.extern t3d_viewport_calc_viewspace_pos
	.extern t3d_fog_set_enabled
	.extern t3d_fog_set_range
	.extern t3d_fog_set_color
	.extern t3d_anim_create
	.extern t3d_anim_destroy
	.extern t3d_anim_set_playing
	.extern t3d_anim_set_looping
	.extern t3d_anim_set_speed
	.extern t3d_anim_update
	.extern t3d_anim_attach
	.extern t3d_skeleton_create
	.extern t3d_skeleton_destroy
	.extern t3d_skeleton_update
	.extern t3d_skeleton_draw
	.extern t3d_state_set_vertex_fx
	.extern t3d_state_set_drawflags
	.extern t3d_push_draw_flags
	.extern t3d_pop_draw_flags
	.extern t3d_model_get_object_by_index
	.extern t3d_model_get_object_by_name
	.extern t3d_model_get_material
	.extern t3d_model_get_vertex_count
	.extern t3d_model_bake_pos
	.extern t3d_draw_object
	.extern t3d_draw_indexed
	.extern t3d_segment_set
	.extern t3d_rdpq_draw_object
	.extern t3d_vert_load
	.extern t3d_vert_load_srt
	.extern t3d_tri_draw
	.extern t3d_tri_sync
	.extern __pak_fix16_div
	.extern __pak_alloc
	.extern __pak_free
	.extern __pak_panic
	.extern memcpy
	.extern memset
	.extern snprintf
	.extern strlen
	.extern strcmp
	.extern strncmp
	.extern strstr
	.extern pak_str_eq
	.extern pak_map_set
	.extern pak_map_get
	.extern pak_map_has
	.extern pak_map_remove
	.extern pak_pool_acquire
	.extern pak_pool_release


	.section .text
	.globl transform_point
	.type transform_point, @function
transform_point:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $a0, 136($sp)
    sw $a1, 140($sp)
    sw $a2, 144($sp)
    lw $t3, 136($sp)
    li $t2, 0
    sll $t2, $t2, 2
    addu $t3, $t3, $t2
    lwc1 $f12, 0($t3)
    swc1 $f12, 160($sp)
    lw $t2, 140($sp)
    lwc1 $f12, 0($t2)
    lwc1 $f14, 160($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 156($sp)
    lw $t2, 136($sp)
    li $t1, 1
    sll $t1, $t1, 2
    addu $t2, $t2, $t1
    lwc1 $f12, 0($t2)
    swc1 $f12, 160($sp)
    lw $t1, 140($sp)
    lwc1 $f12, 4($t1)
    lwc1 $f14, 160($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 156($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t3, 136($sp)
    li $t2, 2
    sll $t2, $t2, 2
    addu $t3, $t3, $t2
    lwc1 $f12, 0($t3)
    swc1 $f12, 156($sp)
    lw $t2, 140($sp)
    lwc1 $f12, 8($t2)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 152($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    li $t4, 3
    sll $t4, $t4, 2
    addu $t5, $t5, $t4
    lwc1 $f12, 0($t5)
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    lw $t7, 144($sp)
    swc1 $f12, 0($t7)
    move $t9, $t8
    lw $t3, 136($sp)
    li $t2, 4
    sll $t2, $t2, 2
    addu $t3, $t3, $t2
    lwc1 $f12, 0($t3)
    swc1 $f12, 160($sp)
    lw $t2, 140($sp)
    lwc1 $f12, 0($t2)
    lwc1 $f14, 160($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 156($sp)
    lw $t2, 136($sp)
    li $t1, 5
    sll $t1, $t1, 2
    addu $t2, $t2, $t1
    lwc1 $f12, 0($t2)
    swc1 $f12, 160($sp)
    lw $t1, 140($sp)
    lwc1 $f12, 4($t1)
    lwc1 $f14, 160($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 156($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t3, 136($sp)
    li $t2, 6
    sll $t2, $t2, 2
    addu $t3, $t3, $t2
    lwc1 $f12, 0($t3)
    swc1 $f12, 156($sp)
    lw $t2, 140($sp)
    lwc1 $f12, 8($t2)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 152($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    li $t4, 7
    sll $t4, $t4, 2
    addu $t5, $t5, $t4
    lwc1 $f12, 0($t5)
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    lw $t7, 144($sp)
    swc1 $f12, 4($t7)
    move $t9, $t8
    lw $t3, 136($sp)
    li $t2, 8
    sll $t2, $t2, 2
    addu $t3, $t3, $t2
    lwc1 $f12, 0($t3)
    swc1 $f12, 160($sp)
    lw $t2, 140($sp)
    lwc1 $f12, 0($t2)
    lwc1 $f14, 160($sp)
    mul.s $f12, $f14, $f12
    swc1 $f12, 156($sp)
    lw $t2, 136($sp)
    li $t1, 9
    sll $t1, $t1, 2
    addu $t2, $t2, $t1
    lwc1 $f12, 0($t2)
    swc1 $f12, 160($sp)
    lw $t1, 140($sp)
    lwc1 $f12, 4($t1)
    lwc1 $f14, 160($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 156($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 152($sp)
    lw $t3, 136($sp)
    li $t2, 10
    sll $t2, $t2, 2
    addu $t3, $t3, $t2
    lwc1 $f12, 0($t3)
    swc1 $f12, 156($sp)
    lw $t2, 140($sp)
    lwc1 $f12, 8($t2)
    lwc1 $f14, 156($sp)
    mul.s $f12, $f14, $f12
    lwc1 $f14, 152($sp)
    add.s $f12, $f14, $f12
    swc1 $f12, 148($sp)
    lw $t5, 136($sp)
    li $t4, 11
    sll $t4, $t4, 2
    addu $t5, $t5, $t4
    lwc1 $f12, 0($t5)
    lwc1 $f14, 148($sp)
    add.s $f12, $f14, $f12
    lw $t7, 144($sp)
    swc1 $f12, 8($t7)
    move $t9, $t8
.Ltransform_point_ret_0:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size transform_point, . - transform_point

	.section .text
	.globl render_cube
	.type render_cube, @function
render_cube:
    addiu $sp, $sp, -416
    sw $ra, 412($sp)
    sw $fp, 408($sp)
    addiu $fp, $sp, 416
    sw $zero, 148($sp)
    sw $zero, 152($sp)
    sw $zero, 156($sp)
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    swc1 $f12, 148($sp)
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    swc1 $f12, 152($sp)
    la $t6, .Lf320
    lwc1 $f12, 0($t6)
    swc1 $f12, 156($sp)
    addiu $t9, $sp, 148
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    sw $zero, 172($sp)
    sw $zero, 176($sp)
    sw $zero, 180($sp)
    la $t6, gs
    lwc1 $f12, 324($t6)
    swc1 $f12, 172($sp)
    la $t6, gs
    lwc1 $f12, 320($t6)
    swc1 $f12, 176($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 180($sp)
    addiu $t9, $sp, 172
    addiu $t8, $sp, 160
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    sw $zero, 196($sp)
    sw $zero, 200($sp)
    sw $zero, 204($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 196($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 200($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 204($sp)
    addiu $t9, $sp, 196
    addiu $t8, $sp, 184
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    addiu $t8, $sp, 184
    sw $t8, 208($sp)
    addiu $t8, $sp, 160
    sw $t8, 212($sp)
    addiu $t8, $sp, 136
    sw $t8, 216($sp)
    la $a0, gs
    addiu $a0, $a0, 256
    lw $a1, 216($sp)
    lw $a2, 212($sp)
    lw $a3, 208($sp)
    sw $t9, 96($sp)
    jal t3d_mat4_from_srt_euler
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    move $t9, $zero
    addiu $t8, $sp, 220
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    lw $t7, 12($t9)
    sw $t7, 12($t8)
    lw $t7, 16($t9)
    sw $t7, 16($t8)
    lw $t7, 20($t9)
    sw $t7, 20($t8)
    lw $t7, 24($t9)
    sw $t7, 24($t8)
    lw $t7, 28($t9)
    sw $t7, 28($t8)
    move $t9, $zero
    addiu $t8, $sp, 252
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    lw $t7, 12($t9)
    sw $t7, 12($t8)
    lw $t7, 16($t9)
    sw $t7, 16($t8)
    lw $t7, 20($t9)
    sw $t7, 20($t8)
    lw $t7, 24($t9)
    sw $t7, 24($t8)
    lw $t7, 28($t9)
    sw $t7, 28($t8)
    li $t9, 0
    sw $t9, 284($sp)
.Lloop_h_2:
    lw $t8, 284($sp)
    li $t7, 8
    sge $t9, $t8, $t7
    beqz $t9, .Lif_end_4
    nop
    j .Lloop_x_3
    nop
.Lif_end_4:
    sw $zero, 300($sp)
    sw $zero, 304($sp)
    sw $zero, 308($sp)
    la $t6, cube_vx
    lw $t5, 284($sp)
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    lwc1 $f12, 0($t6)
    swc1 $f12, 300($sp)
    la $t6, cube_vy
    lw $t5, 284($sp)
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    lwc1 $f12, 0($t6)
    swc1 $f12, 304($sp)
    la $t6, cube_vz
    lw $t5, 284($sp)
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    lwc1 $f12, 0($t6)
    swc1 $f12, 308($sp)
    addiu $t9, $sp, 300
    addiu $t8, $sp, 288
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    sw $zero, 324($sp)
    sw $zero, 328($sp)
    sw $zero, 332($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 324($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 328($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 332($sp)
    addiu $t9, $sp, 324
    addiu $t8, $sp, 312
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    addiu $t8, $sp, 312
    sw $t8, 212($sp)
    addiu $t8, $sp, 288
    sw $t8, 216($sp)
    la $a0, gs
    addiu $a0, $a0, 256
    lw $a1, 216($sp)
    lw $a2, 212($sp)
    sw $t9, 96($sp)
    jal transform_point
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $zero, 348($sp)
    sw $zero, 352($sp)
    sw $zero, 356($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 348($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 352($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 356($sp)
    addiu $t9, $sp, 348
    addiu $t8, $sp, 336
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    addiu $t8, $sp, 336
    sw $t8, 212($sp)
    addiu $t8, $sp, 312
    sw $t8, 216($sp)
    la $a0, gs
    lw $a1, 216($sp)
    lw $a2, 212($sp)
    sw $t9, 96($sp)
    jal t3d_viewport_calc_viewspace_pos
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    addiu $t7, $sp, 336
    lwc1 $f12, 0($t7)
    addiu $t7, $sp, 220
    lw $t6, 284($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    swc1 $f12, 0($t7)
    move $t9, $t8
    addiu $t7, $sp, 336
    lwc1 $f12, 4($t7)
    addiu $t7, $sp, 252
    lw $t6, 284($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    swc1 $f12, 0($t7)
    move $t9, $t8
    li $t8, 1
    lw $t7, 284($sp)
    addu $t8, $t7, $t8
    sw $t8, 284($sp)
    move $t9, $t8
    j .Lloop_h_2
    nop
.Lloop_x_3:
    la $t8, face_col
    li $t7, 0
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $a0, 0($t8)
    sw $t9, 96($sp)
    jal rdpq_set_mode_fill
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $t9, 0
    sw $t9, 360($sp)
.Lloop_h_5:
    lw $t8, 360($sp)
    li $t7, 12
    sge $t9, $t8, $t7
    beqz $t9, .Lif_end_7
    nop
    j .Lloop_x_6
    nop
.Lif_end_7:
    la $t8, tri_idx
    lw $t5, 360($sp)
    li $t4, 3
    mul $t6, $t5, $t4
    li $t5, 0
    addu $t7, $t6, $t5
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $t9, 0($t8)
    sw $t9, 364($sp)
    la $t8, tri_idx
    lw $t5, 360($sp)
    li $t4, 3
    mul $t6, $t5, $t4
    li $t5, 1
    addu $t7, $t6, $t5
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $t9, 0($t8)
    sw $t9, 368($sp)
    la $t8, tri_idx
    lw $t5, 360($sp)
    li $t4, 3
    mul $t6, $t5, $t4
    li $t5, 2
    addu $t7, $t6, $t5
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $t9, 0($t8)
    sw $t9, 372($sp)
    addiu $t7, $sp, 220
    lw $t6, 364($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lwc1 $f12, 0($t7)
    cvt.w.s $f12, $f12
    mfc1 $t9, $f12
    sw $t9, 376($sp)
    addiu $t7, $sp, 252
    lw $t6, 364($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lwc1 $f12, 0($t7)
    cvt.w.s $f12, $f12
    mfc1 $t9, $f12
    sw $t9, 380($sp)
    addiu $t7, $sp, 220
    lw $t6, 368($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lwc1 $f12, 0($t7)
    cvt.w.s $f12, $f12
    mfc1 $t9, $f12
    sw $t9, 384($sp)
    addiu $t7, $sp, 252
    lw $t6, 368($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lwc1 $f12, 0($t7)
    cvt.w.s $f12, $f12
    mfc1 $t9, $f12
    sw $t9, 388($sp)
    addiu $t7, $sp, 220
    lw $t6, 372($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lwc1 $f12, 0($t7)
    cvt.w.s $f12, $f12
    mfc1 $t9, $f12
    sw $t9, 392($sp)
    addiu $t7, $sp, 252
    lw $t6, 372($sp)
    sll $t6, $t6, 2
    addu $t7, $t7, $t6
    lwc1 $f12, 0($t7)
    cvt.w.s $f12, $f12
    mfc1 $t9, $f12
    sw $t9, 396($sp)
    lw $t7, 384($sp)
    lw $t6, 376($sp)
    subu $t8, $t7, $t6
    lw $t6, 396($sp)
    lw $t5, 380($sp)
    subu $t7, $t6, $t5
    mul $t9, $t8, $t7
    sw $t9, 400($sp)
    lw $t7, 388($sp)
    lw $t6, 380($sp)
    subu $t8, $t7, $t6
    lw $t6, 392($sp)
    lw $t5, 376($sp)
    subu $t7, $t6, $t5
    mul $t9, $t8, $t7
    sw $t9, 404($sp)
    lw $t7, 400($sp)
    lw $t6, 404($sp)
    subu $t8, $t7, $t6
    li $t7, 0
    slt $t9, $t8, $t7
    beqz $t9, .Lif_end_8
    nop
    la $t8, face_col
    la $t6, tri_face
    lw $t5, 360($sp)
    sll $t5, $t5, 2
    addu $t6, $t6, $t5
    lw $t7, 0($t6)
    sll $t7, $t7, 2
    addu $t8, $t8, $t7
    lw $a0, 0($t8)
    sw $t9, 96($sp)
    jal rdpq_set_fill_color
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    lw $t8, 396($sp)
    sw $t8, 20($sp)
    lw $t8, 392($sp)
    sw $t8, 16($sp)
    lw $a3, 388($sp)
    lw $a2, 384($sp)
    lw $a1, 380($sp)
    lw $a0, 376($sp)
    sw $t9, 96($sp)
    jal rdpq_triangle
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lif_end_8:
    li $t8, 1
    lw $t7, 360($sp)
    addu $t8, $t7, $t8
    sw $t8, 360($sp)
    move $t9, $t8
    j .Lloop_h_5
    nop
.Lloop_x_6:
.Lrender_cube_ret_1:
    lw $fp, 408($sp)
    lw $ra, 412($sp)
    addiu $sp, $sp, 416
    jr $ra
    nop
	.size render_cube, . - render_cube

	.section .text
	.globl update
	.type update, @function
update:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    move $t9, $a0
    addiu $t8, $sp, 136
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    la $t7, gs
    lwc1 $f12, 328($t7)
    swc1 $f12, 140($sp)
    la $t6, gs
    lwc1 $f12, 320($t6)
    lwc1 $f14, 140($sp)
    add.s $f12, $f12, $f14
    la $t7, gs
    swc1 $f12, 320($t7)
    move $t9, $t8
    la $t7, gs
    lwc1 $f12, 332($t7)
    swc1 $f12, 140($sp)
    la $t6, gs
    lwc1 $f12, 324($t6)
    lwc1 $f14, 140($sp)
    add.s $f12, $f12, $f14
    la $t7, gs
    swc1 $f12, 324($t7)
    move $t9, $t8
    la $t7, gs
    lwc1 $f12, 320($t7)
    swc1 $f12, 140($sp)
    la $t6, .Lf322
    lwc1 $f12, 0($t6)
    lwc1 $f14, 140($sp)
    c.lt.s $f12, $f14
    li $t9, 0
    bc1f .Lfgt_11
    nop
    li $t9, 1
.Lfgt_11:
    beqz $t9, .Lif_end_10
    nop
    la $t7, .Lf322
    lwc1 $f12, 0($t7)
    swc1 $f12, 140($sp)
    la $t6, gs
    lwc1 $f12, 320($t6)
    lwc1 $f14, 140($sp)
    sub.s $f12, $f12, $f14
    la $t7, gs
    swc1 $f12, 320($t7)
    move $t9, $t8
.Lif_end_10:
    la $t7, gs
    lwc1 $f12, 324($t7)
    swc1 $f12, 140($sp)
    la $t6, .Lf322
    lwc1 $f12, 0($t6)
    lwc1 $f14, 140($sp)
    c.lt.s $f12, $f14
    li $t9, 0
    bc1f .Lfgt_13
    nop
    li $t9, 1
.Lfgt_13:
    beqz $t9, .Lif_end_12
    nop
    la $t7, .Lf322
    lwc1 $f12, 0($t7)
    swc1 $f12, 140($sp)
    la $t6, gs
    lwc1 $f12, 324($t6)
    lwc1 $f14, 140($sp)
    sub.s $f12, $f12, $f14
    la $t7, gs
    swc1 $f12, 324($t7)
    move $t9, $t8
.Lif_end_12:
    addiu $t7, $sp, 136
    lw $t8, 0($t7)
    lb $t9, 8($t8)
    beqz $t9, .Lif_end_14
    nop
    la $t7, .Lf323
    lwc1 $f12, 0($t7)
    swc1 $f12, 140($sp)
    la $t6, gs
    lwc1 $f12, 328($t6)
    lwc1 $f14, 140($sp)
    sub.s $f12, $f12, $f14
    la $t7, gs
    swc1 $f12, 328($t7)
    move $t9, $t8
.Lif_end_14:
    addiu $t7, $sp, 136
    lw $t8, 0($t7)
    lb $t9, 9($t8)
    beqz $t9, .Lif_end_15
    nop
    la $t7, .Lf323
    lwc1 $f12, 0($t7)
    swc1 $f12, 140($sp)
    la $t6, gs
    lwc1 $f12, 328($t6)
    lwc1 $f14, 140($sp)
    add.s $f12, $f12, $f14
    la $t7, gs
    swc1 $f12, 328($t7)
    move $t9, $t8
.Lif_end_15:
    addiu $t7, $sp, 136
    lw $t8, 4($t7)
    lb $t9, 3($t8)
    beqz $t9, .Lif_end_16
    nop
    li $t8, 0
    la $t7, gs
    sb $t8, 336($t7)
    move $t9, $t8
.Lif_end_16:
.Lupdate_ret_9:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size update, . - update

	.section .text
	.globl init_scene
	.type init_scene, @function
init_scene:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    jal t3d_viewport_create
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    move $t8, $v0
    la $t7, gs
    move $a0, $t7
    move $a1, $t8
    li $a2, 256
    sw $t9, 96($sp)
    sw $t8, 100($sp)
    sw $t7, 104($sp)
    jal memcpy
    nop
    lw $t9, 96($sp)
    lw $t8, 100($sp)
    lw $t7, 104($sp)
    move $t9, $t8
    la $t8, .Lf324
    lwc1 $f12, 0($t8)
    swc1 $f12, 136($sp)
    la $t8, .Lf325
    lwc1 $f12, 0($t8)
    swc1 $f12, 140($sp)
    la $t8, .Lf326
    lwc1 $f12, 0($t8)
    swc1 $f12, 144($sp)
    la $a0, gs
    lwc1 $f12, 136($sp)
    swc1 $f12, 8($sp)
    lwc1 $f14, 140($sp)
    lwc1 $f12, 144($sp)
    sw $t9, 96($sp)
    jal t3d_viewport_set_projection
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $zero, 160($sp)
    sw $zero, 164($sp)
    sw $zero, 168($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 160($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 164($sp)
    la $t6, .Lf327
    lwc1 $f12, 0($t6)
    swc1 $f12, 168($sp)
    addiu $t9, $sp, 160
    addiu $t8, $sp, 148
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    sw $zero, 184($sp)
    sw $zero, 188($sp)
    sw $zero, 192($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 184($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 188($sp)
    la $t6, .Lf321
    lwc1 $f12, 0($t6)
    swc1 $f12, 192($sp)
    addiu $t9, $sp, 184
    addiu $t8, $sp, 172
    lw $t7, 0($t9)
    sw $t7, 0($t8)
    lw $t7, 4($t9)
    sw $t7, 4($t8)
    lw $t7, 8($t9)
    sw $t7, 8($t8)
    addiu $t8, $sp, 172
    sw $t8, 196($sp)
    addiu $t8, $sp, 148
    sw $t8, 200($sp)
    la $a0, gs
    lw $a1, 200($sp)
    lw $a2, 196($sp)
    sw $t9, 96($sp)
    jal t3d_set_camera
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    la $t7, .Lf321
    lwc1 $f12, 0($t7)
    la $t7, gs
    swc1 $f12, 320($t7)
    move $t9, $t8
    la $t7, .Lf328
    lwc1 $f12, 0($t7)
    la $t7, gs
    swc1 $f12, 324($t7)
    move $t9, $t8
    la $t7, .Lf329
    lwc1 $f12, 0($t7)
    la $t7, gs
    swc1 $f12, 328($t7)
    move $t9, $t8
    la $t7, .Lf3210
    lwc1 $f12, 0($t7)
    la $t7, gs
    swc1 $f12, 332($t7)
    move $t9, $t8
    li $t8, 1
    la $t7, gs
    sb $t8, 336($t7)
    move $t9, $t8
.Linit_scene_ret_17:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size init_scene, . - init_scene

	.section .text
	.globl main
	.type main, @function
main:
    addiu $sp, $sp, -320
    sw $ra, 316($sp)
    sw $fp, 312($sp)
    addiu $fp, $sp, 320
    li $t8, 1
    sw $t8, 16($sp)
    li $a3, 0
    li $a2, 3
    li $a1, 2
    li $a0, 0
    sw $t9, 96($sp)
    jal display_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal joypad_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal timer_init
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal init_scene
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lloop_h_19:
    sw $t9, 96($sp)
    jal joypad_poll
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    li $a0, 0
    sw $t9, 96($sp)
    jal joypad_get_status
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 136($sp)
    addiu $a0, $sp, 136
    sw $t9, 96($sp)
    jal update
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    la $t7, gs
    lbu $t8, 336($t7)
    sltiu $t9, $t8, 1
    beqz $t9, .Lif_end_21
    nop
    j .Lloop_x_20
    nop
.Lif_end_21:
    sw $t9, 96($sp)
    jal display_get
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 140($sp)
    li $a1, 270016767
    lw $a0, 140($sp)
    sw $t9, 96($sp)
    jal rdpq_attach_clear
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal render_cube
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    sw $t9, 96($sp)
    jal rdpq_detach_show
    nop
    lw $t9, 96($sp)
    move $t9, $v0
    j .Lloop_h_19
    nop
.Lloop_x_20:
    sw $t9, 96($sp)
    jal rdpq_close
    nop
    lw $t9, 96($sp)
    move $t9, $v0
.Lmain_ret_18:
    lw $fp, 312($sp)
    lw $ra, 316($sp)
    addiu $sp, $sp, 320
    jr $ra
    nop
	.size main, . - main

	.section .rodata
	.align 2
.Lf320:
	.word 1070386381
	.align 2
.Lf321:
	.word 0
	.align 2
.Lf322:
	.word 1086918649
	.align 2
.Lf323:
	.word 974997842
	.align 2
.Lf324:
	.word 1112014848
	.align 2
.Lf325:
	.word 1065353216
	.align 2
.Lf326:
	.word 1065749158
	.align 2
.Lf327:
	.word 1086324736
	.align 2
.Lf328:
	.word 1056964608
	.align 2
.Lf329:
	.word 1017370378
	.align 2
.Lf3210:
	.word 1012202996

	.section .data
	.align 2
	.globl cube_vx
cube_vx:
	.word 3212836864
	.word 1065353216
	.word 1065353216
	.word 3212836864
	.word 3212836864
	.word 1065353216
	.word 1065353216
	.word 3212836864
	.align 2
	.globl cube_vy
cube_vy:
	.word 3212836864
	.word 3212836864
	.word 1065353216
	.word 1065353216
	.word 3212836864
	.word 3212836864
	.word 1065353216
	.word 1065353216
	.align 2
	.globl cube_vz
cube_vz:
	.word 3212836864
	.word 3212836864
	.word 3212836864
	.word 3212836864
	.word 1065353216
	.word 1065353216
	.word 1065353216
	.word 1065353216
	.align 2
	.globl tri_idx
tri_idx:
	.word 0
	.word 1
	.word 2
	.word 0
	.word 2
	.word 3
	.word 5
	.word 4
	.word 7
	.word 5
	.word 7
	.word 6
	.word 4
	.word 0
	.word 3
	.word 4
	.word 3
	.word 7
	.word 1
	.word 5
	.word 6
	.word 1
	.word 6
	.word 2
	.word 3
	.word 2
	.word 6
	.word 3
	.word 6
	.word 7
	.word 4
	.word 5
	.word 1
	.word 4
	.word 1
	.word 0
	.align 2
	.globl tri_face
tri_face:
	.word 0
	.word 0
	.word 1
	.word 1
	.word 2
	.word 2
	.word 3
	.word 3
	.word 4
	.word 4
	.word 5
	.word 5
	.align 2
	.globl face_col
face_col:
	.word 4283760895
	.word 3425894655
	.word 4287103231
	.word 577175551
	.word 289721599
	.word 1152057343

	.section .bss
	.align 2
	.globl gs
gs:
	.space 340
